### ISSUE TITLE
NAL_UNIT_AU_DELIMITER (9) Problem

### ISSUE THREAD

**Issue by awakecoding** [cisco/openh264#1136]
Hi,

I am trying to decode H264 bitmap streams encoded by a Microsoft H264 encoder. For some reason, the first frame always fails to decode properly, with the following error:

2 - parse_nal(), no exist Sequence Parameter Sets ahead of sequence when try to decode NAL(type:9).

The code which throws the error is found in au_parser.cpp:

  if (! (IS_SEI_NAL (pNalUnitHeader->eNalUnitType) || IS_SPS_NAL (pNalUnitHeader->eNalUnitType)
         || pCtx->bSpsExistAheadFlag)) {
    if (pCtx->bPrintFrameErrorTraceFlag) {
      WelsLog (pLogCtx, WELS_LOG_WARNING,
               "parse_nal(), no exist Sequence Parameter Sets ahead of sequence when try to decode NAL(type:%d).\n",
               pNalUnitHeader->eNalUnitType);
    }
    pCtx->iErrorCode	= dsNoParamSets;
    return NULL;
  }

I used a tool to analyze the first H264 frame that I am getting from the server. The first NAL is of type 9, or NAL_UNIT_AU_DELIMITER. I found that this type was defined in the headers, but that no code appears to be using it.

The second NAL in the bitmap stream is of type 7, which seems to be what the failing check was looking for:

!! Found NAL at offset 4 (0x0004), size 2 (0x0002) 
XX 00 00 00 01 09 10 
==================== NAL ====================
 forbidden_zero_bit : 0 
 nal_ref_idc : 0 
 nal_unit_type : 9 ( Access unit delimiter ) 
======= Access Unit Delimiter =======
 primary_pic_type : 0 ( I ) 
!! Found NAL at offset 10 (0x000A), size 24 (0x0018) 
XX 00 00 00 01 67 42 C0 1F 95 A0 10 01 86 9B 20 00 

==================== NAL ====================
 forbidden_zero_bit : 0 
 nal_ref_idc : 3 
 nal_unit_type : 7 ( Sequence parameter set ) 
======= SPS =======
...

What would be the easiest way to make OpenH264 work with this? The H264 frames are received in the context of an RDP8.1 session, where the server is using H264 as a generic codec to encode remote desktop graphics. I do not know how important that NAL is, maybe I could manually strip it from the bitmap stream before passing it to OpenH264.

**Comment by sijchen** [comment]
this support should be in master now
