### ISSUE TITLE
Received green layer overlaps the video frame when running Android device.

### ISSUE THREAD

**Issue by thieplehuu** [cisco/openh264#1163]
When i running encode and decode in Android device, I received green layer overlaps the video frame. Such as image bellow.
![image1](https://cloud.githubusercontent.com/assets/3166238/3568298/fd64933c-0b2d-11e4-8978-42eecd8f03fa.png)

When I shake the device, the image clarity is shown.
![image2](https://cloud.githubusercontent.com/assets/3166238/3569261/758d071e-0b3c-11e4-895f-fe82da2689ee.png)

In my encode function:
I get NV21 data from android camera after that i convert it to yuv420 and encode it by openh264 EncodeFrame function.

In my decode function:
I use openh264 DecodeFrame function after that i convert yuv420 output data to RGBA format.

I tried it in IOS else encountered a problem so on but color is gray color instead green color. And I tried it in Windows OS else works well.
I don't know where my wrong. Please help me, thank so much.

This is my parametes settings for encode function:

 ISVCEncoder\*   pSVCEncoder; // OpenH264 encoder instance
    tUint32 uWidth = 640;
    tUint32 uHeight = 480;
    UINT uBitrate = 1000000;
    UINT uFramerate = 15.0f;
    SSourcePicture  SrcPic;
    UCHAR pcEncInputFrameBuffer[(uWidth \* uHeight \* 3)/2]; // For Android NV21 to YUV420 conversion
    WelsCreateSVCEncoder(&pSVCEncoder);
    SEncParamExt encodingParam;
    memset(&encodingParam, 0, sizeof(SEncParamExt));
    pSVCEncoder->GetDefaultParams(&encodingParam);
    encodingParam.iUsageType     = CAMERA_VIDEO_REAL_TIME;
    encodingParam.iInputCsp      = videoFormatI420;
    encodingParam.iPicWidth      = uWidth;
    encodingParam.iPicHeight     = uHeight;
    encodingParam.iTargetBitrate = uBitrate;
    encodingParam.fMaxFrameRate  = uFramerate;
    encodingParam.iRCMode        = RC_OFF_MODE;
    encodingParam.iTemporalLayerNum         = 1;
    encodingParam.iSpatialLayerNum          = 1; 
    int i;
    for (i = 0; i < encodingParam.iSpatialLayerNum; i++) {
        encodingParam.sSpatialLayers[i].iVideoWidth     = uWidth;
        encodingParam.sSpatialLayers[i].iVideoHeight    = uHeight;
        encodingParam.sSpatialLayers[i].fFrameRate      = uFramerate; 
        encodingParam.sSpatialLayers[i].iSpatialBitrate = uBitrate ; 
        encodingParam.sSpatialLayers[i].uiProfileIdc    = PRO_BASELINE; // PRO_SCALABLE_HIGH; 
        encodingParam.sSpatialLayers[i].uiLevelIdc      = LEVEL_3_1;
        encodingParam.sSpatialLayers[i].sSliceCfg.uiSliceMode = SM_DYN_SLICE; 
        encodingParam.sSpatialLayers[i].sSliceCfg.sSliceArgument.uiSliceSizeConstraint = 1300; 
    }
    encodingParam.uiIntraPeriod              = uFramerate; /\* I-Frame interval in frames */
    encodingParam.bEnableSpsPpsIdAddition    = 1;
    encodingParam.bPrefixNalAddingCtrl       = 0;
    encodingParam.iPaddingFlag               = 0;
    encodingParam.uiMaxNalSize               = 1300;
    encodingParam.bEnableLongTermReference   = 1;
    encodingParam.iLtrMarkPeriod             = uFramerate;
    iRet = pSVCEncoder->InitializeExt(&encodingParam);
    lLumaSize = (uWidth) \* (uHeight);
    lChroSize = (lLumaSize >> 2);
    memset(&SrcPic, 0, sizeof(SSourcePicture));
    SrcPic.iColorFormat = videoFormatI420;
    SrcPic.iPicWidth = uWidth;
    SrcPic.iPicHeight = uHeight;
    SrcPic.iStride[0]  = uWidth;
    SrcPic.iStride[1]  = uWidth >> 1;
    SrcPic.iStride[2]  = uWidth >> 1;
    SrcPic.iStride[3]  = 0;
    SrcPic.uiTimeStamp = uwTimestamp;
    SrcPic.pData[0] = inputBuffer;
    SrcPic.pData[1] = SrcPic.pData[0] + lLumaSize;
    SrcPic.pData[2] = SrcPic.pData[1] + lChroSize;
    SrcPic.pData[3] = NULL;
    memset(&info, 0, sizeof(SFrameBSInfo));

**Comment by danhuynh0803** [comment]
@luuanhtu  Hi, I'm seeing a similar issue on my end. Can you clarify what you did to get the green flash to resolve. Can you please include a code sample on how you saved off the PPS and SPS together with the IDR frame?
