### ISSUE TITLE
Questions about encoding some similar images

### ISSUE THREAD

**Issue by taigacon** [cisco/openh264#1260]
Suppose I have some pictures with similar content, and I want to compress it using h264 format, making it into something similar to a video stream. Also, I want it to be able for me to get every frame’s picture whenever I want to, but after I’ve read through the api, I’m a little bit confused and here are some questions I have:
 While encoding the pictures, do I just put these pictures into the encoder and let it encode?
 How do I get the image of any frames? I didn’t find a seek method in the decoder’s api. How should I implement it?

**Comment by sijchen** [comment]
as answered, the input format has to be yuv, you can convert the image format to yuv, then set encoder to be IDRperiod=1, then the encoder will encoder all frames into IDR frame which you can separately decode.
