### ISSUE TITLE
horribly buggy naming

### ISSUE THREAD

**Issue by pps83** [cisco/openh264#1282]
Can somebody please fix file names before it's too late. There are lots of duplicate file names in encoder/decoder. In some cases files are almost identical (example: decoder\core\arm\intra_pred_neon.S and encoder\core\arm\intra_pred_neon.S), or have very different contents (ex: decoder\core\src\mc.cpp and encoder\core\src\mc.cpp). Also, there are multiple header files with the same names all over the place.

that's just ugly.

**Comment by sijchen** [comment]
we've combined the mentioned files and will continue combining duplicated files as mentioned in https://github.com/cisco/openh264/issues/921
