### ISSUE TITLE
Is there any plan for implementing CABAC for entropy encoding in decoder?

### ISSUE THREAD

**Issue by robelsharma** [cisco/openh264#1339]
From source code I have seen that you are generating ERROR when you got CABAC on slice header.
```
 if (pPps->bEntropyCodingModeFlag) {
WelsLog (pLogCtx, WELS_LOG_WARNING, "ParseSliceHeaderSyntaxs(): CABAC in Enhancement layer not supported.");
return GENERATE_ERROR_NO (ERR_LEVEL_SLICE_HEADER, ERR_INFO_UNSUPPORTED_CABAC_EL);
}
```

**Comment by ethanhugg** [comment]
CABAC should now be implemented.  The tests in test/api have examples of it working.

**Comment by robelsharma** [comment]
Thanks to the Collaborators.
Is the binary release ready or still it is in development phase?

**Comment by ethanhugg** [comment]
It's in the 1.3 release, which matches the code in the branch named 'openh264v1.3'.

**Comment by robelsharma** [comment]
Thanks! I will take it for a run.
