### ISSUE TITLE
support reconstruction frame dump with actual video yuv size

### ISSUE THREAD

**Issue by YUV-pixel** [cisco/openh264#1345]
Hi,

I have yet implement to support reconstruction frames dump with actual video yuv size. Such as original input video size is 320x180 or 640x360 etc, width or height might not be multiple of 16 pixel. In these cases, so far wels encoder dump rec output is 320x192 and 640x368, respectively. Those rec(s) contain well 16 pixels aligned parts.

Using iActualWidth / Height of sDependencyLayer[did] instead of iWidthPixel/iHeightPixel of current picture, can fix this issue.

**Comment by ruil2** [comment]
fixed!
