### ISSUE TITLE
DYN_SLIC模式下编码问题

### ISSUE THREAD

**Issue by chgaowei** [cisco/openh264#1401]
ophenh264 release 1.1 bug描述
使用如下的的h264文件（请先解码，在编码），编码的过程中会存在问题，1.1release版本会触发断言。最新版本不会触发断言，但是编码处理的内容错误。
具体参数如下：
     width = 1920; //1280; //1920;
     height = 1080; //720; //1080;
     frame_rate = 24;
     multiple_thread_id = 1;
     bitrate = 4 * 1024 * 1024;
     max_bitrate = 6 * 1024 * 1024;
     slice_mode = H264_SM_DYN_SLICE ;
     slice_cfg. max_slice_size = 1400;

另外测试发现，如果max_slice_size 设定为1800以上就没有问题。初步分析是slice索引采用unsigned char类型，最大255，而这个视频的输出可能超过256个slice。

多线程模式下，最大slice大小设置不起作用，一个图像最大只支持35个slice。导致有slice超出最大限制。

注：测试视频文件链接：http://pan.baidu.com/s/1o6FPZzO

**Comment by sijchen** [comment]
This problem should already be fixed in v1.3.1.
