### ISSUE TITLE
No API to track which input for the decoder/encoder belongs to which output

### ISSUE THREAD

**Issue by sdroege** [cisco/openh264#1404]
Currently there is no way to track the input-output relationship of the codec. It would be good if some arbitrary ID could be added to the input data, which is then copied over to the output data.

This is useful for tracking frame reordering and making sure to assign appropriate timestamps to the output.

**Comment by sdroege** [comment]
Which change solved this?

**Comment by sijchen** [comment]
"Currently neither the decoder nor the encoder support any reordering of frames", so there is no need for such API?

**Comment by sdroege** [comment]
Agreed, I was wondering about the "solved" label :)
