### ISSUE TITLE
Support High Profile decoding

### ISSUE THREAD

**Issue by Daiz** [cisco/openh264#1407]
With just Constrained Baseline Profile decoding support, OpenH264 is basically limited to WebRTC and WebRTC only. The vast, vast majority of H.264 video (especially HD video) on the web uses High Profile. Do I need to say more?

**Comment by ethanhugg** [comment]
The people currently working on OpenH264 have prioritized the conferences use cases.  High profile would be great to have as well but it will have to come later unless more contributors join the project.
