### ISSUE TITLE
测试空域分层编码的问题

### ISSUE THREAD

**Issue by mars1001** [cisco/openh264#1413]
测试空域分层，分为两层，配置文件内容如下所示，编码得到的264码流，使用h264dec解码得到的yuv，只有第一帧显示正常，从第二帧开始就是灰色，但能看到运动残差部分，请问是什么原因？我在windows7和ubantu上测试得到的结果一样。

另外请问专家：既然openh264能够支持svc，能不能在testbin目录下，给出一个空域分层为2的测试配置文件。这个目录下只有空域分层为1的样例配置文件。您方便留下一个email方便请教吗，或者您联系我，我的email：mars_1001@hotmail.com

配置文件如下：

welsenc_vd_rc.cfg
#============================== GENERAL ==============================
UsageType 0 #0: camera video 1:screen content
SourceWidth 320 # Input frame width
SourceHeight 192 # Input frame height
InputFile ../res/CiscoVT2people_320x192_12fps.yuv
OutputFile test_vd_rc.264 # Bitstream file
MaxFrameRate 30 # Maximum frame rate [Hz]
FramesToBeEncoded -1 # Number of frames (at input frame rate), -1

TemporalLayerNum 4 # temporal layer number(1--4)
IntraPeriod 0 # Intra Period ( multipler of GoP size or -1)
EnableSpsPpsIDAddition 1

EnableFrameCropping 1 # enable frame cropping flag

MaxNalSize 0 # Unit:Byte, Maximum Nal size
#============================== LOOP FILTER ==============================
LoopFilterDisableIDC 0 # Loop filter idc (0: on, 1: off)
LoopFilterAlphaC0Offset 0 # AlphaOffset(-6..+6): valid range
LoopFilterBetaOffset 0 # BetaOffset (-6..+6): valid range

#============================== SOFTWARE IMPLEMENTATION ==============================
MultipleThreadIdc 1 # 0: auto(dynamic imp. internal encoder); 1: multiple threads imp. disabled; > 1: count number of threads;

#============================== RATE CONTROL ==============================
RCMode -1 # 0: quality mode; 1: bitrate mode; 2: bitrate limited mode; -1: rc off mode
TargetBitrate 600 # Unit: kbps, controled by EnableRC also
MaxOverallBitrate 800 # Unit: kbps, max bitrate overall

#============================== DENOISE CONTROL ==============================
EnableDenoise 1 # Enable Denoise (1: enable, 0: disable)

#============================== SCENE CHANGE DETECTION CONTROL =======================
EnableSceneChangeDetection 1 # Enable Scene Change Detection (1: enable, 0: disable)

#============================== BACKGROUND DETECTION CONTROL ==============================
EnableBackgroundDetection 1 # BGD control(1: enable, 0: disable)

#============================== ADAPTIVE QUANTIZATION CONTROL =======================
EnableAdaptiveQuantization 1 # Enable Adaptive Quantization (1: enable, 0: disable)

#============================== LONG TERM REFERENCE CONTROL ==============================
EnableLongTermReference 1 # Enable Long Term Reference (1: enable, 0: disable)
LongTermReferenceNumber 2 # long term reference number (1-4):screen content (1-2):camera video
LtrMarkPeriod 30 # Long Term Reference Marking Period

#============================== LAYER DEFINITION ==============================
PrefixNALAddingCtrl 1 # Control flag of adding prefix unit (0: off, 1: on)
NumLayers 2 # Number of layers
LayerCfg layer1_vd_rc.cfg # Layer 0 configuration file
LayerCfg layer2_vd_rc.cfg # Layer 1 configuration file

layer1_vd_rc.cfg
Layer 0 Configuration File

#============================== INPUT / OUTPUT ==============================
FrameWidth 160 # Input frame width
FrameHeight 96 # Input frame height
FrameRateIn 6 # Input frame rate [Hz]
FrameRateOut 6 # Output frame rate [Hz]
ReconFile rec_layer_me1.yuv # Reconstructed file

#============================== CODING ==============================
ProfileIdc 66 # value of profile_idc (or 0 for auto detection)

InitialQP 24 # Quantization parameters for base quality layer
#================================ RATE CONTROL ===============================
SpatialBitrate 150 # Unit: kbps, controled by DisableRC also
MaxSpatialBitrate 250 # Unit: kbps, max bitrate for current layer
#============================== MultiSlice Slice Argument ==============================

#for S/M Slice(s) mode settings

SliceMode 0 # 0: sigle slice mode; >0: multiple slices mode, see below;
SliceSize 1500
SliceNum 1 # multiple slices number specified

SlicesAssign0 960 # count number of MBs in slice #0
SlicesAssign1 0 # count number of MBs in slice #1
SlicesAssign2 0 # count number of MBs in slice #2
SlicesAssign3 0 # count number of MBs in slice #3 -- seting here is for better testing
SlicesAssign4 0 # count number of MBs in slice #4
SlicesAssign5 0 # count number of MBs in slice #5
SlicesAssign6 0 # count number of MBs in slice #6

SlicesAssign7 0 # count number of MBs in slice #7

layer2_vd_rc.cfg
Layer 1 Configuration File

#============================== INPUT / OUTPUT ==============================
FrameWidth 320 # Input frame width
FrameHeight 192 # Input frame height
FrameRateIn 12 # Input frame rate [Hz]
FrameRateOut 12 # Output frame rate [Hz]
ReconFile rec_layer_me2.yuv # Reconstructed file

#============================== CODING ==============================
ProfileIdc 83 # value of profile_idc (or 0 for auto detection)

InitialQP 26 # Quantization parameters for base quality layer
#================================ RATE CONTROL ===============================
SpatialBitrate 400 # Unit: kbps, controled by DisableRC also
MaxSpatialBitrate 600 # Unit: kbps, max bitrate for current layer
#============================== MultiSlice Slice Argument ==============================

#for S/M Slice(s) mode settings

SliceMode 0 # 0: sigle slice mode; >0: multiple slices mode, see below;
SliceSize 1500
SliceNum 1 # multiple slices number specified

SlicesAssign0 960 # count number of MBs in slice #0
SlicesAssign1 0 # count number of MBs in slice #1
SlicesAssign2 0 # count number of MBs in slice #2
SlicesAssign3 0 # count number of MBs in slice #3 -- seting here is for better testing
SlicesAssign4 0 # count number of MBs in slice #4
SlicesAssign5 0 # count number of MBs in slice #5
SlicesAssign6 0 # count number of MBs in slice #6
SlicesAssign7 0 # count number of MBs in slice #7

本来想附图，结果jpg和png都不能成功贴到这儿。

**Comment by sijchen** [comment]
我们建议您还是使用英文提问这样有可能会对其他有类似问题的人有帮助.
We will recommend you to use English in questions so that others having similar questions may get some hint.

There is no claim of decoder supporting svc for now, we are not supporting two-layer as console input in decoder for now. You may consider separating the bit stream into two layers yourself.

**Comment by mstorsjo** [comment]
How do I decode SVC content after separating the bitstream into two layers? The base layer is of course trivial to decode, but how do I decode the second layer that depends on the first one? Or is that not possible with the current OpenH264 decoder (when using the API, not only when using the h264dec console tool) either?

**Comment by dongzha** [comment]
Hi, current openh264 decoder only supports decoding of single layer bitstream. E.g. an AVC base layer, or an enhancement layer that does not depend on the base layer.

**Comment by sijchen** [comment]
close because answered
