### ISSUE TITLE
publish signed hashes for binaries

### ISSUE THREAD

**Issue by FelixSchwarz** [cisco/openh264#1417]
As a user who downloaded Cisco's binary build I would like to verify that the module is really what was published by Cisco.

For example you could publish GPG-signed hashsums (e.g. sha + md5) for the binaries.

**Comment by sijchen** [comment]
is this related to https://github.com/cisco/openh264/issues/893?

**Comment by FelixSchwarz** [comment]
Well, #893 is a much broader approach. I was thinking about something much more light-weight:
I assume that Ciscos build process is fine and I trust Cisco for openh264 binaries but still I want to verify that I downloaded indeed Ciscos code and not some random bits from a man-in-the-middle attack (or Cisco's server was hacked).

Of course reproducible builds could be considered a solution for that situation but that requires me to build the binaries myself for comparison.

My suggestion was just to sign the hashes (md5, sha1, ...) with GPG as it is common for open source software. That way I can verify that I got the right binary – regardless of how I retrieved the binary bits. This should be very easy to implement as part of the release process and requires no code changes.

**Comment by luser** [comment]
This seems pretty reasonable. For Firefox releases we publish a list of file hashes, and sign the hash file, so for example:
http://ftp.mozilla.org/pub/firefox/releases/42.0/
has:
http://ftp.mozilla.org/pub/firefox/releases/42.0/SHA512SUMS
and http://ftp.mozilla.org/pub/firefox/releases/42.0/SHA512SUMS.asc

**Comment by huili2** [comment]
@FelixSchwarz  Current release binaries have all signatures from Cisco. Hope this can completely solve your issue.

**Comment by FelixSchwarz** [comment]
> @FelixSchwarz Current release binaries have all signatures from Cisco. Hope this can completely solve your issue.

Ah, great :-)
Where can I find  these binaries? The release page does not list them as far as I can see: https://github.com/cisco/openh264/releases

**Comment by huili2** [comment]
@FelixSchwarz a latest release named 1.7.0 will soon be available :)
