### ISSUE TITLE
Problem with 'make install' for iOS build

### ISSUE THREAD

**Issue by ivanlin** [cisco/openh264#1421]
Hi, 

My problem is that, after succeeding build iOS build with "make OS=ios ARCH=arm64" I tried to use 'make install' to install all necessary files into a folder (e.g. /Users/ivanlin/opt)

After typing 'make install' I hit a problem instantly with the error message listed below:

> Ivanteki-MacBook-Pro:openh264 ivanlin$ make install
> cd ./ && sh ./codec/common/generate_version.sh
> Generated codec/common/inc/version.h
> c++ -O3 -m64 -DX86_ASM -Wall -fPIC -MMD -MP   -I./codec/api/svc -I./codec/common/inc  ->I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o >codec/encoder/plus/src/welsEncoderExt.o codec/encoder/plus/src/welsEncoderExt.cpp
> nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/encoder/core/x86/coeff.o >codec/encoder/core/x86/coeff.asm
> nasm: fatal: unrecognised output format `macho64' - use -hf for a list
> type`nasm -h' for help
> make: **\* [codec/encoder/core/x86/coeff.o] Error 1

Has anyone experienced this before? 
Any ideas are welcome. Thanks.

Ivan

**Comment by saurabh-1** [comment]
Hello. 
I am faced this same issue when compiling the library for x86_64 architecture build all other builds compiled successfully. The log is as listed below

make OS=ios ARCH=x86_64 install
2016-04-17 13:51:11.252 xcodebuild[738:16274] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-17 13:51:11.253 xcodebuild[738:16274] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmBrowser.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-17 13:51:11.567 xcodebuild[739:16280] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-17 13:51:11.568 xcodebuild[739:16280] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmBrowser.xcplugin' not present in DVTPlugInCompatibilityUUIDs
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/au_set.o codec/encoder/core/src/au_set.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/deblocking.o codec/encoder/core/src/deblocking.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/decode_mb_aux.o codec/encoder/core/src/decode_mb_aux.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/encode_mb_aux.o codec/encoder/core/src/encode_mb_aux.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/encoder.o codec/encoder/core/src/encoder.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/encoder_data_tables.o codec/encoder/core/src/encoder_data_tables.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/encoder_ext.o codec/encoder/core/src/encoder_ext.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/get_intra_predictor.o codec/encoder/core/src/get_intra_predictor.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/md.o codec/encoder/core/src/md.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/mv_pred.o codec/encoder/core/src/mv_pred.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/nal_encap.o codec/encoder/core/src/nal_encap.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/picture_handle.o codec/encoder/core/src/picture_handle.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/ratectl.o codec/encoder/core/src/ratectl.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/ref_list_mgr_svc.o codec/encoder/core/src/ref_list_mgr_svc.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/sample.o codec/encoder/core/src/sample.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/set_mb_syn_cabac.o codec/encoder/core/src/set_mb_syn_cabac.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/set_mb_syn_cavlc.o codec/encoder/core/src/set_mb_syn_cavlc.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/slice_multi_threading.o codec/encoder/core/src/slice_multi_threading.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/svc_base_layer_md.o codec/encoder/core/src/svc_base_layer_md.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/svc_enc_slice_segment.o codec/encoder/core/src/svc_enc_slice_segment.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/svc_encode_mb.o codec/encoder/core/src/svc_encode_mb.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/svc_encode_slice.o codec/encoder/core/src/svc_encode_slice.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/svc_mode_decision.o codec/encoder/core/src/svc_mode_decision.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/svc_motion_estimate.o codec/encoder/core/src/svc_motion_estimate.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/svc_set_mb_syn_cabac.o codec/encoder/core/src/svc_set_mb_syn_cabac.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/svc_set_mb_syn_cavlc.o codec/encoder/core/src/svc_set_mb_syn_cavlc.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/wels_preprocess.o codec/encoder/core/src/wels_preprocess.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/wels_task_base.o codec/encoder/core/src/wels_task_base.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/wels_task_encoder.o codec/encoder/core/src/wels_task_encoder.cpp
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/core/src/wels_task_management.o codec/encoder/core/src/wels_task_management.cpp
sh ./codec/common/generate_version.sh ./
fatal: Not a git repository (or any of the parent directories): .git
Generated codec/common/inc/version_gen.h
clang++ -O3 -DNDEBUG -m64 -DX86_ASM -Wall -fPIC -MMD -MP -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -miphoneos-version-min=5.1 -DAPPLE_IOS -fembed-bitcode -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/encoder/core/inc -I./codec/encoder/plus/inc -I./codec/processing/interface -c -o codec/encoder/plus/src/welsEncoderExt.o codec/encoder/plus/src/welsEncoderExt.cpp
nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/encoder/core/x86/coeff.o codec/encoder/core/x86/coeff.asm
nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/encoder/core/x86/dct.o codec/encoder/core/x86/dct.asm
nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/encoder/core/x86/intra_pred.o codec/encoder/core/x86/intra_pred.asm
codec/encoder/core/x86/intra_pred.asm:286: fatal: No section for index 2 offset 0 found

make: *** [codec/encoder/core/x86/intra_pred.o] Error 1
