### ISSUE TITLE
Whether or not we can change the framerate or bitrate after Initialize Encoder

### ISSUE THREAD

**Issue by luuanhtu** [cisco/openh264#1422]
Could we change the encoder's parameter e.g frame rate, bitrate, while running (after Initialize)

**Comment by earthskin** [comment]
i cann't setOption for ENCODER_OPTION_FRAME_RATE or ENCODER_OPTION_BITRATE, it's return 1, this is error, anyone help?

**Comment by drakkan** [comment]
same here,

encoder->SetOption (ENCODER_OPTION_BITRATE, &bitrate) 

fails,  what's wrong?

I see this error

[OpenH264] this = 0x0x7f944c001190, Error:CWelsH264SVCEncoder::SetOption():ENCODER_OPTION_BITRATE,iBitrate = 0
