### ISSUE TITLE
How to set GOP size

### ISSUE THREAD

**Issue by ysksuzuki** [cisco/openh264#1423]
Hi, All

How can I set GOP size with openh264?
I want to configure key frame interval. But I can't find such parameter.

Checking the help of h264enc cui tool, I could find the gop option. But It seems as if it has not been implemented.

I will appreciate your help with this situation.

version: openh264v1.1

**Comment by sijchen** [comment]
you may try "-spsid 0", I remember in some other comments it says the MP4 file may want constant parameter set id.
