### ISSUE TITLE
the library should link against pthread 

### ISSUE THREAD

**Issue by ensonic** [cisco/openh264#1427]
Right now when using openh264 one gets
//usr/local/lib/libopenh264.so: undefined reference to `sem_init'
//usr/local/lib/libopenh264.so: undefined reference to `sem_destroy'
//usr/local/lib/libopenh264.so: undefined reference to `sem_timedwait'
//usr/local/lib/libopenh264.so: undefined reference to `pthread_create'
//usr/local/lib/libopenh264.so: undefined reference to `sem_post'
//usr/local/lib/libopenh264.so: undefined reference to `sem_trywait'
//usr/local/lib/libopenh264.so: undefined reference to `sem_wait'
//usr/local/lib/libopenh264.so: undefined reference to `pthread_join'
if not happen to already link -lpthread.

**Comment by mstorsjo** [comment]
I think this issue can be closed now. @ensonic - can you recheck?

**Comment by ensonic** [comment]
Looks good now. Thanks!
