### ISSUE TITLE
Provide API/ABI version information

### ISSUE THREAD

**Issue by tp-m** [cisco/openh264#1435]
It would be great if openh264 could provide developers with some kind of version information at

  (a) build time (in headers)
  (b) run time (i.e. can be queried via a functional call or retrieved from an exported variable)

This could be in form of a single number, such as OPENH264_BUILD for example, which is simply increased whenever the API is changed; or a standard major/minor/micro version scheme, where the major number changes indicate a non-backwards compatible ABI/API break, and minor/micro numbers normal feature/bug-fix releases.

This would allow developers to more easily accommodate different versions of the API and check for different versions of the API.

It's also good practice for libraries.

**Comment by mstorsjo** [comment]
This should be available now (since the 1.3 release).
