### ISSUE TITLE
encoder bug? encoded output become gray  after 1-2 hours

### ISSUE THREAD

**Issue by jim12345** [cisco/openh264#1658]
Hi.
After 1-2 hours sometimes the h264 output become gray - it is hard to explain how it looks so i attached screenshot.
It keeps like that until I stop the encoding.
What can cause this issue?
Bug in the encoder?
Please look in the attached image.

Thanks!
![image1-1](https://cloud.githubusercontent.com/assets/7906839/5515834/b630200a-8885-11e4-9efd-1e71357c2c11.JPG)

**Comment by Benc1900** [comment]
1) Someone know if this issue got resolved in new versions?
2) when new binaries will be created? the one here :
https://github.com/cisco/openh264/releases
is 1.5 years old...
