### ISSUE TITLE
Getting started with Openh264

### ISSUE THREAD

**Issue by ModiGit** [cisco/openh264#1676]
Hi,

I am new to the Openh264 code. I am trying to use it with ubuntu 12.04. I followed the instructions in the read me file to install the required files on a Ubuntu 12.04, but the problem is that I don't know what IDE to use (Eclipse or netbeans) and how to set up the whole project from all the provided files. Also, say for example if I have a video file how can I use Openh264 to encode it and decode it.
I would really appreciate if you can help me with that.

Thanks for your time...

**Comment by hoanganhstc** [comment]
:D like this question, I think User Manual is not enough "How to use" !
