### ISSUE TITLE
Supported profiles

### ISSUE THREAD

**Issue by jim12345** [cisco/openh264#1690]
As i understand Openh264 supports baseline profile only - is that still true?
If yes, any planes to support higher quality profiles in the future?
If yes and ETA?

Thanks.!

**Comment by huili2** [comment]
We're now gradually supporting Main and High as planned.
At least now, there are some CABAC functions supported already both in encoder and decoder.

**Comment by jim12345** [comment]
Any ETA for the Main and High profile?
I.E days/weeks/months/years

**Comment by oanguenot** [comment]
Hi,

In which file can I found more information on supported profiles ?

Thanks, in advance,
Olivier

**Comment by ethanhugg** [comment]
The readme has a pretty good overview:
https://github.com/cisco/openh264/blob/master/README.md
If you want to look in the code you could start here:
https://github.com/cisco/openh264/blob/master/codec/encoder/core/src/encoder_ext.cpp#L124


-EH
