### ISSUE TITLE
can not decode the this 264 file

### ISSUE THREAD

**Issue by sunnyqeen** [cisco/openh264#1699]
It can not decode the following 264 file with version 1.3.1 using decConsoled.exe on windows 7.
While version 1.1 works.

![111 264](https://cloud.githubusercontent.com/assets/649698/5615873/915cb0c8-94ff-11e4-94ae-1fc589526eb7.jpeg)

download the attached image and renamed to .264

**Comment by huili2** [comment]
As the error concealment method in console has been changed to Freeze method. This bitstream does not start with correct IDR, so it is considered to be freezing until a correct new IDR comes.

If you want to make it work, you can change the following codes in h264dec.cpp:
int32_t iErrorConMethod = ERROR_CON_SLICE_COPY; 
( Now default is:ERROR_CON_SLICE_MV_COPY_CROSS_IDR_FREEZE_RES_CHANGE)
before:
pDecoder->SetOption (DECODER_OPTION_ERROR_CON_IDC, &iErrorConMethod);

A

**Comment by huili2** [comment]
Glad it works!.

It is not a bug. At first the code set the default EC method. But it can be later replaced by SetOption.
So you may delete the SetOption(). This usage just tells users how to use the SetOption to set/replace the original settings as a demo code.

**Comment by sunnyqeen** [comment]
The issue is value set in sDecParam.eEcActiveIdc will not take affect.
It will always revert to the default DECODER_OPTION_ERROR_CON_IDC.

In this case, if I use sDecParam.eEcActiveIdc = ERROR_CON_SLICE_COPY and delete the SetOption() function, I can not decode my file any more.

**Comment by huili2** [comment]
It is strange. Actually, SetOption is an optional function. 
I guess you may modify the code at the wrong position.
In console code, there are at least two lines (for different number of input parameters of command line) of sDecParam.eEcActiveIdc = ERROR_CON_XXX.
You need to make correct modification so that it can work.

**Comment by sunnyqeen** [comment]
Hi huili,
After debug, I find the bug.
It's in the decoder.cpp
int32_t DecoderConfigParam (PWelsDecoderContext pCtx, const SDecodingParam* kpParam) {
  if (NULL == pCtx || NULL == kpParam)
    return 1;

  pCtx->pParam	= (SDecodingParam*)WelsMalloc (sizeof (SDecodingParam), "SDecodingParam");

  if (NULL == pCtx->pParam)
    return 1;

  memcpy (pCtx->pParam, kpParam, sizeof (SDecodingParam));
  pCtx->eOutputColorFormat	= pCtx->pParam->eOutputColorFormat;
  int32_t iRet = DecoderSetCsp (pCtx, pCtx->pParam->eOutputColorFormat);
  if (iRet)
    return iRet;
  pCtx->eErrorConMethod = pCtx->pParam->eEcActiveIdc;
!!!!!! here, it's missing the code to call the function InitErrorCon

In welsDecoderExt.cpp the SetOption call, you can find the similar call

  } else if (eOptID == DECODER_OPTION_ERROR_CON_IDC) { // Indicate error concealment status
    if (pOption == NULL)
      return cmInitParaError;

    iVal	= * ((int*)pOption);	// int value for error concealment idc
    iVal = WELS_CLIP3 (iVal, (int32_t) ERROR_CON_DISABLE, (int32_t) ERROR_CON_SLICE_MV_COPY_CROSS_IDR_FREEZE_RES_CHANGE);
    m_pDecContext->eErrorConMethod = (ERROR_CON_IDC) iVal;
    InitErrorCon (m_pDecContext);

**Comment by huili2** [comment]
Yeah, you are right. Thanks very much for that. I'll create a pull request for this fix.
