### ISSUE TITLE
Problem in decoding H264 file

### ISSUE THREAD

**Issue by fld2865** [cisco/openh264#1712]
Hi developers,
I'm trying to get acquainted with openh264, and I was able to successfully compile the decoder libraries from the source code, and I can decode the .264 files in the res directory into the corresponding YUV ones. I'm using openh264 v. 1.3.1.
I tried with other 264 files, originated from the conversion of MPG2 files into AVI H.264, and taking the H.264 part of it through an H264 parser. Unfortunately, though, all the files I tried (although obtained through the same procedure) end up with an empty YUV file, and the decConsole shows that no frames were decoded, as per the enclosed picture.
Since I cannot attach the offending 264 file, how can I submit the issue?

Thanks & best regards,

F. LANDE
f_lande@yahoo.it
![decconsole](https://cloud.githubusercontent.com/assets/10450828/5664036/372d0d64-974d-11e4-8ed9-60e5224da829.jpg)

**Comment by mstorsjo** [comment]
Make sure the files you are decoding are H264 baseline - that's the only profile the decoder can decode currently. (The only feature outside of baseline that currently is supported is CABAC.)

**Comment by fld2865** [comment]
Hi mstorsjo,
I guess you're probably right, but how can I tell that the file I'm trying to decode is/isn't "H264 baseline", or how can I obtain this kind of file, i.e. what is the recommended converter to use from, say, MPG1/2 to AVI (H264) as container file?
Thanks,
fld2865

**Comment by sijchen** [comment]
Hi, maybe you can try setting the decoder log level to more detailed ones to see if there is any error reported. We may adjust our error reporting log to send a warning if we find the bit stream uses some coding tools we are not supported yet.

**Comment by fld2865** [comment]
Hi,
enclosed is the output I get after setting the log level to 6, so I guess it is exactly a matter of currently unsupported features.
Are there any plans to support higher level profiles beyond baseline?

Thanks & best regards,

f_lande

![image1](https://cloud.githubusercontent.com/assets/10450828/5678348/b336128a-97f1-11e4-9b46-c91c1eba0c44.jpg)

**Comment by sijchen** [comment]
Hi, from the output you gave there is no hint on what the unsupported feature is. At present there is only CABAC support in the codes, and we did not announce its support yet since we are still testing its stability. More supports such as Transform8x8 is still in building. Thanks.

**Comment by fld2865** [comment]
Hi sijchen,
I was able to convert my H264 files to baseline level, and now I can properly uncompress them.
I'll stay tuned for new versions and features.
Thanks & best regards,

f_lande
