### ISSUE TITLE
SFrameBSInfo allocating to the same memory position

### ISSUE THREAD

**Issue by chuckleplant** [cisco/openh264#1723]
~~Edited previous issue completely~~

Using the Encoder, I allocate new SFrameBSInfo structures at every new frame, and store them in a queue for later processing. 

However, the `EncodeFrame (const SSourcePicture* kpSrcPic, SFrameBSInfo* pBsInfo)` function allocates the encoded resulting data in the same memory position. This is the data in `SFrameBSInfo.sLayerInfo[0]->pBsBuf[0]`.. Which means I'm losing the data from previous frames.

Is this expected? Am I missing something?

Best!

**Comment by dongzha** [comment]
Have you tried to check byte 00 00 01?

**Comment by mstorsjo** [comment]
I would say this is expected. You aren't given ownership of the data returned here (as in, you don't have any way of freeing it), so it is only available until the next EncodeFrame call (or until the encoder is destroyed). If you want to keep it longer than that, you need to copy it to a buffer you own yourself.

**Comment by BO45** [comment]
Yes I would also say this is by design. Most codecs impls work this way. Please don't change :)

**Comment by chuckleplant** [comment]
Is it due to optimization? Is the encoder allocating some memory space to always encode there? If encoding + streaming, it might be better not to copy the data twice. Once when getting the data, and then copying it over to the streamer.

@dongzha , not sure if that solves this. In any case, that is not strictly necessary as the SFrameBSInfo has enough information for you to iterate over NAL units.

**Comment by BO45** [comment]
It makes sense to not stress the memory manager. As codecs are optimized towards using caching and registers as much as possible. When using codecs, it is best to optimally have 1 buffer for input, and 1 output buffer through your whole pipeline. Copying is a no-no. You never know how big the payload may be in the future.

**Comment by chuckleplant** [comment]
Thanks for the explanation @BO45 !
