### ISSUE TITLE
what is in /sdcard/welsenc/cfgs.txt

### ISSUE THREAD

**Issue by notedit** [cisco/openh264#1777]
i want to test openh264 in my android device,  i run WelsEncTest project, but i can not  find cfgs.txt.

anyone can give a help.

**Comment by syureyi** [comment]
you should create such file which content can be written  as follows:
 welsenc1.cfg
 welsenc2.cfg
 welsencx.cfg
........


The welsencx.cfg locate in /openh264/testbin/, you should adb such file to you /sdcard.

**Comment by notedit** [comment]
thanks
