### ISSUE TITLE
Cross compiling openH264

### ISSUE THREAD

**Issue by badr-badri** [cisco/openh264#1796]
Hello guys, 
Could you please indicate me a procedure to follow to cross compile openH264 ?
Actually I'm in this architecture x86_64 GNU/Linux and I want to compile for these ones : mingw-w64-i686 and mingw-w64-x86-64 
Thanks in advance

**Comment by lililya** [comment]
难道你们是来帮我翻墙的？咱这里有法律我自己基本没用过，其实我可以制作一个超级pro，加上r5，我对你们的意思不是很明白，不是第1语言，翻译老反啊，哎。。。

Date: Wed, 4 Feb 2015 11:48:21 -0800

**Comment by badr-badri** [comment]
Would you please explain what you're saying in English ?

**Comment by sijchen** [comment]
@lililya, 您好, 原问题是关于openh264在linux上的交叉编译, 我不明白您的回复和这个问题的关系. 

@badr-badri, Hi, could you just check the MakeFile and the .mk files under the build/ folder, to see if those help you? BTW, I don't think the above Chinese comments are relevant to your question. Thanks

**Comment by mstorsjo** [comment]
`make OS=mingw_nt ARCH=i686 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ AR=i686-w64-mingw32-ar` and `make OS=mingw_nt ARCH=x86_64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ AR=x86_64-w64-mingw32-ar` are the commands that you need.

**Comment by badr-badri** [comment]
Thanks a lot for your response @mstorsjo :)

**Comment by lililya** [comment]
我哪里长的像男人啊，靠，走开，不需要你们帮

**Comment by sijchen** [comment]
close this since the question is solved.

**Comment by sijchen** [comment]
@lililya hi, I don't see anything in this discussion related to your comments, please notice that all your replies are public, please respect the discussion and all others reading the discussion.
@lililya 您好, 这里之前没有提到任何性别相关的字眼,  您的所有回复是公开的, 会被所有人读到, 希望您尊重这个讨论区和阅读讨论的所有人.

**Comment by cyberwetware** [comment]
@mstorsjo Thank you very much, they are helpful.
