### ISSUE TITLE
Issues with Cross Compiling for Android 19 

### ISSUE THREAD

**Issue by Anna7105** [cisco/openh264#1801]
I am using CygWin Make from Windows 8 PC, to build the open H264 library for Android.
SDK = 22.3
NDK = 9RC
TARGET (API) = 19

The instructions for Android build are here https://github.com/cisco/openh264
When I perform 
make OS=android NDKROOT=$ANDROID_NDK TARGET=$ANDROID_TARGET

The ANDROID_NDK variable is set fine. I can 'echo $ANDROID_NDK' and see the path correctly.
same with $ANDROID_TARGET. Also the SDK location is added to $PATH in Cygwin

The error I receive is 
arm-linux-androideabi-gcc.exe: error: /cygdrive/c/users/Public/Documents/Embarcadero/Studio/15.0/PlatformSDKs/android-ndk-r9c/sources/android/cpufeatures/cpu-features.c: No such file or directory

I am able to cd to that location (from within Cygwin) and the files and directories are all in place.
Any idea why the GCC cannot understand the path?

**Comment by syureyi** [comment]
I remember someone met such issue too, I suggest u try:
"make OS=android NDKROOT=$ANDROID_NDK TARGET=$ANDROID_TARGET clean" 
then "make OS=android NDKROOT=$ANDROID_NDK TARGET=$ANDROID_TARGET"

**Comment by mstorsjo** [comment]
I think the issue is that cygwin uses different kinds of unix paths - the NDK compiler itself isn't cygwin based, but requires normal windows style paths, and the mix of different build systems and path conversions don't turn out right.

It should work when you build from within msys though - I tried it a few months ago. See this post for more discussion on the matter: http://stackoverflow.com/questions/25243003/complile-error-openh264-using-android-ndk

**Comment by Anna7105** [comment]
Thanks mstorsjo and syureyi

The cygwin paths were an issue all along, I just needed a way to make the NDK understand them.
And the MSYS & MINGW did the trick

http://www.mingw.org/wiki/MSYS
http://www.mingw.org/wiki/Getting_Started

There were few errors it was throwing, but the CLEAN took care of them.
What a relief. Thanks for your valuable inputs.
Appreciate that!

**Comment by sujithchakka** [comment]
Hi,
I am Sujith, after compiling and build the openh264(got the .so file and header files),and
Question is,
1) How do i integrate that in to my android project?
2) How to invoke the H264 component in the .so file and display it in the android layer?

**Comment by Anna7105** [comment]
I am using an IDE that cross compiles my C++ code to Android and other platforms.
Just needed to list the .a file in the list of "Additionally linked libraries" in my IDE.

Also, in my case I am using the openh264.a file not the .so.
The reason being that my app fails installation when it has the openh264.so file in the deployment. I haven't figured out how to include multiple .so files in a single APK.

Archive Library (.a) 
1. This is statically to your Android app at compile time.
2. If the library code changes then it requires recompilation of your Android app

Shared Object (.so)
1. This is dynamically linked to your Android app at runtime
2. If the .so file changes  you need not recompile your Android app
