### ISSUE TITLE
android 64-bit  support?

### ISSUE THREAD

**Issue by notedit** [cisco/openh264#1807]
i see there is no android 64-bit support.  when we will have this?

**Comment by mstorsjo** [comment]
Where do you see that there's no support for that? Support for arm64, x86_64 and mips64 should be available since around the 1.1 release, at least in 1.2 and 1.3.

**Comment by notedit** [comment]
@mstorsjo  https://github.com/cisco/openh264#os-support

**Comment by mstorsjo** [comment]
Ah, I see. Ok, I'll make sure that gets fixed.

**Comment by alexcohn** [comment]
There is a glitch in the script, at least [on Mac OS](http://stackoverflow.com/questions/33239915/ndk-build-error-fatal-error-stdint-h-no-such-file-or-directory-on-mac-os-x). The correct command line is 

    make OS=android ARCH=arm64 TARGET=android-21 NDKLEVEL=21

On the face of it, this duplication is not necessary, but at least it deserves to be documented.
