### ISSUE TITLE
Decoding .m4v file with openh264

### ISSUE THREAD

**Issue by Jobq** [cisco/openh264#1818]
Hi folks, I have been working on using openh264 to decode a .m4v file that I have produced with the help of ffmpeg/libx264. I can read my .m4v file with vlc and ffplay in a standard way. However as I am trying to decode it and get my .yuv file out of it, I get the following:

./h264dec output.m4v output.yuv
H264 source file name: output.m4v..
Sequence output file name: output.yuv..
_______________________________
[OpenH264] this = 0x0x8cb3048, Warning:Max AU size exceeded. Allowed size = 7077888, current size = 10677392
[OpenH264] this = 0x0x8cb3048, Warning:ParseSps(): level_idx (226).
[OpenH264] this = 0x0x8cb3048, Warning:Max AU size exceeded. Allowed size = 7077888, current size = 10648289
[OpenH264] this = 0x0x8cb3048, Warning:Max AU size exceeded. Allowed size = 7077888, current size = 10550676
[OpenH264] this = 0x0x8cb3048, Warning:ParseSps(): level_idx (34).
[OpenH264] this = 0x0x8cb3048, Warning:Max AU size exceeded. Allowed size = 7077888, current size = 9078963
[OpenH264] this = 0x0x8cb3048, Warning:Max AU size exceeded. Allowed size = 7077888, current size = 22884788
[OpenH264] this = 0x0x8cb3048, Warning:ParseSps(): level_idx (0).
[OpenH264] this = 0x0x8cb3048, Warning:ParseSps(): level_idx (0).
_______________________________
iWidth:         0
height:         0
Frames:         0
decode time:    0.109801 sec
FPS:            0.000000 fps
_______________________________

Specifically, I don't understand what is this "Max AU size exceeded". What is wrong in my decoding process here ? Am i using the decoder in the wrong way ?

Thank you for your time.

**Comment by ethanhugg** [comment]
Chances are your m4v is not constrained baseline.  Decoder features are described here:
https://github.com/cisco/openh264/blob/master/README.md#decoder-features
