### ISSUE TITLE
problem on setting level idc (release 1.3.1)

### ISSUE THREAD

**Issue by mujdatbayar** [cisco/openh264#1819]
Hi,

I'm trying to set level idc.
  encoder_->SetOption(ENCODER_OPTION_LEVEL, &newLevel);
or
  param.sSpatialLayers[i].uiLevelidc = newLevel;
  encoder_->InitializeExt(param);

However it doesn't work. Level is set to 5.0 by default. How can i initialize my encoder with level idc 1.3 or 2.0. Is there any correlation between level idc and other parameters(e.g target bitrate)?

Thanks.

**Comment by sijchen** [comment]
Hi, 
yes, under UsageType=CAMERA_VIDEO_REAL_TIME, when other parameters exceeds the level limits of H.264 Annex, the encoder will increase the level-idc to make the bit stream conformed to the level limits. You may be interested in trying CAMERA_VIDEO_NON_REAL_TIME in master, which should be honoring level-idc setting and modifying other parameters accordingly, however, this CAMERA_VIDEO_NON_REAL_TIME setting is still experimental, so there can be some bugs around its logic. Thanks.
