### ISSUE TITLE
Question about the glibc version which a distributed binary is built with.

### ISSUE THREAD

**Issue by ysksuzuki** [cisco/openh264#1820]
I tried to use ffmpeg with OpenH264 using a binary which is distributed via the URL below, on CentOS6.
But it failed and displayed the error message below.
Can you provide a binary which is built with glibc-2.12?
I'm sorry if I'm asking too much, but I would really appreciate your help.

I still need to use CentOS6 specifically, and upgrading glibc is problematic.
The reason why I want to use the distributed binary is to take advantage of the provider pre-paying the license royalties/fees.

Thanks in advance.

URL:
http://ciscobinary.openh264.org/libopenh264-1.3.0-linux64.so.bz2

error message:
```
ffmpeg: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /lib64/libopenh264.so.0)
```

**Comment by ysksuzuki** [comment]
I found the URL below.
When the firefox was installing OpenH264 Video Codec plugin, it downloaded OpenH264 binary via the URL.
It works with ffmpeg on CentOS6.
Can I use the URL below besides the URL I mentioned my previous comment?

URL:
http://ciscobinary.openh264.org/openh264-linux64-v1.3.zip

**Comment by ethanhugg** [comment]
Yes that's the Gecko Media Plugin version that ships with Firefox.  You can use that instead if it works for you, it's licensed the same way as the regular downloads.

**Comment by ysksuzuki** [comment]
Thank! It lets me use by all means!
