### ISSUE TITLE
Decoding H.264 stream failed

### ISSUE THREAD

**Issue by cyberwetware** [cisco/openh264#1828]
Decoding H.264 stream failed, the stream is generated by Redmi Note Phone with Mediatek MT6592 SOC. Error messages as:
./h264dec vv.h264 cc.yuv -trace 2
[OpenH264] Warning:DecodeCurrentAccessUnit() failed (1048) in frame: 24 uiDId: 0 uiQId: 0
[OpenH264] Warning:invalid syntax vertical mv 2814
[OpenH264] Warning:DecodeCurrentAccessUnit() failed (1048) in frame: 27 uiDId: 0 uiQId: 0 

in general, DecodeFrame2 function return 32 or 36.

In addition, a copy of sample(raw H.264 file with .jpg suffix) is attached and openh264 version is v1.2.0.
![vv h264](https://cloud.githubusercontent.com/assets/1283878/6457762/717506a6-c1b5-11e4-85d9-aba48fe38fea.jpg)

Any help is welcome, thanks a lot.

**Comment by sijchen** [comment]
Hi seems this bit stream has some loss in it so the decoder complains.

**Comment by huili2** [comment]
This bitstream has the feature of 8x8 transform, a feature of HIGH profile. It is not well supported yet in codec. It is now in development.
Thanks for your interest for that.

**Comment by cyberwetware** [comment]
@sijchen VLC, SMPlayer, ffplayer decode this file normally, excepting incorrect UV panels in display.
Could you do some test with the sample, thank you.

**Comment by sijchen** [comment]
@cyberwetware , huili2 above did some test with the bit stream and he has an answer.

**Comment by cyberwetware** [comment]
@huili2 Thanks for your comment, looking forward the new feature in next release.

**Comment by cyberwetware** [comment]
Yeah, I known the reason of decoding issue, thank you both, @sijchen and @huili2 .

**Comment by dapirian** [comment]
I'm running into the same issue. I'm encoding with x264, baseline profile. What setting do I need to change to make openh264 decode it properly?

**Comment by sijchen** [comment]
@dapirian could you please post the error message you met.

**Comment by dapirian** [comment]
[OpenH264] this = 0x0x7fb7d9736ac0, Warning:invalid syntax vertical mv 23913
    [OpenH264] this = 0x0x7fb7d9736ac0, Warning:DecodeCurrentAccessUnit() failed (1035) in frame: 3 uiDId: 0 uiQId: 0
    [OpenH264] this = 0x0x7fb7d9736ac0, Info:decode failed, failure type:36

**Comment by sijchen** [comment]
let's move to the new github issue you raised.
