### ISSUE TITLE
GPU Acceleration?

### ISSUE THREAD

**Issue by digitalfx** [cisco/openh264#1841]
Does this framework support GPU accelerated decode? Playing back a 1080p video in Firefox (OS X) is pushing my CPU right up to 100% :cry:

**Comment by dongzha** [comment]
Unfortunately, GPU accelerated decoding is not supported now by openh264.

**Comment by sijchen** [comment]
Does the bit steam be fed to decoder at a constant speed such as 30frame per second or it is fed at a whole (as in the decoder console)? if the latter, the decoder will try to use all available resource to decode which may make the CPU usage to jump.

**Comment by digitalfx** [comment]
I do appologise, however I was mistaken by the CPU usage. That was actually on a VP9 stream. VP9 disabled and it's down to a more manageable 40-50%. Can I leave this issue open as a "would be nice to have" feature request, or is this really out of the question for this project?

**Comment by sijchen** [comment]
Hi, good to know that it is false alarm, I will close this one then. There is no plan for supporting GPU Acceleration in this project yet.
