### ISSUE TITLE
Decoder want to switch between spatial layer must force an intra frame ?

### ISSUE THREAD

**Issue by kotakakaji** [cisco/openh264#1842]
I try to demo openh264 with a video call application. I have 4 spatial layers with different resolution. For example:
Layer 1: 162 x 120
Layer 2: 256 x 192
Layer 3: 320 x 240
Layer 4: 640 x 480

First the decoder decode video stream with layer 1, every thing is good. Then I switch to higher resolution, decode process fail with 32 error code.

This problem gone when I force encoder encode an intra frame (encoder->ForceIntraFrame(true)) every time decoder want to change layer. But I don't want this (due to large size of I frame)

How I can solve this?

**Comment by sijchen** [comment]
Hi, I don't know if there is a standard-conformance and non-SEI way for an H.264 bit stream to change resolution without intra-frame.

**Comment by kotakakaji** [comment]
Thanks for replying, sijchen.
I think I must accept this in my app.

**Comment by lililya** [comment]
Hello...

**Comment by lililya** [comment]
我可以打开196条线里无数的个人信号，你们到底是不是职业的。看不明白#地球在换环境面临从东方到西方的磁场的交互啊
