### ISSUE TITLE
When will openh264 support B-frame ?

### ISSUE THREAD

**Issue by portsip** [cisco/openh264#1844]
When will openh264 support B-frame ?

Thanks

**Comment by ethanhugg** [comment]
The current contributors to this project are focused on the conferencing use cases and B-frame is not on their short list.  Getting this soon would require new contributors who want to put this in.

**Comment by youaresoomean** [comment]
Are there any new activities regarding full Main+HighProfile/B-frame support? 
Thanks for the info!

**Comment by ruil2** [comment]
currently openh264 decoder supports CHP, encoder supports main profile without B frame.
