### ISSUE TITLE
Warning thrown with gcc 4.8.2

### ISSUE THREAD

**Issue by ethanhugg** [cisco/openh264#1858]
Warning thrown on Linux with gcc 4.8.2, the default version for Ubuntu 14.04.  This is newer than the gcc 4.6.3 which runs on Travis which is why we haven't seen it there yet even though we build with -Werror.

A command line like this "CFLAGS=-Werror make -B", gives:

In file included from ./codec/encoder/core/inc/svc_enc_golomb.h:44:0,
                 from codec/encoder/core/src/svc_encode_slice.cpp:43:
./codec/common/inc/golomb_common.h: In function ‘void WelsEnc::WelsSliceHeaderWrite(WelsEnc::sWelsEncCtx*, WelsCommon::SBitStringAux*, WelsEnc::SDqLayer*, WelsEnc::SSlice*, int32_t*)’:
./codec/common/inc/golomb_common.h:131:44: error: array subscript is above array bounds [-Werror=array-bounds]
     n += (g_kuiGolombUELength[iTmpValue - 1] >> 1);
                                            ^
./codec/common/inc/golomb_common.h: In function ‘void WelsEnc::WelsSliceHeaderExtWrite(WelsEnc::sWelsEncCtx*, WelsCommon::SBitStringAux*, WelsEnc::SDqLayer*, WelsEnc::SSlice*, int32_t*)’:
./codec/common/inc/golomb_common.h:131:44: error: array subscript is above array bounds [-Werror=array-bounds]
     n += (g_kuiGolombUELength[iTmpValue - 1] >> 1);
                                            ^
cc1plus: all warnings being treated as errors
make: *** [codec/encoder/core/src/svc_encode_slice.o] Error 1

**Comment by huili2** [comment]
from the logic, the subscript value "iTmpvalue - 1“ will always be in between the scope of array.

**Comment by ethanhugg** [comment]
The two lines that cause this are here:
https://github.com/cisco/openh264/blob/master/codec/encoder/core/src/svc_encode_slice.cpp#L263
https://github.com/cisco/openh264/blob/master/codec/encoder/core/src/svc_encode_slice.cpp#L330

It appears the send 0xFFFFFFFF into BsWriteUE:
https://github.com/cisco/openh264/blob/master/codec/common/inc/golomb_common.h#L114

The logic there doesn't do what you want with this value as iTmpValue ends up being 0.

**Comment by huili2** [comment]
Thanks very much. The input data uiNumRefIdxL0Active should not be less than 1.
@sijchen , @ruil2 , we will check the cases.

**Comment by sijchen** [comment]
this is just a warning saying that it may have problem or it really met some problem on with gcc 4.8.2?
I checked the logics, we will do WelsSliceHeaderExtInit before trying to write these headers, in WelsSliceHeaderExtInit, pCurSliceHeader->uiNumRefIdxL0Active is set to 1 at P_SLICE but not in I_SLICE, in the writing part, only when P_SLICE will the above two lines be executed.

**Comment by ethanhugg** [comment]
This should be fixed by pull req 1894
