### ISSUE TITLE
Travis failures on OSX

### ISSUE THREAD

**Issue by ethanhugg** [cisco/openh264#1860]
Something changed in our Travis environment that is causing errors like this:
https://travis-ci.org/ethanhugg/openh264/jobs/53861472

I have done some rollbacks and builds that used to work now no longer do so I don't think it's our recent changes.  More along the lines of us detecting SSE2 when it's not really offered in the VM.   I have been unable to duplicate this with my MacBookPro.    The .travis.yml for OSX is here:
https://github.com/ethanhugg/openh264/blob/travis.osx/.travis.yml
In case anyone what's to try it out.

**Comment by sijchen** [comment]
@zhilwang

**Comment by zhilwang** [comment]
From the travis log, we can see that there are several SSSE3 functions and one SSE2 function pass the UT, so the OSX VMs definitely support the SSE2 and SSSE3 instructions. I think there may be no relation with the CPU feature detecting.

**Comment by ethanhugg** [comment]
Good point.  We need to determine somehow whether this points to something we should fix or whether this is a problem with the Travis VM in which case we would have to find a different solution for CI on OSX.

**Comment by lililya** [comment]
开源触碰了我的额头却无法了解我需要帮助。need help

**Comment by sijchen** [comment]
@lililya , we don't know which kind of help you need.

**Comment by lililya** [comment]
你们弄那么多内容，累不累啊

**Comment by lililya** [comment]
Happy

**Comment by lililya** [comment]
*derffccftrf

**Comment by zhilwang** [comment]
I have added CPU infor detecting (sysctl -a | grep machdep.cpu) in .travis.yml, and get that the VMs supporting SSE2, SSSE3, SSE4.1. I think there may be some instructions of the VMs don't work well because most of the failing UT cases are asm code functions. Still need more time to dig it out

**Comment by lililya** [comment]
Ffhhbyy

**Comment by lililya** [comment]
Yhhh

**Comment by lililya** [comment]
Qq

**Comment by zhilwang** [comment]
The issue is introduced by the using of new version 2.11.08 of nasm. It will get error when using RIP-relative addresses to get rodata constants in nasm2.11.08 while nasm2.11.06 works well. There is one statement "Fix segmentation failure when rip addressing is used in macho64 backend" in the nasm release note of Version 2.11.08. So I think this might well be the problem of nasm2.11.08 itself. I suggest we use the previous version of nasm like 2.11.06 to build x86_64 asm code in MAC OSX.

**Comment by sijchen** [comment]
good catch @zhilwang ; so it is related to Travis VM settings, I am wondering if it is possible for us to use some settings to limit our Travis test environment using some specific version of nasm?

**Comment by zhilwang** [comment]
I have set Travis MAC OSX VMs to using specific version of nasm like 2.11.06, and Travis worked well.
The workable .travis.yml for OSX is here: 
https://github.com/zhilwang/openh264/blob/nasm-test1/.travis.yml
and following link is the result
https://travis-ci.org/zhilwang/openh264/jobs/56045920

**Comment by ethanhugg** [comment]
Excellent.  This solution seems to be working for me as well.  I am concerned now though that people will make their own builds with the wrong version of nasm since it builds fine but doesn't work right.   

Should we put a check in the makefiles to prevent building with 2.11.08 and/or explain this in the README?

**Comment by sijchen** [comment]
it will be good if we can put a check to prevent building with 2.11.08

**Comment by zhilwang** [comment]
I think we should explain this in the README

**Comment by sijchen** [comment]
we can add an explanation as well

**Comment by mstorsjo** [comment]
I think this is more of a bug in nasm 2.11.08 than intentional behaviour (although they might have tried to fix some other related thing). Using nasm 2.11.08 also breaks libav, which works fine with earlier versions of nasm, and with yasm. So perhaps this issue should be reported to nasm?

**Comment by zhilwang** [comment]
I have posted the issue in the forum of nasm, waiting for their response.
