### ISSUE TITLE
Decoding problem

### ISSUE THREAD

**Issue by KursonSerg** [cisco/openh264#1886]
h264dec can't decode video stream. I attach video sample.
Note: I can play this sample via player.
https://drive.google.com/file/d/0B9BH5swc36-rNmd6and5cUd0VTA/view?usp=sharing

**Comment by huili2** [comment]
This bitstream is within HIGH profile with transform_8x8_flag equal to 1 together with CABAC enabled. It is still in development now.

**Comment by KursonSerg** [comment]
Thanks for reply!

**Comment by HaiboZhu** [comment]
Hi, the high profile support in openh264 has been finished. It will support this bitstream soon.

**Comment by KursonSerg** [comment]
Good news, thank you!

**Comment by KursonSerg** [comment]
Great work, decoder works as expected!
