### ISSUE TITLE
Some Questions About Using This In Android

### ISSUE THREAD

**Issue by dengdai1993** [cisco/openh264#1905]
Recently,I want to learn about video encode,I find many ways to encode h264,but the soft encoding is too slow.I want to know the delay about openh264 using in android,and do you have more detail documents or demo about android.
Thank you all the same.

**Comment by sijchen** [comment]
this does not look like a codec problem. 
for android builds of openh264, please check https://github.com/cisco/openh264#for-android-builds
and there are some test scripts may be used for reference: https://github.com/cisco/openh264/tree/master/autotest/performanceTest/android
