### ISSUE TITLE
Redundant Slices in decoder

### ISSUE THREAD

**Issue by Jobq** [cisco/openh264#1917]
Hi folks,

Is there any support for redundant pictures and redundant slices in openh264 encoder and specifically in the decoder ? I am trying to generate two flows, one with primary pictures and one with redundant pictures. The second one would be some kind of back up stream, should the first stream be lost.

Thanks in advance.

**Comment by huili2** [comment]
Hi Jobq, redundant pictures is not supported in openh264 in neither encoder nor decoder.

**Comment by Jobq** [comment]
Hi, thanks for the reply. Will Redundant Slices be supported in the future
of openH264 development ?

**Comment by sijchen** [comment]
there is no plan for that yet.
