### ISSUE TITLE
Buffer for a decoder

### ISSUE THREAD

**Issue by octalflow** [cisco/openh264#1929]
Is it possible to set output yuv buffers for a decoder ?
There is no need to copy yuv to my own buffer if I can set the yuv buffer.
BTW, Why the openh264 preserve 3 yuv buffers for a decoder ?
thank you.

**Comment by huili2** [comment]
Not sure if I completely got what you mean. 
I assume you want to give a buffer yourself for the decoder. However, it is not supported.
A copy operation is must whatever in outer decoder (current implementation) or inner decoder (your assumption?).
for 3 yuv buffers, it was designed that YUV components can be independently stored, and also it is reserved for possible RGB or other color space formats.

**Comment by octalflow** [comment]
Thank you for answer.
