### ISSUE TITLE
Question about satd functions

### ISSUE THREAD

**Issue by brly** [cisco/openh264#1930]
On my environment(Mac OS X 10.10.2), "return value" of `WelsSampleSatd16x16_sse41` and `WelsSampleSatd16x16_c` are different. I Checked at `WelsEnc::CalculateSatdCost`.
Is this intentionally ?
Possibly it was my fault. (print by force... fail to notice premise..)

**Comment by mstorsjo** [comment]
They should produce identical results, and there's even unit tests that verify this. Try `./codec_unittest --gtest_filter=SadSatdAssemblyFuncTest.WelsSampleSatd16x16_sse41` - see `test/encoder/EncUT_Sample.cpp` for code that verifies it.

If you do have specific input where they don't behave similarly, then it's of course a bug that should be fixed.

**Comment by brly** [comment]
Results of `./codec_unittest --gtest_filter=SadSatdAssemblyFuncTest.WelsSampleSatd16x16_sse41` commands is below.

![2015-05-08 0 45 20](https://cloud.githubusercontent.com/assets/1570550/7519535/cd82603a-f51b-11e4-8d9d-2cbd03f97795.png)

Also, `WelsSampleSatd8x8_sse41`, `WelsSampleSatd8x16_sse41`, `WelsSampleSatd16x8` are failed.
`WelsSampleSatd4x4_sse41` passed unittest.

**Comment by zhilwang** [comment]
The issue may come from the version of nasm. Can you check the version of nasm to see whether it is 2.11.08? If yes, you should use the older version of nasm like 2.11.06.

**Comment by brly** [comment]
As you pointed out I used nasm-2.11.08. I modified nasm-version(to 2.11.06) and it worked well. All test-case passed.
Thanks!
