### ISSUE TITLE
h264 does not get recognized

### ISSUE THREAD

**Issue by Wandang** [cisco/openh264#1943]
I am using firefox 38.0 on a Win 8.1 64bit system.

I have openH264 1.4 installed. However youtube does not recognize it at all (via youtube.com/html5). This results in beeing unable to watch most videos on youtube in quality above 360p. Some videos work with 1080p 60 fps.

This issue is connected to this superuser entry: https://superuser.com/questions/913936/firefox-html5-only-360p

**Comment by ethanhugg** [comment]
OpenH264 is not used in Firefox for playing youtube videos.  It is used for WebRTC real-time video.  Your issue may be related to one of these in Mozilla's bugzilla, or you can create a new bug for it there:

https://bugzilla.mozilla.org/show_bug.cgi?id=1139290
https://bugzilla.mozilla.org/show_bug.cgi?id=1109833
https://bugzilla.mozilla.org/show_bug.cgi?id=987120
