### ISSUE TITLE
Change QP dynamically in RC_OFF_MODE

### ISSUE THREAD

**Issue by llyzs** [cisco/openh264#1962]
We are trying to use RC_OFF_MODE and control the QP value of every frame ourselves. We tried to use SetOption(ENCODER_OPTION_SVC_ENCODE_PARAM_EXT) to change the QP value in encParamExt.sSpatialLayers[0].iDLayerQp but nothing happened. Please check.

Further analysis of the codes has shown that the QP value is simply not copied to the original config, so I made this simple patch and it seems to work.

<pre>diff --git a/codec/encoder/core/src/encoder_ext.cpp b/codec/encoder/core/src/encoder_ext.cpp
index bf31c31..33119af 100644
--- a/codec/encoder/core/src/encoder_ext.cpp
+++ b/codec/encoder/core/src/encoder_ext.cpp
@@ -4607,6 +4607,7 @@ int32_t WelsEncoderParamAdjust (sWelsEncCtx** ppCtx, SWelsSvcCodingParam* pNewPa
       pOldDlp->iSpatialBitrate	= pNewDlp->iSpatialBitrate;
 
       pOldDlp->uiProfileIdc		= pNewDlp->uiProfileIdc;			// value of profile IDC (0 for auto-detection)
+      pOldDlp->iDLayerQp		= pNewDlp->iDLayerQp;
 
       /* Derived variants below */
       pOldDlpInternal->iTemporalResolution	= pNewDlpInternal->iTemporalResolution;
</pre>

**Comment by llyzs** [comment]
Created this PR: https://github.com/cisco/openh264/pull/1963

**Comment by sijchen** [comment]
Thanks a lot for the finding, the PR is merged.
