### ISSUE TITLE
How to reduce encode/decode time

### ISSUE THREAD

**Issue by raycad** [cisco/openh264#1986]
I'm having an issue relates to encode/decode time in some Android devices have low CPU and RAM. I would like to reduce the encode/decode time, the quality is not important. Here are my information:
OpenH264 revision: 8c60f84f7b
Using NEON: enabled

Encode initiation:
oh264_data->enc->GetDefaultParams(&eprm);
eprm.uiIntraPeriod = 8;
eprm.iTemporalLayerNum = 1;
eprm.iSpatialLayerNum = 1;

eprm.iUsageType = CAMERA_VIDEO_REAL_TIME;
eprm.iPicWidth = 640;
eprm.iPicHeight = 480;
eprm.iRCMode = RC_TIMESTAMP_MODE;
eprm.iTargetBitrate = 512000;
eprm.fMaxFrameRate = 25;
eprm.uiMaxNalSize = 1500;
eprm.bEnableFrameSkip = false; // frame skipping
eprm.bEnableDenoise = false; // denoise control
eprm.bEnableBackgroundDetection = false; // background detection control
eprm.bEnableAdaptiveQuant = 0; // adaptive quantization control
eprm.bEnableLongTermReference = false;
eprm.iLTRRefNum = 0;
eprm.iLtrMarkPeriod = 30;
eprm.bIsLosslessLink = false;
//eprm.bPrefixNalAddingCtrl = false;
eprm.bEnableSSEI = false;
eprm.bSimulcastAVC = false;
eprm.iNumRefFrame = AUTO_REF_PIC_COUNT;
eprm.iMultipleThreadIdc = 0;

SliceModeEnum sliceMode = (oh264_data->whole ? SM_SINGLE_SLICE : SM_DYN_SLICE);
// Intialize 4 spatial layer with differrent bitrate (same res)
for (int i = 0; i < eprm.iSpatialLayerNum; i++) {
    if (i == 0)
        eprm.sSpatialLayers[i].uiProfileIdc = PRO_BASELINE;
    else
        eprm.sSpatialLayers[i].uiProfileIdc = PRO_SCALABLE_BASELINE;
    eprm.sSpatialLayers[i].uiLevelIdc = LEVEL_3_1;
    eprm.sSpatialLayers[i].iVideoWidth = eprm.iPicWidth;
    eprm.sSpatialLayers[i].iVideoHeight = eprm.iPicHeight;
    eprm.sSpatialLayers[i].iSpatialBitrate = eprm.iTargetBitrate;
    eprm.sSpatialLayers[1].iMaxSpatialBitrate = eprm.iMaxBitrate;
    eprm.sSpatialLayers[i].fFrameRate = eprm.fMaxFrameRate;
    eprm.sSpatialLayers[i].sSliceCfg.uiSliceMode = sliceMode;
    if (eprm.sSpatialLayers[i].sSliceCfg.uiSliceMode == SM_DYN_SLICE) {
        eprm.sSpatialLayers[i].sSliceCfg.sSliceArgument.uiSliceSizeConstraint = param->enc_mtu;
        eprm.uiMaxNalSize = param->enc_mtu;
    }
}
Please let me know how to do and configure suitable parameters. Thanks in advance!

**Comment by sijchen** [comment]
you can set the target resolution to be smaller than source resolution, for example by setting target resolution to be 320x240 given a 640x480 source.

**Comment by raycad** [comment]
Thanks for your comment but I want to do it from the encode because the input frame must be in 640x480. Do you know if there is any parameter of encoder can change the encode time?

**Comment by sijchen** [comment]
in this line:
(oh264_data->whole ? SM_SINGLE_SLICE : SM_DYN_SLICE)
you may try replacing SM_SINGLE_SLICE to SM_FIXEDSLCNUM_SLICE, and set the slice num to be for example 4, this will enable multi-threading when (oh264_data->whole) is true.

The present multi-threading may not have a very good up-speeding, we are planning some improvements on multi-threading as well.

**Comment by raycad** [comment]
When setting the uiSliceNum to 4 the remote just shows apart of the top frame, the bottom always be blinked and displayed one color.

**Comment by sijchen** [comment]
interesting, seems either there is some limitation in the packetization part or the decoder at receiver side has problem in decoding multi-slice bit streams.

**Comment by raycad** [comment]
Yep, maybe like that.

**Comment by sijchen** [comment]
if you are not using openh264 decoder at the receiver side then we have nothing to do with this.

**Comment by raycad** [comment]
Ok. Thank you very much for your support.
