### ISSUE TITLE
Android project - JNI file mentionning encconsole.exe - No such thing in source

### ISSUE THREAD

**Issue by leye0** [cisco/openh264#1987]
I see this the MyJni.cpp file, for Android:

```
argv[0] = (char*) ("decConsole.exe");
```

But there is no decConsole.exe file anywhere when compiling, neither can I see how it would be produced.

**Comment by licaiguo** [comment]
argv[0] is not used in android or ios, it is just a place holder. In fact, you can set anything to it

**Comment by sijchen** [comment]
I think it is answered?

**Comment by leye0** [comment]
Yes. It's still totally unclear how you can just compile your openh264 code
and obtain an executable for android (just like compiling ffmpeg on arm
would give an executable on Android that can be run as a process). I also
think that your release should contain a compiled process. Otherwise, no
one can benefit from your licensing terms, which is more or less:
"You can use openh264 to encode to h264 in your project if you use it on
the fly".

I can't see any process or dynamic library that can be embedded directly in
an Android project and used as-is when browsing through all the sources.

**Comment by sijchen** [comment]
a bit confused. can't you use the binary here: 
http://ciscobinary.openh264.org/libopenh264-1.4.0-android19.so.bz2

quote: https://github.com/cisco/openh264/releases

**Comment by leye0** [comment]
Would it be possible to provide for Android the console tool you are
building for the other platforms: h264dec / h264enc?

Currently, if I peer inside an x86 release, I can see that any - let's say
- Windows application could use the command-line tool as-is. (example: You
download it using a WebClient, then use it on the fly, thus complying with
the MPEG-LA licensing), but there is not the same opportunity for Android,
where you have to find all the binding yourself for the .so library, etc.

That would be amazingly great!
Regards

**Comment by sijchen** [comment]
Regarding Android console for encoder/decoder, it seems we don't have the plan on this yet, you are welcome to contribute on this.

**Comment by leye0** [comment]
I will certainly. :)

Ticket can be closed.

Thanks
