### ISSUE TITLE
Audio Asynchronisation with HTML5 Video Playback

### ISSUE THREAD

**Issue by BestNoob** [cisco/openh264#1996]
Audio Async with HTML5 Video Playback after a few Minutes
(as example: Streamcloud)

**Comment by ethanhugg** [comment]
Could you give more details on a test case you have for this that involves OpenH264?

**Comment by BestNoob** [comment]
I have simply deaktivated the plugin inside Firefox and now it is running like before without problems.
Klite Codec Pack, Firefox, DivX , Adobe Flash installed. Klite and DivX does not like each other but that has nothing to do with the playback problems, i uninstalled those and still had this problem so i daeaktivated it now and its running.

**Comment by ethanhugg** [comment]
On Firefox, OpenH264 is used for WebRTC, but not for video playback.

You might want to check that your platform codecs are up-to-date, here's a bug about that:
https://bugzilla.mozilla.org/show_bug.cgi?id=1127111

If your problem persists, you may want to file a bug with the Firefox team on their bug system - https://bugzilla.mozilla.org
