### ISSUE TITLE
win7  vs2010 mingw compile ，some error，please help

### ISSUE THREAD

**Issue by guhui** [cisco/openh264#2005]
the config：
/e/workspace/src/openh264

export PATH="$PATH:/d/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin:/d/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/IDE"

export INCLUDE="d:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Include;C:\Program Files (x86)\Windows Kits\8.0\Include\um;C:\Program Files (x86)\Windows Kits\8.0\Include\shared"

export LIB="C:\Program Files (x86)\Windows Kits\8.0\Lib\Win8\um\x64;d:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\lib"

export PATH="$PATH:/C/nasm"

export PATH="$PATH:/C/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Bin"

export PATH="$PATH:/C/Program Files (x86)/Git/bin"

and the mingw window：
rm -f openh264.dll
cl -LD -nologo -Feopenh264.dll codec/encoder/core/src/au_set.obj codec/encoder/core/src/deblocking.obj codec/encoder/core/src/decode_mb_aux.obj codec/encoder
t.obj codec/encoder/core/src/get_intra_predictor.obj codec/encoder/core/src/md.obj codec/encoder/core/src/mv_pred.obj codec/encoder/core/src/nal_encap.obj co
mgr_svc.obj codec/encoder/core/src/sample.obj codec/encoder/core/src/set_mb_syn_cabac.obj codec/encoder/core/src/set_mb_syn_cavlc.obj codec/encoder/core/src/
svc_encode_mb.obj codec/encoder/core/src/svc_encode_slice.obj codec/encoder/core/src/svc_mode_decision.obj codec/encoder/core/src/svc_motion_estimate.obj cod
ncoder/plus/src/welsEncoderExt.obj codec/encoder/core/x86/coeff.obj codec/encoder/core/x86/dct.obj codec/encoder/core/x86/intra_pred.obj codec/encoder/core/x
core/x86/score.obj codec/decoder/core/src/au_parser.obj codec/decoder/core/src/bit_stream.obj codec/decoder/core/src/cabac_decoder.obj codec/decoder/core/src
er/core/src/decoder_core.obj codec/decoder/core/src/decoder_data_tables.obj codec/decoder/core/src/error_concealment.obj codec/decoder/core/src/fmo.obj codec
re/src/mv_pred.obj codec/decoder/core/src/parse_mb_syn_cabac.obj codec/decoder/core/src/parse_mb_syn_cavlc.obj codec/decoder/core/src/pic_queue.obj codec/dec
rocessing/src/adaptivequantization/AdaptiveQuantization.obj codec/processing/src/backgrounddetection/BackgroundDetection.obj codec/processing/src/common/memo
mplexityAnalysis.obj codec/processing/src/denoise/denoise.obj codec/processing/src/denoise/denoise_filter.obj codec/processing/src/downsample/downsample.obj
tefuncs.obj codec/processing/src/scenechangedetection/SceneChangeDetection.obj codec/processing/src/scrolldetection/ScrollDetection.obj codec/processing/src/
ocessing/src/x86/denoisefilter.obj codec/processing/src/x86/downsample_bilinear.obj codec/processing/src/x86/vaa.obj codec/common/src/common_tables.obj codec
xpand_pic.obj codec/common/src/intra_pred_common.obj codec/common/src/mc.obj codec/common/src/memory_align.obj codec/common/src/sad_common.obj codec/common/s
ec/common/x86/expand_picture.obj codec/common/x86/intra_pred_com.obj codec/common/x86/mb_copy.obj codec/common/x86/mc_chroma.obj codec/common/x86/mc_luma.obj
  -pdb:openh264.pdb -def:openh264.def -implib:openh264_dll.lib
cl: 命令行 error D8021 :无效的数值参数“/Wl,--no-undefined”
make: *** [openh264.dll] Error 2

**Comment by ethanhugg** [comment]
Could you tell us the make line you used?  Was it "make OS=msvc", or something else?

**Comment by guhui** [comment]
thank for your answer !, i make line is  "make OS=msvc "
there the setting pic which i upload,

![123](https://cloud.githubusercontent.com/assets/5454537/8327261/925b5f68-1a99-11e5-899a-78992bb8b00d.jpg)

![woaini](https://cloud.githubusercontent.com/assets/5454537/8327404/a86eedbe-1a9a-11e5-801d-966bfe73e04d.jpg)

**Comment by ethanhugg** [comment]
In your snapshot where you are building vaacalculation I noticed you have many more command-line options than are in our make files.  The same line from my build looks like this:

cl -O2 -Ob1 -Oy- -Zi -GF -Gm- -GS -Gy -DNDEBUG -MT  -DX86_ASM -DX86_32_ASM -nologo -Fdopenh264.pdb -W3 -EHsc -fp:precise -Zc:wchar_t -Zc:forScope -D_VARIADIC_MAX=10 -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/processing/interface -I./codec/processing/src/common -I./codec/processing/src/adaptivequantization -I./codec/processing/src/downsample -I./codec/processing/src/scrolldetection -I./codec/processing/src/vaacalc -c -Focodec/processing/src/vaacalc/vaacalculation.obj codec/processing/src/vaacalc/vaacalculation.cpp

So perhaps you have environment variables like CFLAGS/LDFLAGS set that are adding options to your build.

**Comment by zhsunny** [comment]
can you tell me where do you change the PATH,INCLUDE and LIB ?

**Comment by sijchen** [comment]
close this since answered and no updates from asker.
