### ISSUE TITLE
Audio stops halfway through video

### ISSUE THREAD

**Issue by normads** [cisco/openh264#2006]
When a video is playing the audio stops halfway or sometimes the audio plays and the video stops. 
Happens repeatedly on videos on coursera.com
Experienced this on firefox 38.0.5 and many versions before.

**Comment by ethanhugg** [comment]
On Firefox, OpenH264 is used for WebRTC, but not for video playback.

You might want to check that your platform codecs are up-to-date, here's a bug about that:
https://bugzilla.mozilla.org/show_bug.cgi?id=1127111

If your problem persists, you may want to file a bug with the Firefox team on their bug system - https://bugzilla.mozilla.org

**Comment by normads** [comment]
Thanks. Sorry for the false alarm
