### ISSUE TITLE
Error Compiling Visual Studio 2012

### ISSUE THREAD

**Issue by ryanovsky** [cisco/openh264#2007]
I updated my Path, Include, and Lib variables to have:
"$PATH:/c/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin:/c/Program Files (x86)/Microsoft Visual Studio 11.0/Common7/IDE"
INCLUDE="C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include;C:\Program Files (x86)\Windows Kits\8.0\Include\um;C:\Program Files (x86)\Windows Kits\8.0\Include\shared"
LIB="C:\Program Files (x86)\Windows Kits\8.0\Lib\Win8\um\x86;C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\lib"

yet when I try to run the make file using:
nmake OS=msvc

I get the following error:
makefile(1) : fatal error U1000: syntax error : ')' missing in macro invocation Stop.

Please let me know why I am unable to compile using vs2012,  I have spent a long time trying to figure out how to compile and am stuck.

Thank You!

**Comment by ethanhugg** [comment]
You'll want to be in an MSYS shell and do 'make OS=msvc' which will use GNU make instead of nmake the Microsoft one.

**Comment by ryanovsky** [comment]
If I use the MSYS shell from MinGW, does that mean there is no way to compile using visual studio?

**Comment by ethanhugg** [comment]
The supported build is the command line make.  The OS=msvc makes it use the CLI tools from Visual Studio, but we do not supply .sln files for the various versions of VS.
