### ISSUE TITLE
When will openh264 support Periodic Intra Refresh ?

### ISSUE THREAD

**Issue by sui87** [cisco/openh264#2014]
When will openh264 support Periodic Intra Refresh ?

Thanks

**Comment by sijchen** [comment]
Hi if you mean periodical intra frame, you can set: uiIntraPeriod to some number >1.

**Comment by sui87** [comment]
By Periodic Intra Refresh, I mean that we do not send I frames after the first I frame. Instead, a columns or rows of macroblocks are forcefully coded in Intra mode every frame, so that the entire frames is refreshed over a period of time. Care is taken to make sure that the motion vectors do not cross the column/row that is currently being forced in intra mode. See the implementation of PIR in x264 for example.

**Comment by sijchen** [comment]
we did consider that before but we don't have that in short-term plan yet at present.

**Comment by ThomasVolkert** [comment]
Are there maybe news on this?
BR.

**Comment by huili2** [comment]
Till now there is no update on this.
