### ISSUE TITLE
how to build for android on Windows

### ISSUE THREAD

**Issue by cindycindyhi** [cisco/openh264#2016]
I've installed cygWin/android-sdk/android-ndk. 
But there are lots of problems when I build with cygwin. I got the error "/bin/sh:android command not found" when execute " cd .\codec\build\android\dec && D:\myWork\androidndkr9d\ndk-build -B APP_ABI=armeabi-v7a && android update project -t 19 -p . && ant debug" because my android in /android-sdk/tools/ is android.bat which cannot be found and execute in cygwin.
 Is there a good way to build for android on windows?

**Comment by cindycindyhi** [comment]
it seems that I should change "android" to "/.../android-sdk/android.bat" in all scripts. But i don't know which file should be changed except Makefile.

**Comment by huili2** [comment]
@cindycindyhi we formally supports MinGW and Microsoft Visual Studio to build openh264. Cygwin is not in our support list. Thanks for your information.
