### ISSUE TITLE
Real time compression/decompression

### ISSUE THREAD

**Issue by ryanovsky** [cisco/openh264#2017]
Are there any example implementations of encoding and decoding of a real time stream?
Any help or examples would be appreciated.

**Comment by ethanhugg** [comment]
If you use Firefox and go to his URL:
https://mozilla.github.io/webrtc-landing/pc_test.html
And select "Require H.264 video" then Firefox will use OpenH264 to encode and decode the video in realtime.   All the code being used in that example is open source.

**Comment by ryanovsky** [comment]
Thanks!
