### ISSUE TITLE
decode one frame  problem?

### ISSUE THREAD

**Issue by Noiled** [cisco/openh264#2043]
a h264 stream  may be like SPS PPS I P P P P I P P...
I just want to decode one frame , I  choose a  I frame to decode, 
commonly, decoder should know sps pps  to decode a I frame , known as extra data,
and  I want to know how to pass such info  to openh264 decoder, and decode just one frame(I frame)

**Comment by huili2** [comment]
Not very clear about your question.
But decoder should have sps&pps already, (now by pass decoder the NAL of sps&pps), then pass the NAL of I frame data.

**Comment by Noiled** [comment]
just got it work , 
but I think  it would be better to provide a interface to set this data
