### ISSUE TITLE
strange results under windows

### ISSUE THREAD

**Issue by mailgate** [cisco/openh264#2044]
Hello!

I'm using openh264 to decode a stream within a cross-platform application, built with Qt.
So, just the same code runs well in win/macos/android environments.
But as per windows, decoder shows too often zero status of SBufferInfo.iBufferStatus, which I use to determine successful decoding. In same conditions decoder under windows is almost unusable.

win version is compiled win mingw32.

Any clues?

**Comment by HaiboZhu** [comment]
Hi, the codec should has the same output under different platform. About the question, the description is  vague than I can not determine the root causes. Can you provide more information about it?

**Comment by mailgate** [comment]
Hello! Looks like I've met some strange behaviour of QT lib in win32 environment... it doesn't deliver notification (signal in their glossary) about some new UDP packets arrived within the stream, so the stream became broken and codec just reveal it. I had to rewrite some QT-based code to fix it, so the issue is resolved.
