### ISSUE TITLE
How to calculate PSNR when I call the EncodeFrame (const SSourcePicture* kpSrcPic, SFrameBSInfo* pBsInfo) function?

### ISSUE THREAD

**Issue by cindycindyhi** [cisco/openh264#2045]

**Comment by huili2** [comment]
As encoder does not output reconstructed frame by default, one way to calculate PSNR is to use decoder to get the decoded YUV, and use PSNR tools to compare with the input original YUV data.

**Comment by sijchen** [comment]
close this since answered and no update from asker.
