### ISSUE TITLE
can't play convert jpg to mp4 by libx64

### ISSUE THREAD

**Issue by wangniancai** [cisco/openh264#2053]
./ffmpeg -y -i ./jpgs/0_%d.jpg -r 30000/1001 -b:a 2M -bt 4M -vcodec libx264 -pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0 -an targetFile.mp4 

just can play first frame ,could you please do me a favor

**Comment by sijchen** [comment]
it does not like to be in the scope of this github?

**Comment by sijchen** [comment]
close it because of lack of updates from asker
