### ISSUE TITLE
Question about openH264 encoder speed.

### ISSUE THREAD

**Issue by ylr5693042** [cisco/openh264#2067]
hello, I've tested openh264 codec recently, and I was confused with one question:
comparing with x264, the speed of openh264's encoding 1080p sequence to one spatial layer and one temparal layer is lower.
The testing is on Intel Core i5 CPU@1.40GHz 1.40GHz,  encoding parameters  are as below, I changed the sParam.iMultipleThreadIdc from 1 to 8(1,2,4,8),  the best result is 12fps ,while x264 can achieve up to 40fps.
parameters of one spatial layer and one temporal layer:

---

  sParam.iUsageType = CAMERA_VIDEO_REAL_TIME;
  sParam.fMaxFrameRate  = 24.0f;                // input frame rate
  sParam.iPicWidth      = 1920;                 // width of picture in samples
  sParam.iPicHeight     = 1080;                  // height of picture in samples
  sParam.iTargetBitrate = 2500000;              // target bitrate desired
  sParam.iMaxBitrate    = UNSPECIFIED_BIT_RATE;

  sParam.iTemporalLayerNum = 1;    // layer number at temporal level
  sParam.iSpatialLayerNum  = 1;    // layer number at spatial level
  sParam.bEnableDenoise          = 0;    // denoise control
  sParam.bEnableBackgroundDetection = 0; // background detection control
  sParam.bEnableAdaptiveQuant            = 1; // adaptive quantization control
  sParam.bEnableFrameSkip                  = 0; // frame skipping
  sParam.bEnableLongTermReference   = 0; // long term reference control
  sParam.iLtrMarkPeriod = 30;
  sParam.uiIntraPeriod  = 24;           // period of Intra frame
  sParam.eSpsPpsIdStrategy = INCREASING_ID;
  sParam.bPrefixNalAddingCtrl = 0;
  sParam.iComplexityMode = LOW_COMPLEXITY;

  sParam.iRCMode        = RC_BITRATE_MODE;      //  rc mode control
  sParam.iMinQp           = 21;
  sParam.iMaxQp          = 35;
  sParam.iEntropyCodingModeFlag = 1;
  sParam.iMultipleThreadIdc = 1;
  sParam.uiMaxNalSize = 1300;

  int iIndexLayer = 0;
  sParam.sSpatialLayers[iIndexLayer].uiProfileIdc       = PRO_BASELINE;
  sParam.sSpatialLayers[iIndexLayer].iVideoWidth       = 1920;
  sParam.sSpatialLayers[iIndexLayer].iVideoHeight       = 1080;
  sParam.sSpatialLayers[iIndexLayer].fFrameRate         = 24.0f;
  sParam.sSpatialLayers[iIndexLayer].iSpatialBitrate    = 1500000;
  sParam.sSpatialLayers[iIndexLayer].iMaxSpatialBitrate    = UNSPECIFIED_BIT_RATE;
  sParam.sSpatialLayers[iIndexLayer].sSliceCfg.uiSliceMode = SM_DYN_SLICE;

---

Did I use openh264 in a wrong way? or the reason  why it goes on such a low speed?

Can anyone help me? thanks.

**Comment by sijchen** [comment]
do you intentionally want to use iEntropyCodingModeFlag=1 which is CABAC?

**Comment by jpxiong** [comment]
The same question about how to speed up encoding. @sijchen Thanks.

**Comment by sijchen** [comment]
One possible way is to enable multiple threading in encoding, by setting:
>sParam.iMultipleThreadIdc = 4;
However, the enabling multi-threading with this high resolution 1080p under the following mode "uiSliceMode = SM_DYN_SLICE", may have some known issue of triggering error during encoding when the content is complex. There is a plan to fix this already and is in progress. 

One possible way is to use CAVLC rather than CABAC, by setting:
> sParam.iEntropyCodingModeFlag = 0

**Comment by ruil2** [comment]
@ylr5693042 
1. what is x264 configure on your testing? ( --preset = ultrafast , superfast or veryfast)
2. the gap of speed is very little with the same quality between x264 and openh264 in baseline profile

**Comment by huili2** [comment]
If no update, will close this days afterwards.

**Comment by Chris-LuYu** [comment]
you need set sParam.sSpatialLayers[iIndexLayer].sSliceCfg.uiSliceMode = SM_FIXEDLCNUM_SLICE;
