### ISSUE TITLE
the correct way of extracting one layer from svc bitstream

### ISSUE THREAD

**Issue by ylr5693042** [cisco/openh264#2068]
hi,
 I wanna extract one layer from openh264 bitstream,  the encoder has been set to generate 3 temporal layers and 4 spatial layers.

suppose i wanna to get one layer of (Tid=2, Did=2) ,The way I extract the target bs is selecting all the nal unit that satisfying (Tid<=2, Did=2) from the encoded bitstream. 

it turns out the target bs can be decoded by openh264 decoder successfully , while failure by ffmpeg.

Did I extract the layer bs in a correct way? 
if not, what's the right way to do so.
if it‘s correct by coincidence, then why does openH264 realize the SVC standard in this way, because obviously it doesn't support spatial dependency and cause spatial bitstream redundancy.

waiting for any reply, thanks.

**Comment by huili2** [comment]
Is it because the used SPS is subsetSPS, which ffmpeg could not parse?
openh264 can simply parse subsetSPS in addition to SPS.

**Comment by ylr5693042** [comment]
thanks for your replay!
yes, ffmpeg can decode layer with Did=0, while fails to decode any layers with Did>0. 

BTW, did I extract the target layer in a correct way?

**Comment by huili2** [comment]
Your extractor seems OK to me.

**Comment by ylr5693042** [comment]
I appreciate your answer.

Then one more thing,  why does openH264 implement the standard  SVC in this way, obviously it doesn't support spatial dependency and cause spatial bitstream redundancy.

**Comment by sijchen** [comment]
you can set simulcastAVC flag=1 to avoid the SVC header.

**Comment by melement** [comment]
Hi, 
> (Tid=2, Did=2)
Could someone tell what is Tid/Did?
Tid = maybe temporal ID?

**Comment by sijchen** [comment]
temporal id and spatial id

**Comment by melement** [comment]
@sijchen
Thank you!

**Comment by steven8274** [comment]
I'm still confused about the course of abstracting one layer from svc bitstream.My encode parameter is set this way:
...
param.iTemporalLayerNum          = 1;
param.iSpatialLayerNum              = 2;
...

My ababstracting code is like：
int iLayer = 0;
while (iLayer < _sFbi.iLayerNum)
{
	SLayerBSInfo* pLayerBsInfo = &_sFbi.sLayerInfo[iLayer];
	if (pLayerBsInfo != NULL && pLayerBsInfo->uiSpatialId <= 1)
	{
		int iLayerSize = 0;
		int iNalIdx = pLayerBsInfo->iNalCount - 1;
		do 
		{
			iLayerSize += pLayerBsInfo->pNalLengthInByte[iNalIdx];
			-- iNalIdx;
		} while (iNalIdx >= 0);
		memcpy(outData + iFrameSize, pLayerBsInfo->pBsBuf, iLayerSize);
		iFrameSize += iLayerSize;
	}
	++iLayer;
}

However, the decoder can not decode the abstracted data.Instaed, if I change 'pLayerBsInfo->uiSpatialId <= 1' to 'pLayerBsInfo->uiSpatialId == 0', the decoder can decode the data successfully!

Could any one tell me what's wrong with my abstracting course?

**Comment by ruil2** [comment]
@steven8274 You are using two spatial layers and  your buffer stores the bitstream from two layers, so the decoder can't decode bitstream correctly.  in order to separate different layer into different buffer, you need to use "pLayerBsInfo->uiSpatialId" as index.
