### ISSUE TITLE
Make fails on embedded arm5 NAS: 'CPU_COUNT' was not declared in this scope

### ISSUE THREAD

**Issue by cemacf** [cisco/openh264#2089]
~/build/openh264-master # make ARCH=arm
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/common_tables.o codec/common/src/common_tables.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/copy_mb.o codec/common/src/copy_mb.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/cpu.o codec/common/src/cpu.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/crt_util_safe_x.o codec/common/src/crt_util_safe_x.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/deblocking_common.o codec/common/src/deblocking_common.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/expand_pic.o codec/common/src/expand_pic.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/intra_pred_common.o codec/common/src/intra_pred_common.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/mc.o codec/common/src/mc.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/memory_align.o codec/common/src/memory_align.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/sad_common.o codec/common/src/sad_common.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/utils.o codec/common/src/utils.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/welsCodecTrace.o codec/common/src/welsCodecTrace.cpp
g++ -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/WelsThreadLib.o codec/common/src/WelsThreadLib.cpp
codec/common/src/WelsThreadLib.cpp: In function 'WELS_THREAD_ERROR_CODE WelsQueryLogicalProcessInfo(WelsLogicalProcessInfo*)':
codec/common/src/WelsThreadLib.cpp:480: error: 'CPU_COUNT' was not declared in this scope
make: *** [codec/common/src/WelsThreadLib.o] Error 1

**Comment by nathankidd** [comment]
My Centos 5 (2.6.18 kernel) box has the same build error. *man 3 CPU_COUNT* (on my Debian 8 box) says:
> CPU_COUNT() first appeared in glibc 2.6.

On my Centos box:
> $ /lib/libc.so.6 
> GNU C Library stable release version 2.5, by Roland McGrath et al.
> ...

Patch coming.

**Comment by nathankidd** [comment]
That patch assumes your embedded system has at least GLIBC 2.3.3, otherwise all bets are off.  It fixes my CentOS 5 build.

**Comment by cemacf** [comment]
I think this has fixed it for me too, in that the relevant module now compiles.  Thanks.

However, although it's not strictly to do with this issue, I'd be grateful for a little more help.  I now get an error at the next stage of linking:

/i-data/244ca2a4/admin/build/openh264-master # make
cc -O3 -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/common/arm/ -march=armv7-a -mfpu=neon -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/arm/expand_picture_neon.o codec/common/arm/expand_picture_neon.S
make: cc: Command not found
make: *** [codec/common/arm/expand_picture_neon.o] Error 127
/i-data/244ca2a4/admin/build/openh264-master #

Is there a command-line option or environment define to tell it to use gcc to link?

Thanks and regards,
Charles
www.macfh.co.uk/CEMH.html 

-----Original Message-----

**Comment by nathankidd** [comment]
You should open a new ticket for a different issue.   

(As for the actual issue, I can only make a guess that cc is the command the makefile uses for the assembler, which seems odd but I'm not familiar with typical ARM assemblers.  Most systems have a symlink from cc to gcc. If *cc* is correct for assembling then maybe you just need to add a symlink.)

**Comment by cemacf** [comment]
Thanks for the advice. Please see below ...

www.macfh.co.uk/CEMH.html 

-----Original Message-----

**Comment by nathankidd** [comment]
Bearing in mind that I don't have any experience looking at the openh264 ARM side,
1) If *as* is crashing try upgrading to a new version. Is it far out of date?
2) If the makefile assumes armv7/neon then it seems probable the assembly requires it, so you need to build with USE_ASM off

**Comment by cemacf** [comment]
Thanks for your continuing good will and help, Nathan.  Please see below ...

www.macfh.co.uk/CEMH.html 

> From: Nathan Kidd [mailto:notifications@github.com]
> Sent: 04 September 2015 23:25
> To: cisco/openh264
> Subject: Re: [openh264] Make fails on embedded arm5 NAS: 'CPU_COUNT' was not declared in this scope (#2089)
>
> Bearing in mind that I don't have any experience looking at the openh264 ARM side,
> 1) If as is crashing try upgrading to a new version. Is it far out of date?

~/build/openh264-master # as --version
GNU assembler (GNU Binutils) 2.19.1
Copyright 2007 Free Software Foundation, Inc.

... also ...

~/build/openh264-master # gcc --version
gcc (GCC) 4.2.3
Copyright (C) 2007 Free Software Foundation, Inc.

The problem is that, this being an embedded device, a Zyxel NSA221 NAS, it's somewhat non-standard, and it can be very difficult to install or upgrade anything that doesn't come as part of a firmware upgrade, or else can be installed by a version of ipkg that was originally built for a very similar but nevertheless slightly different arm system.  Thus, building anything on the device more or less has to be done with the development tools ipkg can provide, which are the versions above.

2) If the makefile assumes armv7/neon then it seems probable the assembly requires it, so you need to build with USE_ASM off

I've now tried editing the following files:
	codec/common/src/WelsThreadLib.cpp - to apply your patch - successful, thanks
	build/arch.mk - comment out line 8 -DHAVE_NEON - apparently successful
	Makefile - comment out line 54 USE_ASM=Yes - apparently successful
	build/platform-linux.mk - alter line 7 to remove the D option - apparently successful

Nevertheless, I'm still not there:

~/build/openh264-master # make
sh ./codec/common/generate_version.sh ./
fatal: Not a git repository (or any parent up to mount point /root)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Keeping existing codec/common/inc/version_gen.h

So I think now there are at least the following seperate problems, which, unless advised to the contrary, I will log as one or more seperate issues:
	:-(	No recognition of the correct arm cpu
	:-(	No way to tell make that we haven't got a neon fpu
	:-(	No way to tell make not to define USE_ASM
	:-(	The last problem which I understand is something to do with git, but no more.

**Comment by cemacf** [comment]
As the last effort came out something of a mess, in the interests of clarity as to who said what, I'll try again:

Thanks for your continuing good will and help, Nathan.  Please see below ...

www.macfh.co.uk/CEMH.html 

> Bearing in mind that I don't have any experience looking at the openh264 ARM side,
> 1) If as is crashing try upgrading to a new version. Is it far out of date?

~/build/openh264-master # as --version
GNU assembler (GNU Binutils) 2.19.1
Copyright 2007 Free Software Foundation, Inc.

... also ...

~/build/openh264-master # gcc --version
gcc (GCC) 4.2.3
Copyright (C) 2007 Free Software Foundation, Inc.

The problem is that, this being an embedded device, a Zyxel NSA221 NAS, it's somewhat non-standard, and it can be very difficult to install or upgrade anything that doesn't come as part of a firmware upgrade, or else can be installed by a version of ipkg that was originally built for a very similar but nevertheless slightly different arm system.  Thus, building anything on the device more or less has to be done with the development tools ipkg can provide, which are the versions above.

> 2) If the makefile assumes armv7/neon then it seems probable the assembly
> requires it, so you need to build with USE_ASM off

I've now tried editing the following files:
	codec/common/src/WelsThreadLib.cpp - to apply your patch - successful, thanks
	build/arch.mk - comment out line 8 -DHAVE_NEON - apparently successful
	Makefile - comment out line 54 USE_ASM=Yes - apparently successful
	build/platform-linux.mk - alter line 7 to remove the D option - apparently successful

Nevertheless, I'm still not there:

~/build/openh264-master # make
sh ./codec/common/generate_version.sh ./
fatal: Not a git repository (or any parent up to mount point /root)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Keeping existing codec/common/inc/version_gen.h

So I think now there are at least the following seperate problems, which, unless advised to the contrary, I will log as one or more seperate issues:
	:-(	No recognition of the correct arm cpu
	:-(	No way to tell make that we haven't got a neon fpu
	:-(	No way to tell make not to define USE_ASM
	:-(	The last problem which I understand is something to do with git, but no more.

**Comment by nathankidd** [comment]
30-second suggestions:
1) assembler is quite old, try upgrading
2) it is usually much easier to upgrade your toolchain and build when using a cross-build environment  (i.e. on your x86 Linux box using e.g. arm-linux-gcc) rather than on the native embeded host
3) try *USE_ASM=No* rather than unsetting that var completely

**Comment by cemacf** [comment]
I think I am happy now for this specific issue to be closed.  I still have some problems as described above and below, but, where appropriate, I will raise new issues.  Thanks for the help and advice.

www.macfh.co.uk/CEMH.html 

> -----Original Message-----
> From: Nathan Kidd [mailto:notifications@github.com]
> Sent: 05 September 2015 17:26
> To: cisco/openh264
> Cc: cemacf
> Subject: Re: [openh264] Make fails on embedded arm5 NAS: 'CPU_COUNT' was not declared in this scope (#2089)

> 30-second suggestions:
> 1) assembler is quite old, try upgrading

The trouble with this suggestion is that I've tried it many times before, and always encounter some problem or other.  Despite delays caused by a HD crashing in the NAS I was using  -  fortunately it was the secondary HD, not the primary I was using for this, and even more fortunately that is currently being restored from the other NAS; my version of RAID is to have two NASs  -  I've just given it an umpteenth attempt, and although I got further this time than ever before, in that at least this time the dependencies mpc, mpfr, and gmp all made, checked, and installed successfully, gcc itself still failed to make:

	./configure
		--prefix=/opt/share
		--includedir=/opt/include:/opt/share/include:/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/include
		--with-gmp-include=/opt/share/include/
		--with-gmp-lib=/opt/share/lib
		--with-mpfr-include=/opt/share/include/
		--with-mpfr-lib=/opt/share/lib
		--with-mpc-include=/opt/share/include/
		--with-mpc-lib=/opt/share/lib

... note that includedir includes the directory containing stdio.h, yet ...

/root/build/gcc-4.8.2/host-armv5tejl-unknown-linux-gnueabi/gcc/xgcc -B/root/build/gcc-4.8.2/host-armv5tejl-unknown-linux-gnueabi/gcc/ -B/opt/share/armv5tejl-unknown-linux-gnueabi/bin/ -B/opt/share/armv5tejl-unknown-linux-gnueabi/lib/ -isystem /opt/share/armv5tejl-unknown-linux-gnueabi/include -isystem /opt/share/armv5tejl-unknown-linux-gnueabi/sys-include    -g -O2 -O2  -g -O2 -DIN_GCC   -W -Wall -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fPIC -fno-inline -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fPIC -fno-inline -I. -I. -I../../host-armv5tejl-unknown-linux-gnueabi/gcc -I../.././libgcc -I../.././libgcc/. -I../.././libgcc/../gcc -I../.././libgcc/../include  -DHAVE_CC_TLS  -o _muldi3.o -MT _muldi3.o -MD -MP -MF _muldi3.dep -DL_muldi3 -c ../.././libgcc/libgcc2.c -fvisibility=hidden -DHIDE_EXPORTS
In file included from ../.././libgcc/libgcc2.c:27:0:
../.././libgcc/../gcc/tsystem.h:87:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.

> 2) it is usually much easier to upgrade your toolchain and build
> when using a cross-build environment (i.e. on your x86 Linux box
> using e.g. arm-linux-gcc) rather than on the native embeded host

Again, I've tried various cross-build tool chains, including yocto and crosstool-ng, and had problems with both, but as it was a while ago, I can't remember now what the problems were.

3) try USE_ASM=No rather than unsetting that var completely

Ok, will try that.  Thanks.
