### ISSUE TITLE
Is there an option to write mp4 files?

### ISSUE THREAD

**Issue by amtri** [cisco/openh264#2092]
Hello,

This may not be the place for this question. If that's the case, my apologies. But many other forums state that h264=mp4. Apparently, it is not as I should be able to read mp4 files in QuickTime - but I cannot just rename the h264 file to mp4 and play it there.

Is there an option to generate mp4 with h264Enc? If not - or not applicable - if you can point me to how one can generate a mp4 file I would appreciate it.

Thanks.

**Comment by HaiboZhu** [comment]
H.264/AVC is MP4 part 10, not equal to mp4. You can package the h264 file into mp4 file using other tools.

**Comment by sijchen** [comment]
answered.
