### ISSUE TITLE
RC fail for the bitstream 720p5994_parkrun_ter.yuv

### ISSUE THREAD

**Issue by QuPengfei** [cisco/openh264#2095]
hi,

I met one issue when encoding the stream 720p5994_parkrun_ter.yuv with bitrate 2000kbps, but actually the output is 6161Kbps. I use the framerate 30fps.

I noticed it is related to the parameter "SpatialBitrate". if I set it as 2000, the RC will failed. If it is 600, the output bitrate is still ~2000kbps.

BTW, I test on one 1080P stream and did not see the issue.

is this an issue?

attach the cfg file:
# Cisco Scalable H.264/AVC Extension Encoder Configuration File

#============================== GENERAL ==============================
UsageType        0            #0: camera video 1:screen content
SourceWidth      1280          #input video width
SourceHeight     720          #input video height
InputFile       /home/bqu/workspace/stream/YUV_files/720p5994_parkrun_ter.yuv # Input  file
OutputFile              enc.h264               # Bitstream file
MaxFrameRate            30                     # Maximum frame rate [Hz]
FramesToBeEncoded       -1                    # Number of frames (at input frame rate)

TemporalLayerNum       1                     # temporal layer number(1--4)
IntraPeriod            0                    # Intra Period ( multipler of GoP size or -1)
EnableSpsPpsIDAddition  1

EnableFrameCropping 	1 		       # enable frame cropping flag
EntropyCodingModeFlag   0                #0:cavlc 1:cabac
MaxNalSize            0            # Unit:Byte, Maximum Nal size
#============================== LOOP FILTER ==============================
LoopFilterDisableIDC       0                   # Loop filter idc (0: on, 1: off,
                                               # 2: on except for slice boundaries,
                                               # 3: two stage. slice boundries on in second stage
                                               # 4: Luma on but Chroma off (w.r.t. idc=0)
                                               # 5: Luma on except on slice boundaries, but Chroma off in enh. layer (w.r.t. idc=2)
                                               # 6: Luma on in two stage. slice boundries on in second stage, but Chroma off (w.r.t. idc=3)
LoopFilterAlphaC0Offset	0                      # AlphaOffset(-6..+6): valid range
LoopFilterBetaOffset	0                      # BetaOffset (-6..+6): valid range
#============================== SOFTWARE IMPLEMENTATION ==============================
MultipleThreadIdc			    1	# 0: auto(dynamic imp. internal encoder); 1: multiple threads imp. disabled; > 1: count number of threads;

#============================== RATE CONTROL ==============================
RCMode			        1				        # 0: quality mode;  1: bitrate mode;                                             # 2: buffer based mode,can't control bitrate; -1: rc off mode;
TargetBitrate			2000				    # Unit: kbps, controled by EnableRC also
MaxOverallBitrate       0                    # Unit: kbps, max bitrate overall, 0 - unspecified
EnableFrameSkip			0		#Enable Frame Skip

#============================== DENOISE CONTROL ==============================
EnableDenoise                   0              # Enable Denoise (1: enable, 0: disable)

#============================== SCENE CHANGE DETECTION CONTROL =======================
EnableSceneChangeDetection			1			# Enable Scene Change Detection (1: enable, 0: disable)

#============================== BACKGROUND DETECTION CONTROL ==============================
EnableBackgroundDetection		 1     # BGD control(1: enable, 0: disable)

#============================== ADAPTIVE QUANTIZATION CONTROL =======================
EnableAdaptiveQuantization			1			# Enable Adaptive Quantization (1: enable, 0: disable)

#============================== LONG TERM REFERENCE CONTROL ==============================
EnableLongTermReference             1              # Enable Long Term Reference (1: enable, 0: disable)
LtrMarkPeriod                       30             # Long Term Reference Marking Period

#============================== LAYER DEFINITION ==============================
PrefixNALAddingCtrl		0						# Control flag of adding prefix unit (0: off, 1: on)
												# It shall always be on in SVC contexts (i.e. when there are CGS/MGS/spatial enhancement layers)
												# Can be disabled when no inter spatial layer prediction in case of its value as 0
NumLayers              1                      # Number of layers
#//LayerCfg                layer0.cfg		# Layer 0 configuration file
#//LayerCfg                layer1.cfg		# Layer 1 configuration file
LayerCfg                 enc_layer_default.cfg		# Layer 2 configuration file

enc_layer_default.cfg
# Layer Configuration File

#============================== INPUT / OUTPUT ==============================
FrameWidth     1280                     # Input  frame width
FrameHeight    720                    # Input  frame height
FrameRateOut    30                     # Output frame rate [Hz]
ReconFile       rec.yuv          # Reconstructed file

#============================== CODING ==============================
ProfileIdc      66          # value of profile_idc (or 0 for auto detection)

InitialQP       24			# Quantization parameters for base quality layer
#================================ RATE CONTROL ===============================
SpatialBitrate		2000		# Unit: kbps, controled by DisableRC also
MaxSpatialBitrate   0     # Unit: kbps, max bitrate for current layer, 0 - unspecified
#============================== MultiSlice Slice Argument ==============================
# for S/M Slice(s) mode settings
SliceMode			0		# 0: sigle slice mode; >0: multiple slices mode, see below;
SliceSize			1500
SliceNum			1		# multiple slices number specified

SlicesAssign0		960		# count number of MBs in slice #0
SlicesAssign1		0		# count number of MBs in slice #1
SlicesAssign2		0		# count number of MBs in slice #2
SlicesAssign3		0		# count number of MBs in slice #3 -- seting here is for better testing
SlicesAssign4		0		# count number of MBs in slice #4
SlicesAssign5		0		# count number of MBs in slice #5
SlicesAssign6		0		# count number of MBs in slice #6
SlicesAssign7		0		# count number of MBs in slice #7

### DESIGN OF SLICE MODE ####
# 0 SM_SINGLE_SLICE			| SliceNum==1
# 1 SM_FIXEDSLCNUM_SLICE	| according to SliceNum			| Enabled dynamic slicing for multi-thread
# 2 SM_RASTER_SLICE			| according to SlicesAssign		| Need input of MB numbers each slice. In addition, if other constraint in slice_argument is presented, need to follow the constraints. Typically if MB num and slice size are both constrained, re-encoding may be involved.
# 3 SM_ROWMB_SLICE			| according to PictureMBHeight	| Typical of single row of mbs each slice?+ slice size constraint which including re-encoding
# 4 SM_DYN_SLICE			| according to SliceSize		| Dynamic slicing (have no idea about slice_nums until encoding current frame)
# 5 SM_AUTO_SLICE			| according to thread number	| the number of slices is decided by the number of threads,SliceNum is ignored

**Comment by sijchen** [comment]
@ruil2

**Comment by ruil2** [comment]
could you attach openh264 output trace?

**Comment by ruil2** [comment]
no more info
