### ISSUE TITLE
Is "fmtp:102 profile-level-id=4D0029" supported?

### ISSUE THREAD

**Issue by afennell** [cisco/openh264#2097]
Hi
It's seems that it cannot understand something like this:

Media Description, name and address (m): video 6200 RTP/AVP 102
Media Type: video
Media Port: 6200
Media Protocol: RTP/AVP
Media Format: DynamicRTP-Type-102
Media Attribute (a): rtpmap:102 H264/90000
Media Attribute Fieldname: rtpmap
Media Format: 102
MIME Type: H264
Sample Rate: 90000
Media Attribute (a): fmtp:102 profile-level-id=4D0029; packetization-mode=1
Media Attribute Fieldname: fmtp
Media Format: 102 [H264]
Media format specific parameters: profile-level-id=4D0029
Profile: 4d0029
0100 1101 = Profile_idc: Main profile (77)
0... .... = Constraint_set0_flag: 0
.0.. .... = Constraint_set1_flag: 0
..0. .... = Constraint_set2_flag: 0
...0 .... = Constraint_set3_flag: 0
.... 0000 = Reserved_zero_4bits: 0
0010 1001 = Level_id: 41 [Level 4.1 50 Mb/s]
Media format specific parameters: packetization-mode=1
[Packetization mode: Non-interleaved mode (1)]
Media Attribute (a): ex_fmtp:102 2CIF=1
Media Attribute Fieldname: ex_fmtp
Media Attribute Value: 102 2CIF=1

Has anybody experienced troubles of this kind?
Thanks in advance

**Comment by HaiboZhu** [comment]
Hi, 
   Now we only support Constrained Baseline Profile (profile_idc 66), the Main profile (profile_idc 77) has not been supported.
