### ISSUE TITLE
STAP-A NAL Unit Type

### ISSUE THREAD

**Issue by tolis91** [cisco/openh264#2098]
Hi,

does openh264 support NAL Unit Type STAP-A for aggregation packets?

If not supported, are there any suggestions?

Thank you in advance.

**Comment by huili2** [comment]
STAP-A is defined for RTP usage on application level, not on codec level.
You can packetize the encoded NAL unit for any type, whatever aggregation or fragment.

**Comment by tolis91** [comment]
OK!

Thank you very much
