### ISSUE TITLE
Android Implementation

### ISSUE THREAD

**Issue by fire855** [cisco/openh264#2101]
Hello,

is it possible to implement this codec into the android system as alternative to the google h264 decoder?

Regards
Fire

**Comment by huili2** [comment]
Thanks for your concern. If any volunteer is interested in this, it is appreciated.
However, it is beyond the codec itself. We have no plan for that.

**Comment by LifeIsStrange** [comment]
Awesome idea !! But sorry I don't know code, I can Just report bugs. 
Also Just for curiosity, openh264 is better than h264 ? (in term of framerate, power consumption, memory usage, bandwitch usage, etc)

**Comment by LifeIsStrange** [comment]
And why chromium don't use openh264 ?

**Comment by huili2** [comment]
@LifeIsStrange which h264 do you specify? We do not claim openh264 is better than any codec, and anybody can do comparisons if interested. But openh264 can be freely used for webRTC (already paid by Cisco), and is BSD lisensed.

**Comment by LifeIsStrange** [comment]
Forgot it was à stupid question, thank for your answer and sorry to take your time.
