### ISSUE TITLE
Does openh264 support VBR mode?

### ISSUE THREAD

**Issue by QuPengfei** [cisco/openh264#2102]
Does openh264 support VBR mode?

**Comment by zhangweiyu51** [comment]
.mm

**Comment by HaiboZhu** [comment]
Hi, 
   The current openh264 encoder only support the CBR mode. Welcome to contribute on this.

**Comment by HaiboZhu** [comment]
Add a comment: When you initialize the encoder with RC off and fixed the QP with InitializeExt(), you can consider it as a basic VBR.

**Comment by sijchen** [comment]
answered
