### ISSUE TITLE
SSEI not supported - How to obtain TL0PICIDX value in PACSI NAL Unit

### ISSUE THREAD

**Issue by tolis91** [cisco/openh264#2106]
Hi!

I am trying to implement the PACSI NAL Unit in openh264.

As defined in RFC6190, the PACSI NAL Unit contains the field TL0PICIDX that must be equal to tl0_dep_rep_idx as specified in Annex G of [H.264].

However, in order to obtain the value of tl0_dep_rep_idx, the encoder must produce SEI NAL Units (NALU Type = 6), which seems that is not supported yet.

Could you please suggest me an alternative way to obtain tl0_dep_rep_idx, since SEI messages are not supported?

Thank you in advance!

**Comment by HaiboZhu** [comment]
Hi, 
   The tl0_dep_rep_idx which defined in G.13.1.11 has not been supported by current codec. You can not get it directly for the bitstream. I think you can parse the bitstream and calculate it according to G.13.2.11 if you need.

**Comment by tolis91** [comment]
You are right, but I think that there is another way too!
I will try to implement it and, if it works, I will post the alt way of getting TL0PICIDX value.

Anyway, thank you for your reply!
