### ISSUE TITLE
How to set a maximum slice size?

### ISSUE THREAD

**Issue by chuckleplant** [cisco/openh264#2129]
I wanted to set a maximum slice size. For IDR frames I sometimes get frames that are too big. This is for RTSP streaming.

What option should I use if any?

Thanks

**Comment by sijchen** [comment]
set SliceMode to SM_DYN_SLICE and set the targeted size with uiSliceSizeConstraint and iMaxNalSize

**Comment by chuckleplant** [comment]
Thanks!
