### ISSUE TITLE
Get error struct has no member named when build pjsip with openh264?

### ISSUE THREAD

**Issue by jpxiong** [cisco/openh264#2132]
Someone posted a question here : 
http://stackoverflow.com/questions/30207654/get-error-struct-has-no-member-named-when-build-pjsip-with-openh264

Can anyone answer it ?

**Comment by sijchen** [comment]
this may related some version problem, the older version of openh264 has that variable but later versions this is removed.

**Comment by jpxiong** [comment]
So what's the new item instead of  `iInputCsp` ?

Is the following code snippet new way ?
```
int videoFormat = videoFormatI420;
encoder_->SetOption(ENCODER_OPTION_DATAFORMAT, &videoFormat);
```

**Comment by sijchen** [comment]
we now only support on format input so there is no such variable in settings.

**Comment by jpxiong** [comment]
Which format ? 
videoFormatI420 ?

That is to say, if we don't set the input format(No api to set), openh264 will use `videoFormatI420` as default. Right ?

**Comment by sijchen** [comment]
yes

**Comment by jpxiong** [comment]
thanks
