### ISSUE TITLE
Encoding limited to 25 fps

### ISSUE THREAD

**Issue by chuckleplant** [cisco/openh264#2139]
I am encoding a live application, capturing from screen and feeding the encoder frames at a framerate of 30fps. However the output encoded stream is 25 fps, this generates a decoder delay that increases over time. 
I can't find why this is. 

If I set my application to run at 25 fps then both run at the same speed and the decoder catches up, but so far it's impossible to get a 30fps output stream.

This seems related to: #1394

Thanks for the library!

**Comment by sijchen** [comment]
can you output the log and check the lines with "EncoderStatistics"? what is the "SpeedInMs" value there?

**Comment by ruil2** [comment]
@chuckleplant  if you still have questions on this, please submit a new issue and attach the logs. 
we will follow this continually. thanks!
