### ISSUE TITLE
Is it possible to compile the android version only with encode module?

### ISSUE THREAD

**Issue by jpxiong** [cisco/openh264#2144]

**Comment by sijchen** [comment]
Theoretically yes but we did not try that before.

**Comment by jpxiong** [comment]
What's the encode module depend on? After finish compiling , there are `libcommon.a`,	`libdecoder.a`,	`libencoder.a`,	`libopenh264.a` and `libprocessing.a`. Thanks.

**Comment by sijchen** [comment]
libcommon.a and libprocessing.a are what libdecoder.a and libencoder.a depend on. libopenh264.a is a sum of them all.

**Comment by jpxiong** [comment]
Thanks.
