### ISSUE TITLE
Warning sign when I build with Microsoft Visual Studio 2013

### ISSUE THREAD

**Issue by yoolbin92** [cisco/openh264#2145]
Hi
when I build encoder and decoder with visual studio, visual studio tells me that I successfully build them. But I do not see h264dec.exe and h264enc.exe output files. I suspect the warning signs are the causes of the problem. 
How should I solve this problem?

Thanks

Decoder' warning sign

1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1361,5): warning MSB8012: TargetPath(C:\Users\SPI\Desktop\Yool-bin\openh264-master\codec\build\win32\dec\.\..\..\..\..\bin\Win32\Debug\WelsDecCore.lib) does not match the Library's OutputFile property value (C:\Users\SPI\Desktop\Yool-bin\openh264-master\bin\Win32\Debug\welsdcore.lib). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Lib.OutputFile).
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1363,5): warning MSB8012: TargetName(WelsDecCore) does not match the Library's OutputFile property value (welsdcore). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Lib.OutputFile).
1>  WelsDecCore.vcxproj -> C:\Users\SPI\Desktop\Yool-bin\openh264-master\codec\build\win32\dec\.\..\..\..\..\bin\Win32\Debug\WelsDecCore.lib

----------------------------------------------------------------------
Encoder's warning sign

1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1361,5): warning MSB8012: TargetPath(C:\Users\SPI\Desktop\Yool-bin\openh264-master\codec\build\win32\enc\.\..\..\..\..\bin\Win32\Debug\WelsEncCore.lib) does not match the Library's OutputFile property value (C:\Users\SPI\Desktop\Yool-bin\openh264-master\bin\Win32\Debug\welsecore.lib). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Lib.OutputFile).
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1363,5): warning MSB8012: TargetName(WelsEncCore) does not match the Library's OutputFile property value (welsecore). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Lib.OutputFile).
1>  WelsEncCore.vcxproj -> C:\Users\SPI\Desktop\Yool-bin\openh264-master\codec\build\win32\enc\.\..\..\..\..\bin\Win32\Debug\WelsEncCore.lib

**Comment by sijchen** [comment]
please build encConsole/decConsole project for the console exes. is there anything you change in the project settings?

**Comment by yoolbin92** [comment]
That was stupid mistake. 
I set encConsole/decConsole as "Set as startup project"
Now I can compile and debug properly. Thanks for helping
