### ISSUE TITLE
Does openh264 have FMO feature?

### ISSUE THREAD

**Issue by yoolbin92** [cisco/openh264#2146]
When I read encoder's configuration file (.cfg), it seems openh264 does not have FMO option. But  when I skim over the source codes, it seems openh264 has fmo implementation. Does this mean developers plan to include FMO in openh264?
Thanks

**Comment by sijchen** [comment]
no there is no plan yet, we are supporting constrained baseline profile for now and it does not cover that. Welcome to contribute.
