### ISSUE TITLE
Is there any sample decoder configuration file?

### ISSUE THREAD

**Issue by yoolbin92** [cisco/openh264#2166]
I want to decode 264 bitstream with different option but I don't see welsdec.cfg under test folder.
Is it not provided on purpose due to some issue? If it is not, could anyone give me sample decoder cfg file?

Thanks

**Comment by sijchen** [comment]
decoder does not require decoder.cfg when it runs.

**Comment by yoolbin92** [comment]
I know I don't have to use decoder.cfg to decode but if I don't use, openh264 will use default error concealment which is ERROR_CON_SLICE_COPY. Since I want to try with different provided error concealment and the effects, I want to use configuration files.
I can see openh264 has 8 different error concealment. From codec_app_def.h, I see
 ERROR_CON_DISABLE = 0,
  ERROR_CON_FRAME_COPY,
  ERROR_CON_SLICE_COPY,
  ERROR_CON_FRAME_COPY_CROSS_IDR,
  ERROR_CON_SLICE_COPY_CROSS_IDR,
  ERROR_CON_SLICE_COPY_CROSS_IDR_FREEZE_RES_CHANGE,
  ERROR_CON_SLICE_MV_COPY_CROSS_IDR,
  ERROR_CON_SLICE_MV_COPY_CROSS_IDR_FREEZE_RES_CHANGE

Now I made my own configuration file and change error concealment option but I do not see impact of error concealment. So now I wonder if the error concealment implemented in openh264.

Thanks

**Comment by sijchen** [comment]
so you are requiring an option interface for decoder when running as in console. 
@HaiboZhu

**Comment by yoolbin92** [comment]
https://drive.google.com/file/d/0B-WGX6_NyKFSRUVqV3FSZUEtMXc/view?usp=sharing
I am using this damaged bitstream for testing purpose. I use netem to introduce 5% packet loss and VLC to stream. When I use ffmpeg to decode, I get 422 frames in total. However, openh264 decoder gives me 209 frames. Does this tell that openh264 lacks of error concealment? I still need to investigate more what causes this problem but I really appreciate if you suggest me how to approach this problem.

PS. I am sorry that I keep asking question that is unrelated to my topic
Thanks

**Comment by yoolbin92** [comment]
So once I disable NO_DELAY_DECODING under h264dec.cpp I see 421 frames and do not see any frame loss which is good. And I actually have to change value line 107 under h264dec.cpp if I want to change option for error concealment otherwise it won't change.
