### ISSUE TITLE
dsBitstreamError when decoding video

### ISSUE THREAD

**Issue by jeremygeras** [cisco/openh264#2168]
I am getting dsBitstreamError reported when trying to decode the video stream attached.  It is working properly when I use an H.264 decoder from a different vendor, so I am reasonably certain it's an issue with the openh264 decoder.

Note the attachment is a .pcap which I had to rename to .png so that I could successfully attach it to this issue report.

![media_video pcap](https://cloud.githubusercontent.com/assets/15163140/10551622/ce554606-7402-11e5-9358-1a932fbe0a66.png)

**Comment by yoolbin92** [comment]
I don't think openh264 can directly decodes pcap file. I convert pcap into 264 bitstream by using videosnarf. Once you convert, you should be able to decode 264 bitstream
http://ucsniff.sourceforge.net/videosnarf.html

**Comment by jeremygeras** [comment]
I use my own tools to replay the packets from the pcap to the decoder.  The tools are not in question, as they work well enough with other streams.

**Comment by jeremygeras** [comment]
Debugged this a bit more, and the error seems to come from this block in ParseSliceHeaderSyntaxs(..):

    if (pSliceHead->iFrameNum != 0) {
      WelsLog (pLogCtx, WELS_LOG_WARNING,
               "ParseSliceHeaderSyntaxs(), invaild frame number: %d due to IDR frame introduced!",
               pSliceHead->iFrameNum);
      return GENERATE_ERROR_NO (ERR_LEVEL_SLICE_HEADER, ERR_INFO_INVALID_FRAME_NUM);
    }

...  in my case pSliceHead->iFrameNum is 8

**Comment by jeremygeras** [comment]
And furthermore I just confirmed that if I comment out the above 'if' block and allow the function to continue, then I can see video.

So ...  what is this check pSliceHead->iFrameNum != 0 actually good for?

**Comment by huili2** [comment]
This judge exists for IDR picture, where iFrameNum should be equal to 0. 
It seems your bitstream is not compliant to Rec.

**Comment by jeremygeras** [comment]
Will anything really bad happen if we just comment out that block?  Is this something that perhaps should be adopted into openh264 for increased interoperability?

**Comment by huili2** [comment]
If permitted, unexpected results would happen to many cases. So openh264 would not support such illegal bitstream decoding, especially for IDR error.
