### ISSUE TITLE
Could you explain about error concealment?

### ISSUE THREAD

**Issue by yoolbin92** [cisco/openh264#2169]
under typedef enum ERROR_CON_IDC, I can see eight different error concealment types.
I understand other types of concealment but I do not understand what FREEZE_RES_CHANGE does.
Could anyone explain how FREEZE_RES_CHANGE is supposed to do in error concealment?
Thanks

**Comment by huili2** [comment]
FREEZE_RES_CHANGE means when resolution changes and error happens to that specific IDR picture, EC will not take effect. (Current simple EC methods cannot well handle this case.) Decoder will not output any data until next complete IDR comes and is successfully decoded.
