### ISSUE TITLE
Different compression results from multiple runs when running multithreaded.

### ISSUE THREAD

**Issue by GregoryJWolfe** [cisco/openh264#2181]
I am running ffmpeg with libopenh264.  I'm using it to convert a .mov video file to .mp4 with H264 compression.  When I run single threaded/single sliced I get the same result each time.  However, with two threads/two slices I get slightly different results each time.  I've attached a Windows batch script that demonstrates the problem.  The batch script references "in.mov" as the input video, but since I've seen this problem using more than one input .mov file, you should be able to see the problem using any old .mov file you have lying around.

The attached Windows batch script converts the .mov file twice, extracts the individual frames from each output to TIFF image files, then does a pixel compare of corresponding frames.  The program PixCompare.exe is a diagnostic program I have that performs that function, exiting with an exit code of 0/1 if the images match/don't match.  Hopefully you have a similar image compare program available.

Here's some relevant information about the environment I am using:

FFmpeg version:  2.6.2
libopenh264 version:  v1.5.0 (openh264-master.zip, downloaded 10/21/2015)
Build environment:  MinGW on Windows 7
Runtime environment:  Windows 7

THE SYSTEM WOULD NOT LET ME ATTACH A FILE; SEE CONTENTS BELOW:
>
@ setlocal
@ prompt $G
@ rem --- run test using 1 thread/slice
@ rem --- delete previous results
@ if  EXIST *.mp4  @ del *.mp4
@ if  EXIST *.tif  @ del *.tif
@ rem --- convert .MOV to .MP4 with H264 video twice
ffmpeg.exe -y -v 32 -ss 0 -i in.mov -f mp4 -vcodec libopenh264 -vframes 60 -strict -2 -an -threads 1 -slices 1 out1.mp4
ffmpeg.exe -y -v 32 -ss 0 -i in.mov -f mp4 -vcodec libopenh264 -vframes 60 -strict -2 -an -threads 1 -slices 1 out2.mp4
@ rem --- extract individual frames to TIFF images
ffmpeg.exe -y -v 32 -ss 0 -i out1.mp4 -f image2 -pix_fmt rgb24 -vcodec tiff -vframes 60 -strict -2  "out1f%%03d.tif"
ffmpeg.exe -y -v 32 -ss 0 -i out2.mp4 -f image2 -pix_fmt rgb24 -vcodec tiff -vframes 60 -strict -2  "out2f%%03d.tif"
@ rem --- compare frames
@ for  %%B in ( out1*.tif )  do  @ call :CompareFrames "%%~fB"
@ pause
@ rem --- run test using 2 threads/slices
@ rem --- delete previous results
@ if  EXIST *.mp4  @ del *.mp4
@ if  EXIST *.tif  @ del *.tif
@ rem --- convert .MOV to .MP4 with H264 video twice
ffmpeg.exe -y -v 32 -ss 0 -i in.mov -f mp4 -vcodec libopenh264 -vframes 60 -strict -2 -an -threads 2 -slices 2 out1.mp4
ffmpeg.exe -y -v 32 -ss 0 -i in.mov -f mp4 -vcodec libopenh264 -vframes 60 -strict -2 -an -threads 2 -slices 2 out2.mp4
@ rem --- extract individual frames to TIFF images
ffmpeg.exe -y -v 32 -ss 0 -i out1.mp4 -f image2 -pix_fmt rgb24 -vcodec tiff -vframes 60 -strict -2  "out1f%%03d.tif"
ffmpeg.exe -y -v 32 -ss 0 -i out2.mp4 -f image2 -pix_fmt rgb24 -vcodec tiff -vframes 60 -strict -2  "out2f%%03d.tif"
@ rem --- compare frames
@ for  %%B in ( out1*.tif )  do  @ call :CompareFrames "%%~fB"
@ pause
@ goto :EOF
:CompareFrames
@ echo.compare %~n1
@ set Other="%~1"
@ set Other=%Other:out1=out2%
@ PixCompare.exe %1 %Other%
@ set Status=%ERRORLEVEL%
@ if  %Status% neq 0  @ pause
@ goto :EOF

**Comment by sijchen** [comment]
when being set with multi-threading, under the slice modes of "SM_FIXEDSLCNUM_SLICE", "SM_DYN_SLICE" and "SM_AUTO_SLICE", openh264 encoder will do load-balancing by changing the slicing in a picture. This will make the running under multi-threading not identical at each run. I am not sure how the parameter is when ffmpeg calling openh264

**Comment by GregoryJWolfe** [comment]
Here is the relevant FFmpeg source code (libopenh264enc.c).  In my usage I have set avctx->slices = 2, and have set the number of threads to 2.

    AVCodecContext *avctx;
    SVCContext *s = avctx->priv_data;
    SEncParamExt param = { 0 };

    s->slice_mode = SM_AUTO_SLICE;
    if (avctx->slices > 1)
        s->slice_mode = SM_FIXEDSLCNUM_SLICE;
    param.sSpatialLayers[0].sSliceCfg.uiSliceMode               = s->slice_mode;
    param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceNum = avctx->slices;

Can you explain how/why the multithread results are not identical?  I.e., are the results in this case “wrong”, or “valid but different because …”?

Greg W.

_______________________________
Gregory J. Wolfe | Software Engineer
Imaging – Consumer, Retail Systems Solutions | Kodak Alaris Inc., 2400 Mt. Read Blvd,Rochester, NY 14615
gregory.wolfe@kodakalaris.com | 585.441.7735 | Fax 585.722.6324 |
www.kodakalaris.com
[cid:image001.png@01D0784F.34F11A30]
Information contained in this e-mail transmission may be privileged, confidential, and covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521.

If you have received this e-mail transmission in error, please treat it as you would like your own email sent in error to be treated:

·         notify us immediately by return email of the error, and

·         delete the message from your system without reading, forwarding, or copying it.

Thank you in advance for your courtesy!

**Comment by sijchen** [comment]
it is “valid but different because" the slicing may be re-allocated for load-balancing among the threads, during the run-time of the encoder.

**Comment by GregoryJWolfe** [comment]
Sijchen:

Is the difference in the result due to something like a random number used to seed the processing of each slice?  Or does the processing of each slice depend on results or state from the processing of previous slices?

Greg W.

_______________________________
Gregory J. Wolfe | Software Engineer
Imaging – Consumer, Retail Systems Solutions | Kodak Alaris Inc., 2400 Mt. Read Blvd,Rochester, NY 14615
gregory.wolfe@kodakalaris.com | 585.441.7735 | Fax 585.722.6324 |
www.kodakalaris.com
[cid:image001.png@01D0784F.34F11A30]
Information contained in this e-mail transmission may be privileged, confidential, and covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521.

If you have received this e-mail transmission in error, please treat it as you would like your own email sent in error to be treated:

·         notify us immediately by return email of the error, and

·         delete the message from your system without reading, forwarding, or copying it.

Thank you in advance for your courtesy!

**Comment by mstorsjo** [comment]
As far as I understand, it tries to adjust how the images are divided into slices in a way to make sure that each slice takes about the same amount of time to encode, so the division depends on the individual runtime of each encode.

If you add a `return false;` at the start of `NeedDynamicAdjust` in `codec/encoder/core/src/slice_multi_threading.cpp`, the results end up deterministic in my tests.

**Comment by mstorsjo** [comment]
So perhaps it would be useful to add an option for disabling the dynamic slice adjustment, which potentially can give slightly worse performance, but allows getting deterministic results.

**Comment by sijchen** [comment]
yes, it is "tries to adjust how the images are divided into slices in a way to make sure that each slice takes about the same amount of time to encode"

**Comment by sijchen** [comment]
yes we can add the option

**Comment by GregoryJWolfe** [comment]
First, thanks for taking the time to investigate this.

Second, we would definitely use the "no dynamic adjustment" option to get deterministic results for the current work we are doing, which is analyzing the tradeoff between quality and compressed file size.  Given that the "dynamic adjustment" gives "valid but different" results that are not visually apparent, we might choose to turn on the dynamic adjustment when generating products for the consumer in order to get the (anticipated) slightly better performance when running with multiple threads.

Next question:  if dynamic adjustment is not being performed, then multi-threaded executions will produce the same result from run to run.  Will THAT result match the result from a single threaded run?

**Comment by sijchen** [comment]
For now, you can try using slice-mode = 2, and set the MB numbers in each slice, to avoid the dynamic adjustment.

The answer to the next question should be yes, if no, pls let us know.

**Comment by del** [comment]
Hey guys, I guess you used a function called @del somewhere because I'm
being copied on all this and I'd rather not be :)

Feel free to remove me from the cc line.

Cheers,
Daniel

**Comment by GregoryJWolfe** [comment]
The quickest test I could try (based on my current understanding of libopenh264) was to use mstorsjo's modification of always returning false from NeedDynamicAdjust().  With that change, I ran various combinations of threads=1 or 2 with slices=1 or 2, all with slice_mode=SM_FIXEDSLCNUM_SLICE.

Test results:

(1) For two runs with the same thread/slice values, the output is now deterministic (i.e., output doesn't change from run to run).

(2) For two runs with slices=1, output is always the same, thread count doesn't matter.

(3) For one run with slices=1 and one with slices=2, the output is different.  In particular, the output from threads/slices=1/1 does not match that from threads/slices=2/2.

(4) For two runs with slices=2, the only way to get matching output is if threads=2 for both runs.

Is this what you expected?
----------
DANIEL , SORRY IF YOU GET THIS MESSAGE... I'm just using the GitHub "Comment" feature.  To paraphrase the Wizard as the balloon left Oz, "I can't make it stop!  I don't know how it works!"

**Comment by GregoryJWolfe** [comment]
I have no idea why "Is this what you expected?" is in a larger/bold font!

**Comment by sijchen** [comment]
I don't see there is problem with the 4 tests mentioned in the latest post.

----

I guess the emails are related to your original post, I've edited it and hopefully it stops bugging Daniel

**Comment by GregoryJWolfe** [comment]
OK.  I will continue to use my locally modified version of the libopenh264 source until the option to turn on/off the dynamic slice adjustment is available.

**Comment by sijchen** [comment]
loadbalancing can be turned off now with the commit f3c4b878ffde64307deb68ba4b6668d119fdfcdf
