### ISSUE TITLE
How to limit the size of a SLayerBSInfo?

### ISSUE THREAD

**Issue by jpxiong** [cisco/openh264#2182]
I got a problem that the number of nal is `28` in only one `SLayerBSInfo`. Thus, the buffer size is 226345, too large. Is there any way to limit the size of one `SLayerBSInfo`?

**Comment by HaiboZhu** [comment]
The buffer size is relate with the output video resolution, quality, content, etc. If you want to reduce the total nal size, please reduce the resolution, quality, bit rate, etc.
