### ISSUE TITLE
How to extract YUV  values from every pixel in frame?

### ISSUE THREAD

**Issue by yoolbin92** [cisco/openh264#2183]
I am trying to extract YUV information from DPB.
I can see that under PWelsDecoderContext data structure, there is pPreviousDecodedPictureInDpb and it points to pData[0], pData[1], pData[2]. Respectively each one should represent Y, U, and V. But these are types of uint8_t which I do not understand.

How does pData which is typedef unsigned char represent YUV for pixels? Could you explain how to convert pData[0,1,2] to extract YUV for every pixels? Thanks in advance.

**Comment by sijchen** [comment]
pData[0], pData[1], pData[2] point to Y/U/V component of a frame.
uint8_t is unsigned char

**Comment by yoolbin92** [comment]
So
pData[0] points to a iMbX x iMbY area of Y (luma) values.
pData[1] points to a iMbX/2 x iMbY/2 area of Cr (U) values.
pData[2] points to a iMbX/2 x iMbY/2 area of Cb (V) values.

Assume I have 352 x 288 resolution video. If I want to find YUV from first pixel located at (0,0).
pData[0][0] should give me Y value of first pixel because 0 x 0 + 0 is 0. Is this correct?
What if I want to find YUV from pixels at (0,15), (15, 0), or (15,15)? These pixels should be from first Macroblock.

**Comment by sijchen** [comment]
iMbX/Y -> iPixelX/Y

check the Stride or Linesize value under that struct for the stride for accessing the start of each row.

**Comment by yoolbin92** [comment]
Hi sijchen:
Thanks for responding and sorry about keep asking.
But I still cannot find the correct formula for finding index for pData[0][?]
Lets say I want to find Y values from one MB which has 16 pixels.

for (int i = 0; i < 16; i++){
         strider = iLinesieze[0];
         index = iMbY * 16 * strider + iMbX * 16 + i;  // Is this correct formula?
         Yvalue = pData[0][index];
}

I do not get correct Y value when I used above formula.

**Comment by sijchen** [comment]
one MB is 16x16=256 pixel.
the above one is the first row of that MB and you need to make sure the stride is correct.
