### ISSUE TITLE
build error "error: symbol `XGETBV' redefined" for android "ARCH=x86"

### ISSUE THREAD

**Issue by jpxiong** [cisco/openh264#2202]
I got a build error:

```
codec/common/x86/cpuid.asm:196: error: symbol `XGETBV' redefined
```

The NDK version is `android-ndk-r10d`

The command i used is:

```
make -B OS=android ARCH=x86 TARGET=android-21 NDKLEVEL=21 NDKROOT=~/Library/Android/android-ndk-r10d/
```

**Comment by huili2** [comment]
I also use the same NDK version on android-23, but meet no problem. How about other environment, like nasm, etc?

**Comment by mstorsjo** [comment]
What nasm version do you use? I.e., what does `nasm -v` say?

**Comment by jpxiong** [comment]
```
$ nasm -v
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Aug 17 2015
```
@mstorsjo

**Comment by mstorsjo** [comment]
Ok, so your nasm tool is way too old, you need a much newer one.

(Also note that the latest stable version of nasm, 2.11.08, is broken for 64 bit mac osx, so if you want to build for OS X as well, you should take e.g. the previous release, 2.11.06.)

**Comment by jpxiong** [comment]
It works fine after i upgrade the nasm. Thanks. @mstorsjo

**Comment by Pauldic** [comment]
Upgrade solved this issue for me
