### ISSUE TITLE
Long Term Reference frame usage

### ISSUE THREAD

**Issue by miseri** [cisco/openh264#2203]
Where can I find more information regarding the **Long Term Reference** frames and how they are intended to be used?

Specifically, is it possible to use the "*Long Term Reference (LTR) frames*" capability together with the "*Reference picture list modification*" to tell the encoder which frames can be used as a reference
for subsequent frames and change the reference frames e.g. as feedback arrives from the receiver?
 
Any pointers would be appreciated.

**Comment by sijchen** [comment]
need to set: "bEnableLongTermReference" to be true.

check the encoder's SetOption with the following options:
ENCODER_LTR_RECOVERY_REQUEST,
  ENCODER_LTR_MARKING_FEEDBACK,
  ENCODER_LTR_MARKING_PERIOD,
  ENCODER_OPTION_LTR,

**Comment by miseri** [comment]
sijchen, thanks for the reponse. I had seen all those options in the source code, but that doesn't answer my question.

Could you please elaborate on how to use the feature, i.e.  when to set ENCODER_LTR_RECOVERY_REQUEST, etc. or alternatively, is there sample code
on how to use it?

**Comment by sijchen** [comment]
**Use**:
1, enable LTR with "ENCODER_OPTION_LTR" and set "ENCODER_LTR_MARKING_PERIOD" if you want it
2, use "ENCODER_LTR_MARKING_FEEDBACK" to mark the LTR frames which are successfully received by receiver side
3, use "ENCODER_LTR_RECOVERY_REQUEST" when received a recovering request from receiver


**Sample codes**: 
in the UT file of encode_decode_api_test.cpp, you can find several test case related to LTR, just search by name.
BTW, we are planning to separate different function UTs into different files, so those test case may be moved to some other file and not in encode_decode_api_test.cpp in the future.
