### ISSUE TITLE
OpenH264 did not reach target bitrate

### ISSUE THREAD

**Issue by dcpang** [cisco/openh264#2205]
I have been trying to bennchmark rate-distortion performance of openh264 against x264. However, I have been having trouble setting target bitrate above 1 Mpbs. 

I use the following commands:
h264enc -org input.yuv -sw 1280 -sh 720 -frms <number of frames> -utype 1 -nalsize 50000 -frin 30 -cabac 1 -rc 1 -tarb 2500 -maxbrTotal 2500 -numtl 0 -iper 0 -numl 1 -ltarb 0 2500 -lmaxb 0 2500 -fs 0 -dw 0 1280 -dh 0 720 -frout 0 30 -lqp 0 0 -slcmd 0 4  -bf output.h264

When I calculate the target bitstream size, the target bitrate is only around 1 Mbps with a PSNR distortion of around 42 dB. Is this because there is internal constraint in terms of minimal QP ?

**Comment by sijchen** [comment]
yes there is minimal QP, pls check iMinQp in input parameter, note that there are some work undergoing with multi-slicing, the setting of "-slcmd 0 4"  may have encoding problem when the bit stream is too large.

**Comment by dcpang** [comment]
Thanks, @sijchen , how to modify minQP on the command line ?

**Comment by sijchen** [comment]
seems it is missed in console for standalone running, we will add them later. It is available in the encoder interface though

**Comment by sijchen** [comment]
commit for adding interface in console ab7eb1535dfb55984c43e021dfa676158f2d0d3c

**Comment by thompon** [comment]
Hello,
Do you know where the rate-distortion optimization is computed in the source code?
In which .cpp file is it?
Thanks in advance!
