### ISSUE TITLE
problem building openh264 for android platform

### ISSUE THREAD

**Issue by riazhasan93** [cisco/openh264#2214]
I'm trying to build openh264 for android with following command : 
```
$ make OS=android NDKROOT=/Users/nazmulhasan/android-ndk-r10d TARGET=android-17 ARCH=x86
```

And getting the following error:
```
/Users/nazmulhasan/android-ndk-r10d/toolchains/x86-4.8/prebuilt/darwin-x86/bin/../lib/gcc/i686-linux-android/4.8/../../../../i686-linux-android/bin/ld: error: codec/common/cpu-features.o: incompatible target
codec/common/src/WelsThreadLib.o:WelsThreadLib.cpp:function WelsQueryLogicalProcessInfo: error: undefined reference to 'wels_getCpuCount'

```

**Comment by sijchen** [comment]
Hi, can you try: 
> make OS=android NDKROOT=/Users/hfvideomac/wspace/bin/android-ndk-r9d TARGET=android-19

**Comment by mstorsjo** [comment]
It sounds to me like your build environment is unclean (e.g. `codec/common/cpu-features.o` exists but is for a different architecture). To clean it properly, do `make OS=android NDKROOT=/Users/nazmulhasan/android-ndk-r10d TARGET=android-17 ARCH=x86 clean`, not just `make clean`, since the latter will probably miss removing the android specific object files.

**Comment by huili2** [comment]
another method is, to add explicit file removing command for "clean_Android", i.e., add "codec/common/src/cpu-features.o" in "clean_Android".
@mstorsjo is it OK, as we have already defined "clean_Android" in Makefile?

**Comment by jpxiong** [comment]
I got the following error. Any suggestion? Thanks.
```
nasm -DX86_32 -f elf -I./codec/common/x86/   -o codec/common/x86/cpuid.o codec/common/x86/cpuid.asm
codec/common/x86/cpuid.asm:196: error: symbol `XGETBV' redefined
make: *** [codec/common/x86/cpuid.o] Error 1

```

**Comment by mstorsjo** [comment]
@jpxiong Don't hijack others' issue reports just to get attention to your own.

**Comment by mstorsjo** [comment]
@huili2 That doesn't really help, since clean_Android is only called if you do "make OS=android clean". If you just do "make clean", it won't do clean_Android.

**Comment by riazhasan93** [comment]
thanks all i solved it using @mstorsjo  solutions.

**Comment by etworker** [comment]
@mstorsjo 's solution is work for me, thanks!

**Comment by mcjambi** [comment]
i have add "clean after "OS=android" and it worked!
