### ISSUE TITLE
iOS x86_64 compiling failed

### ISSUE THREAD

**Issue by dieforfree** [cisco/openh264#2216]
I try to cross-compile openh264 on my Mac, and the target is iPhone simulator, but without luck. I compile successfully  when set target to armv7, arm64 or i386. Can u guys give me a hint what I missing?  Thanks!

**Here is what I got**

```gcc
....
nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/common/x86/deblock.o codec/common/x86/deblock.asm
codec/common/x86/deblock.asm:1758: fatal: No section for index 2 offset 0 found
```

**Compile environment**
System: OS X 10.11.1
iPhoneSimulator SDK: 9.1
clang++: Apple LLVM version 7.0.0 (clang-700.1.76)/Target: x86_64-apple-darwin15.0.0/Thread model: posix
nasm: 2.11.08

**Command to compile**
make OS=ios arch=x86_64

**Openh264 version**
Both lastest(643df65c585b87a980679fe4a3f1a30732c3feca) and v1.0.0 (bdb7d758c1edce3c42c7fdc203328aae28f08008), and both produce the same error.

**Comment by zhilwang** [comment]
Can you try the nasm 2.11.06?

**Comment by dieforfree** [comment]
@zhilwang I have tried nasm 2.11.06, Both versions and all archs (armv7, armv7s, arm64, i386 and x86_64) compile successfully. Thank you for the quick response. 
One more question,  I got messages like `XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenh264.a(coeff.o) has no symbols` when set arch to x86_64, is that an error or I can ignore it safely? Thanks again.

**Comment by zhilwang** [comment]
You can just ignore it. It only works on ARCH=i386.
