### ISSUE TITLE
How to use openH264 to decode RTSP in iOS ?

### ISSUE THREAD

**Issue by yjjwxy2** [cisco/openh264#2218]
I looked at the decode demo,but I don't know how to use.I hope to have a detailed steps.Thanks

**Comment by sijchen** [comment]
the input of decoder is supposed to be binary 264 bitstream.

**Comment by yjjwxy2** [comment]
not the url address？rtsp://admin@123456@192.168.1.233:9554/std/monitor/1000009$1$0$0/1
this address is not useful？

**Comment by miseri** [comment]
RTSP is a signaling protocol which typically transports H.264 over RTP. openh264 is a library that implements the H.264 video coding standard and has *nothing* to do with transport. Use a library like live555 (www.live555.com) for RTSP/RTP/RTCP, and then you can pass the received H.264 frames to the openH264 decoder.
