### ISSUE TITLE
Input data with YUY2 or BGRA when encode

### ISSUE THREAD

**Issue by oiramario** [cisco/openh264#2226]
How to fill SSourcePicture structure member when I want encode webcam YUY2 video to h264.
Thanks for any reply.

**Comment by huili2** [comment]
@oiramario openh264 supports only I420 input.

**Comment by oiramario** [comment]
What about EVideoFormatType, it's used for output or ?

**Comment by huili2** [comment]
It is used for possible future usage. But now it is not done yet.

**Comment by oiramario** [comment]
It's clear, thanks.
