### ISSUE TITLE
Can not open h264 source file, check its legal path related please

### ISSUE THREAD

**Issue by yjjwxy2** [cisco/openh264#2229]
What is legal path?
I will decode this url address: rtsp://admin:123456@192.168.1.51:554/mpeg4   with h264.
  if (kpH264FileName) {
    pH264File = fopen (kpH264FileName, "rb");
     
    if (pH264File == NULL) {
      fprintf (stderr, "Can not open h264 source file, check its legal path related please..\n");
      return;
    }
kpH264FileName =  rtsp://admin:123456@192.168.1.51:554/mpeg4
Why pH264File is null?

**Comment by huili2** [comment]
It is not related to codec level. Please check with other on this.
btw: if the file is not raw h264 bitstream, e.g., encapsulated in mp4/mkv/avi/... format, it cannot be correctly decoded.

**Comment by sijchen** [comment]
close because of no update
