### ISSUE TITLE
Missing license headers in many source files

### ISSUE THREAD

**Issue by henbos** [cisco/openh264#2233]
Assuming we want all files to have license headers they need to be added to the following files.
(Note: the list may be incomplete or contain errors. It was produced by a script we use in the chromium project to check license headers on a few weeks old commit.)

/testbin/CmdLineExample.sh
/build/mktargets.py
/build/mktargets.sh
/autotest/unitTest/android/run_AutoTest_android.sh
/autotest/unitTest/ios/run_AutoTest_ios.sh
/autotest/unitTest/run_unitTest.sh
/autotest/performanceTest/android/run_AutoTest_android.sh
/autotest/performanceTest/ios/run_AutoTest_ios.sh
/autotest/performanceTest/parsePerfData.sh
/code-coverage.sh
/docs/doxygen2rst.py
/codec/build/android/dec/jni/myjni.cpp
/codec/build/android/dec/src/com/wels/dec/WelsDecTest.java
/codec/build/android/enc/jni/myjni.cpp
/codec/build/android/enc/src/com/wels/enc/WelsEncTest.java
/codec/build/windowsphone/all/CodecApp/Properties/AssemblyInfo.cs
/codec/build/windowsphone/all/CodecApp/App.xaml.cs
/codec/build/windowsphone/all/CodecApp/MainPage.xaml.cs
/codec/build/windowsphone/all/CodecApp/LocalizedStrings.cs
/codec/build/windowsphone/all/CodecRTComponent.h
/codec/build/windowsphone/all/CodecRTComponent.cpp
/codec/common/generate_version.sh
/codec/common/inc/version.h
/codec/common/inc/deblocking_common.h
/codec/common/src/deblocking_common.cpp
/run_Test.sh
/test/processing/ProcessUT_VaaCalc.cpp
/test/processing/ProcessUT_ScrollDetection.cpp
/test/processing/ProcessUT_DownSample.cpp
/test/processing/ProcessUT_AdaptiveQuantization.cpp
/test/utils/InputStream.h
/test/utils/HashFunctions.h
/test/utils/FileInputStream.h
/test/utils/DataGenerator.h
/test/utils/BufferedData.h
/test/build/android/jni/codec_unittest.cpp
/test/build/android/src/com/cisco/codec/unittest/MainActivity.java
/test/build/ios/codec_unittest/codec_unittest/ViewController.m
/test/build/ios/codec_unittest/codec_unittest/ViewController.h
/test/build/ios/codec_unittest/codec_unittest/AppDelegate.m
/test/build/ios/codec_unittest/codec_unittest/main.m
/test/build/ios/codec_unittest/codec_unittest/AppDelegate.h
/test/build/windowsphone/codec_ut/CodecUTApp/Properties/AssemblyInfo.cs
/test/build/windowsphone/codec_ut/CodecUTApp/App.xaml.cs
/test/build/windowsphone/codec_ut/CodecUTApp/MainPage.xaml.cs
/test/build/windowsphone/codec_ut/CodecUTApp/LocalizedStrings.cs
/test/build/windowsphone/codec_ut/Codec_UT_RTComponent.h
/test/build/windowsphone/codec_ut/Codec_UT_RTComponent.cpp
/test/encoder_binary_comparison/run_PrepareAllTestData.sh
/test/encoder_binary_comparison/Scripts/run_ParseYUVInfo.sh
/test/encoder_binary_comparison/Scripts/run_SafeDelete.sh
/test/encoder_binary_comparison/Scripts/run_BitStreamToYUV.sh
/test/encoder_binary_comparison/Scripts/run_BinarySHA1Comparison.sh
/test/encoder_binary_comparison/run_Main.sh
/test/decoder/DecUT_IdctResAddPred.cpp
/test/decoder/DecUT_ErrorConcealment.cpp
/test/decoder/DecUT_DecExt.cpp
/test/decoder/DecUT_DeblockCommon.cpp
/test/decoder/DecUT_ParseSyntax.cpp
/test/decoder/DecUT_Deblock.cpp
/test/decoder/DecUT_IntraPrediction.cpp
/test/decoder/DecUT_PredMv.cpp
/test/encoder/EncUT_MotionCompensation.cpp
/test/encoder/EncUT_ExpGolomb.cpp
/test/encoder/EncUT_ParameterSetStrategy.cpp
/test/encoder/EncUT_Sample.cpp
/test/encoder/EncUT_MotionEstimate.cpp
/test/encoder/EncUT_MBCopy.cpp
/test/encoder/EncUT_DecodeMbAux.cpp
/test/encoder/EncUT_GetIntraPredictor.cpp
/test/encoder/EncUT_EncoderMb.cpp
/test/encoder/EncUT_EncoderMbAux.cpp
/test/encoder/EncUT_SVC_me.cpp
/test/encoder/EncUT_InterfaceTest.cpp
/test/encoder/EncUT_MemoryAlloc.cpp
/test/encoder/EncUT_MemoryZero.cpp
/test/encoder/EncUT_EncoderExt.cpp
/test/encoder/EncUT_Reconstruct.cpp
/test/api/simple_test.cpp
/test/api/decoder_test.cpp
/test/api/encoder_test.cpp
/test/api/BaseEncoderTest.cpp
/test/api/encode_decode_api_test.cpp
/test/api/c_interface_test.c
/test/api/BaseDecoderTest.cpp
/test/api/cpp_interface_test.cpp
/test/api/DataGenerator.cpp
/test/api/decode_encode_test.cpp
/test/BaseEncoderTest.h
/test/BaseDecoderTest.h
/test/test_stdint.h
/test/common/ExpandPicture.cpp

**Comment by HaiboZhu** [comment]
Thanks for your suggestions. Welcome to contribute on openh264 project.
