### ISSUE TITLE
Using settings to reach very low bitrate

### ISSUE THREAD

**Issue by Jobq** [cisco/openh264#2243]
Hi,

I am trying to perform encoding with very low bitrates (~50kbps) on a 854x480 video and it seems the encoder setting are not well taken into account since the generated video is a 170kbps one. 

I tried to modify the QP parameters, wouldn't change anything on the bitrate though. 

Are there any settings I could use to achieve very low bitrate encoding ??

**Comment by sijchen** [comment]
what is the current parameter you are using?

**Comment by ruil2** [comment]
no more info. if have the same issue again, please submit a new one.
