### ISSUE TITLE
No debug symbols for non-Windows release builds

### ISSUE THREAD

**Issue by luser** [cisco/openh264#2252]
https://github.com/cisco/openh264/commit/b5792a09f9c80c0f0bf3a6faacd8883c086817e6 fixed the Windows build so we get PDB files when building release, but on other platforms we're not building with debug symbols, so we won't get good symbols for crash reporting etc.

This should be as simple as adding -g to C[XX]FLAGS, but we'll probably also want a make target to strip the binaries for release.

**Comment by HaiboZhu** [comment]
Thanks for your suggestion and we will add it soon. Welcome to contribute on openh264 project.

**Comment by pengyanhai** [comment]
Hi @HaiboZhu, this fix should be included in v1.5.2 which was supposed to be released on Nov 24th according to Maire. I talked to Sijia and others in SJ and we are not able to make it done before the date. So I asked @luser to submit a PR for us. Please contact @luser about how to get the fix done as soon as possible.

**Comment by ruil2** [comment]
added debug symbols
