### ISSUE TITLE
multithreaded decoding with multiple sliced bitstream

### ISSUE THREAD

**Issue by soliton4** [cisco/openh264#2290]
my bitstream is using 4 slices, i was hoping to get better decoding time by default when using the newest 1.5 version.
however there is no noticable difference between 1 sliced encoded video and 4 sliced.
is there some config value i need to use to enable multithreaded decoding?

i am using the openh264 windows dll inside a node native module.

**Comment by sijchen** [comment]
the decoder does not support multi-thread decoding yet.

**Comment by soliton4** [comment]
oh i missread the release notes. thought it was mentioning multithreaded decoding.

any idea when decoding will be multithreaded?

**Comment by soliton4** [comment]
or could you point me in the direction of where multithreaded decoding could be implemented? maybe i could help?

**Comment by sijchen** [comment]
@HaiboZhu for the question.

**Comment by sijchen** [comment]
BTW, @soliton4 thanks a lot for the intention to help!

**Comment by soliton4** [comment]
@HaiboZhu @sijchen i got an agreement from my employer that i could at least try to contribute multithreaded decoding.
i would need a few pointers thou because i am not quite sure how slices are implemented in h264 stream and how much the threads need to depend on each other.

any chance you could help me out here?

**Comment by HaiboZhu** [comment]
Sorry for late reply. We have no plan about multi threads decoding recently. Thanks for your contribution on openh264 project. We can discuss the details by email. My email address is: haibozhu@cisco.com

**Comment by lthung13** [comment]
@HaiboZhu  and @soliton4,

We understood that multi-threads decoding wasn't planned to be supported at openh264 library but might you please share us multithreaded decoding implementation?
It would be great help for us in digging to performance matter.

My email is: letronghung@gmail.com

Thanks in advanced,
Hung
