### ISSUE TITLE
Use openh264 in VLC?

### ISSUE THREAD

**Issue by yoolbin92** [cisco/openh264#2293]
I am not sure if I can ask this question here but I wonder if it is possible to replace VLC's decoder with openh264 decoder.

I believe VLC uses ffmpeg to decode h264 bitstream so I think I just need to replace ffmpeg decoder with openh264 decoder.
How should I approaching this problem? Can someone share ideas how to do this?

**Comment by volvet** [comment]
it is not suitable place to discuss the topic.      
However,     it is not difficult to integrate openh264 decoder into ffmpeg,   you need design AVCodec base on openh264 APIs.     things like that:

```

AVCodec ff_h264_vdpau_decoder = {
    .name           = "h264_vdpau",
    .long_name      = NULL_IF_CONFIG_SMALL("H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (VDPAU acceleration)"),
    .type           = AVMEDIA_TYPE_VIDEO,
    .id             = AV_CODEC_ID_H264,
    .priv_data_size = sizeof(H264Context),
    .init           = ff_h264_decode_init,
    .close          = h264_decode_end,
    .decode         = h264_decode_frame,
    .capabilities   = AV_CODEC_CAP_DR1 | AV_CODEC_CAP_DELAY | AV_CODEC_CAP_HWACCEL_VDPAU,
    .flush          = flush_dpb,
    .pix_fmts       = (const enum AVPixelFormat[]) { AV_PIX_FMT_VDPAU_H264,
                                                     AV_PIX_FMT_NONE},
    .profiles       = NULL_IF_CONFIG_SMALL(profiles),
    .priv_class     = &h264_vdpau_class,
};
```

**Comment by yoolbin92** [comment]
As you suggested, I am trying to design AVCodec base on openh264. Currently it looks like:
    
AVCodec openh264 = {
	.name = "openh264 ",
	.long_name = "H.264",
	.type = AVMEDIA_TYPE_VIDEO,
	.id = AV_CODEC_ID_H264,
	.priv_data_size = sizeof(ISVCDecoder),
	.init = openh264_decode_init,
	.close = openh264_decode_close,
	.decode = openh264_decode_frame,
};
/* The init function */
static int openh264_decode_init(AVCodecContext *avctx)
{
	ISVCDecoder *pSvcDecoder = avctx->priv_data;
	CreateDecoder(pSvcDecoder);

	SDecodingParam sDecParam = { 0 };
	sDecParam.sVideoProperty.eVideoBsType = VIDEO_BITSTREAM_AVC;
	
	Initialize(&sDecParam);

	return 0;
}
/* the uninit function */
static int openh264_decode_close(AVCodecContext *avctx)
{
	//Uninitialize();
}

/* This is the main decode function */
static int openh264_decode_frame(AVCodecContext *avctx, void *data, int *got_frame, AVPacket *avpkt)
{
	//DecodeFrame();
}
    

I know I need to implement more but I am not sure if I am integrating openh264 decoder properly into ffmpeg. As long as I use openh264 api from codec_api.h, will I be fine? Sorry I am new to this field

**Comment by BilyakA** [comment]
@ghost please have a look at [this repo](https://github.com/ASTIM/OpenH264-VLC-Plugin)
