### ISSUE TITLE
Latency increses on each IFrame (OpenH264 in Firefox)

### ISSUE THREAD

**Issue by Paultok** [cisco/openh264#2319]
Hi,

I am observing a strange behaviour in the decoded video of a WebRTC stream in Firefox. The problem is that whenever Firefox receives an IFrame, the latency in the decoded video slightly increases, although the video appears smooth. For example, the stream is real time at the beginning, but may end up having several seconds of latency after few minute of continuous streaming, if these IFrames are received periodically (say 1 per second). NOTE: this problem does _NOT_ depend on the presence or absence of SPS/PPS NALs immediately before each IFrame (except the first SPS/PPS when the stream starts, of course).

Is this a known issue? Do you know how to fix this problem?

**Comment by HaiboZhu** [comment]
It seems that your problem is not caused by openh264 decoder as I have not found the similar problem when I used codec directly (not in WebRTC). I think you can ask this question on Mozilla's webpage.

**Comment by Paultok** [comment]
Ok, but I wonder if you have ever tried to output one IFrame every 1s and see what happens after 2 minutes of continuous streaming with regard to latency...

**Comment by huili2** [comment]
No update on this, and codec has no same phenomenon as the same issue. If more information is required, please turn to webRTC for more help.
