### ISSUE TITLE
Can we update bitrate/fps dynamically?

### ISSUE THREAD

**Issue by jpxiong** [cisco/openh264#2320]
Is there any way to update bitrate/fps dynamically in the runtime ?

**Comment by volvet** [comment]
ENCODER_OPTION_BITRATE can help you for this case.

**Comment by earthskin** [comment]
setOption(ENCODER_OPTION_BITRATE,&int)   return 1,  it's error, can anyone help?

**Comment by sijchen** [comment]
to set in a SBitrateInfo rather than &int

**Comment by sijchen** [comment]
close because of no further updates
