### ISSUE TITLE
openh264 v1.5.1 crashes when a thread can not be created

### ISSUE THREAD

**Issue by hardening** [cisco/openh264#2348]
If we're running out of resources and we can't create a thread, then the full context is freed but the threads that have been created aren't killed, leading to segfault.

Patch follows.

**Comment by sijchen** [comment]
thank you for the input. In fact the function CreateSliceThreads is going to retire and its counterpart is WELS_THREAD_ERROR_CODE CWelsThread::Start() under common/src/WelsThread.cpp Ln76. We need to figure out how to perform a same protection as you mentioned in the latter function....

**Comment by HaiboZhu** [comment]
Thanks for hardening's contribution on it.
