### ISSUE TITLE
parse_nal: no exists PPS ahead of sequence; NAL_SLICE_IDR

### ISSUE THREAD

**Issue by IceCubeDev** [cisco/openh264#2356]
Greetings,

I am having troubles decoding a h264 video bitstream. My application first receives 20 bytes containing the SPS and PPS data. After that I start receiving complete frames. I am using DecodeFrame2 to decode the data, but I am receiving the following error:

> [OpenH264] this = 0x0024ADD0, Info:CWelsDecoder::init_decoder(), openh264 codec
> version = openh264 default: 1.4, ParseOnly = 0
> [OpenH264] this = 0x0024ADD0, Info:eVideoType: 1
> Free: 0
> [OpenH264] this = 0x0024ADD0, Warning:parse_nal(), no exist Picture Parameter Se
> ts ahead of sequence when try to decode NAL (type:5).
> [OpenH264] this = 0x0024ADD0, Info:decode failed, failure type:1

I analyzed the data that was coming in using h.264 analysis application and this is the result I got:

```
Number | NAL Type | NAL Size
0             SPS           8
1             PPS           4
2            IDR_SLICE 293
3            SLICE         6
4            SLICE         3123
5            IDR_SLICE  3218
.... 
```

Any idea why I am receiving the error?

**Comment by sijchen** [comment]
it is possible that the PPS needed by one of the slice is not contained in the bit stream. We cannot tell until we know that is in the syntax of this bit stream.

**Comment by HaiboZhu** [comment]
No update for a long time, close this issue.
