### ISSUE TITLE
Decoder speed issue

### ISSUE THREAD

**Issue by wattwurm** [cisco/openh264#2370]
I build a simple player which displays the h264 content on a SDL surface. Built on top of the h264dec console example I commented out the file write and added displaying the content on a SDL surface which is just a memcopy. Then I noticed that the playback is quite slow. All the time is spent in the DecoderFrameNoDelay.

My video file is 2000x1000 at 30fps. 
With mplayer the file plays within 2s to the end where with openh264 it takes 12s.
Is there any chance to get near the 2s with openh264?

**Comment by ruil2** [comment]
1. which platform you are running your player?
2.could you send the openh264 build parameters? 
thanks!

**Comment by ruil2** [comment]
if have still questions, please contact with us freely. thanks!
