### ISSUE TITLE
No pps NAL units in encoded stream - Forcing encoder to generate pps 

### ISSUE THREAD

**Issue by efrosa** [cisco/openh264#2373]
We use the openh264 encoder to create a video stream but we are not getting any pps nal units.
Is there an option that we need to specify to have it included in the stream? we do get sps NAL units every once in a while.
[openh264 trace (1).txt](https://github.com/cisco/openh264/files/140523/openh264.trace.1.txt)

**Comment by sijchen** [comment]
PPS is always following SPS in the bitstream openh264 encoder outputs.

**Comment by n8o** [comment]
I'm not seeing any PPS packets as well. 
[OpenH264] this = 0x0x6778d0, Debug:WelsEncoderEncodeExt() OutputInfo iLayerId = 0,iNalType = 0,iNalCount = 2, first Nal Length=19,uiSpatialId = 0,uiTemporalId = 0,iSubSeqId = 0
[OpenH264] this = 0x0x6778d0, Debug:WelsEncoderEncodeExt() OutputInfo iLayerId = 1,iNalType = 1,iNalCount = 1, first Nal Length=220790,uiSpatialId = 0,uiTemporalId = 0,iSubSeqId = 0

Here are the first parts of the bitstream. Am i missing something?
00 00 00 01 67 42 C0 34 43 23 50 14 07 A4 03 C2 21 1A 80 00 00 00 01 65 B4 00 01 00 00 1F ....

**Comment by huili2** [comment]
@n8o we never see this before. How did you encode this with what parameters or configurations?

**Comment by n8o** [comment]
I'm rather new to using this so it's probably me. I'm using the sample code from the example. I'm taking in a jpg. converting it to YUV and then sending it to the encoder.
`   //Step1:setup encoder

    ISVCEncoder* encoder_;

    rv = WelsCreateSVCEncoder (&encoder_);

    //Step2:initilize with basic parameter

    SEncParamBase param;
    param.iUsageType = CAMERA_VIDEO_REAL_TIME;
    param.fMaxFrameRate = 60;
    param.iPicWidth = lumaWidth;
    param.iPicHeight = lumaHeight;
    param.iTargetBitrate = 50000000;
    encoder_->Initialize (&param);

    //Step3:set option, set option during encoding process

    //encoder_->SetOption (ENCODER_OPTION_TRACE_LEVEL, &g_LevelSetting);
    videoFormat = videoFormatI420;
    iTraceLevel = WELS_LOG_DEBUG;
    encoder_->SetOption (ENCODER_OPTION_DATAFORMAT, &videoFormat);
    encoder_->SetOption (ENCODER_OPTION_TRACE_LEVEL, &iTraceLevel);


    //Step4: encode and store ouput bistream

    SFrameBSInfo info;
    SSourcePicture pic;

    pic.iPicWidth =  lumaWidth;
    pic.iPicHeight = lumaHeight;
    pic.iColorFormat = videoFormatI420;
    pic.iStride[0] = pic.iPicWidth;
    pic.iStride[1] = pic.iStride[2] = pic.iPicWidth >> 1;
    pic.pData[0] = buf.data();
    pic.pData[1] = pic.pData[0] + lumaWidth * lumaHeight;
    pic.pData[2] = pic.pData[1] + (lumaWidth * lumaHeight >> 2);

    rv = encoder_->EncodeParameterSets(&info);
    rv = encoder_->EncodeFrame (&pic, &info);`

**Comment by huili2** [comment]
@n8o from your trace, we can see the first output has two outputs: ",iNalCount = 2, first Nal Length=19". Could you please check if you correctly got the two data (SPS&PPS), or you may just wrongly write out SPS only?

**Comment by n8o** [comment]
The way I understand it is that the iNalCount is the index number in SFrameBSInfo.sLayerInfo.
i read all 19 bytes out of the [0] indexed item in pBsBuf. it only had 1 start code in it with a nalu type of SPS. 

index [1] in SFrameBSInfo.sLayerInfo had a length of 220790 and was the NALu type 5 (SLICE_LAYER_IDR)

those were all the SFrameBSInfo.sLayerInfo in one call to the encoder (encoder_->EncodeFrame)

**Comment by n8o** [comment]
I figured out the issue. I was only reading one length out of the pNalLengthInByte and didn't realize it was an array of lengths.

**Comment by huili2** [comment]
@n8o fine. :)
