### ISSUE TITLE
Very different compressed file sizes when using 2 slices vs. 1 slice.

### ISSUE THREAD

**Issue by GregoryJWolfe** [cisco/openh264#2377]
I am using openh264 (current master) with FFmpeg.  With all other parameters the same, the compressed file size is radically different depending on the number of slices specified, and whether or not load balancing is on:

              load     compressed
    slices  balancing  file size
    ------  ---------  ----------
      1        N/A      2,880,193
      2        on       4,777,473
      2        off     19,301,756

There are two unexpected results here:

(1) Why is the 2-slice-with-load-balancing output 66% bigger than the 1-slice output?

(2) Why is the 2-slice-without-load-balancing output 4 times bigger than the 2-slice-with-load-balancing output?

I also have an implementation of SSIM that I use to measure the output compressed video quality vs. the original losslessly compressed video.  The SSIM numbers correlate with the compressed file sizes, with the largest file having the highest quality (as expected).

For these test runs I have set the bit rates to be very high, equal to the bit rate needed for uncompressed YUV 420 video.

If this is not a bug, then I would like to know how to set the compression parameters so that I get similar output file sizes from all three cases.  In particular, I am wondering if I need to set iMinQp and iMaxQp?

Below is diagnostic output showing some of the compression parameters:

1 slice:

    Info:CWelsH264SVCEncoder::SetOption(), openh264 codec version = .
    Info:CWelsH264SVCEncoder::InitEncoder(), openh264 codec version = 
    Info:iUsageType = 0,iPicWidth= 1920;iPicHeight= 1080;iTargetBitrate= 597196800;iMaxBitrate= 597196800;iRCMode= 0;iPaddingFlag= 0;iTemporalLayerNum= 1;iSpatialLayerNum= 1;fFrameRate= 24.000000f;uiIntraPeriod= 96;eSpsPpsIdStrategy = 0;bPrefixNalAddingCtrl = 0;bSimulcastAVC=0;bEnableDenoise= 0;bEnableBackgroundDetection= 1;bEnableSceneChangeDetect = 1;bEnableAdaptiveQuant= 1;bEnableFrameSkip= 0;bEnableLongTermReference= 0;iLtrMarkPeriod= 30;iComplexityMode = 1;iNumRefFrame = 1;iEntropyCodingModeFlag = 0;uiMaxNalSize = 0;iLTRRefNum = 0;iMultipleThreadIdc = 1;iLoopFilterDisableIdc = 0 (offset(alpha/beta): 0,0;iMaxQp = 51;iMinQp = 0)
    Info:sSpatialLayers[0]: .iVideoWidth= 1920; .iVideoHeight= 1088; .fFrameRate= 24.000000f; .iSpatialBitrate= 597196800; .iMaxSpatialBitrate= 0; .sSliceArgument.uiSliceMode= 1; .sSliceArgument.iSliceNum= 1; .sSliceArgument.uiSliceSizeConstraint= 1500;uiProfileIdc = 66;uiLevelIdc = 0
    Info:SliceArgumentValidationFixedSliceMode(), uiSliceNum(1) you set for SM_FIXEDSLCNUM_SLICE, now turn to SM_SINGLE_SLICE type!
    Warning:bEnableFrameSkip = 0,bitrate can't be controlled for RC_QUALITY_MODE,RC_BITRATE_MODE and RC_TIMESTAMP_MODE without enabling skip frame.
    Info:WELS CPU features/capacities (0x4007fe3f) detected: 	HTT:      Y, MMX:      Y, MMXEX:    Y, SSE:      Y, SSE2:     Y, SSE3:     Y, SSSE3:    Y, SSE4.1:   Y, SSE4.2:   Y, AVX:      Y, FMA:      Y, X87-FPU:  Y, 3DNOW:    N, 3DNOWEX:  N, ALTIVEC:  N, CMOV:     Y, MOVBE:    Y, AES:      Y, NUMBER OF LOGIC PROCESSORS ON CHIP: 8, CPU CACHE LINE SIZE (BYTES):        64
    Info:WelsInitEncoderExt() exit, overall memory usage: 26749630 bytes
    Info:CWelsH264SVCEncoder::~CWelsH264SVCEncoder()
    Info:CWelsH264SVCEncoder::Uninitialize(), openh264 codec version = .
    Info:WelsUninitEncoderExt(), pCtx= 04810fc8, iMultipleThreadIdc= 1.
    Info:FreeMemorySvc(), verify memory usage (0 bytes) after free..

2 slices, load balancing on:

    Info:CWelsH264SVCEncoder::SetOption(), openh264 codec version = .
    Info:CWelsH264SVCEncoder::InitEncoder(), openh264 codec version = 
    Info:iUsageType = 0,iPicWidth= 1920;iPicHeight= 1080;iTargetBitrate= 597196800;iMaxBitrate= 597196800;iRCMode= 0;iPaddingFlag= 0;iTemporalLayerNum= 1;iSpatialLayerNum= 1;fFrameRate= 24.000000f;uiIntraPeriod= 96;eSpsPpsIdStrategy = 0;bPrefixNalAddingCtrl = 0;bSimulcastAVC=0;bEnableDenoise= 0;bEnableBackgroundDetection= 1;bEnableSceneChangeDetect = 1;bEnableAdaptiveQuant= 1;bEnableFrameSkip= 0;bEnableLongTermReference= 0;iLtrMarkPeriod= 30;iComplexityMode = 1;iNumRefFrame = 1;iEntropyCodingModeFlag = 0;uiMaxNalSize = 0;iLTRRefNum = 0;iMultipleThreadIdc = 2;iLoopFilterDisableIdc = 0 (offset(alpha/beta): 0,0;iMaxQp = 51;iMinQp = 0)
    Info:sSpatialLayers[0]: .iVideoWidth= 1920; .iVideoHeight= 1088; .fFrameRate= 24.000000f; .iSpatialBitrate= 597196800; .iMaxSpatialBitrate= 0; .sSliceArgument.uiSliceMode= 1; .sSliceArgument.iSliceNum= 2; .sSliceArgument.uiSliceSizeConstraint= 1500;uiProfileIdc = 66;uiLevelIdc = 0
    Warning:bEnableFrameSkip = 0,bitrate can't be controlled for RC_QUALITY_MODE,RC_BITRATE_MODE and RC_TIMESTAMP_MODE without enabling skip frame.
    Info:WELS CPU features/capacities (0x4007fe3f) detected: 	HTT:      Y, MMX:      Y, MMXEX:    Y, SSE:      Y, SSE2:     Y, SSE3:     Y, SSSE3:    Y, SSE4.1:   Y, SSE4.2:   Y, AVX:      Y, FMA:      Y, X87-FPU:  Y, 3DNOW:    N, 3DNOWEX:  N, ALTIVEC:  N, CMOV:     Y, MOVBE:    Y, AES:      Y, NUMBER OF LOGIC PROCESSORS ON CHIP: 8, CPU CACHE LINE SIZE (BYTES):        64
    Info:WelsInitEncoderExt() exit, overall memory usage: 39296476 bytes
    Info:CWelsH264SVCEncoder::~CWelsH264SVCEncoder()
    Info:CWelsH264SVCEncoder::Uninitialize(), openh264 codec version = .
    Info:WelsUninitEncoderExt(), pCtx= 047c0fc8, iMultipleThreadIdc= 2.
    Info:FreeMemorySvc(), verify memory usage (0 bytes) after free..

2 slices, load balancing off:

    Info:CWelsH264SVCEncoder::SetOption(), openh264 codec version = .
    Info:CWelsH264SVCEncoder::InitEncoder(), openh264 codec version = 
    Info:iUsageType = 0,iPicWidth= 1920;iPicHeight= 1080;iTargetBitrate= 597196800;iMaxBitrate= 597196800;iRCMode= 0;iPaddingFlag= 0;iTemporalLayerNum= 1;iSpatialLayerNum= 1;fFrameRate= 24.000000f;uiIntraPeriod= 96;eSpsPpsIdStrategy = 0;bPrefixNalAddingCtrl = 0;bSimulcastAVC=0;bEnableDenoise= 0;bEnableBackgroundDetection= 1;bEnableSceneChangeDetect = 1;bEnableAdaptiveQuant= 1;bEnableFrameSkip= 0;bEnableLongTermReference= 0;iLtrMarkPeriod= 30;iComplexityMode = 1;iNumRefFrame = 1;iEntropyCodingModeFlag = 0;uiMaxNalSize = 0;iLTRRefNum = 0;iMultipleThreadIdc = 2;iLoopFilterDisableIdc = 0 (offset(alpha/beta): 0,0;iMaxQp = 51;iMinQp = 0)
    Info:sSpatialLayers[0]: .iVideoWidth= 1920; .iVideoHeight= 1088; .fFrameRate= 24.000000f; .iSpatialBitrate= 597196800; .iMaxSpatialBitrate= 0; .sSliceArgument.uiSliceMode= 1; .sSliceArgument.iSliceNum= 2; .sSliceArgument.uiSliceSizeConstraint= 1500;uiProfileIdc = 66;uiLevelIdc = 0
    Warning:bEnableFrameSkip = 0,bitrate can't be controlled for RC_QUALITY_MODE,RC_BITRATE_MODE and RC_TIMESTAMP_MODE without enabling skip frame.
    Info:WELS CPU features/capacities (0x4007fe3f) detected: 	HTT:      Y, MMX:      Y, MMXEX:    Y, SSE:      Y, SSE2:     Y, SSE3:     Y, SSSE3:    Y, SSE4.1:   Y, SSE4.2:   Y, AVX:      Y, FMA:      Y, X87-FPU:  Y, 3DNOW:    N, 3DNOWEX:  N, ALTIVEC:  N, CMOV:     Y, MOVBE:    Y, AES:      Y, NUMBER OF LOGIC PROCESSORS ON CHIP: 8, CPU CACHE LINE SIZE (BYTES):        64
    Info:WelsInitEncoderExt() exit, overall memory usage: 39296476 bytes
    Info:CWelsH264SVCEncoder::~CWelsH264SVCEncoder()
    Info:CWelsH264SVCEncoder::Uninitialize(), openh264 codec version = .
    Info:WelsUninitEncoderExt(), pCtx= 047d0fc8, iMultipleThreadIdc= 2.
    Info:FreeMemorySvc(), verify memory usage (0 bytes) after free..

**Comment by GregoryJWolfe** [comment]
I've done some more research on this problem.  The reason the file size gets so much smaller in the 2 slice/load balancing case is that the quantization parameter starts at 12 and quickly rises to the maximum value of 36.  For the 2 slice/no load balancing case it only rises to about 23.

In file ratectl.cpp, function RcUpdatePictureQpBits(), there is the following code:

```
for (i = 0; i < pCurSliceCtx->iSliceNumInFrame; i++) {
  iTotalQp += pSOverRc->iTotalQpSlice;
  iTotalMb += pSOverRc->iTotalMbSlice;
  ++ pSOverRc;
}
// ... some other code ...
pWelsSvcRc->iAverageFrameQp = WELS_DIV_ROUND (INT_MULTIPLY * iTotalQp, iTotalMb * INT_MULTIPLY);
// ... some other code ...
pWelsSvcRc->iLastCalculatedQScale = pWelsSvcRc->iAverageFrameQp;
```

The iLastCalculatedQScale value is larger for the load balanced case, which in turn drives the quantization parameter larger.

Member variables iTotalQpSlice and iTotalMbSlice are updated in function WelsRcMbInfoUpdateGom().  I have not been able to find any comments as to what they mean.  I also have no idea why their values are different with/without load balancing.  I'm hoping that someone on the team will read this and have a flash of insight.

**Comment by mstorsjo** [comment]
FWIW, is this a regression since the last releases? AFAIK there's been lots of changes in the RC area, and most of that happened after the latest release, so the latest release might be more stable.

**Comment by GregoryJWolfe** [comment]
This problem appears to have existed in version 1.5.1.  I built 1.5.1 with and without load balancing, ran the same tests, and got results similar to the master branch (see first comment above):

              load     compressed
    slices  balancing  file size
    ------  ---------  ----------
      1        N/A      3,097,007
      2        on       4,220,431
      2        off     19,665,491

Note that to achieve no load balancing with multiple slices, I modified function NeedDynamicAdjust() in file slice_multi_threading.cpp so that it always returns false (no adjustment needed).  No one else would have noticed this problem in v1.5.1 since no one else would have been able to run multiple slices with load balancing turned off unless they made the same modification.

So the bottom line is that when the ability to turn off load balancing was added, it exposed a problem that was already there.  To clarify things, we want to run multiple slices with dynamic load balancing turned off so that we get repeatable results from run to run.  A slight difference in file size compared to the single slice case is to be expected, since each frame will be compressed as two independent "half frames".  However, the magnitude of the actual differences looks like a bug to me.

**Comment by sijchen** [comment]
thanks a lot for the reporting the problem! We will debug this.

**Comment by GregoryJWolfe** [comment]
Just wondering whether any progress has been made against this problem (last comment was two months ago).  I just reran the above test using the latest code from the master branch and got essentially the same result (with slight differences in output video file sizes).

Also, any predictions as to when version 1.6 will become official?  I know that the FFmpeg community has patches that can't be applied to their master branch until openh264 1.6 is available.  We would like to see openh264 1.6 become a stable release, FFmpeg get updated with the appropriate patches, and then update our software.

**Comment by ruil2** [comment]
sorry for miss this issue.

1. very different compressed size on slice1 and slice2. I will check this root cause and give the update. 
2.in your configure, bitrate is very large.Is it only for testing? "iTargetBitrate= 597196800". it should be 597 Mbits.

**Comment by ruil2** [comment]
I had fixed it on https://github.com/cisco/openh264/pull/2467
The root cause is:  the target bitrate is very large, which causes the each slice target size overflow. 
I don't find the obvious difference on load balance on/off. so I am not sure this fix had resolved load balancing issue.

if still have questions, please let me know. thanks a lot again.

**Comment by GregoryJWolfe** [comment]
Thanks for taking care of this!

In answer to your other question, yes, the bit rate was set artificially high in order to generate a "best possible quality" output video that could compared against the same video compressed using smaller bit rates.  The goal is to find the best tradeoff point between quality and compressed video file size.

I will get the latest version of code from the master branch, rerun my test, and report back.

**Comment by GregoryJWolfe** [comment]
I did a more comprehensive test using the latest code from the master branch.  The results are shown below.  "sl" indicates the slice count, "lb" indicates the load balancing setting.  Other relevant settings are iRCMode=RC_QUALITY_MODE and iEntropyCodingModeFlag=1.  The remaining parameter values are the defaults set in FFmpeg's libopenh264enc.c (as updated for openh264 1.6).  The test video file is 10 seconds in length.

                      file size (bytes)
    bit rate     sl=1      sl=2,lb=1   sl=2,lb=0 
    --------   ---------   ---------   ---------
    99532800     3330406     4053958     6899913 
    11943936     3083679     3754281     6605387 
     5971968     2987161     3677679     6501573 
     2388787     2900209     3970663     6723575 
     1194393     2889415     3974533     6707138 
      746496     2889415     3989638     6707138 

There are still significant differences in file sizes for the same bit rate setting depending on the slice count and load balancing settings.  The more disturbing thing is that the file size, as expected, decreases with decreasing bit rate, but after a certain point it actually gets bigger for the 2 slice runs.  Please help me interpret these results.

Just to make sure we're on the same page, my understanding of the meaning of the bit rate setting is that it indicates the target for (compressed video data size in bits) / (video length in seconds).  The file sizes above include header and other overhead bytes, so one would expect them to be slightly larger than the target size of the compressed video data alone.

**Comment by GregoryJWolfe** [comment]
I reran the above test with iEntropyCodingModeFlag=0:

                      file size (bytes)
    bit rate     sl=1      sl=2,lb=1   sl=2,lb=0 
    --------   ---------   ---------   ---------
    99532800     3659645     4526915    18749622 
    11943936     3290298     4141245     6905346 
     5971968     3111251     4121975     4493330 
     2388787     2627254     2696002     2580131 
     1194393     2461778     2467344     2466266 
      746496     2459580     2466268     2465863 

At least for these settings the file sizes decrease monotonically as the bit rates decrease.  You will also note that the file sizes are comparable for all three columns for the three lowest bit rates, and only diverge at the higher bit rates.

**Comment by ruil2** [comment]
Is your testing based on ffmpeg or openh264 test app?

**Comment by ruil2** [comment]
I found the root cause that file size isn't correct with iEntropyCodingModeFlag=1.
fixed in https://github.com/cisco/openh264/pull/2469

I still can't reproduce the below case. I need to do more testings on this.  if you have other info, please let me know.

I reran the above test with iEntropyCodingModeFlag=0:

                      file size (bytes)
    bit rate     sl=1      sl=2,lb=1   sl=2,lb=0 
    --------   ---------   ---------   ---------
    99532800     3659645     4526915    18749622 
    11943936     3290298     4141245     6905346 
     5971968     3111251     4121975     4493330 
     2388787     2627254     2696002     2580131 
     1194393     2461778     2467344     2466266 
      746496     2459580     2466268     2465863

**Comment by ruil2** [comment]
I ran openh264 console app, the below is my result. 

 iEntropyCodingModeFlag=1.

                             file size (bytes)
 target bitrate         sl=1              sl=2,lb=0           sl=2,lb=1 
 (bps) 
  --------              ---------             ---------                 ---------
99532000	  93611481	91844820	91100895
11943000	 23049026	22523880	22553904
5971000	        11590691	 11499156  	11494056
2388000	        4868615	        4941445	         4937887
1194000          3305203	        3357475	         3351641
746000	       3089503	        3148321	         3148255


 iEntropyCodingModeFlag=0.

                             file size (bytes)
 target bitrate         sl=1              sl=2,lb=0           sl=2,lb=1 
 (bps) 
  --------              ---------             ---------                 ---------
99532000	100040781	98333109	97816849
11943000	23059197	22531759	22546219
5971000	       11629204	       11571286	        11568267
2388000	       5036893	        5056736   	5048884
1194000   	3736753	        3778788	        3769385
746000	        3563441	       3607971	        3609000

Could you  run openh264 console application to check this issue on your side?I will also continue to probe this issue on my side.

**Comment by GregoryJWolfe** [comment]
My testing is using source code from the FFmpeg master branch (now maybe a week or two old).  We use the libav* libraries directly from our own application code.

Greg W.

_______________________________
Gregory J. Wolfe | Software Engineer
Imaging – Consumer, Retail Systems Solutions | Kodak Alaris Inc., 2400 Mt. Read Blvd,Rochester, NY 14615
gregory.wolfe@kodakalaris.com | 585.441.7735 | Fax 585.722.6324 |
www.kodakalaris.com
[cid:image001.png@01D0784F.34F11A30]
Information contained in this e-mail transmission may be privileged, confidential, and covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521.

If you have received this e-mail transmission in error, please treat it as you would like your own email sent in error to be treated:

·         notify us immediately by return email of the error, and

·         delete the message from your system without reading, forwarding, or copying it.

Thank you in advance for your courtesy!

**Comment by GregoryJWolfe** [comment]
Your test results look like what I want my test results to look like.  I will attempt to duplicate my test using ffmpeg.exe and provide you with the command line.

I would also like to run my tests using the fix you made for #2469.  When will it be available from the master branch?

**Comment by GregoryJWolfe** [comment]
Here are test results generated using ffmpeg.exe with iEntropyCodingModeFlag=0 (-cabac 0).  The ffmpeg command used is provided before the tabular results.  The slice/thread values follow the -slices and -threads switch arguments, the load balancing value follows the -load_balancing switch, and the bit rate value follows the -b:v switch:

    ffmpeg.exe -v warning -y -ss 0 -i SandalsBirdsTrees.mov -f mp4 -pix_fmt yuv420p
    -vcodec libopenh264 -strict -2 -an -g 96 -slices 2 -threads 2
    -load_balancing 0 -b:v 746496 -cabac 0 "SandalsBirdsTrees_derived.mp4"

                  file size (bytes)
    bit rate     sl=1      sl=2,lb=1   sl=2,lb=0 
    --------   ---------   ---------   ---------
    99532800     6561052     7789887    25031078
    11943936     5814530     7296217     8116007
     5971968     5480582     5920829     5804392
     2388787     4868089     4873115     4879436
     1194393     4868454     4873747     4875049
      746496     4868508     4870938     4872510

These results show the same general pattern as before (the actual numbers are different because my test app applies the alpha channel in the original video file to the RGB values before compression, and ffmpeg does not).  For lower bit rates the values are very similar, but for the two highest bit rates there are significant differences.  As before, the biggest difference is for the highest bit rate with two slices and load balancing turned off.

I should also mention that the input video file was generated digitally by a graphic artist and is stored losslessly using qtrle.  There is lots of black space in it because the animated graphic elements are intended to be composited on top of a customer's digital photograph using the alpha channel in the video.  Only the RGB values are used to create the output video file.  Is it possible that all those zero-valued pixels are somehow influencing the compression implementation to behave differently.

I've attached a PNG image of the first frame from the input video.  It includes the alpha channel.
![sandalsbirdstrees_f00000i](https://cloud.githubusercontent.com/assets/15108070/15437507/788362a6-1e95-11e6-97f6-fe5f76e29fd6.png)

**Comment by GregoryJWolfe** [comment]
For what it's worth, my preference would be for all three cases (1 slice, 2 slices with LB, 2 slices without LB) to give the same results as 2 slices without LB.  My implementation of SSIM for measuring video quality shows that the larger output files have higher quality, which I have verified visually.  This gives me more choices as far as trading off quality for file size.  The SSIM quality of the output video files produced by the other two cases are actually below the quality threshold I have determined as "satisfactory", even at the highest bit rate, so using either of those settings does not give me a high enough quality output video.

**Comment by ruil2** [comment]
@GregoryJWolfe I had got what is your input source, you can move the png from the page to avoid the license issue.

**Comment by GregoryJWolfe** [comment]
Sorry I did not respond sooner, I have been away from the office for a while.

I do not understand what is meant by "camera sequences", but here are my latest results at various bit rates with load balancing on and off.  I've attached the video file (inside a ZIP file) for you to see if you can reproduce the results (no licensing problems with this one).  The FFmpeg command is also shown below:

    ffmpeg -v warning -y -ss 0 -i "PM ChineseNY_H15.mp4" -f mp4 -pix_fmt yuv420p -vcodec 
    libopenh264 -an -strict -2 -g 96 -slices 2 -threads 2 -load_balancing 0 -b:v 99532800 
    -cabac 0 -color_range jpeg -colorspace bt709 -color_primaries bt709 -color_trc bt709 
    -vf scale=out_range=jpeg:out_color_matrix=bt709 "PM ChineseNY_H15_derived.mp4"

                file size (bytes)
    bit rate   sl=2,lb=1   sl=2,lb=0 
    --------   ---------   ---------
    99532800     9063736    14238916
    11943936     6635361     6931206
     5971968     5103584     5073346
     2388787     4118506     3985263
     1194393     3658956     3632752
      746496     3577796     3565756

You can set the bit rate, load balancing, and entropy encoding using "-b:v", "-load_balalncing", and "-cabac" switches.  Note that I have applied the FFmpeg patches for openh264 1.6, and added the "load_balancing" switch to be able to run this test.

The results are very similar except at high bit rates.  As I've remarked before, sometimes I want a high bit rate in order to obtain a higher quality output video.  Also note that in my actual usage I am starting with a very big losslessly compressed video file.  In order for the input video file to be of a manageable size for this test, I started with an H264 compressed video.

[PM ChineseNY_H15.zip](https://github.com/cisco/openh264/files/291868/PM.ChineseNY_H15.zip)

**Comment by ruil2** [comment]
@GregoryJWolfe now I can reproduce your issue. I will check it. thanks!
