### ISSUE TITLE
How to find the size of decodedFrame2() output

### ISSUE THREAD

**Issue by Devikaelangovan** [cisco/openh264#2379]
Hi,

I'm facing issue on few android devices while copying the data from DecodeFrame2()

This is my code:

        uint8_t* m_yuvData[3];
        SBufferInfo yuvDataInfo;
	memset(&yuvDataInfo, 0, sizeof(SBufferInfo));
	m_yuvData[0] = NULL;
	m_yuvData[1] = NULL;
	m_yuvData[2] = NULL;
         DECODING_STATE decodingState = m_decoder->DecodeFrame2(bufferData, bufferDataSize, m_yuvData, &yuvDataInfo);

	if(yuvDataInfo.iBufferStatus == 1)
	{
	        int yStride = yuvDataInfo->UsrData.sSystemBuffer.iStride[0];
        	int uvStride = yuvDataInfo->UsrData.sSystemBuffer.iStride[1];
	        uint32_t width = yuvDataInfo->UsrData.sSystemBuffer.iWidth;
	       uint32_t height = yuvDataInfo->UsrData.sSystemBuffer.iHeight;
	       size_t yDataSize = (width * height) + (height * yStride);
	       size_t uvDataSize = (((width * height) / 4) + (height * uvStride));
                size_t requiredSize = yDataSize + (2 * uvDataSize);
               	uint8_t* yuvBufferedData = (uint8_t*)malloc(requiredSize);

.// when i move yuvData[0] to another location i am getting crash.
             memcpy(yuvBufferedData, yuvData[0], yDataSize);
	memcpy(yuvBufferedData + yDataSize, yuvData[1], uvDataSize);
	memcpy(yuvBufferedData + yDataSize + uvDataSize, yuvData[2], uvDataSize);
}

The above code snippet is working on high end android devices. but on few android devices after processing first frame, second frame onwards i am getting crash in first memcpy() statement.

What is wrong in this code? and how to calculate the buffer size from the output of DecodeFrame2().
If i process alternative frames(instead of 30, just 15 frames alternative ones), it is copying fine. 
Please help me to fix this?

**Comment by Devikaelangovan** [comment]
It is for Standard resolution images (640*480)

**Comment by Devikaelangovan** [comment]
This is for 640 * 480 resolution. I am receiving Frame from Camera, and uncompressing the frame(Demux)->decoding frame(H264)->YUVtoRGB conversion. These all happening in single thread. Till decode part its working fine. I've written the output of Decoder into .yuv file and played on YUV player. It is playing fine. But when i tried to Copy the output of Decode into another buffer(for YUV to RGB conversion), it is crashing on low end devices. First frame completing all the stages successfully. Second frame failing consistently.

**Comment by ruil2** [comment]
which module did the second frame fail in?

**Comment by ruil2** [comment]
yDataSize is wrong, it should be  (height * yStride);
uvDataSize should be (height/2 * uvStride)
