### ISSUE TITLE
Android arm64 compiling failed, please help

### ISSUE THREAD

**Issue by ioleon13** [cisco/openh264#2381]
My compiling enviorment
OS:ubuntu 64bit
NDK:android-ndk-r10e
build: make OS=android NDKROOT=**MYPATH**/android-ndk-r10e/ TARGET=2 ARCH=arm64 NDKLEVEL=21

error info:
rm -f libopenh264.so
*_/android-ndk-r10e//toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ -shared -o libopenh264.so codec/encoder/core/src/au_set.o codec/encoder/core/src/deblocking.o codec/encoder/core/src/decode_mb_aux.o codec/encoder/core/src/encode_mb_aux.o codec/encoder/core/src/encoder.o codec/encoder/core/src/encoder_data_tables.o codec/encoder/core/src/encoder_ext.o codec/encoder/core/src/get_intra_predictor.o codec/encoder/core/src/md.o codec/encoder/core/src/mv_pred.o codec/encoder/core/src/nal_encap.o codec/encoder/core/src/picture_handle.o codec/encoder/core/src/ratectl.o codec/encoder/core/src/ref_list_mgr_svc.o codec/encoder/core/src/sample.o codec/encoder/core/src/set_mb_syn_cabac.o codec/encoder/core/src/set_mb_syn_cavlc.o codec/encoder/core/src/slice_multi_threading.o codec/encoder/core/src/svc_base_layer_md.o codec/encoder/core/src/svc_enc_slice_segment.o codec/encoder/core/src/svc_encode_mb.o codec/encoder/core/src/svc_encode_slice.o codec/encoder/core/src/svc_mode_decision.o codec/encoder/core/src/svc_motion_estimate.o codec/encoder/core/src/svc_set_mb_syn_cabac.o codec/encoder/core/src/svc_set_mb_syn_cavlc.o codec/encoder/core/src/wels_preprocess.o codec/encoder/core/src/wels_task_base.o codec/encoder/core/src/wels_task_encoder.o codec/encoder/core/src/wels_task_management.o codec/encoder/plus/src/welsEncoderExt.o codec/encoder/core/arm64/intra_pred_aarch64_neon.o codec/encoder/core/arm64/intra_pred_sad_3_opt_aarch64_neon.o codec/encoder/core/arm64/memory_aarch64_neon.o codec/encoder/core/arm64/pixel_aarch64_neon.o codec/encoder/core/arm64/reconstruct_aarch64_neon.o codec/encoder/core/arm64/svc_motion_estimation_aarch64_neon.o codec/decoder/core/src/au_parser.o codec/decoder/core/src/bit_stream.o codec/decoder/core/src/cabac_decoder.o codec/decoder/core/src/deblocking.o codec/decoder/core/src/decode_mb_aux.o codec/decoder/core/src/decode_slice.o codec/decoder/core/src/decoder.o codec/decoder/core/src/decoder_core.o codec/decoder/core/src/decoder_data_tables.o codec/decoder/core/src/error_concealment.o codec/decoder/core/src/fmo.o codec/decoder/core/src/get_intra_predictor.o codec/decoder/core/src/manage_dec_ref.o codec/decoder/core/src/memmgr_nal_unit.o codec/decoder/core/src/mv_pred.o codec/decoder/core/src/parse_mb_syn_cabac.o codec/decoder/core/src/parse_mb_syn_cavlc.o codec/decoder/core/src/pic_queue.o codec/decoder/core/src/rec_mb.o codec/decoder/plus/src/welsDecoderExt.o codec/decoder/core/arm64/block_add_aarch64_neon.o codec/decoder/core/arm64/intra_pred_aarch64_neon.o codec/processing/src/adaptivequantization/AdaptiveQuantization.o codec/processing/src/backgrounddetection/BackgroundDetection.o codec/processing/src/common/memory.o codec/processing/src/common/WelsFrameWork.o codec/processing/src/common/WelsFrameWorkEx.o codec/processing/src/complexityanalysis/ComplexityAnalysis.o codec/processing/src/denoise/denoise.o codec/processing/src/denoise/denoise_filter.o codec/processing/src/downsample/downsample.o codec/processing/src/downsample/downsamplefuncs.o codec/processing/src/imagerotate/imagerotate.o codec/processing/src/imagerotate/imagerotatefuncs.o codec/processing/src/scenechangedetection/SceneChangeDetection.o codec/processing/src/scrolldetection/ScrollDetection.o codec/processing/src/scrolldetection/ScrollDetectionFuncs.o codec/processing/src/vaacalc/vaacalcfuncs.o codec/processing/src/vaacalc/vaacalculation.o codec/processing/src/arm64/adaptive_quantization_aarch64_neon.o codec/processing/src/arm64/down_sample_aarch64_neon.o codec/processing/src/arm64/pixel_sad_aarch64_neon.o codec/processing/src/arm64/vaa_calc_aarch64_neon.o codec/common/src/cpu-features.o codec/common/src/common_tables.o codec/common/src/copy_mb.o codec/common/src/cpu.o codec/common/src/crt_util_safe_x.o codec/common/src/deblocking_common.o codec/common/src/expand_pic.o codec/common/src/intra_pred_common.o codec/common/src/mc.o codec/common/src/memory_align.o codec/common/src/sad_common.o codec/common/src/utils.o codec/common/src/welsCodecTrace.o codec/common/src/WelsTaskThread.o codec/common/src/WelsThread.o codec/common/src/WelsThreadLib.o codec/common/src/WelsThreadPool.o codec/common/arm64/copy_mb_aarch64_neon.o codec/common/arm64/deblocking_aarch64_neon.o codec/common/arm64/expand_picture_aarch64_neon.o codec/common/arm64/intra_pred_common_aarch64_neon.o codec/common/arm64/mc_aarch64_neon.o --sysroot=/vagrant/ndk/android-ndk-r10e//platforms/android-21/arch-arm64  -Wl,--no-undefined -Wl,-z,relro -Wl,-z,now -Wl,-soname,libopenh264.so
codec/common/src/cpu-features.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make: *_\* [libopenh264.so] Error 1

**Comment by ioleon13** [comment]
When i remove the file "cpu-features.o" manually, compiling was successed. The "make clean" cmd was not remove the file automatically

**Comment by mstorsjo** [comment]
You need to include all the other make parameters when doing `make clean`, i.e. in your case `make OS=android NDKROOT=MYPATH/android-ndk-r10e/ TARGET=2 ARCH=arm64 NDKLEVEL=21 clean`.
