### ISSUE TITLE
git versioning seems off

### ISSUE THREAD

**Issue by sekret1** [cisco/openh264#2387]
Hi! I'm about to upload a git package of this software to the AUR of Archlinux. In order to get the version I basically use

$ git describe
v1.1-1909-g52d25f5

Now I discovered, that this version seems very outdated, since the latest release versino is 1.5.
Even more strangely I discovered, that there's a completely different version if I use --tags

$ git describe --tags
v1.3-1069-g52d25f5

I'm not the biggest expert of git etc, so if I'm only blind, please enlighten me. But to me it seems like you don't take good care of this!

**Comment by ruil2** [comment]
git describe:
By default (without --all or --tags) git describe only shows annotated tags.

-tags
Instead of using only the annotated tags, use any tag found in refs/tags namespace. This option enables matching a lightweight (non-annotated) tag.
