### ISSUE TITLE
Bad performance of OpenH264 decoder in Android Platform

### ISSUE THREAD

**Issue by zhangzijian** [cisco/openh264#2388]
My decoder works very lower performance in Android device.
My decoder configuratiion is:
  1 decoderParam.pFileNameRestructed = NULL;
  2 decoderParam.eOutputColorFormat = videoFormatI420;
  3 decoderParam.uiCpuLoad = 0;
  4 decoderParam.uiTargetDqLayer = 0;
  5 decoderParam.eEcActiveIdc = ERROR_CON_DISABLE;
  6 decoderParam.bParseOnly = false;
  7 decoderParam.sVideoProperty.eVideoBsType = VIDEO_BITSTREAM_AVC;
  8 decoderParam.sVideoProperty.size = sizeof(pContext->decoderParam.sVideoProperty);

and I decode use api:
pDecoder->DecodeFrame2

and test result is:

20ms - 40ms per frame in movement video when decoding

Pls help me. Thank you.

**Comment by huili2** [comment]
How about the resolution, and what's the Android device capability?

**Comment by zhangzijian** [comment]
solved the problem. Because the video frame encoder iEntropyCodingModeFlag is set to use CABAC.
