### ISSUE TITLE
How to enable log in android platform

### ISSUE THREAD

**Issue by zhangzijian** [cisco/openh264#2393]
Hi, is  there anyway to enable log in android. I try to set ENCODER_OPTION_TRACE_CALLBACK with function: void (*)(void* context, int level, const char* message)  but CRASH .

**Comment by ruil2** [comment]
int level = WELS_LOG_INFO;
m_pEncoder->SetOption(ENCODER_OPTION_TRACE_LEVEL, &level);
 ret = m_pEncoder->SetOption(ENCODER_OPTION_TRACE_CALLBACK, (void *)&pLog);
  if (ret != 0) {
         ......
   }

trace output sample.
