### ISSUE TITLE
openH264 last git with FFmpeg

### ISSUE THREAD

**Issue by madovsky** [cisco/openh264#2396]
Hi,

I couldn't compile FFmpeg with last git and even last stable version of openH264.
don't know if I must open an issue here on FFmpeg so I did it both

**Comment by madovsky** [comment]
btw, which version of openH264 compiles with FFMPEG?

**Comment by thewierdnut** [comment]
the ffmpeg version is relying on SM_AUTO_SLICE in the SliceModeEnum, which appears to be removed. 

Version 1.5 compiles fine for me.

**Comment by promgamer** [comment]
Same here. Can't compile ffmpeg with openH264 lib. How did you guys solved it?

**Comment by thewierdnut** [comment]
it compiles fine with openh264 version 1.5. 

The ffmpeg developers will have to update their libs to match, but they may wait to do so until openh264 issues a new release.

**Comment by Maypeur** [comment]
I'm waiting for a new release of Openh264 to modify FFmpeg handle, but after many month even if I see a lot of improvement on openh264 i do not see newer build :( 
Is there any plan for that ?
Thanks.

**Comment by madovsky** [comment]
yes it would be nice to see the last git compiled successfully with FFmpeg...

**Comment by Maypeur** [comment]
I thing the file outdated is : https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libopenh264enc.c

**Comment by Maypeur** [comment]
Moreover, the file seems to do not implement a lot of OpenH264 options.

**Comment by madovsky** [comment]
maybe you can push a commit about it

**Comment by Maypeur** [comment]
Maybe i was not very clear, i do not have modify FFmpeg but i'm waiting for a new release of OpenH264 to start trying something. Anyway, i'm not an FFmpeg developer so i thing it would be better to request an update on FFmpeg git to have a well working update...

**Comment by thewierdnut** [comment]
The place for this discussion is probably on the ffmpeg defect mentioned by
the original poster. Unfortunately, I can't find it.

**Comment by promgamer** [comment]
I did compile FFMPEG last stable version with openH264 1.5 with success, as @thewierdnut pointed out. Thanks!
