### ISSUE TITLE
build solution with visual studio 2012

### ISSUE THREAD

**Issue by phidepzaick** [cisco/openh264#2400]
I am studying about intra prediction in H264.I downloaded your code to my computer.but when i build solution, visual studio 2012 note that:
1>------ Build started: Project: WelsVP, Configuration: Debug Win32 ------
1>  Performing Custom Build Tools
1>  'nasm' is not recognized as an internal or external command,
1>  operable program or batch file.
1>  Performing Custom Build Tools
1>  'nasm' is not recognized as an internal or external command,
1>  operable program or batch file.
1>  Performing Custom Build Tools
1>  'nasm' is not recognized as an internal or external command,
1>  operable program or batch file.
1>  Performing Custom Build Tools
1>  'nasm' is not recognized as an internal or external command,
1>  operable program or batch file.
1>  Performing Custom Build Tools
1>  'nasm' is not recognized as an internal or external command,
1>  operable program or batch file.
1>  Performing Custom Build Tools
1>  'nasm' is not recognized as an internal or external command,
1>  operable program or batch file.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 9009.
2>------ Build started: Project: WelsEncCore, Configuration: Debug Win32 ------
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>  Performing Custom Build Tools
2>  'nasm' is not recognized as an internal or external command,
2>  operable program or batch file.
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 9009.
3>------ Build started: Project: WelsEncPlus, Configuration: Debug Win32 ------
3>  welsEncoderExt.cpp
3>  welsCodecTrace.cpp
3>  DllEntry.cpp
3>  Generating Code...
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(1137,5): warning MSB8012: TargetPath(C:\Users\Phidepzai\Source\Repos\openh264\codec\build\win32\enc.........\bin\Win32\Debug\WelsEncPlus.dll) does not match the Linker's OutputFile property value (C:\Users\Phidepzai\Source\Repos\openh264\bin\Win32\Debug\welsenc.dll). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(1139,5): warning MSB8012: TargetName(WelsEncPlus) does not match the Linker's OutputFile property value (welsenc). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
3>LINK : fatal error LNK1104: cannot open file '.........\bin\Win32\Debug\welsecore.lib'
4>------ Build started: Project: encConsole, Configuration: Debug Win32 ------
4>  welsenc.cpp
4>  read_config.cpp
4>  Generating Code...
4>LINK : fatal error LNK1104: cannot open file '.........\bin\Win32\Debug\welsenc.lib'
========== Build: 0 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========
Can you help me resolve this problem.
Thanks in advance!

**Comment by GuangweiWang** [comment]
it seems you have not installed 'NASM' in you computer, you can download 'NASM' from http://www.nasm.us/

**Comment by phidepzaick** [comment]
i installed NASM in my computer before.did you build this solution success.can you tell me what were software you installed?
Thanks!!!!!!!!

**Comment by GuangweiWang** [comment]
two question: 
1. do you add you 'NASM' execute path to "PATH"? 
2. the version of your NASM?

may be you can copy NASM to the execute path of visual  studio 2012, have a try

**Comment by phidepzaick** [comment]
-I installed NASM version 2.12 but I don't know how to add NASM to "PATH"?
I'm student,so i haven't experience in this problem.
can you show me steps to build this solution with visual studio?
thanks you very much for your reply!!@@

**Comment by phidepzaick** [comment]
I just copy NASM to folder :visual studio/vc/bin
and i only saw this error "1>LINK : fatal error LNK1104: cannot open file '.\..\..\..\..\bin\Win32\Debug\welsenc.lib'"
what should i do?

**Comment by phidepzaick** [comment]
thanks for your reply!!
i built successful solution.
can you tell me how can i create file .exe??

**Comment by phidepzaick** [comment]
4>LINK : fatal error LNK1104: cannot open file '.\..\..\..\..\bin\Win32\Debug\welsenc.lib'
help me!!

**Comment by GuangweiWang** [comment]
this error caused by using a higher version visual studio to open a low version vs project, in this case, the visual studio can not set the target name/path automatically. you can set the corresponding enviroment variable in vs2012 by yourself.

**Comment by phidepzaick** [comment]
oh.I don't see the file welsecore.lib on 'debug' folder.

**Comment by ruil2** [comment]
@phidepzaick  you also can refer to  "For Windows Builds"  part on https://github.com/cisco/openh264 page. thanks!
