### ISSUE TITLE
libtool warning "same member name" when linking libopenh264 with my library

### ISSUE THREAD

**Issue by takikoma** [cisco/openh264#2430]
The following warnings are printed by xcode when using libtool to link libopenh264 with my own static library:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning same member name (deblocking.o) in output file used for input files: /xxxxxx/libopenh264.a(deblocking.o) and: /xxxxxx/libopenh264.a(deblocking.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning same member name (decode_mb_aux.o) in output file used for input files: /xxxxxx/libopenh264.a(decode_mb_aux.o) and: /xxxxxx/libopenh264.a(decode_mb_aux.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning same member name (get_intra_predictor.o) in output file used for input files: /xxxxxx/libopenh264.a(get_intra_predictor.o) and: /xxxxxx/libopenh264.a(get_intra_predictor.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning same member name (intra_pred_neon.o) in output file used for input files: /xxxxxx/libopenh264.a(intra_pred_neon.o) and: /xxxxxx/libopenh264.a(intra_pred_neon.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning same member name (mv_pred.o) in output file used for input files: /xxxxxx/libopenh264.a(mv_pred.o) and: /xxxxxx/libopenh264.a(mv_pred.o) due to use of basename, truncation and blank padding

**Comment by huili2** [comment]
@takikoma openh264 is using namespace WelsEnc. It would be very rare that your own lib happened to be the same as openh264 with the same namespace.
If that's real the case, you have to modify one of the namespace.
