### ISSUE TITLE
bEnableFrameSkip=0, bitrate can't be controlled

### ISSUE THREAD

**Issue by Prakash19921206** [cisco/openh264#2435]
Hi
i am using openh264(openh264-1.4.0-win32msvc.dll) along with opencv 3.1 (C++) in visual studio,  i wanted to save webcam videos in mp4 with H.264

before using openh264, in console i was seeing an warning message 
"Failed to load openh264 library : openh264-1.4.0-win32msvc.dll
   please check your environment and/or download from here: 
https://github.com/cisco/openh264/releases"
(also video was not been saved)

so i downloaded the dll & kept in a folder with my program file(exe)
now when i run the program, i'm seeing different error 
"[OpenH264] this = 0x0DE312C0, warning: bEnabledFrameSkip=0, bitrate can't be controlled for RC_QUALITY_MODE and RC_TIMESTAMP_MODE without enabling skip frame"
(now video is saved, but size is very high! bit rate is around 1200 Kbps)

for me, the very purpose of using h264 is to reduce the file size.. i think i may have to build h264 myself with some changes to remove this error, can anyone guide me how?  or tell me if there is a way to reduce bit rate?

Thanks & regards

**Comment by sijchen** [comment]
the second warning is just related to rate-control setting so you don't need to build the lib yourself. Pls check your encoder setting to make sure you are setting the parameter correctly.

**Comment by Prakash19921206** [comment]
Thanks for your reply sijchen
can you pls elaborate? how t ochange encoder setting?

this line of code is used to save video in opencv
VideoCapture cap(0);
cap.set(VIDEOWRITER_PROP_QUALITY, 0); //this line has no effect on output
> VideoWriter write = VideoWriter("D:/movie.mp4", CV_FOURCC('H', '2', '6', '4'), 10.0, cv::Size(192, 144), true);

**Comment by sijchen** [comment]
how do you set the encoding parameter?

**Comment by Prakash19921206** [comment]
in opencv, i just specify the codec, resolution(cv::Size) , frame rate  [as shown in above code]

but in opencv we cannot set bit rate,   i am using openh264 dll file as its required by opencv to encode & save video. i'm not referencing openh264 in visual studio.

is there any way to solve this?

**Comment by ruil2** [comment]
if you build ffmpeg by yourself, you can change openh264 setting in https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libopenh264enc.c.

it is better to give us your openh264 trace output, if you have it. thanks!

**Comment by Prakash19921206** [comment]
@ruil2 Thanks for replying.
sorry i don't have openh264 trace output. 
if i build ffmpeg my self, somehow i need to generate opencv_ffmpeg310.dll
in opencv website this library file comes pre compiled, even if i compile myself i cannot change any settings related to ffmpeg
in this case how to continue? 
can you direct me to any tutorial?  

Thanks

with regards
-Prakash

**Comment by ruil2** [comment]
sorry, I can't give this tutorial. you can refer to opencv guide.

**Comment by bianliangpai** [comment]
I'm facing the same question. @Prakash19921206 Do you have any solution now ?

**Comment by Prakash19921206** [comment]
not with h264 codec,  instead i'm using xvid codec.
alternatively you can use [AForge.Net ](http://www.aforgenet.com/)library. it gives many options for video encoding.

**Comment by bianliangpai** [comment]
@Prakash19921206  Ok, thanks.
