### ISSUE TITLE
release binaries missing for 1.5.1 and 1.5.2

### ISSUE THREAD

**Issue by nfedera** [cisco/openh264#2437]
Cisco's [OpenH264 FAQ](http://www.openh264.org/faq.html) refers to the RELEASES file in the main directory of the openh264 github repository at https://github.com/cisco/openh264/blob/master/RELEASES for _the binary modules for downloading to users_.

However, there are no binaries available for the 1.5.1 and 1.5.2 releases listed in this file.

Since the [1.5.1 branch](https://github.com/cisco/openh264/commits/openh264v1.5.1) has some very important (post 1.5.0) security fixes I'm wondering if and when the according binaries will be available.

**Comment by bmiklautz** [comment]
@nfedera good question I was wondering the same. I search for the 1.5.1 and 1.5.2 binaries as well and couldn't find them.

**Comment by HaiboZhu** [comment]
Thanks for your support on openh264. The differences between 1.5.x and 1.5 are some security fixes for GMP plugin. The provided binary files do not include the GMP plugin so we will not provide binary files for version 1.5.x

**Comment by nfedera** [comment]
@HaiboZhu hmm, thanks but I don't really see how e.g. commit 9e75838c8638c48a32b15c73c9da7b1fe942fd5f is related to the GMP plugin.

**Comment by kuboosoft** [comment]
Hi, why no make a tag release, is very confuse...

**Comment by HaiboZhu** [comment]
Hi, we didn't release the v1.5.1, v1.5.2 and v1.5.3 for some reasons. Now the new release v1.6 has been published and we will make the release process more formal. Thank you for all your supports on openh264 project.
