### ISSUE TITLE
Encoding screen content

### ISSUE THREAD

**Issue by mikhaylo1** [cisco/openh264#2443]
Hi, 
I use openh264 together with gstreamer to encode windows PC screent content and then live stream it.

Have tried various settings but always end up with issues encoding hard scenes. The hard scenes for openh264 are scenes with large amout of text content. Everything works smooth till I open any text document with large amout of text and start moving it over the screen. Once it happens I see dramatic decreasing of fps and encoded stream become pixelated, forzen and broken (that happens when resolution is above then 1024*768 ).
I assume that is openh264 because when I try other h264 encoders with the same gstreamer pipeline I don see such behaviour.

I have tried 1.4 and 1.5 version of openh264 and various settings and combinations - iUsageType, iTargetBitrate, iRCMode (the most worst case when iRCMode=RC_QUALITY_MODE), uiProfileIdc,bEnableBackgroundDetection, bEnableSceneChangeDetect, bEnableFrameSkip

Need an advice what is the best settings to encode PC screen content with large amout of text?

**Comment by ruil2** [comment]
could you attach the bitstreams from openh264 and other codec? let me check why it is. thanks!

**Comment by mikhaylo1** [comment]
Yes, please find attached 2 videos with equal screen recordings
 using openh264 and other h264 encoder. You can find openh264 working very well until there is a large text content on the screen.
iUsageType is pointet to "screen type", other settings are default
[openh264.zip](https://github.com/cisco/openh264/files/220464/openh264.zip)
[x264.zip](https://github.com/cisco/openh264/files/220466/x264.zip)

**Comment by ruil2** [comment]
openh264 has mosaic issue when the content changes very large. It means that some data package are lost, decoder did error concealment. could you turn off the EC on decoder side?

 m_pDecParam->eEcActiveIdc = ERROR_CON_DISABLE; 

Meanwhile in order to avoid low fps, you can set bEnableFrameSkip as 0.

**Comment by mikhaylo1** [comment]
Thank you for the unswer,
picture became broken much faster if I use bEnableFrameSkip = false. But anyway that setting doesn't help much in this case.

Also I have no control on a decoder side, since that is a livestreaming app, and there could be various 3th party decoders working with my stream.

How do you think, will you have a chance to work on this mosaic issue in a near future ?

**Comment by ruil2** [comment]
The encoder bitstream should not have mosaic issue. I guess that some data are discarded when the bitrate is overflow on decoder side or other module.

Can you attach the openh264 trace output?  let me have a check. thanks!

**Comment by ruil2** [comment]
no more trace info.
