### ISSUE TITLE
1.4 binary for iOS

### ISSUE THREAD

**Issue by pepeek** [cisco/openh264#2445]
Do you have version 1.4 binary for iOS?
I don't see it in the listings.

I want to use it with ffmpeg and they claim that the last supported version is 1.4 :-(

BTW, does anyone succeeded to use openh264 with ffmpeg for iOS and Android?
If you could share the instructions that would make my day ;-)

**Comment by ruil2** [comment]
openh264 1.4 version:
v1.4.0
------
http://ciscobinary.openh264.org/libopenh264-1.4.0-android19.so.bz2
http://ciscobinary.openh264.org/libopenh264-1.4.0-linux32.so.bz2
http://ciscobinary.openh264.org/libopenh264-1.4.0-linux64.so.bz2
http://ciscobinary.openh264.org/libopenh264-1.4.0-osx32.dylib.bz2
http://ciscobinary.openh264.org/libopenh264-1.4.0-osx64.dylib.bz2
http://ciscobinary.openh264.org/openh264-1.4.0-win32msvc.dll.bz2
http://ciscobinary.openh264.org/openh264-1.4.0-win64msvc.dll.bz2

you can find the release info from https://github.com/cisco/openh264/blob/master/RELEASES.

**Comment by zbty** [comment]
Dear ruil2, I guess pepeek asked the question whether cisco offers a binary of version 1.4 for iOS.

Honestly, your answer means "no". Am I correct? 
Thank you.

**Comment by ruil2** [comment]
Before 1.5 version, there is no iOS binary release.
