### ISSUE TITLE
Performance vs encoded data size

### ISSUE THREAD

**Issue by i1Eugen** [cisco/openh264#2449]
I am trying to get about 24 frames per second for a 960x540 video using OpenH264 C++ library. I tried different parameters for SEncParamExt and I cannot get better codec performance instead of smaller encoded data. I get about 16-20 fps on my computer.

Here is my current config:

> SEncParamExt param;
> m_pEncoder->GetDefaultParams(&param);
> param.fMaxFrameRate = 30;
> param.bEnableFrameSkip = false;
> param.iMinQp = 20;
> param.iMaxQp = 30;
> param.iPicWidth = m_frameFormat.GetWidth();
> param.iPicHeight = m_frameFormat.GetHeight();
> param.iTargetBitrate = 5000000;
> param.bEnableDenoise = false;
> param.iSpatialLayerNum = 1;
> param.iTemporalLayerNum = 1;
> param.iMultipleThreadIdc = 2;
> param.bUseLoadBalancing = true;
> 
> for (int i = 0; i < param.iSpatialLayerNum; i++)
> {
>     param.sSpatialLayers[i].iVideoWidth = m_frameFormat.GetWidth()  >> > (param.iSpatialLayerNum - 1 - i);
>     param.sSpatialLayers[i].iVideoHeight = m_frameFormat.GetHeight() >> (param.iSpatialLayerNum - 1 - i);
>     param.sSpatialLayers[i].fFrameRate = 30;
>     param.sSpatialLayers[i].iSpatialBitrate = param.iTargetBitrate;
>     param.sSpatialLayers[i].sSliceArgument.uiSliceMode = SM_FIXEDSLCNUM_SLICE;
>     param.sSpatialLayers[i].sSliceArgument.uiSliceNum = 2;
> }
> 
> param.iTargetBitrate *= param.iSpatialLayerNum;

I tried different values for param.iComplexityMode and param.iRCMode and I get the necessary frame rate but a very bad picture quality (small output encoded data). Also I played with quantization levels and it did not help.

Previously I worked with VP8 and now I have tested the same video with it. It easily produces 24 frames per second (and even more) for the same video. The encoded data size is bigger (about 500Kb per second vs 200Kb per second in the case of OpenH264) but it is very convenient for me.

What am I doing wrong? What should I do to increase OpenH264 performance in my case? Bigger encoded data size is not a problem for me.

Thanks,
Eugen

**Comment by sijchen** [comment]
iComplexityMode is not with much use for now. 
play with iRCMode and iMaxQp should be helpful on the quality side. 

what resolution and platform are the tests on?

**Comment by i1Eugen** [comment]
I was mistaken in my first message. Actually, the resolution is 1920x1080, but the video player (or youtube window) size is 960x540.

I use Windows 8 and capture the desktop using DXGI, then convert the ARGB picture to Yuv420, then use OpenH264 to encode it.

I use modular structure in my software. When I change OpenH264 encoder to VP8 encoder, it works much faster and easily does 24 fps. So I think that I am doing something wrong in the case of OpenH264. Yes, I tried to play with iRCMode and it did not help me a lot. IMaxQp slightly changes fps but I get about 20 fps in the best case. When I maximize the video to full screen size, it almost dies with 4-8 fps.

**Comment by ruil2** [comment]
Could you try to use param.iMultipleThreadIdc = 1 for your parameter setting? other parameters can keep no change firstly.

**Comment by i1Eugen** [comment]
Yes, sure.
**param.iMultipleThreadIdc = 1**

> param.fMaxFrameRate = 30;
> param.bEnableFrameSkip = false;
> param.iMinQp = 20;
> param.iMaxQp = 30;
> param.iPicWidth = m_frameFormat.GetWidth();
> param.iPicHeight = m_frameFormat.GetHeight();
> param.iTargetBitrate = m_frameFormat.GetWidth() * m_frameFormat.GetHeight() * 24 * 2 * 0.07;
> param.bEnableDenoise = false;
> param.iSpatialLayerNum = 1;
> param.iTemporalLayerNum = 1;
> param.iMultipleThreadIdc = 1;
> param.bUseLoadBalancing = true;
> param.sSpatialLayers[0].iVideoWidth = param.iPicWidth;
> param.sSpatialLayers[0].iVideoHeight = param.iPicHeight;
> param.sSpatialLayers[0].fFrameRate = 24;
> param.sSpatialLayers[0].iSpatialBitrate = param.iTargetBitrate;
> param.sSpatialLayers[0].sSliceArgument.uiSliceMode = SM_FIXEDSLCNUM_SLICE;
> param.sSpatialLayers[0].sSliceArgument.uiSliceNum = 2;

I got about 10-12 fps and about 300 Kb/s. Please see the attached IMultipleThreadIdc_1.txt logfile. Please note that the video does not start from the beginning of encoding. I start it manually in a couple of seconds from beginning.

Then I changed it back to two.
**param.iMultipleThreadIdc = 2**

I got about 12-15 fps and about 350 Kb/s. Please see the attached iMulitpleThreadIdc_2.txt logfile.

Then I changed the target bitrate.
**param.iTargetBitrate = 2000000**

I got about 12-15 fps and about 200 Kb/s. Please see the attached iTargetBitrate_2000000.txt.

Then I tried to play with iRCMode. Subjectively, I did not see any significant changes.

[iMultipleThreadIdc_1.txt](https://github.com/cisco/openh264/files/236814/iMultipleThreadIdc_1.txt)
[iMultipleThreadIdc_2.txt](https://github.com/cisco/openh264/files/236815/iMultipleThreadIdc_2.txt)
[iTargetBitrate_2000000.txt](https://github.com/cisco/openh264/files/236816/iTargetBitrate_2000000.txt)

**Comment by ruil2** [comment]
from your trace, I didn't see encoding parameters. could you send the log again? 
and  the encoding speed is above 20fps, How to get the the speed info on your side?

**Comment by i1Eugen** [comment]
> from your trace, I didn't see encoding parameters. could you send the log again? 

Yes, sure. I have added encoding parameters to the logs.
[iMultipleThreadIdc_1_ext_logs.txt](https://github.com/cisco/openh264/files/238800/iMultipleThreadIdc_1_ext_logs.txt)
[iMultipleThreadIdc_2_ext_logs.txt](https://github.com/cisco/openh264/files/238801/iMultipleThreadIdc_2_ext_logs.txt)

> and the encoding speed is above 20fps, How to get the the speed info on your side?

As I mentioned in my previous message, I start the video not from beginning of encoding. So when you see above 20fps, it is mouse cursor moving. When the video started, the fps is worse.

The extended logs are recorded with video started from the beginning of encoding. Also I have  added FPS to logs (keyword "FPS"). Please, look at it.

**Comment by ruil2** [comment]
1. which version are you using openh264?
2. I didn't see openh264 encoding parameters from openh264 itself.
    could you set the trace level or trace sink before initialization?
3. release or debug are your using? openh264 library is built by ourself?
4. which platform are you running on?

**Comment by i1Eugen** [comment]
> which version are you using openh264?

I downloaded it on Monday via **Download Zip** here. In the RELEASES file last what it says is:

v1.5.2
------
- Fix GMP Plugin causing the Browser crash on Android

> I didn't see openh264 encoding parameters from openh264 itself. could you set the trace level or trace sink before initialization?

How can I do it? Right now I am doing the following:

```
	int nTraceLevel = WELS_LOG_DETAIL;
	m_pEncoder->SetOption(ENCODER_OPTION_TRACE_LEVEL, &nTraceLevel);
	
	WelsTraceCallback callback = CodecTraceCallback;
	m_pEncoder->SetOption(ENCODER_OPTION_TRACE_CALLBACK, &callback);
```

As far as I understand WELS_LOG_DETAIL is the most detailed log level. Should I do something else to get encoding parameters from the codec itself?

> release or debug are your using? openh264 library is built by ourself?

1) I use the release 64 bit version.
2) Yes, I compiled it myself via build/AutoBuildForWPAndWindows.bat Win64-Release-C

> which platform are you running on?
Windows 8, (i3 - 2100). Also I tried it on WIndows 10 (i5 - 2400) and got about the same results.

**Comment by ruil2** [comment]
I did a testing on Win8(i5 2400 CPU  3.09GHZ). Almost same configure with you, 1920x1080 video encoding speed is above 30fps.

Now I have no idea about your low performance issue.  You can try to only test encoder performance by using encoder console application.

**Comment by ruil2** [comment]
if still have questions, please submit issue freely. thanks!
