### ISSUE TITLE
Supported profiles

### ISSUE THREAD

**Issue by divyahs** [cisco/openh264#2450]
I went through opeh264 code, i find that it is supporting for baseline and main profile, but i didnt find B frame prediction. 

But in README.md file specified its supports only Constrained Baseline Profile up to Level 5.2. 

Is codec supports main profile? if so how to do B frame settings.

**Comment by huili2** [comment]
As you mentioned, it fully supports Constrained Baseline Profile, with some other tools in Main and High. For B frames, it is not supported and till now there is no action on this.

**Comment by harshadapendse** [comment]
@huili2 , will you please explain what are other tools we need to support Main and High profile. Please explain in detail. I am going to use it for webRTC streaming High and Main H264 encoded streams.
