### ISSUE TITLE
SVC quality 

### ISSUE THREAD

**Issue by divyahs** [cisco/openh264#2453]
Hello,  i am checking svc quality  with two layers consider layer 1 and layer 2.  I have created random slice wise loss, whenever their is  complete loss in layer 2, i could see that gray coloured image in decoded output.  

Can you let me know the reason? Thanks in advance

**Comment by divyahs** [comment]
I have tested by giving layer 1 as input, its decoding fine with output 320 x 180 resolution.

layer 1: 320 x 180  base layer
layer 2:  640 x 360  residual layer

But when i gave two layers as a input, at some instances their is a complete loss in layer 2 that time i am getting decoder out put as gray coloured image which is resemble to layer 2.

My question is at that instance output should resemble to layer 1 right  since complete loss in layer 2?

**Comment by divyahs** [comment]
I have setted temporal layer: 1 and spatial layer: 2, can any one tell how to separate out the encoded data of layer 1 and layer 2?

**Comment by HaiboZhu** [comment]
Sorry for late reply. In fact, openh264 only support H.264/AVC single layer decode, and only partly support SVC syntax. You can decode the bitstream across an extractor, or generate the bitstream with simulcast AVC.

**Comment by vincent314314** [comment]
how did svc be implemented in the open264?

**Comment by sijchen** [comment]
we wont fully support svc because the license will be different

**Comment by vincent314314** [comment]
does the openH264 stack support svc？
