### ISSUE TITLE
how to bulid  openh264   for  Mac OSX 64-bit and32-bit

### ISSUE THREAD

**Issue by feipiao** [cisco/openh264#2454]
how to bulid  openh264   for  Mac OSX 64-bit and32-bit

**Comment by Numero7** [comment]
+1

**Comment by Numero7** [comment]
Result of command "make" in the main directory under Macosx

nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/common/x86/cpuid.o codec/common/x86/cpuid.asm
nasm: fatal: unrecognised output format `macho64' - use -hf for a list
type `nasm -h' for help
make: *** [codec/common/x86/cpuid.o] Error 1

**Comment by ruil2** [comment]
mac os 64-bit build: make ARCH=x86_64
 mac os 64-bit build:  make make ARCH=i386
