### ISSUE TITLE
Hardware decoding support

### ISSUE THREAD

**Issue by 7Z0t99** [cisco/openh264#2475]
Please correct me if I am wrong, but AFAIK there is no support for hardware decoding. This is especially interesting for mobile devices, as hardware decoding usually uses significantly less power. So having support for DXVA(2), VA-API, VDPAU, ... would be cool

**Comment by HaiboZhu** [comment]
As a software codec, openh264 only provides the encode & decode functions. You can call related hardware decoding API on the specific platform, such as Apple iOS, etc.
