### ISSUE TITLE
Building on mac for android

### ISSUE THREAD

**Issue by KingZD** [cisco/openh264#2486]
When I use the command "make OS=android ARCH=arm NDKROOT=$NDK_ROOT TARGET=android-19" the following error occurred 

`/Users/zd/company/ndk/android-ndk-r11b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: codec/common/src/cpu-features.o: incompatible target
codec/common/src/cpu.o:cpu.cpp:function WelsCPUFeatureDetect: error: undefined reference to 'wels_getCpuFamily'
codec/common/src/cpu.o:cpu.cpp:function WelsCPUFeatureDetect: error: undefined reference to 'wels_getCpuCount'
codec/common/src/cpu.o:cpu.cpp:function WelsCPUFeatureDetect: error: undefined reference to 'wels_getCpuFeatures'
codec/common/src/WelsThreadLib.o:WelsThreadLib.cpp:function WelsQueryLogicalProcessInfo: error: undefined reference to 'wels_getCpuCount'
collect2: error: ld returned 1 exit status
make: *** [libopenh264.so] Error 1
`
I should pay attention to what issues Thank you

**Comment by Embedded4development** [comment]
linking error, you have to link -lopenh264 in make file responsible to compile "cpu.cpp"
