### ISSUE TITLE
How to set sps/pps to be separately from the stream ?

### ISSUE THREAD

**Issue by aleniuk** [cisco/openh264#2501]
Hello, everybody. Can openh264 encoder make sps/pps nal units, lay separately from the stream?

in ffmpeg there's a code for taking them:

```
if (avctx->flags & AV_CODEC_FLAG_GLOBAL_HEADER) {
        SFrameBSInfo fbi = { 0 };
        int i, size = 0;
        (*s->encoder)->EncodeParameterSets(s->encoder, &fbi);
        for (i = 0; i < fbi.sLayerInfo[0].iNalCount; i++)
            size += fbi.sLayerInfo[0].pNalLengthInByte[i];
        avctx->extradata = av_mallocz(size + AV_INPUT_BUFFER_PADDING_SIZE);
        if (!avctx->extradata) {
            err = AVERROR(ENOMEM);
            goto fail;
        }
        avctx->extradata_size = size;
        memcpy(avctx->extradata, fbi.sLayerInfo[0].pBsBuf, size);
    }
```

but how to make encoder fill fbi.sLayerInfo[0].pBsBuf ? By default it creates the stream with sps/pps nal units inside of it. And I need it to be without SPS/PPS nal units.

And the the reverse situation, If I have sps/pps nal units, that correspond to openh264's opportunities, can I somehow send them to the encoder, so it'll be configured by them?

Thanks.

**Comment by ruil2** [comment]
1. if have SPS/PPS  NALs, they will be put in  fbi.sLayerInfo[0].pBsBuf, and VLC data isn't put  fbi.sLayerInfo[0].pBsBuf, but put in  fbi.sLayerInfo[1...n].pBsBuf.
2. openh264 has no plan to support SPS/PPS input.

**Comment by aleniuk** [comment]
ok, but there are 2 types of nal units: "annex b" nal units, that start from bytes 0x00.00.00.01 , and "avcc" nal units, that start from the length of the following nal unit. It it possible to set openh264 encoding to use "avcc" nal units on the output?

**Comment by mstorsjo** [comment]
@aleniuk No, that's not currently possible. But if you want to do that, you can do what libavcodec/libavformat does, that is:

- Call `(*s->encoder)->EncodeParameterSets(s->encoder, &fbi);` in order to get the SPS/PPS without actually encoding any frame
- When encoding frames, don't include all `fbi.sLayerInfo[n]`, but only include `fbi.sLayerInfo[fbi.iLayerNum - 1]`
- Translate from annex b format to avcc format (this is done in `libavformat/avc.c`)

**Comment by dpingk** [comment]
> @aleniuk No, that's not currently possible. But if you want to do that, you can do what libavcodec/libavformat does, that is:
> 
> * Call `(*s->encoder)->EncodeParameterSets(s->encoder, &fbi);` in order to get the SPS/PPS without actually encoding any frame
> * When encoding frames, don't include all `fbi.sLayerInfo[n]`, but only include `fbi.sLayerInfo[fbi.iLayerNum - 1]`
> * Translate from annex b format to avcc format (this is done in `libavformat/avc.c`)

hello, do you know how to put raw sps/pps into extradata from raw rtp stream?
sps/pps I conduct like ([start code]0x67...), ...

codes like below seems not working

`
AVStream os = avformat_new_stream...
...
os->extradata = av_mallocz(size + PADDING...);
...
memcpy(os->extradata, sps->data, sps->size);
memcpy(os->extradata + sps->size, pps->data, pps->size);
...
`
