### ISSUE TITLE
CPU architectures on Android 

### ISSUE THREAD

**Issue by zbty** [cisco/openh264#2502]
Please, what cpu architectures on Android does Cisco cover by their [license](http://www.openh264.org/BINARY_LICENSE.txt) for their [binary builds](https://github.com/cisco/openh264/releases) for Android?

I have successfully tested licensed binary release v 1.4 for Android on ARM architecture. 

Does Cisco provide any legal way to get/build/use their openh264 encoder on Android of different cpu architectures? For example x86 and x86_64?

If not, why? If it is not a secret.

Thank you.

**Comment by fluffy** [comment]
The folks at Cisco were hoping the community would help sends patches to make an automated a reproducible build process for the binaries. For example something like what is in https://github.com/cisco/openh264/blob/master/build/Dockerfile .  We can provide binaries for other architectures than the ones we currently do. It is purely an issue of time to build and test them but it that was automated we would probably distribute the binaries. 

One bar we had used before was if you are distributing less that 100k copies per year, the royalties from mpeg-la are 0 so we are mostly interested in architectures where the number of copies will be above that.
