### ISSUE TITLE
licensed lib on iOS in production?

### ISSUE THREAD

**Issue by zbty** [cisco/openh264#2503]
Cisco provides [licensed](http://www.openh264.org/BINARY_LICENSE.txt) [binary builds](https://github.com/cisco/openh264/releases) of openh264 encoder for iOS.

Could somebody, please, describe the way how to use it on iOS devices in production? The License requires the library to be loaded by the end user to the device. Perhaps every developer knows the principle of AppStore in application deployment. I guess there is no way how to modify, extend or modify by any other way the files of app after AppStore's evaluation. Any minor change must first pass through the evaluation in AppStore.

Is there any way how to conform the [license](http://www.openh264.org/BINARY_LICENSE.txt) in production for iOS ?

Thank you.

**Comment by fluffy** [comment]
For the most part, I don't think so. Most people are using the apple provided hardware assisted 264 on iOS.
