### ISSUE TITLE
openh264 and FFmpeg

### ISSUE THREAD

**Issue by madovsky** [cisco/openh264#2505]
Is there any workaround to make the last openh264 git compatible with the last FFmpeg git?
Actually only the openh264 version 1.5 compile fine with FFmpeg. thank you very much

**Comment by GregoryJWolfe** [comment]
FYI, a number of FFmpeg patches have been submitted to the FFmpeg developers that are needed for the software to build properly with the latest openh264.  I have manually applied these patches to my own FFmpeg build with no problems.  However, the impression I get from email conversations on the FFmpeg developers mailing list is that the developers will not apply these patches to FFmpeg until there is a stable, supported openh264 release (1.6?) that contains all the changes to which the FFmpeg patches apply.

**Comment by madovsky** [comment]
ok I see, I thought FFmpeg just was lazy to not do it because of their interest with heir libx264 libraries.
I hope it's just not the case and let the users to choose what is their preference.
hope 1.6 version will come soon, thanks for your answer

**Comment by HaiboZhu** [comment]
Thanks for your support on openh264. We will release the latest v1.6 recently.

**Comment by ilovezfs** [comment]
@GregoryJWolfe Any update on this now that 1.6.0 has been released?

I'm intending to vendor 1.5.0 into the ffmpeg formula to temporarily resolve https://github.com/Homebrew/homebrew-core/issues/2946 but I would much prefer a real upstream fix, of course.

Thanks for your work on this!

**Comment by ilovezfs** [comment]
@ HaiboZhu are you contact with the ffmpeg developers to work out a solution for the incompatibility?

**Comment by ilovezfs** [comment]
@HaiboZhu are you contact with the ffmpeg developers to work out a solution for the incompatibility?

**Comment by GregoryJWolfe** [comment]
Please be advised that I am just another user of FFmpeg and libopenh264.  While I have contributed some patches to both, I'm not involved in making the decisions about when patches get applied and/or back-ported.  My suggestion would be to send a request to the FFmpeg developer mailing list that the 1.6 related patches be applied and/or back-ported.

Since we build FFmpeg from the source code, we simply apply the patches ourselves until FFmpeg releases catch up.  That being said, we much prefer that THEY do it so we don't have to maintain our own versions of the modified source files.

**Comment by bermond** [comment]
This issue has been fixed by FFmpeg git commit [293676c476733e81d7b596736add6cd510eb6960](http://git.videolan.org/?p=ffmpeg.git;a=commit;h=293676c476733e81d7b596736add6cd510eb6960).

Now FFmpeg (git master version) compiles correctly when using OpenH264 1.6.0.

**Comment by madovsky** [comment]
Thanks, bermond, very appreciated ;)

**Comment by madovsky** [comment]
Bermond, the last ffmpeg git compiles well with the last openh264 but not 
with the stable ffmpeg release 3.1.1. is it normal?

libavcodec/libopenh264enc.c:54:84: error: ‘SM_AUTO_SLICE’ undeclared here (not in a function)
     { "slice_mode", "set slice mode", OFFSET(slice_mode), AV_OPT_TYPE_INT, { .i64 = SM_AUTO_SLICE }, SM_SINGLE_SLICE, SM_RESERVED, VE, "slice_mode" },
                                                                                    ^
libavcodec/libopenh264enc.c:56:87: error: ‘SM_ROWMB_SLICE’ undeclared here (not in a function)
         { "rowmb", "one slice per row of macroblocks", 0, AV_OPT_TYPE_CONST, { .i64 = SM_ROWMB_SLICE }, 0, 0, VE, "slice_mode" },
                                                                                       ^
libavcodec/libopenh264enc.c:58:68: error: ‘SM_DYN_SLICE’ undeclared here (not in a function)
         { "dyn", "Dynamic slicing", 0, AV_OPT_TYPE_CONST, { .i64 = SM_DYN_SLICE }, 0, 0, VE, "slice_mode" },
                                                                    ^
libavcodec/libopenh264enc.c: In function ‘svc_encode_init’:
libavcodec/libopenh264enc.c:196:23: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
         s->slice_mode = SM_DYN_SLICE;
                       ^
libavcodec/libopenh264enc.c:198:28: error: ‘SSpatialLayerConfig {aka struct <anonymous>}’ has no member named ‘sSliceCfg’
     param.sSpatialLayers[0].sSliceCfg.uiSliceMode               = s->slice_mode;
                            ^
libavcodec/libopenh264enc.c:198:38: error: request for member ‘uiSliceMode’ in something not a structure or union
     param.sSpatialLayers[0].sSliceCfg.uiSliceMode               = s->slice_mode;
                                      ^
libavcodec/libopenh264enc.c:198:5: warning: statement with no effect [-Wunused-value]
     param.sSpatialLayers[0].sSliceCfg.uiSliceMode               = s->slice_mode;
     ^
libavcodec/libopenh264enc.c:199:28: error: ‘SSpatialLayerConfig {aka struct <anonymous>}’ has no member named ‘sSliceCfg’
     param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceNum = avctx->slices;
                            ^
libavcodec/libopenh264enc.c:199:38: error: request for member ‘sSliceArgument’ in something not a structure or union
     param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceNum = avctx->slices;
                                      ^
libavcodec/libopenh264enc.c:199:53: error: request for member ‘uiSliceNum’ in something not a structure or union
     param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceNum = avctx->slices;
                                                     ^
libavcodec/libopenh264enc.c:199:5: warning: statement with no effect [-Wunused-value]
     param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceNum = avctx->slices;
     ^
libavcodec/libopenh264enc.c:201:23: warning: comparison between pointer and integer
     if (s->slice_mode == SM_DYN_SLICE) {
                       ^
libavcodec/libopenh264enc.c:204:36: error: ‘SSpatialLayerConfig {aka struct <anonymous>}’ has no member named ‘sSliceCfg’
             param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceSizeConstraint = s->max_nal_size;
                                    ^
libavcodec/libopenh264enc.c:204:46: error: request for member ‘sSliceArgument’ in something not a structure or union
             param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceSizeConstraint = s->max_nal_size;
                                              ^
libavcodec/libopenh264enc.c:204:61: error: request for member ‘uiSliceSizeConstraint’ in something not a structure or union
             param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceSizeConstraint = s->max_nal_size;
                                                             ^
libavcodec/libopenh264enc.c:204:13: warning: statement with no effect [-Wunused-value]
             param.sSpatialLayers[0].sSliceCfg.sSliceArgument.uiSliceSizeConstraint = s->max_nal_size;
             ^
common.mak:60: recipe for target 'libavcodec/libopenh264enc.o' failed

**Comment by madovsky** [comment]
oops, sorry the result above was with ffmpeg stable 3.0.2, not 3.1.1

**Comment by bermond** [comment]
@madovsky 

It is normal because the latest git commits hasn't being incorporated in the current FFmpeg 3.1.1 release yet (and not even in 3.0.2).

If you want to compile a release version of FFmpeg with OpenH264 1.6.0 support you have two choices:

1) Wait for a newer FFmpeg release version. It will incorporate the latest git commits, including the one that fixed this issue.
2) You can try to apply a patch using the git commit the fixed this issue (the one that I cited in my previous message). In this specific case, notice that **maybe** you will also need to _firstly_ apply a patch from commit [c5d326f551b0312ff581bf1df35b21d956e01523](http://git.videolan.org/?p=ffmpeg.git;a=commit;h=c5d326f551b0312ff581bf1df35b21d956e01523).

Please notice that FFmpeg developers recommend to use the git master version because it incorporates the latest fixes and is considered stable enough mostly of the time. I use the git master version (compiled daily) and it works very well.

**Comment by madovsky** [comment]
ok understood. Yes I usually use the git version, but I was stuck with another software that uses now old version of libav. I hope they will update it soon since I have not enough C language knowledge..
