### ISSUE TITLE
x264 to openh264: Change CRF and Preset in FFMPEG

### ISSUE THREAD

**Issue by Inkeliz** [cisco/openh264#2506]
I use the x264 before, but the GPL license can be a problem.
The openh264 is a nice alternative to x264, but I don't found some things.

The first is the Preset.
Using the -preset XXXX not change anything.
I can't change the CRF, set -crf not affect.

In the "documentation" of FFmpeg: https://www.ffmpeg.org/ffmpeg-codecs.html#libopenh264
Not have this option.

**Have a way to change it using the FFmpeg?**

> Note:  I'm using the ffpmeg command line tool, compiled with openh264!

**Comment by ruil2** [comment]
1. build ffmpeg by using "--enable-libopenh264" 
2. run ffmpeg by using   "-vcodec libopenh264"

**Comment by SortaCore** [comment]
That doesn't solve the issue @ruil2. The question was options "preset" and "crf" are not available in ffmpeg. Can you clarify if they are in openh264 at all?

**Comment by SortaCore** [comment]
@Inkeliz I encourage you to re-open the issue until it's answered properly, if you can.

**Comment by jozefchutka** [comment]
Following [this patch from 2020](https://patchwork.ffmpeg.org/project/ffmpeg/patch/1585926759-22569-1-git-send-email-linjie.fu@intel.com/) quantizer is supported via `-qmin`, `-qmax`.

Tested in ffmpeg 7.0:

```
ffmpeg -i in.mp4 -vcodec libopenh264 out.mp4
# produces 2MB mp4

ffmpeg -i in.mp4 -qmin 30 -vcodec libopenh264 out.mp4
# produces 1MB mp4
```
