### ISSUE TITLE
Bad SHAREDLIBVERSION definition

### ISSUE THREAD

**Issue by marillat** [cisco/openh264#2521]
Hi,

In commit af8240a4407385cb0059db808fb3fc762143e2f4 SHAREDLIBVERSION has been changed from 2 to 0

This is probably a mistake as SHAREDLIBVERSION should never be downgraded (was 1 in 1.5.0)

**Comment by HaiboZhu** [comment]
Hi, thanks for your reminder. Please find the results here: #2511

**Comment by HaiboZhu** [comment]
No update about it, close this issue.

**Comment by marillat** [comment]
The solution has been explained by @mstorsjo in  https://github.com/cisco/openh264/pull/2511#issuecomment-231692001
