### ISSUE TITLE
1.6.0 might not work on OS X 10.8 and earlier

### ISSUE THREAD

**Issue by LordSmokedMeatsAndFishes** [cisco/openh264#2525]
The 1.6.0 OS X dylibs contain "/usr/lib/libc++.1.dylib", but this library does not exist in OS X 10.8 and earlier, so it probably won't work with them.  The 1.5.3 dylibs which work with 10.8 and earlier contain "/usr/lib/libstdc++.6.dylib"....

**Comment by HaiboZhu** [comment]
Thanks for your reminder. We will check it soon. By the way, Do you know how to remove the dependence on "/usr/lib/libc++.1.dylib" and re-direct it to "/usr/lib/libstdc++.6.dylib"? Thank you very much.

**Comment by HaiboZhu** [comment]
Thanks for your reminder. We have fixed this issue locally. We will upload the new binary files soon.

**Comment by HaiboZhu** [comment]
Updated the binary files location in RELEASE file and release description, close this issue.
