### ISSUE TITLE
x86 has text relocations

### ISSUE THREAD

**Issue by zhangguowei** [cisco/openh264#2534]
Compiled x86 version，so has text relocations。
scanelf -qT libopenh264.so
 libopenh264.so: (memory/data?) [0x667D4] in (optimized out: previous CavlcParamCal_sse2) [0x66780]
  libopenh264.so: (memory/data?) [0x667E6] in (optimized out: previous CavlcParamCal_sse2) [0x66780]
  libopenh264.so: (memory/data?) [0x6682F] in (optimized out: previous CavlcParamCal_sse2) [0x66780]
  libopenh264.so: (memory/data?) [0x66882] in (optimized out: previous CavlcParamCal_sse2) [0x66780]
  libopenh264.so: (memory/data?) [0x677C9] in (optimized out: previous WelsI4x4LumaPredH_sse2) [0x677B0]
  libopenh264.so: (memory/data?) [0x677DA] in (optimized out: previous WelsI4x4LumaPredH_sse2) [0x677B0]
  libopenh264.so: (memory/data?) [0x677F0] in (optimized out: previous WelsI4x4LumaPredH_sse2) [0x677B0]
  libopenh264.so: (memory/data?) [0x67801] in (optimized out: previous WelsI4x4LumaPredH_sse2) [0x677B0]
  libopenh264.so: (memory/data?) [0x6783F] in (optimized out: previous WelsI16x16LumaPredPlane_sse2) [0x67820]
  libopenh264.so: (memory/data?) [0x67854] in (optimized out: previous WelsI16x16LumaPredPlane_sse2) [0x67820]
  libopenh264.so: (memory/data?) [0x679B7] in (optimized out: previous WelsI16x16LumaPredPlane_sse2) [0x67820]
  libopenh264.so: (memory/data?) [0x67A1C] in (optimized out: previous WelsIChromaPredPlane_sse2) [0x67A00]
  libopenh264.so: (memory/data?) [0x67A2D] in (optimized out: previous WelsIChromaPredPlane_sse2) [0x67A00]
  libopenh264.so: (memory/data?) [0x67B39] in (optimized out: previous WelsIChromaPredPlane_sse2) [0x67A00]
  libopenh264.so: (memory/data?) [0x67BD0] in (optimized out: previous WelsI4x4LumaPredDDR_mmx) [0x67B70]
  libopenh264.so: (memory/data?) [0x67C77] in (optimized out: previous WelsIChromaPredH_mmx) [0x67C60]
  libopenh264.so: (memory/data?) [0x67C8E] in (optimized out: previous WelsIChromaPredH_mmx) [0x67C60]
  libopenh264.so: (memory/data?) [0x67CA8] in (optimized out: previous WelsIChromaPredH_mmx) [0x67C60]
  libopenh264.so: (memory/data?) [0x67CC0] in (optimized out: previous WelsIChromaPredH_mmx) [0x67C60]
  libopenh264.so: (memory/data?) [0x67CDA] in (optimized out: previous WelsIChromaPredH_mmx) [0x67C60]
  libopenh264.so: (memory/data?) [0x67CF2] in (optimized out: previous WelsIChromaPredH_mmx) [0x67C60]
  libopenh264.so: (memory/data?) [0x67D0C] in (optimized out: previous WelsIChromaPredH_mmx) [0x67C60]
  libopenh264.so: (memory/data?) [0x67D24] in (optimized out: previous WelsIChromaPredH_mmx) [0x67C60]
  libopenh264.so: (memory/data?) [0x67DE4] in (optimized out: previous WelsI4x4LumaPredHD_mmx) [0x67D90]
  libopenh264.so: (memory/data?) [0x67E86] in (optimized out: previous WelsI4x4LumaPredHU_mmx) [0x67E30]
  libopenh264.so: (memory/data?) [0x67F0F] in (optimized out: previous WelsI4x4LumaPredVR_mmx) [0x67EC0]

**Comment by HaiboZhu** [comment]
Hi, Thank you for your support on openh264 project. We have not supply the binary files on android x86 platform now. For your text relocations problem, you can use the "-fPIC" to make it work. We will check this issue later.

**Comment by GuangweiWang** [comment]
@zhangguowei . could you please give more info about you build environment? e.g. your os version, gcc/clang version ...
I can not reproduce this issue in my environment use the default build options.(as the default CFLAGS  include -fPIC options, do you use this option or not?)

**Comment by ruil2** [comment]
fixed in #2611
