### ISSUE TITLE
Need  Exp-Golomb coding related information.

### ISSUE THREAD

**Issue by RajibTheKing** [cisco/openh264#2545]
Please help me providing Exp-Golomb coding related information, Here is the link: 
http://stackoverflow.com/questions/38992443/methods-for-exp-golomb-codeword-construction-and-parsing

**Comment by ruil2** [comment]
@RajibTheKing  you can refer to ITU-T H.264 Specification on 9 section(Parsing Process)  about this.

**Comment by RajibTheKing** [comment]
@ruil2 ...  Thanks for the suggestion, I have already found out the exp-golomb parsing procedure. Thanks again.
