### ISSUE TITLE
Can't compile on OS X

### ISSUE THREAD

**Issue by bumblebritches57** [cisco/openh264#2552]
I called make with: make OS=darwin ARCH=x86_64

and it prints out: 

nasm -DUNIX64 -DHAVE_AVX2 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/common/x86/cpuid.o codec/common/x86/cpuid.asm
nasm: fatal: unrecognised output format `macho64' - use -hf for a list
type `nasm -h' for help
make: *** [codec/common/x86/cpuid.o] Error 1

**Comment by GuangweiWang** [comment]
this error caused by your nasm version is not suitable. 
NASM needed to be installed for assembly code: workable version 2.10.06 or above, nasm can downloaded from http://www.nasm.us/ 
For Mac OSX 64-bit NASM needed to be below version 2.11.08 as nasm 2.11.08 will introduce error when using RIP-relative addresses in Mac OSX 64-bit.
please upgrade you nasm and try again.

**Comment by bumblebritches57** [comment]
I installed that exact version of nasm with homebrew. it still doesn't work.

**Comment by bumblebritches57** [comment]
I installed nasm 2.11.06 with Homebrew...

**Comment by GuangweiWang** [comment]
if you run this:  nasm -v
 on command line, which version it returned?

**Comment by GuangweiWang** [comment]
run this : nasm -v 
on your command line. ensure the version of nasm is consistent with the one you have installed.

**Comment by bumblebritches57** [comment]
This is the version that works: NASM version 2.11.06 compiled on Oct 20 2014

Here's the one that didn't work: NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Aug 24 2016

Which is part of Xcode 8.

**Comment by ruil2** [comment]
for openh264,workable version 2.10.06 or above,

**Comment by bumblebritches57** [comment]
Yeah I got it working, but it's interface is kinda garbage.

**Comment by Allen1207** [comment]
> I installed nasm 2.11.06 with Homebrew...
> 
> Uninstalling that, and installing it from here fixed it: http://www.nasm.us/pub/nasm/releasebuilds/2.11.06/macosx/

hi , how to install the nasm 2.11.06 ? with Homebrew? when I run brew install nasm, it installed the latest version, but how to install the desired version?

**Comment by GuangweiWang** [comment]
latest version is ok.
