### ISSUE TITLE
Multi-thread encoding with v1.5.1 not work properly?

### ISSUE THREAD

**Issue by qzhua** [cisco/openh264#2555]
I found when using SM_FIXEDSLCNUM_SLICE to enable multi-thread encoding  will produce some kind of **vulnerable** or **undecodable** video stream. 
Our test is based on a device with a 4 core armv7-a above CPU , Android 4.4.2 , and linux core 3.4.66. Our scenario is a typical two way video chat on internet, the uplink bandwidth is limited and packetloss rate is very low.
1. In CIF, the video stream produced by the encoder is decodable. The bitrate seems OK, about 300Kbps. But the image looks broken,  and it won't recover when I frame is received. Some times it looked like a grey forg, if someone is moving in front of the camera, this could remove part of the forg. 
   ![screenshot_2016-09-08-11-37-45 1](https://cloud.githubusercontent.com/assets/4395270/18346357/4f134f1c-75f2-11e6-8701-c2de59d29ad6.png)
   ![screenshot_2016-09-08-11-50-54 2](https://cloud.githubusercontent.com/assets/4395270/18346363/5268465e-75f2-11e6-9d8b-acfa88d6f9e1.png)
2. In 4CIF, things are worse. No matter how I changed the bitrate settings, the encoder just produced a very low bitrate (70Kbps) video stream and can not be decoded by our hardware based decoder.  And no IDR/I frame have been send out.

Both v1.5.1 and v1.6 have this problem. When using SM_DYN_SLICE, it seems to produce reasonable quality for CIF, but broken images for 4CIF. 

And the log dump for  4CIF with SM_FIXEDSLCNUM_SLICE
[openh264_v1.5.1_4CIF_black_screen.txt](https://github.com/cisco/openh264/files/461277/openh264_v1.5.1_4CIF_black_screen.txt)
And the log dump for  4CIF with SM_DYN_SLICE , broken images.
[openh264_SM_DYN_SLICE_bad_quality.txt](https://github.com/cisco/openh264/files/461368/openh264_SM_DYN_SLICE_bad_quality.txt)

The code initializing the Encoder and Decoder is as follows.  For SM_DYN_SLICE, we only changed the uiSliceMode to SM_DYN_SLICE.

```    eprm.iUsageType = CAMERA_VIDEO_REAL_TIME;
    eprm.iNumRefFrame = 1;
    eprm.iPicWidth          = param->enc_fmt.det.vid.size.w;
    eprm.iPicHeight         = param->enc_fmt.det.vid.size.h;
    eprm.fMaxFrameRate          = (param->enc_fmt.det.vid.fps.num *
                                   1.0f /
                                   param->enc_fmt.det.vid.fps.denum);
eprm.iTemporalLayerNum      = 1;
eprm.uiIntraPeriod          = 0; /* I-Frame interval in frames */
eprm.iRCMode =RC_QUALITY_MODE;

eprm.eSpsPpsIdStrategy= oh264_data->whole? CONSTANT_ID: INCREASING_ID;
eprm.bEnableFrameCroppingFlag   = true;
eprm.iLoopFilterDisableIdc      = 0;
eprm.iLoopFilterAlphaC0Offset   = 0;
eprm.iLoopFilterBetaOffset      = 0;
eprm.iMultipleThreadIdc     = 0;
eprm.iComplexityMode = MEDIUM_COMPLEXITY;
//eprm.bEnableRc            = 1;
eprm.iTargetBitrate         = 1228000;//param->enc_fmt.det.vid.avg_bps;
//TODO: this may need further improve
LOGD(__FILE__,"video avg_bps is %d ,max_bps is %d, max_fps is %.2f\n",param->enc_fmt.det.vid.avg_bps, param->enc_fmt.det.vid.max_bps,eprm.fMaxFrameRate);
if(param->enc_fmt.det.vid.max_bps >=param->enc_fmt.det.vid.avg_bps)
    eprm.iMaxBitrate = param->enc_fmt.det.vid.max_bps;
else
    eprm.iMaxBitrate = 2328000;//param->enc_fmt.det.vid.avg_bps+100000;
eprm.bEnableFrameSkip       = 1;
eprm.bEnableDenoise         = 1;
eprm.bEnableSceneChangeDetect   = 1;
eprm.bEnableBackgroundDetection = 1;
eprm.bEnableAdaptiveQuant       = 1;
eprm.bEnableLongTermReference   = 0;
eprm.iLtrMarkPeriod         = 30;
eprm.bPrefixNalAddingCtrl       = false;
eprm.iSpatialLayerNum       = 1;
if (!oh264_data->whole) {
    //                eprm.uiMaxNalSize         = param->enc_mtu;
}

pj_bzero(&elayer_ctx, sizeof (SLayerPEncCtx));
elayer_ctx.iDLayerQp        = 24;

elayer_ctx.sSliceCfg.uiSliceMode    = (oh264_data->whole ?
                                       SM_SINGLE_SLICE : SM_FIXEDSLCNUM_SLICE);

elayer_ctx.sSliceCfg.sSliceArgument.uiSliceSizeConstraint = param->enc_mtu; // 
elayer_ctx.sSliceCfg.sSliceArgument.uiSliceNum      = 4;
elayer_ctx.sSliceCfg.sSliceArgument.uiSliceMbNum[0] = 99*4;
elayer_ctx.sSliceCfg.sSliceArgument.uiSliceMbNum[1] = 99*4;
elayer_ctx.sSliceCfg.sSliceArgument.uiSliceMbNum[2] = 99*4;
elayer_ctx.sSliceCfg.sSliceArgument.uiSliceMbNum[3] =99*4;

elayer->iVideoWidth         = eprm.iPicWidth;
elayer->iVideoHeight        = eprm.iPicHeight;
elayer->fFrameRate          = eprm.fMaxFrameRate;
elayer->uiProfileIdc        = eprm.sSpatialLayers[0].uiProfileIdc;
elayer->uiLevelIdc=eprm.sSpatialLayers[0].uiLevelIdc;

elayer->iSpatialBitrate     = eprm.iTargetBitrate;
elayer->iMaxSpatialBitrate      = eprm.iMaxBitrate;

elayer->iDLayerQp           = elayer_ctx.iDLayerQp;
elayer->sSliceCfg.uiSliceMode   = elayer_ctx.sSliceCfg.uiSliceMode;

memcpy( &elayer->sSliceCfg.sSliceArgument,
        &elayer_ctx.sSliceCfg.sSliceArgument,
        sizeof (SSliceArgument));
memcpy( &elayer->sSliceCfg.sSliceArgument.uiSliceMbNum[0],
        &elayer_ctx.sSliceCfg.sSliceArgument.uiSliceMbNum[0],
        sizeof (elayer_ctx.sSliceCfg.sSliceArgument.uiSliceMbNum));

/* Init input picture */
oh264_data->esrc_pic->iColorFormat  = videoFormatI420;
oh264_data->esrc_pic->uiTimeStamp   = 0;
oh264_data->esrc_pic->iPicWidth = eprm.iPicWidth;
oh264_data->esrc_pic->iPicHeight    = eprm.iPicHeight;
oh264_data->esrc_pic->iStride[0]    = oh264_data->esrc_pic->iPicWidth;
oh264_data->esrc_pic->iStride[1]    =
    oh264_data->esrc_pic->iStride[2] =
    oh264_data->esrc_pic->iStride[0]>>1;

oh264_data->enc_input_size = oh264_data->esrc_pic->iPicWidth *
    oh264_data->esrc_pic->iPicHeight * 3 >> 1;
int videoFormat = videoFormatI420;
oh264_data->enc->SetOption (ENCODER_OPTION_DATAFORMAT, &videoFormat);
/* Initialize encoder */
rc = oh264_data->enc->InitializeExt (&eprm);
if (rc != cmResultSuccess) {
    PJ_LOG(4,(THIS_FILE, "SVC encoder Initialize failed, rc=%d", rc));
    return PJMEDIA_CODEC_EFAILED;
}


/*
 * Decoder
 */
sDecParam.sVideoProperty.size   = sizeof (sDecParam.sVideoProperty);
sDecParam.eOutputColorFormat    = videoFormatI420;
sDecParam.uiTargetDqLayer       = (pj_uint8_t) - 1;

sDecParam.eEcActiveIdc =  ERROR_CON_SLICE_MV_COPY_CROSS_IDR;//ERROR_CON_FRAME_COPY;
sDecParam.sVideoProperty.eVideoBsType = VIDEO_BITSTREAM_AVC;

//TODO:
// Apply "sprop-parameter-sets" here

rc = WelsCreateDecoder(&oh264_data->dec);
if (rc) {
    PJ_LOG(4,(THIS_FILE, "Unable to create OpenH264 decoder"));
    return PJMEDIA_CODEC_EFAILED;
}

rc = oh264_data->dec->Initialize (&sDecParam);
if (rc) {
    PJ_LOG(4,(THIS_FILE, "Decoder initialization failed, rc=%d", rc));
    return PJMEDIA_CODEC_EFAILED;
}
```
I test with v1.6 with SM_FIXEDSLCNUM_SLICE as well, the RTP stream for CIF is like the following:

[libopenh264_v1.6_multi_thread_phone2.zip](https://github.com/cisco/openh264/files/608277/libopenh264_v1.6_multi_thread_phone2.zip)
and here is the log
[openh264_v1.6_CIF_FIXEDSLCNUM.log](https://github.com/cisco/openh264/files/608289/openh264_v1.6_CIF_FIXEDSLCNUM.zip)

It shows the video turn bad since the second I-frame and will not recover anyway.

**Comment by ruil2** [comment]
1. how about SM_SINGLE_SLICE mode? 
2.if you turn off multi-threading, how about the result?
3. for bitrate, you can try other bitrate mode such as RC_BITRATE_MODE , RC_TIMESTAMP_MODE

**Comment by fzwoch** [comment]
Maybe this is related. I encountered occasional crashes when enabling multi-threading with multiple slice encoding. This is happening on macOS at least. I'm using the GStreamer 1.10.0 release which (I think) includes OpenH264 1.6. Unfortunately I don't have a complete debug trace but here are some calls for the crash:

```
Process 23263 stopped
* thread #12: tid = 0xe2fe, 0x0000000102e991e3 libopenh264.3.dylib`WelsCommon::CWelsThreadPool::QueueTask(WelsCommon::IWelsTask*) + 35, name = 'probe:src', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000102e991e3 libopenh264.3.dylib`WelsCommon::CWelsThreadPool::QueueTask(WelsCommon::IWelsTask*) + 35
libopenh264.3.dylib`WelsCommon::CWelsThreadPool::QueueTask:
->  0x102e991e3 <+35>: movl   (%rax), %esi
    0x102e991e5 <+37>: movl   0x4(%rax), %ecx
    0x102e991e8 <+40>: movl   %ecx, %edx
    0x102e991ea <+42>: subl   %esi, %edx
(lldb) bt
* thread #12: tid = 0xe2fe, 0x0000000102e991e3 libopenh264.3.dylib`WelsCommon::CWelsThreadPool::QueueTask(WelsCommon::IWelsTask*) + 35, name = 'probe:src', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000102e991e3 libopenh264.3.dylib`WelsCommon::CWelsThreadPool::QueueTask(WelsCommon::IWelsTask*) + 35
    frame #1: 0x0000000102e4838c libopenh264.3.dylib`WelsEnc::CWelsTaskManageBase::ExecuteTaskList(WelsCommon::CWelsCircleQueue<WelsEnc::CWelsBaseTask>**) + 140
    frame #2: 0x0000000102e483f4 libopenh264.3.dylib`WelsEnc::CWelsTaskManageBase::ExecuteTasks(WelsEnc::CWelsBaseTask::ETaskType) + 20
    frame #3: 0x0000000102e12325 libopenh264.3.dylib`WelsEnc::WelsEncoderEncodeExt(WelsEnc::TagWelsEncCtx*, SFrameBSInfo*, Source_Picture_s const*) + 4741
    frame #4: 0x0000000102e49246 libopenh264.3.dylib`WelsEnc::CWelsH264SVCEncoder::EncodeFrameInternal(Source_Picture_s const*, SFrameBSInfo*) + 70
    frame #5: 0x0000000102e491cd libopenh264.3.dylib`WelsEnc::CWelsH264SVCEncoder::EncodeFrame(Source_Picture_s const*, SFrameBSInfo*) + 45
    frame #6: 0x0000000102c315b7 libgstopenh264.so`gst_openh264enc_handle_frame(_GstVideoEncoder*, _GstVideoCodecFrame*) + 679
```

Parameters being used for the GStreamer element are:
```
complexity=low
usage-type=screen
multi-thread=4
slice-mode=auto
rate-control=bitrate
bitrate=4096000
```

From the calls itself it seems like an issue internally to OpenH264 - however I would not rule out any internal mis-configuration from the GStreamer element.

As I said, this happens occasionally, feels like a race condition somewhere. I could not trigger it without multi-threading, but that doesn't necessary mean it couldn't happen there as well.

**Comment by ruil2** [comment]
@qzhua @fzwoch thanks for your feedback. we will try to reproduce this and check the root cause.

**Comment by qzhua** [comment]
Thank you @ruil2 .  I'll try the scenarios your have concerned.

**Comment by qzhua** [comment]
I tested with Openh264 v1.6.0 with some of the condition you have concerned, but there is no improvement. 
1. how about SM_SINGLE_SLICE mode?
For the max MTU constraint, we cannot use single slice mode.

2. if you turn off multi-threading, how about the result?
I turned off multi-threading with `eprm.iMultipleThreadIdc=1`, the quality of video did not improved.

3. for bitrate, you can try other bitrate mode such as RC_BITRATE_MODE , RC_TIMESTAMP_MODE
For  RC_BITRATE_MODE, it did not help either.

I append an RTP capture file in the issue, so you can verify if the bit stream is valid. I have used streameye to exam it, and found that the video turned bad at the second I-frame.

**Comment by ruil2** [comment]
@qzhua 
1. if you have the max MTU limitation, it isn't better to use SM_FIXEDSLCNUM_SLICE. which can't control the NAL size. maybe it is the root cause that the receiver side can't decoded correctly.
2. you can try to use SM_SIZELIMITED_SLICE mode

**Comment by qzhua** [comment]
@ruil2 Thank you. Your answer has solved the problem.
1.  Firstly,  use SM_SIZELIMITED_SLICE instead of SM_FIXEDSLCNUM_SLICE ,  this solved the broken video bit stream.
2. Use RC_TIMESTAMP_MODE instead of RC_BITRATE_MODE, this fixed the abnormal low bit rate and improved video quality problem.


I think I was misled by the comments:
 ` unsigned int  uiSliceSizeConstraint; ///< now only used when uiSliceMode=4`
It should be `uiSliceMode=3`, according to 
```
  SM_SIZELIMITED_SLICE           = 3, ///< | according to SliceSize       | slicing according to size, the slicing will be dynamic(have no idea about slice_nums until encoding current frame)
  SM_RESERVED             = 4
```
