### ISSUE TITLE
Documentation lack

### ISSUE THREAD

**Issue by BilyakA** [cisco/openh264#2568]
OpenH264 has a lot of features and settings, however comments inside code does not provide complete info of what and how will change by setting the same setting to different values.

For example I still can not understand the complete outcome of changing `iUsageType` inside coding param. 
Yes, obvious that `CAMERA_VIDEO_REAL_TIME` must be faster method of encoding than `CAMERA_VIDEO_NON_REAL_TIME`, but what difference in process (quality/bitrate/etc) I'll get while switching between `CAMERA_VIDEO_REAL_TIME` and `SCREEN_CONTENT_REAL_TIME` ?

The same applies to other settings. To not-familiar to h264 standard user almost impossible to understand possible outcome of using non-default values.

**Comment by BilyakA** [comment]
Also by specifying performance/quality impact of each option we can get rid of major part of "performance issue" questions.

**Comment by ruil2** [comment]
@BilyakA  thanks for your feedback. we will improve our document later.
