### ISSUE TITLE
compile error /dct.asm error:instruction expected

### ISSUE THREAD

**Issue by inlcude** [cisco/openh264#2576]

**Comment by inlcude** [comment]
nasm -v 2.07

**Comment by GuangweiWang** [comment]
NASM needed to be installed  version 2.10.06 or above, 
 For Mac OSX 64-bit NASM needed to be below version 2.11.08 as nasm 2.11.08 will introduce error when using RIP-relative addresses in Mac OSX 64-bit

**Comment by inlcude** [comment]
oh,ok
