### ISSUE TITLE
android build error "Compiler not found, bad NDKROOT or ARCH?"

### ISSUE THREAD

**Issue by fengqi-wang** [cisco/openh264#2577]
I'm trying build with:
make OS=android NDKROOT=/opt/android-ndk TARGET=android-21 ARCH=arm NDKLEVEL=21
and got the error:
build/platform-android.mk:52: **\* Compiler not found, bad NDKROOT or ARCH?.  Stop.

am I missing any other environment settings? Thanks!

**Comment by GuangweiWang** [comment]
can you provide more information? e.g. version of NDK

**Comment by GuangweiWang** [comment]
this error caused by NDK tools not according with your TARGET/NDKLEVEL. you can check you NDK tools by this cmd on the path of openh264 project:

NDK_PROJECT_PATH=./codec/build/android/dec make --no-print-dir -f ${YOUR NDK PATH}/build/core/build-local.mk DUMP_TOOLCHAIN_PREFIX APP_ABI=armeabi

this will check if there is suitable compiler for you.

**Comment by fengqi-wang** [comment]
Thanks Guangwei. I tried to set the environment in ~/.bash_profile:
export ANDROID_NDK=/opt/android-tools/android-ndk                                                                                   
export ANDROID_NDK_ROOT=/opt/android-tools/android-ndk                                                                              
export ANDROID_NDK_HOST=linux-x86                                                                                                   
export ANDROID_TARGET_ARCH=armeabi-v7a                                                                                              
export ANDROID_NDK_PLATFORM=android-19                                                                                              
export NDK_TARGET=19 
export ANDROID_NDK_TOOLCHAIN_VERSION=4.8 

but am seeing the following while running your suggested command:
/opt/android-tools/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-

It seems there is a conflict of the NDK_TARGET and TOOLCHAIN_VERSION .

**Comment by GuangweiWang** [comment]
try this:
cd your_android_sdk_path/tools/;
./android update idk --no-ui

**Comment by GuangweiWang** [comment]
try this:
cd your_android_sdk_path/tools/;
./android update sdk --no-ui

**Comment by ruil2** [comment]
@fengqi-wang  Could you try the steps as Guangwei's suggestions? hope to get your feedback. thanks!

**Comment by fengqi-wang** [comment]
@GuangweiWang & @ruil2 , sorry I'm not available on this recently, but thanks for your responses a lot! closing the issue for now.
