### ISSUE TITLE
Emscriptened version of openh264

### ISSUE THREAD

**Issue by koush** [cisco/openh264#2578]
Lots of folks would have a use for having an emscriptened version of these libraries (C code to Javascript)
https://kripken.github.io/emscripten-site/

There's actually a h264 javascript project that is based off the Android h264 implementation:
https://github.com/mbebenita/Broadway

However, Broadway can potentially run into licensing issues with the MPEG-LA.

If I submit a pull request to generate an emscripten'd version of the openh264 implementation (ie, targeting the web platform), would openh264 be willing to publish it?

**Comment by ruil2** [comment]
thanks for you info. Until now we don't have plan to publish javascript version of openh264.
