### ISSUE TITLE
svc to avc

### ISSUE THREAD

**Issue by zzuzhp** [cisco/openh264#2582]
hi, all,
i'm new to h264/svc, and i found that mainstream decoders(e.g. ffmpeg) do not support svc streams, so can svc streams from openh264 be converted to avc without reencodings?
thx!

**Comment by HaiboZhu** [comment]
Hi, from your question, (1) openh264 encoder can output h.264/avc bitstream directly, it is standard compliant, you can decode the bitstream by ffmpeg h.264/avc decoder. (2) If you want to convert the svc bitstream from openh264 (no interlayer reference) to h.264/avc without re-encoding, please use the "DecodeParser" to do it. It will output the h.264/avc bitstream from the lowest layer.

**Comment by zzuzhp** [comment]
i use spatial scability with svc (each layer are of different bitrate and resolution), so
1. if i disable interlayer prediction,  will svc loss too much coding efficiency?
2. no layer dependency if no interlayer prediction, does it mean if i want to decode layer1 , i just need to feed the decoder with nalus only from layer1 and no layer0 nalus are needed ? if so, what is the difference between multi avc streams and a svc stream without interlayer prediction?

**Comment by HaiboZhu** [comment]
Firstly, openh264 only announced support h.264/avc (decoder support constraint high profile), NOT announced support svc extension.
(1) When you encode SVC with reference software such as JSVM, you will lose some coding efficiency when disable the interlayer prediction.
(2) Yes, you are right. When no interlayer prediction, you can decode the layer 1 only with the data from layer 1. A svc bitstream without interlayer prediction can not be decoded with the pure avc decoder such as FFmpeg 264 decoder.

**Comment by zzuzhp** [comment]
thanks for your reply, and i have more doubts that i hope you can help to clarify:
1) if  i disable  interlayer prediction enable 2 spatial layer(CIF & 4CIF), is the openh264's coding complexity equal to that of running 2 avc encoders(CIF & 4CIF) ?
2) if i want to convert  a real svc stream(with interlayer pred) to an avc stream, must i decode the svc frist before re-encodes it to avc? if not, what is the complexity of the transcoding compared to the decode-and-encode way ?

**Comment by HaiboZhu** [comment]
(1) Till now, openh264 can't use the relevant information to help encode other layer, so you are right.
(2) The bitstream extractor tool in JSVM reference software can only extract the specific layer and all dependent layer. If you want to get a specific layer (not the base layer), you need to do the decode-encode operation without transcoding tools. I don't know if there are some open source svc-to-avc transcoding tools you can use directly. About the complexity comparison, you can find the data from the research papers a few years ago.

**Comment by zzuzhp** [comment]
many thanks, Mr zhu!
