### ISSUE TITLE
compiler errors under Visual Studio 2015

### ISSUE THREAD

**Issue by morffiy** [cisco/openh264#2586]
**error : unknown type name 'IUnknown'**
inorder to fix this issue you have to define WIN32_LEAN_AND_MEAN before including windows.h

**Comment by shihuade** [comment]
@morffiy, I double check all build on vs 2015, win32/x64, debug/release, no such kind of issue.
which version of VS2015 you installed?

**Comment by morffiy** [comment]
@shihuade Visual Studio 2015 Update 3 Platform toolset ( Clang with Microsoft CodeGen (v140_clang_c2) )

**Comment by shihuade** [comment]
@morffiy  my VS version is 14.0.24720.00 Update 1.
OK, I will try it with your VS version later

**Comment by ruil2** [comment]
@morffiy  suggest to use makefile to build openh264. you can refer to https://github.com/cisco/openh264#for-windows-builds.  if still have questions, please let us know. thanks!
