### ISSUE TITLE
Rate control misbehaving with SM_FIXEDSLCNUM_SLICE and uiSliceNum > 1

### ISSUE THREAD

**Issue by sprangerik** [cisco/openh264#2591]
I'm getting weird results when I set uiSliceMode = SM_FIXEDSLCNUM_SLICE and uiSliceNum > 1.
With uiSliceNum = 1, things work as expected, but setting a higher number results in the control thinking the input fps is way higher than it is. Example:

> [OpenH264] this = 0x0x7f747c000a80, Warning:Actual input fLatestFrameRate = 490.000000 is quite different from framerate in setting 24.000000, please check setting or timestamp unit (ms), cur_Ts = 3687521622711 start_Ts = 3687521622295
> [OpenH264] this = 0x0x7f747c000a80, Warning:Actual input framerate 490.000000 is different from framerate in setting 24.000000, suggest to use other rate control modes

I verified the input frame rate was indeed 24fps, timestamps looked good.
This was tried with commit 6ba85394e0adfaaa506da900bc93e449e436fb26 and webrtc loopback test. See https://cs.chromium.org/chromium/src/third_party/webrtc/modules/video_coding/codecs/h264/h264_encoder_impl.cc?l=456 for info on how the parameters were set up.

**Comment by ruil2** [comment]
@sprangerik Could you send the info trace to us? thanks!

**Comment by sprangerik** [comment]
Did a short test with ENCODER_OPTION_TRACE_LEVEL = WELS_LOG_DETAIL.
Is this what you wanted?

[h264_rate_control_issue_trace.txt](https://github.com/cisco/openh264/files/581388/h264_rate_control_issue_trace.txt)

**Comment by ruil2** [comment]
thanks @sprangerik.
Could you set bEnableAdaptiveQuant as false to have a try?
I will continue to probe the issue with bEnableAdaptiveQuant = true.

**Comment by sprangerik** [comment]
Hi, with bEnableAdaptiveQuant = false I don't see these issues.
From the sound of it, I guess that's an option we don't want to touch in production code though, right?

**Comment by ruil2** [comment]
Actually this option can be used in production. But from testing, in some cases, there is some issue on this option. so I prefer to turn off this on your side.  Or you can wait for a new commit that will turn off this option in openh264 internal, after tuning well, this option will be turned on.

**Comment by ruil2** [comment]
if you still have question, please submit a new one freely. thanks!
