### ISSUE TITLE
master branch rewritten?

### ISSUE THREAD

**Issue by mstorsjo** [cisco/openh264#2592]
Sometimes between November 2nd and 3rd, it seems like the master branch was rewritten, and a couple of commits were lost. Why did this happen?

Prior to this, the master branch hash was 21ebee2974612385860a36ed431311de4f6cd40a, where the last few commits were "merge pull request #2575" and "merge pull request #2574". After November 3rd, the last commit was 6ba85394e0adfaaa506da900bc93e449e436fb26, which does not contain these two pull requests any longer.

Why did this happen? Was there some problem with these two pull requests that you had to fix by removing them from the history that couldn't be fixed incrementally, or was this a mistake by somebody doing a force push, accidentally?

**Comment by ruil2** [comment]
No issue on these two commits ("merge pull request #2575" and "merge pull request #2574")
because one failed pull request is merged into master, in order to remove this pull request, I reset the commit  prior to the failed pull request.

**Comment by mstorsjo** [comment]
What failed pull request did you (try to) remove? As far as I see, only these two PRs were removed; was there some other PR merged afterwards which was bad? In that case, why remove the older ones as well? In my copy of the history there was no other PRs before these two, that now would be removed.

And in any case; you should not rewrite the master branch just to revert some bad commits - rewriting is for the case where it is so bad that it has to be buried properly. For all other cases you can revert individual commits. By rewriting history, you make it much much harder for everybody tracking the project to understand what actually happened.

**Comment by ruil2** [comment]
https://github.com/cisco/openh264/pull/2573 
yes, I made a mistake on this.

**Comment by ruil2** [comment]
@mstorsjo How to check the commits are changed on your side?

**Comment by mstorsjo** [comment]
I noticed it when I did update the master branch using "git pull", where it suddenly created a merge commit, since I had the old version of the master branch with the commits that you had removed. Before this update, my local version of the master branch was 21ebee2974612385860a36ed431311de4f6cd40a.

**Comment by ruil2** [comment]
thanks for this feedback.
