### ISSUE TITLE
Usage in C#.Project

### ISSUE THREAD

**Issue by mbedded** [cisco/openh264#2596]
Hello Cisco-Team,

thank you for deploying this codec public and enable the usage for custom projects. #2595 asked for any bindings to c#. Currently i am facing a close problem.
I used a DllExport-Viewer to see which methods are public exported when i download *openh264-1.6.0-win32msvc.dll*.
Currently i get methods like:
- WelsCreateDecoder
- WelsCreateSVCEncoder
- WelsDestroyDecoder
- WelsDestroySvcEncoder
- ...

But how do i get started in a .NET WPF-Project which uses C#? Is there any tutorial (or wrapper) planned to make development/using easier? I could write a Wrapper on my own which uses PInvoke to execute the methods..

Currently i am stuck and i don't know how to start a MediaCapture (e.g. Webcam) and encode this stream to H264. I think i have to get the stream on my own (using 3rd party libs or Microsoft classes) but i want to receive the stream/video and encode it with your library to stream it to other devices.
I hope you can help me or reference to some sources where i can find further information.

Thank you very much,
Matthias

**Comment by ruil2** [comment]
you can find the guideline in  microsoft msdn about C# project.
for MediaCapture, please refer to https://code.msdn.microsoft.com/windowsapps/media-capture-sample-adf87622

**Comment by mbedded** [comment]
Hello ruil2,

thank you for that quick response. I will download and investigate the samples.
