### ISSUE TITLE
Failed To Decode skipped frame.

### ISSUE THREAD

**Issue by silverdragon106** [cisco/openh264#2597]
Hi.
I'm using openh264 version 1.6.0 to build simple video software.
But there is some issues.
When i 'm going to decode a skipped frame, then decoding is failed while returning dsDataErrorConcealed.
Just this is problem.
Is it possitble?
What is the solution?
Thanks.

**Comment by ruil2** [comment]
@silverdragon106  could you attach your bitstream? after analyzing the bitstream, we will give some proposal. thanks1

**Comment by huili2** [comment]
Any update about this issue? If no further info, this will be closed.
