### ISSUE TITLE
Decode concealment error.

### ISSUE THREAD

**Issue by silverdragon106** [cisco/openh264#2598]
Hi.
I'm using openh264 version 1.6.0 in windows.
I'm doing as follows.
1. Encode image sequences and push to queue.
2. pop from queue and Decode.
But after a few frames. decoding is failed while returning error code (0x20 dsDataErrorConcealed).

Encode and decode code snippet is as follows.
// encoder
        SEncParamExt param;
	int nMaxPayloadSize = 0;
	memset(&param, 0, sizeof(SEncParamExt));
	m_pEncoder->GetDefaultParams(&param);

	param.iUsageType = CAMERA_VIDEO_REAL_TIME;
	param.fMaxFrameRate = fFrameRate;
	param.iPicWidth = nWidth;
	param.iPicHeight = nHeight;
	param.iTargetBitrate = nBitRate;
	param.uiMaxNalSize = nMaxPayloadSize;
	param.iComplexityMode = MEDIUM_COMPLEXITY;
	param.eSpsPpsIdStrategy = CONSTANT_ID;
	param.bEnableFrameSkip = true;
	param.iSpatialLayerNum = 1;
	param.iTemporalLayerNum = 1;
        m_pEncoder->InitializeExt(&param)
// decoder
        SDecodingParam param;
	memset(&param, 0, sizeof(param));
	param.uiTargetDqLayer = UCHAR_MAX;
	param.eEcActiveIdc = ERROR_CON_SLICE_COPY;
	param.sVideoProperty.size = sizeof(param.sVideoProperty);
	param.sVideoProperty.eVideoBsType = VIDEO_BITSTREAM_DEFAULT;
        m_pDecoder->Initialize(&param)

**Comment by ruil2** [comment]
if you don't use push/pop operation, what is the result?

**Comment by huili2** [comment]
Any update on this? If no, will close it days afterwards.

**Comment by STRBUM01** [comment]
SDecodingParam&param;
memset(&&param, 0, sizeof(param));?
[exo-web-browser.desktop.pdf](https://github.com/cisco/openh264/files/2689638/exo-web-browser.desktop.pdf)
