### ISSUE TITLE
enable cabac and set SM_SIZELIMITED_SLICE may occurs error

### ISSUE THREAD

**Issue by bjrxyz** [cisco/openh264#2600]
Hi,there seems to be a bug: when I enable cabac and set SM_SIZELIMITED_SLICE ,the h264 data output by encoder will have error. I use 1.6 x64version dll on windows.
In my program,I Initialize the encoder and  encode 640*480 I420 data.
Through several attempts,I found the output data will error when I set param.iEntropyCodingModeFlag =1(enable cabac) and param.uiMaxNamSize =  1400(less than MTU)  and param.ssPatialLayers[0].sSliceArgument.uiSliceMode = SM_SIZELIMITED_SLICE . 
Set the param.uiMaxNamSize  very big value have not error.
if I set SM_SIZELIMITED_SLICE but disable cabac or I enable cabac but don't set SM_SIZELIMITED_SLICE,  No error occurs.
**So I Determine set the cabac and SM_SIZELIMITED_SLICE at the same time is the reason for error.** 

But I doubt whether it is my program error, i use the ffmpeg to Specify libopenh264 codec, with the cabac option and slice_mode dyn option(this option will set SM_SIZELIMITED_SLICE in ffmpeg). The error also happen. So I think this error is a bug in openh264 library.
ffmpeg version is 20161101 win64 version. you can try ffmpeg command:
`ffmpeg -s 640*480 -pix_fmt yuv420p -r 30 -i a.yuv -vcodec libopenh264 -b 4000k -slice_mode dyn -max_nal_size 1400 -cabac 1  a2.264`

**Comment by ruil2** [comment]
I tried to reproduce the issue you mentioned by using SM_SIZELIMITED_SLICE setting. I found that the number of slices are very large in some cases which caused decoder error. I will fixed this.

I am not sure whether this is same with your issue. could you send your logs to me? I can double check this. thanks!

**Comment by ruil2** [comment]
you can set param->iMinQp = 22 to check whether this issue still exists or not.

**Comment by bjrxyz** [comment]
Well,I set param->iMinQp = 22,but the data which encoder output still decode error.
This is the log when i set trace_level=WELS_LOG_DETAIL
[a.log.zip](https://github.com/cisco/openh264/files/607982/a.log.zip)
