### ISSUE TITLE
Decoding in VLC

### ISSUE THREAD

**Issue by ealloradai** [cisco/openh264#2601]
Hi all,
i built the codec for macosx and linked to a VLC plugin project (this project https://github.com/ASTIM/OpenH264-VLC-Plugin)

With this and usign VLC parameter --demux=h264 i can correctly play raw h264 file. 
The problem is when decoding h264 stream provided via RTSP to my Axis M1125. For every NAL i obtain error number 16. The following is the SDP provided by the Axis

How can i decode this? What kind of NALS do OpenH264 codec expects?

Thanks

```
v=0
o=- 3253925629317495365 1 IN IP4 172.16.16.129
s=Session streamed with GStreamer
i=rtsp-server
t=0 0
a=tool:GStreamer
a=type:broadcast
a=range:npt=now-
a=control:rtsp://172.16.16.129:554/axis-media/media.amp?videocodec=h264
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:50000
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4d0029;sprop-parameter-sets=Z00AKeKQDwBE/LgLcBAQGkHiRFQ=,aO48gA==
a=control:rtsp://172.16.16.129:554/axis-media/media.amp/stream=0?videocodec=h264
a=framerate:30.000000
a=transform:-1.000000,0.000000,0.000000;0.000000,-1.000000,0.000000;0.000000,0.000000,1.000000
```

**Comment by ealloradai** [comment]
I apologize,
At the end of the day i discovered that is enough to  to open the url with an `&spsppsenabled=yes`.
What i do not understand is that i have a lot of errors during buffering
many `dsDataErrorConcealedz` and 0x22 ...

**Comment by jesup** [comment]
VLC likely doesn't see (or doesn't support) sprop-parameter-sets.  You could emulate it by decoding the parameter sets and inserting them before any data - it comprises a PPS and an SPS.

**Comment by ealloradai** [comment]
Thank you for the answer, i'm new to h264 so i will check those parameters and i will let you know.

**Comment by ruil2** [comment]
it seems that your question has been fixed. closed this issue. if you still questions, please submit the new issue freely. thanks!
