### ISSUE TITLE
undefined-behavior: shift exponent 32 is too large for 32-bit type 'uint32_t'

### ISSUE THREAD

**Issue by tysmith** [cisco/openh264#2602]
STR:
1) build with undefined behavior sanitizer
2) run test_case.264 with h264dec

Results:
codec/decoder/core/inc/dec_golomb.h:81:3: runtime error: shift exponent 32 is too large for 32-bit type 'uint32_t' (aka 'unsigned int')
    #0 0x5f9540 in WelsDec::BsGetBits(WelsCommon::TagBitStringAux*, int, unsigned int*) codec/decoder/core/inc/dec_golomb.h:78:16
    #1 0x5fdb5b in WelsDec::ParseVui(WelsDec::TagWelsDecoderContext*, WelsDec::TagSps*, WelsCommon::TagBitStringAux*) codec/decoder/core/src/au_parser.cpp:1519:5
    #2 0x5eb207 in WelsDec::ParseSps(WelsDec::TagWelsDecoderContext*, WelsCommon::TagBitStringAux*, int*, int*, unsigned char*, int) codec/decoder/core/src/au_parser.cpp:1138:5
    #3 0x5e7749 in WelsDec::ParseNonVclNal(WelsDec::TagWelsDecoderContext*, unsigned char*, int, unsigned char*, int) codec/decoder/core/src/au_parser.cpp:599:12
    #4 0x5219aa in WelsDecodeBs codec/decoder/core/src/decoder.cpp:751:16
    #5 0x502c5a in WelsDec::CWelsDecoder::DecodeFrame2(unsigned char const*, int, unsigned char**, TagBufferInfo*) codec/decoder/plus/src/welsDecoderExt.cpp:520:3
    #6 0x500e0c in WelsDec::CWelsDecoder::DecodeFrameNoDelay(unsigned char const*, int, unsigned char**, TagBufferInfo*) codec/decoder/plus/src/welsDecoderExt.cpp:441:16
    #7 0x4f33ed in H264DecodeInstance(ISVCDecoder*, char const*, char const*, int&, int&, char const*, char const*) codec/console/dec/src/h264dec.cpp:221:5
    #8 0x4f4cd7 in main codec/console/dec/src/h264dec.cpp:362:3
    #9 0x7fca9b40982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #10 0x41bc18 in _start (/home/ubuntu/build/build/h264dec+0x41bc18)

[test_case.zip](https://github.com/cisco/openh264/files/604578/test_case.zip)

**Comment by huili2** [comment]
Thanks for your information. Will check and fix if existing.
