### ISSUE TITLE
Serious bug in version 1.6

### ISSUE THREAD

**Issue by zjudongze** [cisco/openh264#2618]
Version 1.6 encoder has a serious bug.
Using following parameters to encode will produce illformed bitstream; when decoding, it will trigger errors in CheckIntra16x16PredMode.
 
pPtrEnc->GetDefaultParams (&sSvcParam);
 sParam.iUsageType = CAMERA_VIDEO_REAL_TIME;
  sParam.fMaxFrameRate  = 30.0f;                // input frame rate
  sParam.iPicWidth      = 1280;                 // width of picture in samples
  sParam.iPicHeight     = 720;                  // height of picture in samples
  sParam.iTargetBitrate = 200000;              // target bitrate desired
  sParam.iMaxBitrate    = UNSPECIFIED_BIT_RATE;
  sParam.iRCMode        = RC_TIMESTAMP_MODE;      //  rc mode control
  sParam.iTemporalLayerNum = 1;    // layer number at temporal level
  sParam.iSpatialLayerNum  = 1;    // layer number at spatial level
  sParam.bEnableDenoise    = 0;    // denoise control
  sParam.bEnableBackgroundDetection = 1; // background detection control
  sParam.bEnableAdaptiveQuant       = 1; // adaptive quantization control
  sParam.bEnableFrameSkip           = 1; // frame skipping
  sParam.bEnableLongTermReference   = 0; // long term reference control
  sParam.iLtrMarkPeriod = 30;
  sParam.uiIntraPeriod  = 0;           // period of Intra frame
  sParam.eSpsPpsIdStrategy = INCREASING_ID;
  sParam.bPrefixNalAddingCtrl = 0;
  sParam.iComplexityMode = MEDIUM_COMPLEXITY;
  sParam.bSimulcastAVC         = true;
  int iIndexLayer = 0;
  sParam.sSpatialLayers[iIndexLayer].uiProfileIdc       = PRO_BASELINE;
  sParam.sSpatialLayers[iIndexLayer].iVideoWidth        = 1280;
  sParam.sSpatialLayers[iIndexLayer].iVideoHeight       = 720;
  sParam.sSpatialLayers[iIndexLayer].fFrameRate         = 30.0f;
  sParam.sSpatialLayers[iIndexLayer].iSpatialBitrate    = 200000;
  sParam.sSpatialLayers[iIndexLayer].iMaxSpatialBitrate    = UNSPECIFIED_BIT_RATE;
  sParam.sSpatialLayers[iIndexLayer].sSliceArgument.uiSliceMode = SM_FIXEDSLCNUM_SLICE;
  sParam.iMultipleThreadIdc = 2;

There are three key parameters related to this problem.
1.  sParam.bEnableFrameSkip   must be enabled;
2.   sParam.iMultipleThreadIdc = 2  must be multithreaded
3.   sParam.iTargetBitrate = 200000;       sParam.sSpatialLayers[iIndexLayer].iSpatialBitrate    = 200000; bitrate should be small to enough to trigger frame skip.

**Comment by zjudongze** [comment]
I have also verified this problem using VLC to decode bitstream produced by encConsole.exe.

**Comment by ruil2** [comment]
@zjudongze thanks! I will try to reproduce this issue by using these parameters. Is there the same issue in the latest openh264 master code?

**Comment by zjudongze** [comment]
I have not tried it on the master branch. By looking at git history, I don't see any related bug fix.

**Comment by ruil2** [comment]
Could you attached the bitstream you created?thanks!

**Comment by zjudongze** [comment]
Please refer to the attached file. It is generated by encConsole.exe using exactly the same parameter posted here.
I also cherry pick commit cd9982e from master branch to fix avx related building issue.

[Static.h264.zip](https://github.com/cisco/openh264/files/641355/Static.h264.zip)

**Comment by zjudongze** [comment]
Have you verified this problem?

**Comment by ruil2** [comment]
I can't reproduce this issue by using the latest code from openh264 master. Could you have a try on the latest code? thanks a lot!

**Comment by zjudongze** [comment]
Still the same issue on the master branch.
The codec is compiled using vs2008 and nasm  2.11.06
It can be reproduced on android too.

**Comment by ruil2** [comment]
@zjudongze  ok, let me try it again. It is better to attach openh264 output trace info which will show the more detail info for me. thanks!

**Comment by zjudongze** [comment]
This is output of trace level WELS_LOG_INFO. The code is on master branch commit: f421aab.

Z:\git\external\openh264\testbin>..\bin\Win32\Release\encConsole.exe welsenc_arb
itrary_res.cfg
[OpenH264] this = 0x00251058, Info:CWelsH264SVCEncoder::InitEncoder(), openh264
codec version = openh264 default: 1.4
[OpenH264] this = 0x00251058, Info:iUsageType = 0,iPicWidth= 1280;iPicHeight= 72
0;iTargetBitrate= 200000;iMaxBitrate= 200000;iRCMode= 3;iPaddingFlag= 0;iTempora
lLayerNum= 1;iSpatialLayerNum= 1;fFrameRate= 30.000000f;uiIntraPeriod= 0;eSpsPps
IdStrategy = 1;bPrefixNalAddingCtrl = 0;bSimulcastAVC=1;bEnableDenoise= 0;bEnabl
eBackgroundDetection= 1;bEnableSceneChangeDetect = 1;bEnableAdaptiveQuant= 1;bEn
ableFrameSkip= 1;bEnableLongTermReference= 0;iLtrMarkPeriod= 30, bIsLosslessLink
=0;iComplexityMode = 0;iNumRefFrame = 1;iEntropyCodingModeFlag = 0;uiMaxNalSize
= 0;iLTRRefNum = 0;iMultipleThreadIdc = 2;iLoopFilterDisableIdc = 0 (offset(alph
a/beta): 0,0;iMaxQp = 51;iMinQp = 0)
[OpenH264] this = 0x00251058, Info:sSpatialLayers[0]: .iVideoWidth= 1280; .iVide
oHeight= 720; .fFrameRate= 30.000000f; .iSpatialBitrate= 200000; .iMaxSpatialBit
rate= 0; .sSliceArgument.uiSliceMode= 1; .sSliceArgument.iSliceNum= 0; .sSliceAr
gument.uiSliceSizeConstraint= 1500;uiProfileIdc = 66;uiLevelIdc = 0
[OpenH264] this = 0x00251058, Info:WELS CPU features/capacities (0x40017e3f) det
ected:  HTT:      Y, MMX:      Y, MMXEX:    Y, SSE:      Y, SSE2:     Y, SSE3:
   Y, SSSE3:    Y, SSE4.1:   Y, SSE4.2:   Y, AVX:      Y, FMA:      N, X87-FPU:
 Y, 3DNOW:    N, 3DNOWEX:  N, ALTIVEC:  N, CMOV:     Y, MOVBE:    N, AES:      Y
, NUMBER OF LOGIC PROCESSORS ON CHIP: 2, CPU CACHE LINE SIZE (BYTES):        64
[OpenH264] this = 0x00251058, Info:WelsInitEncoderExt() exit, overall memory usa
ge: 23355645 bytes
Width:          1280
Height:         720
Frames:         42
encode time:    0.322773 sec
FPS:            130.122408 fps
[OpenH264] this = 0x00251058, Info:CWelsH264SVCEncoder::~CWelsH264SVCEncoder()
[OpenH264] this = 0x00251058, Info:CWelsH264SVCEncoder::Uninitialize(), openh264
 codec version = openh264 default: 1.4.
[OpenH264] this = 0x00251058, Info:WelsUninitEncoderExt(), pCtx= 002D0048, iMult
ipleThreadIdc= 2.
[OpenH264] this = 0x00251058, Info:FreeMemorySvc(), verify memory usage (0 bytes
) after free..

**Comment by ruil2** [comment]
@zjudongze I still can't reproduce your issue by using your parameters on macOS and windows. 
from your bitstream, adaptive quant is used, but this feature had been disabled in master branch.
I don't know what is the gaps.

I  appreciate your info very much. But until now I can't find the root cause for the issue you met. 
I still suggest you clean your code and get the latest code to try it again.

**Comment by zjudongze** [comment]
I did more testing today. The result is: it only exists on windows inside parallel desktop.
I tested in 7 machines: four of them are mac using parallel desktops and they all failed (use decConsoled.exe, showing decodeCurrentAccessUnit failed 459804), three of them are native windows and they all passed.

tested machines:
1. macbook 2009 + parallel desktop + windows 7
2. macbook 2011 + parallel desktop 12 + windows 8
3. macbook air 2014 + parallel desktop + windows 8
4. macbook air 2014 + parallel desktop + windows 8
5. lenovo E420 + windows 7
6.  lenovo E420 + windows 10
7. dell pc + windows 10

The source code is clean and fresh.  I only edited welsenc.cpp and two cfg files for testing specific params. 

EXE, built on macbook windows or E420 windows, release or debug,  produces the same result. 
Disable x86_ASM produces the same result.
The bug is not present on version 1.5.

I have attached my change in patch.diff. 
Note: capture.yuv is not included. Please prepare a 720p yuv file, rename it as "capture.yuv" and place in folder testbin, and run the command "..\bin\Win32\Debug\encConsole.exe welsenc_arbitrary_res.cfg".
The prepared yuv file should last for at least a few seconds. Less than 10 frames won't trigger this bug as frame skip won't happen before encoding process has already ended. So don't try "Cisco_Absolute_Power_1280x720_30fps.yuv".


[patch.diff.zip](https://github.com/cisco/openh264/files/676915/patch.diff.zip)

**Comment by zjudongze** [comment]
any update on this issue?

The bug also exists on Android. 
1. Using welsEncoderTest, the encoded h264 bitstream in folder (/sdcard/welsenc/test/yuv/) can't be decoded vlc.
2. Using the default config, encoded h264 bitstream can be decoded using decConsoled on windows and the resulted yuv file is ok
3. Using my specified config, h264 bitstream encoded on android can be decoded by decConsoled on windows, but with errors, which are the same errors found on parallel desktop windows. the resulted yuv file is only 2/5 length of the original file; some frames are dropped during encoding, some frames are not decoded correctly.

**Comment by ruil2** [comment]
if this issue can be reproduced on android, I will try it again. thanks for this info again.

**Comment by ruil2** [comment]
@zjudongze this issue had been fixed. please check this again. thanks for your feedback.

**Comment by zjudongze** [comment]
Verified on master branch.

**Comment by zjudongze** [comment]
@ruil2 Any plan for next release date?
