### ISSUE TITLE
Actually I want to know openh264 supported resolution list to encode. Would you please provide me this information?

### ISSUE THREAD

**Issue by RajibTheKing** [cisco/openh264#2622]

**Comment by huili2** [comment]
Openh264 should be consistent to the definitions on resolutions provided by the profile and level in Annex A. You may refer to the H.264/AVC Standard for more information.

**Comment by RajibTheKing** [comment]
I am very glad to get this reply, @huili2 . 

I searched about H.264/AVC standard resolutions.. but haven't found any suitable answers. It's just said **"Arbitrary resolution, not constrained to multiples of 16x16"**.
I have already tested some video files and I know that openh264 is able to encode or decode 
176x144, 320x240, 352,288, 640x480 videos. 

But, my concern is , I don't know whether openh264 is able to encode  videos with resolutions 50x52, 100x10, 15x21 , 521x211, 800x200 etc 

Is there any other constraints about resolution? This answer will be very helpful for me. 
Thanks in advance.

**Comment by huili2** [comment]
@RajibTheKing Ideally it is "arbitrary resolution" as you mentioned. However, there is max resolution constraint in each level, or more specifically, maxFS (max frame size in MB), e.g., Level 3.1 has maxFS 3600 (the size of 720p by accident).
Besides, openh264 encoder does not support encoding frame with frame width/height smaller than 16 (15x200, 14x14 are neither supported).
Btw:Although it is allowed in openh264 encoder to encode frame with odd size, from other viewpoints, I do not suggest you generate a frame with odd size in I420 format like 521x211.

So from your examples, 100x10, 15x21 are not supported while all others are OK.

**Comment by RajibTheKing** [comment]
I just tested video file with resolution 100x10 using H264. It's working fine. @huili2

**Comment by huili2** [comment]
@RajibTheKing are you sure you can encode this resolution using openh264 encoder? I tried just now, and was not able to on master branch.

**Comment by RajibTheKing** [comment]
@huili2 , Sorry I haven't used openh264, but I just used ffmpeg framework to encode or decode this video. FFmpeg contains -libx264 library. Maybe ffmpeg already modified to encode or decode any video files with arbitrary resolution except odd length. 
I mean, 21x22 or 22x21 or 21x21 can't be processed using ffmpeg + libx264.
 
Finally, my observation is, **[any width (even) x any height (even)]** can be processed using ffmpeg + libx264. 

I don't know openh264 is capable or not. If it's not capable we can modify openh264 to do this job. :)

**Comment by huili2** [comment]
@RajibTheKing Yes, that's why i agreed at very first that H.264 standard supports arbitrary resolution. Odd resolution is usually disabled because it is hard to convert odd width/height I420 format to RGB for display with the same result. You may learn more about I420 format then you may be able to get some info.
Openh264 does not support width/height < 16 just because it is not a usual case, and was designed by intention.

**Comment by RajibTheKing** [comment]
@huili2 , Thanks for your help. Resolution related information for openh264 is clear to me.

**Comment by jesup** [comment]
Firefox supports odd resolutions in OpenH264 IIRC - it's needed for various window-sharing cases and encoding a canvas.captureStream()
