### ISSUE TITLE
codec for mozilla can't play videos in YUV 422p color space pixel format

### ISSUE THREAD

**Issue by suxonca** [cisco/openh264#2629]
I got the video from Big Buck Bunny sample:

 http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4 

I tested it (YUV420p) :

ffprobe -i bbb_sunflower_1080p_30fps_normal.mp4

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'bbb_sunflower_1080p_30fps_normal.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    creation_time   : 2013-12-16T17:44:39.000000Z
    title           : Big Buck Bunny, Sunflower version
    artist          : Blender Foundation 2008, Janus Bager Kristensen 2013
    comment         : Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
    genre           : Animation
    composer        : Sacha Goedegebure
  Duration: 00:10:34.53, start: 0.000000, bitrate: 3481 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 2998 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2013-12-16T17:44:39.000000Z
      handler_name    : GPAC ISO Video Handler
    Stream #0:1(und): Audio: mp3 (mp4a / 0x6134706D), 48000 Hz, stereo, s16p, 160 kb/s (default)
    Metadata:
      creation_time   : 2013-12-16T17:44:42.000000Z
      handler_name    : GPAC ISO Audio Handler
    Stream #0:2(und): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 320 kb/s (default)
    Metadata:
      creation_time   : 2013-12-16T17:44:42.000000Z
      handler_name    : GPAC ISO Audio Handler
    Side data:
      audio service type: main

I transformed it in YUV 422p:

ffmpeg -i bbb_sunflower_1080p_30fps_normal.mp4 -c:v libx264 -pix_fmt yuv422p -c:a copy bbb.mp4

I tested it : 

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'bbb.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Big Buck Bunny, Sunflower version
    artist          : Blender Foundation 2008, Janus Bager Kristensen 2013
    composer        : Sacha Goedegebure
    encoder         : Lavf57.48.103
    comment         : Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
    genre           : Animation
  Duration: 00:10:34.60, start: 0.000000, bitrate: 3522 kb/s
    Stream #0:0(und): Video: h264 (High 4:2:2) (avc1 / 0x31637661), yuv422p, 1920x1080 [SAR 1:1 DAR 16:9], 3197 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 320 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Side data:
      audio service type: main

Then I use a simple video tag and the video stuck on it after download a few chunks of data:
<!DOCTYPE html>
<html>
<head>
</head>

<body>
    
	<video id="VIDEO1" width="420" height="400" controls >
	<source src="./bbb.mp4" type="video/mp4" >
	</video>
	
</body>
</html>

I’m using Firefox 50.1.0
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0
OpenH264 Video Codec provided by Cisco Systems, Inc. Version: 1.6

The Video stuck in IE11 too

But not in Chrome browser.

Regards,
Gab

**Comment by ruil2** [comment]
@suxonca  Currently Openh264 Decoder doesn't support High 4:2:2 profile. openh264 decoder supports constrained baseline profile and constrained high profile.

**Comment by suxonca** [comment]
ruil2, this help us too much in our problem about streaming .thank you very much

**Comment by suxonca** [comment]
One question, if I decode and encode from pixel format 422 to 420p, I lose information (quality or definition) or just I make the data more compressible, I saw that the **size changed** in the video, what this mean?
thanks in advance.

**Comment by huili2** [comment]
from 422 to 420, it surely lost quality, as well as the total YUV file size. I420 is considered  as more natual to human visual effect. 422 or even 444 is more suitable for other high-requirement video compression requirements, like satellite video, medical video, etc.

**Comment by suxonca** [comment]
Thank you very much, now I understand it.

**Comment by suxonca** [comment]
Do you think that Cisco OpenH264 Codec will support YUV 422p in a near future?

**Comment by huili2** [comment]
No, there's no plan in our calendar to suppport 422 in recent months.

**Comment by suxonca** [comment]
Thank you again. I really appreciate your help.
