### ISSUE TITLE
build for android

### ISSUE THREAD

**Issue by miss-o-hara** [cisco/openh264#263]
Hi!

Do you have plans to release the codec for android?
Could you please provide approximate date of the release?

Thanks.

**Comment by mihaicodrean** [comment]
Is there any other format beside I420 really supported as input? I'm asking because I see this code:

```
int CWelsH264SVCEncoder::EncodeFrame (const SSourcePicture* kpSrcPic, SFrameBSInfo* pBsInfo) {
...
  if (kpSrcPic->iColorFormat != videoFormatI420)
    return cmInitParaError;
...
```
