### ISSUE TITLE
not able to encode at 1 fps output rate

### ISSUE THREAD

**Issue by Asheshah** [cisco/openh264#2632]
Hi,

I am using Openh264 to encode YUV data which is coming at 1 frame per second. I want to save in h264 file and transmit using RTSP with 1 FPS. But instead i am getting 25 fps with ffprobe and 30 fps with elecard stream analyser.

How can I get output at 1 FPS?

following is the default encoder params i set : 
		memset (&param, 0, sizeof (SEncParamBase));
		param.iUsageType = EUsageType::CAMERA_VIDEO_REAL_TIME;
		param.fMaxFrameRate = (float)1;
		param.iPicWidth = 1280;
		param.iPicHeight = 800;
		param.iTargetBitrate = 512000;
		param.iRCMode = RC_MODES::RC_OFF_MODE;

And the following are the Information logs :
4 - [OpenH264] this = 0x0C1E15A8, Info:CWelsH264SVCEncoder::SetOption():ENCODER_OPTION_TRACE_CALLBACK callback = 74941ED0.
4 - [OpenH264] this = 0x0C1E15A8, Info:CWelsH264SVCEncoder::InitEncoder(), openh264 codec version = 56c6fc9+M
4 - [OpenH264] this = 0x0C1E15A8, Info:iUsageType = 0,iPicWidth= 1280;iPicHeight= 800;iTargetBitrate= 512000;iMaxBitrate= 0;iRCMode= -1;iPaddingFlag= 0;iTemporalLayerNum= 1;iSpatialLayerNum= 1;fFrameRate= 1.000000f;uiIntraPeriod= 0;eSpsPpsIdStrategy = 1;bPrefixNalAddingCtrl = 0;bSimulcastAVC=0;bEnableDenoise= 0;bEnableBackgroundDetection= 1;bEnableSceneChangeDetect = 1;bEnableAdaptiveQuant= 1;bEnableFrameSkip= 1;bEnableLongTermReference= 0;iLtrMarkPeriod= 30;iComplexityMode = 1;iNumRefFrame = 1;iEntropyCodingModeFlag = 0;uiMaxNalSize = 0;iLTRRefNum = 0;iMultipleThreadIdc = 1;iLoopFilterDisableIdc = 0 (offset(alpha/beta): 0,0;iMaxQp = 51;iMinQp = 0)
4 - [OpenH264] this = 0x0C1E15A8, Info:sSpatialLayers[0]: .iVideoWidth= 1280; .iVideoHeight= 800; .fFrameRate= 1.000000f; .iSpatialBitrate= 512000; .iMaxSpatialBitrate= 0; .sSliceArgument.uiSliceMode= 0; .sSliceArgument.iSliceNum= 0; .sSliceArgument.uiSliceSizeConstraint= 1500;uiProfileIdc = 66;uiLevelIdc = 0
4 - [OpenH264] this = 0x0C1E15A8, Info:WELS CPU features/capacities (0x4000763f) detected: 	HTT:      Y, MMX:      Y, MMXEX:    Y, SSE:      Y, SSE2:     Y, SSE3:     Y, SSSE3:    Y, SSE4.1:   Y, SSE4.2:   Y, AVX:      N, FMA:      N, X87-FPU:  Y, 3DNOW:    N, 3DNOWEX:  N, ALTIVEC:  N, CMOV:     Y, MOVBE:    N, AES:      N, NUMBER OF LOGIC PROCESSORS ON CHIP: 8, CPU CACHE LINE SIZE (BYTES):        64
4 - [OpenH264] this = 0x0C1E15A8, Info:WelsInitEncoderExt() exit, overall memory usage: 13539910 bytes
4 - [OpenH264] this = 0x0C1E15A8, Info:CWelsH264SVCEncoder::SetOption():ENCODER_OPTION_DATAFORMAT, m_iCspInternal= 0x17
4 - [OpenH264] this = 0x0C1E15A8, Info:CWelsH264SVCEncoder::SetOption():ENCODER_OPTION_FRAME_RATE,m_pEncContext->pSvcParam->fMaxFrameRate= 1.000000
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 22.000000, fAverageFrameRate=0.000000, LastFrameRate=0.000000, LatestBitRate=0, LastFrameQP=26, uiInputFrameCount=1, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=85703 at Ts = 215493
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 15.000000, fAverageFrameRate=0.020809, LastFrameRate=0.000000, LatestBitRate=0, LastFrameQP=34, uiInputFrameCount=2, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=86013 at Ts = 311603
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 12.666667, fAverageFrameRate=0.017319, LastFrameRate=0.000000, LatestBitRate=1785, LastFrameQP=34, uiInputFrameCount=3, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=86773 at Ts = 388711
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 16.500000, fAverageFrameRate=0.014797, LastFrameRate=0.000000, LatestBitRate=1785, LastFrameQP=30, uiInputFrameCount=4, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=154275 at Ts = 485820
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 16.600000, fAverageFrameRate=0.013534, LastFrameRate=0.000000, LatestBitRate=1785, LastFrameQP=33, uiInputFrameCount=5, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=171529 at Ts = 584930
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 16.333334, fAverageFrameRate=0.012231, LastFrameRate=0.000000, LatestBitRate=2575, LastFrameQP=33, uiInputFrameCount=6, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=188925 at Ts = 706042
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 15.571429, fAverageFrameRate=0.011811, LastFrameRate=0.000000, LatestBitRate=2575, LastFrameQP=34, uiInputFrameCount=7, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=194727 at Ts = 808153
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 15.250001, fAverageFrameRate=0.011432, LastFrameRate=0.000000, LatestBitRate=2575, LastFrameQP=34, uiInputFrameCount=8, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=198339 at Ts = 915263
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 12.785715, fAverageFrameRate=0.019836, LastFrameRate=1.000000, LatestBitRate=49930, LastFrameQP=35, uiInputFrameCount=14, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=219790 at Ts = 921263
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 11.400000, fAverageFrameRate=0.028099, LastFrameRate=1.000000, LatestBitRate=5808, LastFrameQP=35, uiInputFrameCount=20, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=224236 at Ts = 927263
4 - [OpenH264] this = 0x0C1E15A8, Info:EncoderStatistics: SpatialId = 0,1280x800, SpeedInMs: 11.115384, fAverageFrameRate=0.036223, LastFrameRate=1.000000, LatestBitRate=60229, LastFrameQP=35, uiInputFrameCount=26, uiSkippedFrameCount=0, uiResolutionChangeTimes=0, uIDRReqNum=0, uIDRSentNum=1, uLTRSentNum=NA, iTotalEncodedBytes=255927 at Ts = 933263

Thanks in advance.

Regards,
Ashesh

**Comment by ruil2** [comment]
VUI in h264 bitstream contains fps info. But openh264 doesn't write this info in encoder. 
ffprobe and elecard stream eye should have a default FPS.so you got 25fps in ffprobe and 30fps in elecard tool.

**Comment by Asheshah** [comment]
Thank you for your response.
Is there any way/tweak in existing encoder params, so I can set FPS to 1 or 2?

**Comment by ruil2** [comment]
#1: there is no such parameter in openh264 
#2: no plan on this. 
#3: maybe you can have a try. but I don't think it is a good solution.
      you can wrap h264 into mp4/avi or other files. 

hope it can help you. thanks!

**Comment by Asheshah** [comment]
unfortunately, mp4/avi will not be the option for me, as I also need to transmit every h264 frame through RTSP, and writing and reading in mp4/avi will make extra latency.

I implemented 3rd option of changing VUI information outside encoder, and its working. Just VLC is not able to play at lower FPS of 1. 

Thank you.

**Comment by ruil2** [comment]
It is fine that you found the solution for you.  thanks!
