### ISSUE TITLE
How to call PrintHelp function from c progam

### ISSUE THREAD

**Issue by shreekant30** [cisco/openh264#2634]
I have compiled the openh264 source code. After compilation, it generates libopenh264.so.1.6.0. I have installed this in /usr/local/lib. Now I have written simple c program to call 'PrintHelp' function(codec/console/enc/src/welsenc.cpp).
----------------------------------------
#Filename:main.c
#include <stdio.h>
int main(void)
{
   PrintHelp(); 
    return 0;
}
----------------------------------------
I am trying to compile this by 
gcc -Wall -o test main.c -lopenh264(where -lopenh264 is the library I have installed)

but it gives an error:
/tmp/cc1t44ap.o: In function `main':
main.c:(.text+0x14): undefined reference to `PrintHelp'
collect2: error: ld returned 1 exit status

Any idea what I am missing here?

**Comment by ruil2** [comment]
PrintHelp() function is contained in sample code and isn't in libopenh264.so. 
if you need this function, you can add codec/console/enc/src/welsenc.cpp in you project. thanks!

**Comment by shreekant30** [comment]
Thanks for the reply but  didn't get what is difference between sample code and and libopenh264.so? I am completely new to this and followed the steps given in readme. I have not found any keyword 'samplecode' here what I have downloaded. Please help.
