### ISSUE TITLE
Where is the rate-distortion optimization in the source code?

### ISSUE THREAD

**Issue by thompon** [cisco/openh264#2635]
Hello,
Does anybody know where is performed the rate-distortion optimization in the source code?
In which .cpp file?
Thanks in advance!

**Comment by huili2** [comment]
RDO is not used in encoder.

**Comment by thompon** [comment]
Thank you for your reply but that's very strange because RDO is a very important feature.
So how do they decide which prediction mode should be used for each macroblock ?
There must be something which chooses the prediction mode somewhere in the code.

**Comment by huili2** [comment]
@thompon sorry for late reply. When I mentioned RDO I mean it is calculated by SSD plus rate measurement. In Openh264, a very simple SAD/SATD is used as MD criteria.
