### ISSUE TITLE
Calling 'GetDefaultParams' from c file.

### ISSUE THREAD

**Issue by shreekant30** [cisco/openh264#2640]
Hi, I want to call GetDefaultParams from my custom c application. I have included library to my application. But when I compile my app it gives me an 'error: request for member ‘GetDefaultParams’ in something not a structure or union'.

**Comment by huili2** [comment]
You are trying to access a member of a structure, but in something that is not a structure. Could you please provide the example error code here?

**Comment by huili2** [comment]
Any update on this? If no, will close this days afterwards.
