### ISSUE TITLE
member access within null pointer in WelsDec::ParseScalingList()

### ISSUE THREAD

**Issue by tysmith** [cisco/openh264#2642]
Building with Undefined Behavior sanitizer (UBSan) and running the attached test case will cause the following:

./h264dec test_case.264 /dev/null

codec/decoder/core/src/au_parser.cpp:1674:67: runtime error: member access within null pointer of type 'struct TagSps'
    #0 0x5f6c88 in WelsDec::ParseScalingList(WelsDec::TagSps*, WelsCommon::TagBitStringAux*, bool, bool, bool*, unsigned char (*) [16], unsigned char (*) [64]) codec/decoder/core/src/au_parser.cpp:1674:67
    #1 0x5f6c88 in WelsDec::ParsePps(WelsDec::TagWelsDecoderContext*, WelsDec::TagPps*, WelsCommon::TagBitStringAux*, unsigned char*, int) codec/decoder/core/src/au_parser.cpp:1424
    #2 0x5e9ba0 in WelsDec::ParseNonVclNal(WelsDec::TagWelsDecoderContext*, unsigned char*, int, unsigned char*, int) codec/decoder/core/src/au_parser.cpp:621:12
    #3 0x52257a in WelsDecodeBs codec/decoder/core/src/decoder.cpp:749:16
    #4 0x5037aa in WelsDec::CWelsDecoder::DecodeFrame2(unsigned char const*, int, unsigned char**, TagBufferInfo*) codec/decoder/plus/src/welsDecoderExt.cpp:534:3
    #5 0x501969 in WelsDec::CWelsDecoder::DecodeFrameNoDelay(unsigned char const*, int, unsigned char**, TagBufferInfo*) codec/decoder/plus/src/welsDecoderExt.cpp:455:16
    #6 0x4f33ed in H264DecodeInstance(ISVCDecoder*, char const*, char const*, int&, int&, char const*, char const*) codec/console/dec/src/h264dec.cpp:221:5
    #7 0x4f4b2f in main codec/console/dec/src/h264dec.cpp:360:5
    #8 0x7f840e9a382f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x41bc18 in _start (h264dec+0x41bc18)

[test_case.264.zip](https://github.com/cisco/openh264/files/697928/test_case.264.zip)

**Comment by huili2** [comment]
Thanks for your information. Will check soon.
