### ISSUE TITLE
Possible memory error (uninitialized read) on Windows, using Dr. Memory

### ISSUE THREAD

**Issue by chuckleplant** [cisco/openh264#2660]
I believe this is tightly related to #2499, using the encoder in version v1.6.0 I get the following reports from Dr. Memory. 

```
Error #19: UNINITIALIZED READ: reading register ecx
# 0 WelsEnc::WelsMdI16x16                                           [...\openh264-git\codec\encoder\core\src\svc_base_layer_md.cpp:386]
# 1 WelsEnc::WelsMdIntraMb                                          [...\openh264-git\codec\encoder\core\src\svc_base_layer_md.cpp:958]
# 2 WelsEnc::WelsISliceMdEnc                                        [...\openh264-git\codec\encoder\core\src\svc_encode_slice.cpp:552]
# 3 WelsEnc::WelsCodeOneSlice                                       [...\openh264-git\codec\encoder\core\src\svc_encode_slice.cpp:936]
# 4 WelsEnc::WelsEncoderEncodeExt                                   [...\openh264-git\codec\encoder\core\src\encoder_ext.cpp:3736]
# 5 WelsEnc::CWelsH264SVCEncoder::EncodeFrameInternal               [...\openh264-git\codec\encoder\plus\src\welsencoderext.cpp:405]
# 6 WelsEnc::CWelsH264SVCEncoder::EncodeFrame                       [...\openh264-git\codec\encoder\plus\src\welsencoderext.cpp:382]
``` 

Not sure if #2499 should have solved these as well but they're still present.

**Comment by chuckleplant** [comment]
Here's the full report in case it's useful. [openh264-memory-report.txt](https://github.com/cisco/openh264/files/783070/openh264-memory-report.txt)

There are other blocks of code that report this error.

**Comment by huili2** [comment]
@chuckleplant there was a fix in #2499 in Master branch (not in 1.6.0). Could you please try if it solved your issue on Master? Thanks.

**Comment by huili2** [comment]
If no update, will close this days afterwards.

**Comment by chuckleplant** [comment]
Will check during the week

**Comment by chuckleplant** [comment]
I still encounter the error. Here's the full Dr. Memory report: 
[openh264-master-report.txt](https://github.com/cisco/openh264/files/840930/openh264-master-report.txt)

commit a136ba743425080f896ae125263c6b7c3759be6c

**Comment by chuckleplant** [comment]
_Note_ there's a leak at the end, that's my fault, it's just a variable that I did not delete when closing, does not affect the rest of the report.

**Comment by huili2** [comment]
Could you please give more info, how to do the test to get the result? Thanks.

**Comment by ruil2** [comment]
no more info about this issue, close it.  if still questions, please submit a new one.thanks!
