### ISSUE TITLE
doesn't work ENCODER_OPTION_ENABLE_SPS_PPS_ID_ADDITION.

### ISSUE THREAD

**Issue by taktod** [cisco/openh264#2662]
Hi.

To make encoder.

```
    paramExt.uiIntraPeriod  = 320;           // period of Intra frame
    paramExt.eSpsPpsIdStrategy = INCREASING_ID;
    paramExt.bPrefixNalAddingCtrl = 0;
...
    res = encoder_->InitializeExt(&paramExt);
    bool bval = false;
    encoder_->SetOption(ENCODER_OPTION_ENABLE_SPS_PPS_ID_ADDITION, &bval);
```

with openh264 1.5.0.
encoder seems to work with ConstantID

with openh264 1.6.0.
encoder seems to work with IncreasingID

is this bug?

**Comment by ruil2** [comment]
1. in order to understand the interface easily, sps/pps strategy option name is changed ENCODER_OPTION_SPS_PPS_ID_STRATEGY, the value type is int, not bool
2. there is a strategy update issue after initialization, it is fixed in #2675
