### ISSUE TITLE
Exporting motion vectors

### ISSUE THREAD

**Issue by serhannn** [cisco/openh264#2663]
Is there a way to export the motion vectors during decoding process? Or which part of the source should be modified to add such functionality? Thanks.

**Comment by huili2** [comment]
There is currently no direct way to export MVs in decoder. The data are stored in "pCtx->pCurDqLayer->pMv[0][iMbXy][scanIdx]" whatever CABAC/CAVLC is used.

**Comment by huili2** [comment]
If no update, will close this days afterwards.
