### ISSUE TITLE
Encoding parameters for media streaming adaptation

### ISSUE THREAD

**Issue by jorkey** [cisco/openh264#2671]
Hello!

I encode the video in 4 SVC layers with different bitrates. After encoding that layers are distributed to phones.
The layer is selected according to bandwidth of the network channel.
The problem is that when assigning eSpsPpsIdStrategy = CONSTANT_ID, SPS and PPS packets are given by encoder with numbers corresponding to the layer number, i.e. between 0 and 3.
When move from one layer to another is made, the device's decoder is broken, because new Id of parameter set differs from the initial one.
How do I properly encode to SVC layers, so that I can then easily change on the fly the layer sent to device?
Can I make encoder set SPS and PPS Id to 0 always and for all layers?

Thanks, 
Andrew.

**Comment by huili2** [comment]
I'm not sure what's your scenario. You want to make layer switching? In your case, if not starting with IDR picture, the switched data cannot be decoded even if with same SPS/PPS id. So I don't think it is the requirement on the ID. You should only make switch when new SPS/PPS/IDR is coming. In that case, device should be able to decode.
Or do you mean that device can only decode data with sps id = 0?

**Comment by jorkey** [comment]
Thank for reply.

I make switch only when new SPS/PPS/IDR (together and in such sequence) is coming. When decoding these NALs, the emulator of IPhone in Xcode gives an error. I believe, it supports only CONSTANT_ID strategy, because it does not decode at all from one layer if encode with INCREASING_ID (https://bugs.chromium.org/p/webrtc/issues/detail?id=6100). 
Iphone itself switched to new layer correctly, and this problem could be ignored, but I'm not sure that this error will not occur on other devices, androids in particular.
Can I encode layers and switch between them by SPS/PPS/IDR so output stream can be precessed by decoder that supports only CONSTANT_ID strategy?

Andrew.

**Comment by huili2** [comment]
So your switch seems reasonable. From my understanding, you want to freely switch among layers with the same SPS/PPS id for 4 AVC layers.
However, in this case, you have to encode all sps in all layers with the same ID (as you described in the first comment). It is impossible for PPS to tell which SPS is used for which layer, so without transcoding, I cannot help on this situation.
Is my understanding correct?

**Comment by jorkey** [comment]
I want to encode more than 4 AVC layers simultaneously.
These levels will be coded for various bitrates, for example 50, 100, 150, 200, 250, 300, 350 kbps. Because one openh264 encoder supports encoding only to 4 layers, I will use several encoders.
If it is not impossible to make openh264 encoder set parameters ids always to 0, I will try to transcode encoded packets myself.

**Comment by huili2** [comment]
@jorkey till now it is not easy to fulfill your requirement from current implementation, on either layer number or constant parameter set ID. You may have to do yourself.

**Comment by jorkey** [comment]
Ok. Thank you.
