### ISSUE TITLE
The problem with the quality of coding.

### ISSUE THREAD

**Issue by jorkey** [cisco/openh264#2682]
Hello!
I transcoded the video recorded by iPhone 7 to video of the same quality.
Input/output parameters: size 320x576, 400 kbps, 15 fps.
After transcoding, the quality has become much worse. When the plans changed, a strong pixelization appeared, in some places posterization was noticeable.
After raising the outgoing bitrate to 1200 kbps, the quality of the original and encoded video equaled.

![openh264](https://cloud.githubusercontent.com/assets/1289591/23858501/727ee9da-0822-11e7-9aba-df564c21fea2.jpg)

But my task is to transfer video through low-speed channels and this speed is not what I need.
Here are the encoding parameters:

    SEncParamExt params;
    pEncoder->GetDefaultParams (&params);

    params.iUsageType = CAMERA_VIDEO_REAL_TIME; 
    params.iRCMode = RC_QUALITY_MODE; 
    params.iComplexityMode = HIGH_COMPLEXITY;
    params.fMaxFrameRate = 15;
    params.iTemporalLayerNum = 3;
    params.uiIntraPeriod = 0;   // I call ForceIntraFrame when found key frame in the incoming packet. 
    params.eSpsPpsIdStrategy = CONSTANT_ID;
    params.bPrefixNalAddingCtrl = true; 
    params.bSimulcastAVC = true;
    params.iEntropyCodingModeFlag = 0;
    params.bEnableFrameSkip = false; 
    params.iMaxBitrate = UNSPECIFIED_BIT_RATE;
    params.iMultipleThreadIdc = 0;
    params.bEnableDenoise = false;  
    params.bEnableBackgroundDetection = false; 
    params.bEnableAdaptiveQuant = false; 
    params.bEnableFrameCroppingFlag = false; 
    params.bEnableSceneChangeDetect = false;

    params.iTargetBitrate = 0;
    for (int i = 0; i < layerNum; i++) {
        params.sSpatialLayers[i].fFrameRate = 15;
        params.sSpatialLayers[i].iSpatialBitrate = targetBitrate;
        params.sSpatialLayers[i].iMaxSpatialBitrate = targetBitrate;
        params.sSpatialLayers[i].sSliceArgument.uiSliceMode = SM_SINGLE_SLICE;
        params.iTargetBitrate += targetBitrate;
    }

Is it possible to improve the efficiency of coding?

Andrew.

**Comment by huili2** [comment]
@jorkey in video coding, the worse results should be normal in your case to encode the decoded data from first encoder (iphone hw encoder) by using second encoder (openh264)  , unless it is lossless encoding, or maybe completely the same encoder.
There might be better result if you change the value of iTemporalLayerNum to 1, but it won't help too much.
btw: I assume you set the "layerNum" to 1.
btw again: how did you get the iphone encoded data? what profile, what coding tools were used? These would greatly make contribution to the 400kbps encoding result, as openh264 is mainly focusing on very fast real-time encoding only.

**Comment by jorkey** [comment]
I set LayerNum to 4.  What is optimal iTemporalLayerNum for this configuration?

This are iPhone encoding parameters. Other settings by default.

NSDictionary * params = @{(NSString*)kVTCompressionPropertyKey_RealTime: @YES,
                                  (NSString*)kVTCompressionPropertyKey_AllowFrameReordering: @NO,
                                  (NSString*)kVTCompressionPropertyKey_AverageBitRate: (self.minimized ? @(96 * 1024) : @(300 * 1024)),
                                  (NSString*)kVTCompressionPropertyKey_DataRateLimits: @[(self.minimized ? @(96 * 1024 / 8) : @(300 * 1024 / 8)), @1]};

**Comment by huili2** [comment]
set layerNum to 1, and set iTemporalLayerNum to 1, too. Try if it will help.

**Comment by jorkey** [comment]
With layerNum 1, and iTemporalLayerNum 1 output video quality is same as on picture 2.

**Comment by huili2** [comment]
So that's inevitably quality loss in this case as I described above, due to different encoder tools and strategies. It would be hard for openh264 to get distinct improvement on this for now.

**Comment by jorkey** [comment]
Ok. Is it possible to change any settings on iPhone other than bitrate to solve this problem?

**Comment by huili2** [comment]
Honestly, it is very difficult. Iphone uses hardware encoding, which overwhelms software encoding on speed, so it can use very efficient algorithms. Your aim is to greatly improve openh264 encoding quality on given bitrate, it is beyond current capability.
A tricky way is to encode iphone with very low quality (by setting very small bitrate so that openh264 could hardly harm more on that). But it is not recommended.

**Comment by ruil2** [comment]
@jorkey there must be quality downgrade after transcoding, you can try to change below parameters to improve quality when using openh264.
params.iTemporalLayerNum = 1;
params.iEntropyCodingModeFlag = 1.

**Comment by sijchen** [comment]
close for answered and no updates.
