### ISSUE TITLE
[Encoder] How do I split intra frames into smaller packets?

### ISSUE THREAD

**Issue by chuckleplant** [cisco/openh264#2695]
![image](https://cloud.githubusercontent.com/assets/3345499/24096570/7d83fc54-0d62-11e7-86af-5f510a97eb12.png)

In the snapshot in blue is my openH264 encoder (streamed via RTSP). You can see peeks when Intra frames are encoded. 

Notice another encoder (an RTSP camera) evenly transmitting frames. I wish to split my intra frames into several packets or NAL units. How can I achieve this?

**Comment by huili2** [comment]
@chuckleplant  there are several ways to achieve your goal. A direct way is to encode using constrained size NAL instead of one NAL for a whole frame. Another way is to split the NAL into FU-A packet in RTP level for smooth sending.
Hope this can help.

**Comment by chuckleplant** [comment]
Thanks, I'm still trying a few things on that line. 

I'm trying to understand how to set slicing, _please_ correct me if I'm wrong, 

I've tried three methods:

**Single slice**
```
layerCfg->sSliceArgument.uiSliceMode = SliceModeEnum::SM_SINGLE_SLICE;
```

**Size limited slice**, this makes the stream lose quality, as if intra frames were never correctly sent
```
layerCfg->sSliceArgument.uiSliceMode = SliceModeEnum::SM_SIZELIMITED_SLICE;
layerCfg->sSliceArgument.uiSliceSizeConstraint = m_OH264ExtendedParams.uiMaxNalSize; //2000 for instance
```

**Fixed num slices**
```
layerCfg->sSliceArgument.uiSliceMode = SliceModeEnum::SM_FIXEDSLCNUM_SLICE;
layerCfg->sSliceArgument.uiSliceNum = 16; // Set by trial and error
```

I'm not sure which one's best to use or in which case should I choose which. Single slice does not work for me as it increases the chances of losing an IDR. Right?

I'm actually not sure if the bandwidth peaks are caused by the encoder, I'm currently streaming the encoded nal units as soon as I get them, which should keep me at the desired target bitrate. However, when I get an IDR frame I get a much bigger peak, as more data (split or not) is being sent as fast as possible from my app. 

Hope this makes sense

**Comment by huili2** [comment]
@chuckleplant your 3 slice setting ways are all correct. For streaming purpose, both using SM_SIZELIMITED_SLICE and your splitting on upper layer are OK. However, as IDR is really large, the data peak is unavoidable. 
Besides, to split or not has no direct result with IDR losing probability. It should be guaranteed in transport channel. Even you split into several packets, once one packet is lost, the whole IDR is incompletely decode-able.

**Comment by chuckleplant** [comment]
@huili2, I'm using Live555 to stream, the author [mentions](http://lists.live555.com/pipermail/live-devel/2016-November/020391.html) that if the encoder packs each key frame as a sequence of 'slice' NAL units it can help avoid missing reference frames. 

For OH264, is this the third option, SM_FIXEDSLCNUM_SLICE? That's what I'm currently trying but I'm not sure whether it's the right approach.

**Comment by ruil2** [comment]
SM_FIXEDSLCNUM_SLICE and SM_SIZELIMITED_SLICE both can encoded IDR as some slices. 
 
Did you resolve your issue by changing slice mode? thanks!
