### ISSUE TITLE
Supply arm64 binary

### ISSUE THREAD

**Issue by vidaoaaron** [cisco/openh264#2696]
At the moment there is only 32 bit binaries provided in the releases. Given the license of this library, shouldn't there be an arm64 binary (for android)? Is there a known workaround for this?

**Comment by GuangweiWang** [comment]
Actually, openh264 support android arm64 building, just not provided the corresponding package currently.  openh264 will provide arm64 package for android in the future. please follow the future release. 
Thank you for your attention!

**Comment by vidaoaaron** [comment]
Yes, I understand. Just that this library is currently unusable for arm64 without paying MPEG LA license fees if I understand correctly.

**Comment by GuangweiWang** [comment]
yes, you are right.

**Comment by GuangweiWang** [comment]
if there is no update, this issue will be closed.
