### ISSUE TITLE
How to install for Visual studio

### ISSUE THREAD

**Issue by Whrothus** [cisco/openh264#2697]
I dont get it add all 
spend more then 4 hours to get it to work but nothing 

Ok where did i get 
I got MinGW 
and can install packages 
I can open the special commandpromp in visual studio 
There it ends after 4 hours 

"Our Windows builds use MinGW which can be downloaded from http://www.mingw.org/" No tutorial for installing to visual studio is it not big enough (Visual studio)? 
they have a Search option that is not working if searching for "visual studio" you get a 500 back

"To build with gcc, add the MinGW bin directory (e.g. /c/MinGW/bin) to your path and follow the 'For All Platforms' instructions below." To your path ??? What path ? (hell !? :-D) (so this option i am lost) 

"To build with Visual Studio you will need to set up your path to run cl.exe"
Same what path 
"The easiest way is to start MSYS from a developer command line session"
I can open a command line session but cant open the msys 
How do you do it ? 

 "If you need to do it by hand here is an example from a Windows 64bit install of VS2012:"
Is this a 3the option how to do it? 

"export PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin:/c/Program Files (x86)/Microsoft Visual Studio 11.0/Common7/IDE""
export INCLUDE="C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include;C:\Program Files (x86)\Windows Kits\8.0\Include\um;C:\Program Files (x86)\Windows Kits\8.0\Include\shared"
export LIB="C:\Program Files (x86)\Windows Kits\8.0\Lib\Win8\um\x86;C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\lib"
Where do you put this ? commandline in visualstudio ? (my version should be C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin; /c/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE" )

"Then add OS=msvc to the make line of the 'For All Platforms' instructions." ???

Sorry but i don t get it 
And not a lot info on google did i find.
Can you help me

**Comment by GuangweiWang** [comment]
seems you have install Visual Studio successfully. 
I am not sure what your purpose is. If you just want to get a openh264.dll package, I think the easiest way is download it directly from our page: https://github.com/cisco/openh264/releases
If you want to setup a building environment for openh264 and do some testing on windows, I think the easiest way is use our Visual Studio Project directly(the project located on openh264/codec/build/win32).you can use VS Project build and debug directly without installing MinGW.

your question about "PATH":
"PATH" is a environment variable, you can change/add the PATH value by the following steps:
Control Panel -> System and Security -> System -> Advanced system setting -> Enviroment variables 
select the "PATH" and click edit to add values.

is this helpful for you?

**Comment by Whrothus** [comment]
Thanks for the help 
I will try to add it 
Did not get it what it all meant

**Comment by GuangweiWang** [comment]
If that 2 method above can not match your needs and you want to build a openh264.dll by yourself, you can following steps mentioned in "For Windows Builds" and "For All Platforms" in README.

If you build openh264.dll with gcc, then the MingGW and VS should be all installed. 
after installing VS, MinGW and add the corresponding value to "PATH", follow steps in "For Windows Builds" and "For All Platforms", you can build openh264.dll on your local enviroment.

please let me know what your question/problem is after that.

**Comment by Whrothus** [comment]
Thx for the help so far

Ok a short Update 
This is how far i got 

Option 1
Downloading the Dll is not a problem (Yeah :D )
Adding it as a reference is a lot harder 
its a unmanaged dll i think 
So there is a option to add them manually 
[DllImport(@"<Path>\openh264-1.6.0-win64msvc.dll")]
        public static extern <function>;
I am looking for the <function> and the return type
(Looking add dependency walker to get the functions but have no idea if the path is any good)

Option 2
\openh264-master\codec\build\win32\dec\WelsDecoder.sln
When i try do build(Local Windows Debugger) in Visual Studio (2015) 
It tells "This Project is out of date" "WelsDecCore -DebugWin32" "Would you like to build it?"
When i press Yes you get the standard VS report "there where build errors. Would you like to continue and run the last successful build?" 
And the Error is "MSB6006 "cmd.exe" exited with code 9009" 

I will look further in one of the next days

What i want to view a encoder (that is password protected else the vlc plugin might do the trick) in a c# project 
and take a frame and put the old one on top so i can view the change 
Unfortunately i know only c# (If it needs i will start to learn c++  )
(Now got a program that takes a screenshot and of the encoder program and cuts that out
(that has a green corner around that i select)
But then i need to open all my streams and i depends on the screen resolution

**Comment by GuangweiWang** [comment]
is there anything to update?

**Comment by Whrothus** [comment]
Did not got the hang of it so i did stop the project for me 
(Technically i started a c++ course by the end i wanted to make some progress )
Spotted i was missing the necessary config for VS (Standard c# does not have the packages) 
I Started the Compilere from 2 ways and the message " 'export' is not recognized as an internal or external command ..." I did learn a lot (and got the basic of c++ so not a complete wast of time)

**Comment by shishuo365** [comment]
I compile openh264 nearly, and successed, here is the article and release:
https://blog.ibaoger.com/2017/07/08/compile-openh264-for-windows/
https://github.com/shishuo365/OpenH264Release/tree/master/Windows/x86

**Comment by sijchen** [comment]
close this for no update recently.
