### ISSUE TITLE
lossless encoding

### ISSUE THREAD

**Issue by leochan2009** [cisco/openh264#2711]
Hi ,

I tried to encode images (256x256) losslessly with the following settings. 
the sParam.bIsLosslessLink is set to true
But the decoded images are always slight different from the origin one.
  sParam.iUsageType = CAMERA_VIDEO_REAL_TIME;
  sParam.fMaxFrameRate = 60.0f;                // input frame rate
  sParam.iPicWidth = 256;                 // width of picture in samples
  sParam.iPicHeight = 256;                  // height of picture in samples
  sParam.iTargetBitrate = 2500000;              // target bitrate desired
  sParam.iMaxBitrate = UNSPECIFIED_BIT_RATE;
  sParam.iRCMode = RC_OFF_MODE;      //  rc mode control
  sParam.bIsLosslessLink = true;
  sParam.iTemporalLayerNum = 1;    // layer number at temporal level
  sParam.iSpatialLayerNum = 1;    // layer number at spatial level
  sParam.iEntropyCodingModeFlag = 1;
  sParam.bEnableDenoise = 0;    // denoise control
  sParam.bEnableBackgroundDetection = 1; // background detection control
  sParam.bEnableAdaptiveQuant = 1; // adaptive quantization control
  sParam.bEnableFrameSkip = 0; // frame skipping
  sParam.bEnableLongTermReference = 0; // long term reference control
  sParam.iLtrMarkPeriod = 30;
  sParam.uiIntraPeriod = 16;           // period of Intra frame
  sParam.bUseLoadBalancing = false;
  sParam.eSpsPpsIdStrategy = INCREASING_ID;
  sParam.bPrefixNalAddingCtrl = 0;
  sParam.iComplexityMode = HIGH_COMPLEXITY;
  sParam.bSimulcastAVC = false;
  sParam.iMaxQp = 1;
  sParam.iMinQp = 1;
  int iIndexLayer = 0;
  sParam.sSpatialLayers[iIndexLayer].uiProfileIdc = PRO_BASELINE;
  sParam.sSpatialLayers[iIndexLayer].uiLevelIdc = LEVEL_5_2;
  sParam.sSpatialLayers[iIndexLayer].iVideoWidth = 256;
  sParam.sSpatialLayers[iIndexLayer].iVideoHeight = 256;
  sParam.sSpatialLayers[iIndexLayer].iDLayerQp = 1;
  sParam.sSpatialLayers[iIndexLayer].fFrameRate = 30.0f;
  sParam.sSpatialLayers[iIndexLayer].iSpatialBitrate = 1500000;
  sParam.sSpatialLayers[iIndexLayer].iMaxSpatialBitrate = UNSPECIFIED_BIT_RATE;
  sParam.sSpatialLayers[iIndexLayer].sSliceArgument.uiSliceMode = SM_SINGLE_SLICE;
  sParam.sSpatialLayers[iIndexLayer].sSliceArgument.uiSliceNum = 1;

is the settings correct?
Thanks for your kind help.
Best,
Longquan

**Comment by huili2** [comment]
@leochan2009 losslesslink does not mean it is lossless encoding. It is further used indicating application transport layer feature.
Current codec does not support lossless encoding. If you do want, you can use QP=0 to get a near-lossless encoding result.

**Comment by leochan2009** [comment]
Hi, Thanks for you answer.
I will test the QP = 0 option
