### ISSUE TITLE
Where is the rate-distortion optimization in the source code? (continued)

### ISSUE THREAD

**Issue by thompon** [cisco/openh264#2712]
Hello,

I asked this question some time ago: "Where is the rate-distortion optimization in the source code?" https://github.com/cisco/openh264/issues/2635 

but unfortunately it was closed before a full answer was given.

In which file can we find this SAD/SATD computation?

@huili2 : what do you call "MD criteria"?

Thanks in advance.

**Comment by huili2** [comment]
@thompon  sorry as I did not get reply in time, so I closed that one.
MD criteria is what "chooses the prediction mode" by its methodology. RDO is one key method with high computational complexity, thus it is not used for now. In Openh264, simpler SAD/SATD is used as criteria, in many files including ASM files. You can also find some example codes in sample.cpp like WelsSampleSatd16x16_c().
You may need read the code for more information as it is not concluded as one function.

**Comment by thompon** [comment]
ok. thank you very much.
