### ISSUE TITLE
Unable to use constant SPS/PPS id in version 1.6. OpenH264 seems to ignore configs on Windows. 

### ISSUE THREAD

**Issue by v3c70r** [cisco/openh264#2713]
I'm trying to use constant SPS/PPS id for all of the IDRs. However, the SPS/PPS id keeps increasing though I have set `eSpsPpsIdStrategy` to `CONSTANT_ID` (which should be the default value, I assume). 
Could you kindly let me know if there's anything I missed out to keep it constant?

**Comment by v3c70r** [comment]
The issue above is reproduced on Windows. However, on Linux with the same configuration, the SPS/PPS ids are always constant. The OH264 implementations are latest dynamic libraries grabbed from cisco server.

**Comment by huili2** [comment]
Hi @v3c70r how did you run the encoder, by configure file or by command line? Could you please give more information about it? thanks.

**Comment by v3c70r** [comment]
I'm trying to integrate OpenH264 encoder into my application by loading the dll and the headers. Most of code are following the [wiki](https://github.com/cisco/openh264/wiki/UsageExampleForEncoder).

**Comment by ruil2** [comment]
this issue had been fixed in #2675, you can get this commit or get the latest code from master to verify this.

**Comment by v3c70r** [comment]
Hi @ruil2 , 
I have verified the bug has been fixed in the repo. Could you let us know when will you release the newer version since if we use the library compiled by us, we still need to deal with the MPEG-LA issues.

**Comment by ruil2** [comment]
1.7 release is on going. please wait for several days. thanks!
