### ISSUE TITLE
Firefox+HTML5+H.264+MP4+Orange PI+ARM Cortex-A7: Sound problem

### ISSUE THREAD

**Issue by tstalker** [cisco/openh264#2725]
What do I have:
SoC: Orange Pi+ 2 http://www.orangepi.org/orangepiplus2
CPU: H3 Quad-core ARM Cortex-A7 https://en.wikipedia.org/wiki/ARM_Cortex-A7
OS: Armbian Ubuntu Xenial https://www.armbian.com/orange-pi-plus-2
Audio subsystem: PulseAudio

Problem:
Test video HTML5 H.264/MP4: https://www.quirksmode.org/html5/tests/video.html
Firefox: video is played fine, but audio – NOT: white noise only.
Youtube on Firefox: one part of clips is played fine, second part of clips: video is played fine, but audio – NOT: white noise only.
Naturally, second part of Youtube clips have format H.264/MP4.

However:
Chromium: ALL Youtube clips is played fine.
Downloading test video in format H.264/MP4 to local disk.
mpv: test video is played fine.
kodi: test video is played fine.
Therefore, the problem NOT in hardware, NOT in PulseAudio, but EXACTLY in Firefox or its plugins.

I’m trying install plugins and addons from OS and Firefox repositories, but the problem still is not solved.
Please help me.

**Comment by ruil2** [comment]
Openh264 repository only works on video part. it seems that the issue you met isn't covered here. 
Suggest you submit this issue to a proper site. thanks!
