### ISSUE TITLE
Multithread issue for IOS

### ISSUE THREAD

**Issue by guanxu1984** [cisco/openh264#2726]
Hello,
    I encounter a deadlock when running encoder using multithread for IOS. I init the parameter as follows:
    initParams.iMultipleThreadIdc = 0;
    initParams.sSpatialLayers[0].sSliceArgument.uiSliceMode = SM_FIXEDSLCNUM_SLICE;
    initParams.sSpatialLayers[0].sSliceArgument.uiSliceNum = 2;

    The encoder seems working well for MAC and Android, but deadlock for IOS. This deadlock problem comes from the near version master. And the release version 1.6.0 works well. Have I some mistake in using? or, encoder has a bug?

**Comment by ruil2** [comment]
this is a bug in openh264. we are fixing this issue now. will update it soon.  thanks for your feedback.

**Comment by ruil2** [comment]
fixed in #2729,  if still have questions, please let us know. thanks!
