### ISSUE TITLE
UsageType = SCREEN_CONTENT_REAL_TIME bitrate often exceeds target bitrate during scene changes

### ISSUE THREAD

**Issue by imedwei** [cisco/openh264#2732]
When investigating the screen share encoder bitrate usage in webrtc using openh264, I frequently see the bitrate spike much higher than the target bitrate especially after large scene changes.  This is less than ideal with real time screen content because the content will be paced out and add latency to the delivery of the content.

For example:
![webrtc-internals-bitrate-overshoot](https://cloud.githubusercontent.com/assets/1844430/25504406/b57f3e76-2b52-11e7-9546-53d62cf5f92e.png)

In openh264, I see that with the SCREEN_CONTENT_REAL_TIME, the min/max QP configuration are overridden among other things (MIN_SCREEN_QP         = 26,  MAX_SCREEN_QP         = 35).

Given the typical pattern of screen content which has bursty periods of high scene changes followed by static scenes, is there a configuration that allows for the rate to not spike much beyond the target rate during high scene changes (and accept a lower quality for the first frames after a scene change), but progressively improve the quality afterwards?

Thank you!

**Comment by ruil2** [comment]
Thanks for this feedback.
In order to balance quality and bitrate,we set the range of quant for screen content. You are right, this design doesn't match some user's requirement. So we are working on this to give a configurable solution according to user's requirement. 
  Any suggestions are welcome.

**Comment by imedwei** [comment]
I'm not sure how to get my pull request in, but I have a simple change to make it possible to configure the screen content QP values here:
https://github.com/parlaylabs/upstream-openh264/pull/1

**Comment by ruil2** [comment]
@imedwei  https://github.com/cisco/openh264/pull/2746 this PR supports QP setting by user

**Comment by imedwei** [comment]
@ruil2 Thanks for the heads up with that #2746 change.  That change will address my needs to set the QP values for screen content usage.

Since I had a change already, I have rebased on the latest master with some refinements in the usage.  Could you review the latest and see if it might be helpful to upstream?  Thanks!

**Comment by imedwei** [comment]
@ruil2 Could I get your feedback on parlaylabs#1 ?  It's just a minor change that builds off the PR #2746 

Let me know if it is good.  Thanks!

**Comment by ruil2** [comment]
@imedwei  I had reviewed your changes, it is ok for me. closed this issue. If have any questions, please let us know freely. thanks!
