### ISSUE TITLE
Encoding at 30kbps bitrate broken in v1.3-1552-g664127f

### ISSUE THREAD

**Issue by imedwei** [cisco/openh264#2741]
When trying to encode a YUV file with the following [encode configuration](https://github.com/cisco/openh264/files/974970/Configuration.zip) with bitrate set to 30kbps, only 3 frames are encoded successfully when using  v1.3-1552-g664127f.  This works OK in the older version v1.3-1314-g0fd88df.  Higher bitrates from 300kbps upwards also work OK.

New broken version v1.3-1552-g664127f
Width:		1280
Height:		720
Frames:		3
encode time:	0.312591 sec
FPS:		9.597205 fps

Old working version v1.3-1314-g0fd88df
Width:		1280
Height:		720
Frames:		285
encode time:	1.294076 sec
FPS:		220.234360 fps

**Comment by imedwei** [comment]
I'm not sure how the version numbers work in the openh264 repo, but the v1.3 comes from git describe --tags --long master, but I noticed that you do have tags up to v1.6.0.

I'm comparing openh264 versions between the one that shipped in chrome m54 and the openh264 master.

**Comment by ruil2** [comment]
Did you calculate the actual bitrate in these two versions? According to your encoder configuration, Some frames should be skipped when 720P with 30kpbs.  from our testing, v1.3-1552-g664127f version output bitrate match the target bitrate more closely.

**Comment by ruil2** [comment]
The latest code should match the user's target. so close this issue. if still have questions, please submit a new one. thanks!
