### ISSUE TITLE
Cannot use openh264.lib and openh264.dll in pjsip2.6 uwp project for video call

### ISSUE THREAD

**Issue by kumaran87** [cisco/openh264#2742]
I have been build openh264.lib and openh264.dll as per instruction in https://trac.pjsip.org/repos/ticket/1947.
But cannot use it in pjsip2.6 uwp version for video call.

please tell me how to use openh264.lib and openh264.dll in pjsip2.6 uwp version for video call.
Or need any working samples of video call pjsip2.6 uwp version

I am getting following error while linking 
The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by ruil2** [comment]
sorry, we don't know about pjsip2.6 uwp.   suggest check whether some dependency library exist or not.
