### ISSUE TITLE
build for x86 there error.symbol `XGETBV' redefined.

### ISSUE THREAD

**Issue by zfavourite99** [cisco/openh264#2743]
make OS=android NDKROOT=/Users/zbf/Library/Android/sdk/ndk-bundle TARGET=android-14 ARCH=x86
nasm -DX86_32 -f elf -I./codec/common/x86/   -o codec/common/x86/cpuid.o codec/common/x86/cpuid.asm
codec/common/x86/cpuid.asm:196: error: symbol `XGETBV' redefined
make: *** [codec/common/x86/cpuid.o] Error 1

**Comment by zfavourite99** [comment]
see #2202. nasm too old.

**Comment by GuangweiWang** [comment]
yes, NASM version is too old.
