### ISSUE TITLE
openh264 to take set of frames as input

### ISSUE THREAD

**Issue by khurram-amin** [cisco/openh264#2748]
Hello ervyone,
Can anyone guide me if its possible to modify this library to take set of frames (lets say 10 frames) as input, compress them, to generate output frames, as a set of P and I frames, whereas the interval to generate 'I' frames is configurable?
Similarly the decoder module should be able to take as set of compressed frames as input and output uncompressed-frames, whearas the parameters are configurable through a config file.

**Comment by ruil2** [comment]
1. please refer to  https://github.com/cisco/openh264/blob/master/codec/console/enc/src/welsenc.cpp 
2. IDR interval setting parameter:  uiIntraPeriod

**Comment by sijchen** [comment]
close this for answered and no other updates
