### ISSUE TITLE
iComplexityMode setting not working for medium Complexity

### ISSUE THREAD

**Issue by leochan2009** [cisco/openh264#2753]
Hi,
I am evaluating the speed of the codec, and set the iComplexityMode to be LOW_COMPLEXITY,  MEDIUM_COMPLEXITY  and HIGH_COMPLEXITY  respectively in TagEncParamExt.
The compression ratio and speed for MEDIUM_COMPLEXITY and HIGH_COMPLEXITY are exactly the same. It seems like either one of them is not implemented.

Best Regards,
Longquan

**Comment by ruil2** [comment]
Currently openh264 doesn't provide this support on iComplexityMode. will add this in the future.
