### ISSUE TITLE
Decoding Raw Bytes

### ISSUE THREAD

**Issue by Omid3d** [cisco/openh264#2757]
Hello

In a part of my application I take an Intra-Frame as input (from my camera library) and want to extract corresponding RGB image as output.
The problem is not the input, I already have Intra-Frame as raw bytes, but my problem is generating RGB image from the raw bytes. Which function from your library should I use to decode these raw bytes and generate RGB image?

Thanks

**Comment by ruil2** [comment]
The below info is the features in decoder.   Input is h264 bitstream which is align with h264 specification Annex B, output is YUV 4:2:0 planar.  


Decoder Features

Constrained Baseline Profile up to Level 5.2 (Max frame size is 36864 macro-blocks)
Arbitrary resolution, not constrained to multiples of 16x16
Single thread for all slices
Long Term Reference (LTR) frames
Memory Management Control Operation (MMCO)
Reference picture list modification
Multiple reference frames when specified in Sequence Parameter Set (SPS)
Annex B byte stream input
YUV 4:2:0 planar output
