### ISSUE TITLE
Is it possible to build openh264 lib for UWP (Universal Windows Platform)

### ISSUE THREAD

**Issue by newmytestgit** [cisco/openh264#2761]

**Comment by ycqian** [comment]
I am sorry to tell you that we are not support UWP currently.

**Comment by RubyMoonProductionCo** [comment]
looks to me like someone did because im being microwaved every night after being a subject of a 702 Fisa surveiellence and exposed to radiation

**Comment by RubyMoonProductionCo** [comment]
this code source is physically killing  
me because someone put together licenses and libraries to build a monster that the government and scientist are using to study me as if im an animal
