### ISSUE TITLE
openh264 release for Android & iOS & Windows

### ISSUE THREAD

**Issue by shishuo365** [cisco/openh264#2776]
I compiled openh264 nearly, release is here:
https://github.com/shishuo365/OpenH264Release

Articles:
[Compile OpenH264 for Windows](https://blog.ibaoger.com/2017/07/08/compile-openh264-for-windows/)
[Compile OpenH264 for Android](https://blog.ibaoger.com/2017/07/10/compile-openh264-for-android/)
[Compile OpenH264 for iOS](https://blog.ibaoger.com/2017/07/11/compile-openh264-for-ios/)

**Comment by ruil2** [comment]
you can refer to https://github.com/cisco/openh264/blob/master/RELEASES for openh264 binary. thanks!
