### ISSUE TITLE
Encode SetOption() fails to control bitrate in encoding many spatial layers.

### ISSUE THREAD

**Issue by PeterXu** [cisco/openh264#2778]
In release openh264v1.6,
When set the option of ENCODER_OPTION_BITRATE and ENCODER_OPTION_MAX_BITRATE for each spatial layer or one layer, the output bitrate will not under control and may become very large.

**Comment by huili2** [comment]
@PeterXu did you enable frameskip, and what were the other settings or initializations?

**Comment by PeterXu** [comment]
part settings:

bEnableSSEI=false;
bEnableFrameSkip=true;
bEnableDenoise=false;
bUseLoadBalancing=false;
iLoopFilterDisableIdc=0;
iLoopFilterAlphaC0Offset=0;
iLoopFilterBetaOffset=0

**Comment by huili2** [comment]
@PeterXu could you please try master? I tried and found 1.6 had the issue, but master has fixed it.
btw: ENCODER_OPTION_BITRATE and ENCODER_OPTION_MAX_BITRATE is different from Initialize(), e.g., for actual bitrate, 800000 for 800k, rather than 800.

**Comment by sijchen** [comment]
close this for answered and no updates.
