### ISSUE TITLE
Unable to build on CentOS 7

### ISSUE THREAD

**Issue by xudonax** [cisco/openh264#2780]
There seem to be some difficulties in building the `master` branch on a current install of CentOS 7. For some reason GCC is being called with ARM arguments while I'm on an Intel platform.

Steps to reproduce:
1. Have a clean installation of CentOS
2. Make sure everything is up-to-date (`yum update`)
3. Clone the repository (`git clone https://github.com/cisco/openh264.git`)
4. Run `make ARCH=x86_64`

Expected result:
A binary compiled for the specified architecture

Actual result:
An error complaining about incorrect command line arguments, like so:
```$ make ARCH=x86_64
g++ -mcpu=native -march=native -mtune=native -mfpu=neon-vfpv4 -mfloat-abi=hard -Ofast -O3 -DNDEBUG -m64 -DX86_ASM -DHAVE_AVX2 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -mcpu=native -march=native -mtune=native -mfpu=neon-vfpv4 -mfloat-abi=hard -Ofast -DHAVE_AVX2 -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common/src/common_tables.o codec/common/src/common_tables.cpp
g++: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
g++: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
g++: error: unrecognized command line option ‘-mfpu=neon-vfpv4’
g++: error: unrecognized command line option ‘-mfloat-abi=hard’
g++: error: unrecognized command line option ‘-mfpu=neon-vfpv4’
g++: error: unrecognized command line option ‘-mfloat-abi=hard’
make: *** [codec/common/src/common_tables.o] Error 1
```

Just to be sure, my current commit in the repository after a `git pull` is:
```$ git log -1
commit b26bcda090f40f834fdeeb68bafdd5772dcbd726
Merge: f91bd8b 2b4be05
Author: guangwei <GuangweiWang@users.noreply.github.com>
Date:   Mon Jul 17 18:16:03 2017 +0800

    Merge pull request #2779 from huili2/enhance_encconsole
    
    modify enc sps/pps id strategy in configure file
```

Any advice on what I'm doing wrong?

**Comment by GuangweiWang** [comment]
I build openh264 on CentOS 6.7, the building is successful.
the error you mentioned may be caused by the error value of "OS", can you try this:
make OS=linux ARCH=x86_64?

**Comment by xudonax** [comment]
I tried, but apparently the settings were overwritten in my .bashrc. That survived multiple reboots because I copied it from a different machine. A machine that *was* running an ARM architecture :( Sorry!
