### ISSUE TITLE
Android NDK "stack corruption detected" on ISVCEncoder->GetDefaultParams

### ISSUE THREAD

**Issue by shenyaocn** [cisco/openh264#2808]
When I use latest version for H.264 encode (including x86, x86_64 and armv7a ), It crash and say "stack corruption detected". So I trace and found the problem on ISVCEncoder->GetDefaultParams

**Comment by GuangweiWang** [comment]
hi, @shenyaocn 
could you please describe your issue more in details? e.g. ISVCEncoder->GetDefaultParams which params setting will cause this issue? or what are your parameters setting? thanks.

**Comment by shenyaocn** [comment]
JNIEXPORT jlong JNICALL Java_com_shenyaocn_android_OpenH264_Encoder_createEncoder
  (JNIEnv *env, jobject obj, jint width, jint height) {
	H264Encoder* encoder = new H264Encoder();
    memset(encoder, 0, sizeof(H264Encoder));
    
    if(WelsCreateSVCEncoder(&(encoder->pSvcEncoder)) != 0) {
        delete encoder;
        return 0;
    }
    
	SEncParamExt param;
	memset(&param, 0, sizeof(SEncParamExt));

	encoder->pSvcEncoder->GetDefaultParams(&param);

	param.iRCMode = RC_TIMESTAMP_MODE;
	param.fMaxFrameRate = 20.0;
	param.iUsageType = CAMERA_VIDEO_REAL_TIME;
	param.iPicWidth = width;
	param.iPicHeight = height;
	param.iTargetBitrate = width * height * 2;

	param.iTemporalLayerNum = 1;
	param.iSpatialLayerNum = 1;
	param.bEnableDenoise = 0;
	param.bEnableBackgroundDetection = 1;
	param.bEnableAdaptiveQuant = 1;
	param.bEnableFrameSkip = 1;
	param.bEnableLongTermReference = 0;
	param.iLtrMarkPeriod = 30;
	param.uiIntraPeriod = 3;
	param.eSpsPpsIdStrategy = CONSTANT_ID;

	param.bPrefixNalAddingCtrl = 0;
	param.iLoopFilterDisableIdc = 0;
	param.iEntropyCodingModeFlag = 0;
	param.iMultipleThreadIdc = 0;
	param.iEntropyCodingModeFlag = 1;

	param.sSpatialLayers[0].iVideoWidth = param.iPicWidth;
	param.sSpatialLayers[0].iVideoHeight = param.iPicHeight;
	param.sSpatialLayers[0].fFrameRate = param.fMaxFrameRate;
	param.sSpatialLayers[0].iSpatialBitrate = param.iTargetBitrate;
	param.sSpatialLayers[0].iMaxSpatialBitrate = param.iMaxBitrate;

    if (encoder->pSvcEncoder->InitializeExt(&param) != 0) {
        WelsDestroySVCEncoder(encoder->pSvcEncoder);
        delete encoder;
        return 0;
    }
    
    int videoFormat = videoFormatI420;
	int idr_interval = 32;
	int32_t profile = PRO_BASELINE;
	int32_t level = LEVEL_5_2;

	encoder->pSvcEncoder->SetOption(ENCODER_OPTION_DATAFORMAT, &videoFormat);
	encoder->pSvcEncoder->SetOption(ENCODER_OPTION_IDR_INTERVAL, &idr_interval);
	encoder->pSvcEncoder->SetOption(ENCODER_OPTION_PROFILE, &profile);
	encoder->pSvcEncoder->SetOption(ENCODER_OPTION_LEVEL, &level);

	encoder->h264Buffer = new uint8[H264_BUFFER_COUNT];
    encoder->lastFrameIsKey = false;
    return (jlong)(intptr_t)encoder;
  }

That's the  parameters setting.

Now I use snapshot 'c1f66ea21ba869a4dcf901ad6edfbbaa8cca2618' as source and '6b95de56666d5f48535ff8eb6b22ff1dccbdb98f' 's x86-common.mk to fix Android 6.0 x86 error and everything is OK.

The snapshot 'c1f66ea21ba869a4dcf901ad6edfbbaa8cca2618' is last version can be work fine without 
"stack corruption detected".

**Comment by GuangweiWang** [comment]
great. I'm glad the latest code can solve your problem. your issue can not be reproduced on my side, may need more test.

**Comment by shenyaocn** [comment]
Thanks, I will test it.

**Comment by huili2** [comment]
Close this since no response.
