### ISSUE TITLE
compiled dylib file into xcode 8

### ISSUE THREAD

**Issue by WASIM654321** [cisco/openh264#2839]
i am successfully build the *.a file and *.dylib file. but when i  import into my xcode project it shows me the error the error as follows  
error: 
dyld: Library not loaded: ios_local/lib/libopenh264.4.dylib
  Referenced from: /var/containers/Bundle/~
  Reason: image not found

**Comment by GuangweiWang** [comment]
base you description, I think the libopenh264.4.dylib is built for Mac OS, not for iOS.
can you provide your command line for make/build? thanks.

**Comment by WASIM654321** [comment]
yes i am following this guideline **[(https://trac.pjsip.org/repos/ticket/1947)]** to generate *.a and *.dylib. and one think from the old version of xcode its supports the *.dylib but in the new version it only support the *.tbd file instead of the *.dylib.

**Comment by huili2** [comment]
close this one as it is too long, and not followed again.
