### ISSUE TITLE
Can not decode 264 bit stream generated by omap

### ISSUE THREAD

**Issue by tonybaigang** [cisco/openh264#2840]
Hi, 
I had tried to use the openh264 decoder to decode bit stream generated by TI omap encoder, but it output the yuv data with mosaic.
The first Intra frame is wrong. But ffmpeg and other analyze tool works well. 
[bitstream.zip](https://github.com/cisco/openh264/files/1263433/bitstream.zip)

 
Attach is the bit stream.  

stream file.

**Comment by huili2** [comment]
Thanks for the info. We'll fix the issue ASAP.

**Comment by huili2** [comment]
@tonybaigang it has been fixed by https://github.com/cisco/openh264/pull/2841, which has been merged into master.
could you please check it?

**Comment by tonybaigang** [comment]
Great! It fixed. 
Thanks
