### ISSUE TITLE
Where can I find encoding documentation/examples?

### ISSUE THREAD

**Issue by rtclawson** [cisco/openh264#2844]
I am using ffmpeg to convert animated gifs to mp4, and would like to use openh264. Unfortunately, I can't seem to find any information on what configuration flags are available to me to pass into ffmpeg. For example, when I use libvpx-vp9, I am using the -crf, -b:v, -qmax, and -qmin flags. Help! Thanks.

**Comment by ruil2** [comment]
in order to use openh264 in ffmpeg. you need to do the below steps.
1.build ffmpeg by using "--enable-libopenh264" 
2.use openh264 by adding "-vcodec libopenh264" in command line.

**Comment by rtclawson** [comment]
Thank you for responding. I understand how to tell ffmpeg to use openh264; that is not the problem. The question I have is, what options do I have for setting the quality, compression, bitrate, etc of the output file? Where are those options documented? Thank you!

**Comment by ruil2** [comment]
you can refer to ffmpeg usage document to configure codec which is same with other codec.
