### ISSUE TITLE
FEC with h264 

### ISSUE THREAD

**Issue by peererror** [cisco/openh264#2846]
Hi I am sending video over rtp using openh264 due to udp packet lost nature I am having artifacts is there a way to add fec into the frame from video codecs settings to recover lost parts of the picture ? 

Regards
Zahid Nisar

**Comment by huili2** [comment]
Thanks @peererror  for your interest on this. Currently there's no way to add FEC in video codec. A dummy way is duplicate the NAL packet to decrease the loss rate.

**Comment by gkorovkin** [comment]
@huili2 probably question for another issue but I'll try: despite FEC RTP mechanism there is a another way to do some workaround on picture decoding partial failure - when decoder detects that the some slice/picture data is corrupted and the current frame cannot be properly rebuild then its calling application with some sort of notification or appropriate return code. Application itself might utilitilze RTCP mechanism with PLI/SLI requests that notify other side encoder about this problem. In the next round encoder will try to re-send corresponding data to application so decoder will try to rebuild current frame or continue to work on P frames with no heavy IDR requests. Well yes, it's purely described plain(no SVC) mechanism used in VP8 encoder but is it worth a try to implement it in openh264?

**Comment by sijchen** [comment]
@gkorovkin it looks like that long-term reference frames in H.264 standard can help in the case you mentioned.
