### ISSUE TITLE
Question - Return raw data instead of writing to file

### ISSUE THREAD

**Issue by edwardsanttana** [cisco/openh264#2870]
In my android app I'm sendind the raw bytes of a h264 stream from a camera to a c++ function (via jni) 
 and decoding it using `DecodeFrame2`.

In the android example of this project it **reads a file and outputs the result to another file**. Instead of output to a **.yuv file** I need to return the yuv bytes back to java via JNI. Is it possible?

After calling `pDecoder->DecodeFrame2 (h264Buf, h264BufLen, pData, &sDstBufInfo);` what should i do with the pData to get the bytes?

Thanks!

**Comment by huili2** [comment]
The "pData" stores the YUV wise pixel data with width/height/stride information in sDstBufInfo. You can surely get the bytes through them. A good example can be seen in codec/console/dec/src/h264dec.cpp on the function "Process". It by defaults (given file) stores the buffer into file.
