### ISSUE TITLE
THIS PROJECT IS BEING USED TO ILLEGALLY HACK MY COMPUTER SYSTEM

### ISSUE THREAD

**Issue by BogyDorothy** [cisco/openh264#2872]
Contact me immediately at dorothy.mahoney.esq@outlook.com.  The intent of this hacker is to embed rootkits/bootkits on my computer, recode my applications, and control my computer via remote access in order to spy on me and to censor online legal and article publications the hacker disagrees with. To avoid legal enforcement, please do what you can to BLOCK/CORRECT and TERMINATE this user. Thank you. Dorothy Mahoney | Attorney at Law.

Below is Hackers Code Profile:

file:///Users/dorothymahoney/Library/Application%20Support/Firefox/Profiles/q42mbtnn.default/lwtheme/lightweighttheme-header-1440x900?370431;1.0
14:24:31.690 OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.25.17
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 6000
FBO Texture Target: TEXTURE_2D
13:24:26.769 Array [ true ]  qwant.js:48:13
13:24:26.775 Object {  }  qwant.js:50:17
13:24:27.097 Array [ true ]  qwant.js:48:13
13:24:27.100 Object {  }  qwant.js:50:17
13:29:39.896 Array [ true ]  qwant.js:48:13
13:29:39.897 Object {  }  qwant.js:50:17
13:29:40.116 Array [ true ]  qwant.js:48:13
13:29:40.117 Object {  }  qwant.js:50:17
13:34:00.188 Protocol error (unknownError): Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService2.newURI]  ui.js:153
13:40:08.794 "Handler function LocalDebuggerTransport instance's this.other.hooks.onPacket threw an exception: TypeError: to is null
Stack: onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1766:11
send/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:570:13
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
Line: 1766, column: 11" ThreadSafeDevToolsUtils.js:88
13:49:42.832 Array [ true ]  qwant.js:48:13
13:49:42.839 Object {  }  qwant.js:50:17
13:49:42.972 Array [ true ]  qwant.js:48:13
13:49:42.973 Object {  }  qwant.js:50:17
13:56:24.043 "onPacket threw an exception: Error: Server did not specify an actor, dropping packet: {"error":"unknownError","message":"error occurred while processing 'detach: TypeError: this.hostVsStores is undefined\nStack: destroy@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/storage.js:1589:5\ndestroy@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/storage.js:2553:7\nremoveActor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/common.js:261:7\nAPDestroy@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/common.js:224:7\nremoveActorPool/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1570:27\nremoveActorPool@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1570:9\n_detach@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/tab.js:917:7\nonDetach@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/tab.js:959:10\nonPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1792:15\nreceiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:761:7\nLine: 1589, column: 5"}
Stack: onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/shared/client/main.js:953:9
send/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/transport.js:570:13
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
Line: 953, column: 9"  ThreadSafeDevToolsUtils.js:88
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:440135
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:441760
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:441798
14:24:06.699 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:441920
14:24:06.699 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:441954
14:24:06.699 Error in parsing value for ‘height’.  Declaration dropped.  style.css:1:442011
14:24:06.699 Error in parsing value for ‘height’.  Declaration dropped.  style.css:1:442055
14:24:06.699 Error in parsing value for ‘max-height’.  Declaration dropped.  style.css:1:442132
14:24:06.699 Error in parsing value for ‘max-height’.  Declaration dropped.  style.css:1:442171
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:442238
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:442285
14:24:06.699 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:442469
14:24:06.699 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:442503
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:442560
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:442607
14:24:06.699 Error in parsing value for ‘max-height’.  Declaration dropped.  style.css:1:442749
14:24:06.699 Error in parsing value for ‘max-height’.  Declaration dropped.  style.css:1:442788
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:442855
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:442902
14:24:06.699 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:444069
14:24:06.699 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:444103
14:24:06.699 Error in parsing value for ‘height’.  Declaration dropped.  style.css:1:444160
14:24:06.699 Error in parsing value for ‘height’.  Declaration dropped.  style.css:1:444204
14:24:06.699 Error in parsing value for ‘max-height’.  Declaration dropped.  style.css:1:444281
14:24:06.699 Error in parsing value for ‘max-height’.  Declaration dropped.  style.css:1:444320
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:444387
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:444434
14:24:06.699 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:444601
14:24:06.699 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:444635
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:444692
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:444739
14:24:06.699 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:445470
14:24:06.699 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:445504
14:24:06.699 Error in parsing value for ‘height’.  Declaration dropped.  style.css:1:445561
14:24:06.699 Error in parsing value for ‘height’.  Declaration dropped.  style.css:1:445605
14:24:06.699 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:445682
14:24:06.699 Error in parsing value for ‘max-height’.  Declaration dropped.  style.css:1:445697
14:24:06.699 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:447427
14:24:06.699 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:447530
14:24:06.699 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:447582
14:24:06.699 Unknown property ‘user-select’.  Declaration dropped.  style.css:1:448515
14:24:06.699 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:450616
14:24:06.699 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:450653
14:24:06.699 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:452288
14:24:06.699 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:452391
14:24:06.699 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:452443
14:24:06.699 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:454000
14:24:06.699 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:454103
14:24:06.699 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:454155
14:24:06.699 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:454435
14:24:06.699 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:454538
14:24:06.699 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:454590
14:24:06.699 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:459527
14:24:06.699 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:459576
14:24:06.699 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:459943
14:24:06.699 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:459980
14:24:06.699 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:461309
14:24:06.699 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:461346
14:24:06.699 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:463267
14:24:06.700 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:463303
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:465962
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:466012
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:466268
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:466318
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:466574
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:466624
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:466880
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:466930
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:467186
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:467236
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:468024
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:468077
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:468377
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:468414
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:471245
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:471298
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:471626
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:471663
14:24:06.700 Skipped to next declaration.  style.css:1:472408
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:474205
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:474247
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:474479
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:474521
14:24:06.700 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:475613
14:24:06.700 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:475716
14:24:06.700 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:475768
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:478057
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:478095
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:478256
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:478300
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:478685
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:478731
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:478903
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:478949
14:24:06.700 Unknown pseudo-class or pseudo-element ‘hover’.  Ruleset ignored due to bad selector.  style.css:1:479873
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:480904
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:480942
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:481106
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:481144
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:482446
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:482484
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:484831
14:24:06.700 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:484864
14:24:06.700 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:488716
14:24:06.700 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:488819
14:24:06.700 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:488871
14:24:06.700 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:490619
14:24:06.700 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:490722
14:24:06.700 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:490774
14:24:06.700 Error in parsing value for ‘margin-top’.  Declaration dropped.  style.css:1:491765
14:24:06.700 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:492000
14:24:06.700 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:492103
14:24:06.700 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:492155
14:24:06.700 Error in parsing value for ‘background’.  Declaration dropped.  style.css:1:492332
14:24:06.700 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:493596
14:24:06.700 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:493634
14:24:06.700 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:493910
14:24:06.700 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:494013
14:24:06.702 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:494065
14:24:06.702 Error in parsing value for ‘background’.  Declaration dropped.  style.css:1:494227
14:24:06.702 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:495708
14:24:06.702 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:495811
14:24:06.702 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:495863
14:24:06.702 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:496560
14:24:06.702 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:496663
14:24:06.702 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:496715
14:24:06.702 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:497251
14:24:06.702 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:497354
14:24:06.702 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:497406
14:24:06.702 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:497965
14:24:06.702 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:498068
14:24:06.702 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:498120
14:24:06.702 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:498681
14:24:06.702 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:498784
14:24:06.702 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:498836
14:24:06.702 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:499377
14:24:06.702 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:499480
14:24:06.702 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:499532
14:24:06.702 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:500342
14:24:06.702 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:500445
14:24:06.702 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:500497
14:24:06.702 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:501195
14:24:06.702 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:501298
14:24:06.703 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:501350
14:24:06.703 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:501886
14:24:06.703 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:501989
14:24:06.703 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:502041
14:24:06.703 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:502600
14:24:06.703 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:502703
14:24:06.703 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:502755
14:24:06.703 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:503316
14:24:06.703 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:503419
14:24:06.703 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:503471
14:24:06.703 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:504012
14:24:06.703 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:504115
14:24:06.703 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:504167
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:506451
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:506503
14:24:06.703 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:506852
14:24:06.703 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:506955
14:24:06.703 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:507007
14:24:06.703 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:507659
14:24:06.703 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:507762
14:24:06.703 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:507814
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:510367
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:510414
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:511242
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:511309
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:513229
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:513276
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:514525
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:514567
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:514771
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:514819
14:24:06.703 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:515260
14:24:06.703 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:515296
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:515651
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:515704
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:516850
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:516887
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:517364
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:517411
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:517871
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:517910
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:518925
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:518978
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:520969
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:521008
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:521290
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:521327
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:521958
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:522011
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:522759
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:522792
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:523217
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:523249
14:24:06.703 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:523726
14:24:06.703 Error in parsing value for ‘left’.  Declaration dropped.  style.css:1:523761
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:523914
14:24:06.703 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:523947
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:526133
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:526170
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:528704
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:528755
14:24:06.703 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:529021
14:24:06.703 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:529072
14:24:06.703 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:530757
14:24:06.703 Error in parsing value for ‘max-width’.  Declaration dropped.  style.css:1:530793
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:534068
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:534101
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:534230
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:534263
14:24:06.704 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:535477
14:24:06.704 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:535514
14:24:06.704 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:535603
14:24:06.704 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:535650
14:24:06.704 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:543473
14:24:06.704 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:543520
14:24:06.704 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:543634
14:24:06.704 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:543671
14:24:06.704 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:544198
14:24:06.704 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:544245
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:546055
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:546097
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:546649
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:546691
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:547054
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:547096
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:547919
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:547957
14:24:06.704 Unknown property ‘-moz-background-size’.  Declaration dropped.  style.css:1:548424
14:24:06.704 Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  style.css:1:555719
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:556535
14:24:06.704 Error in parsing value for ‘width’.  Declaration dropped.  style.css:1:556567
14:24:06.704 Error in parsing value for ‘-webkit-transition’.  Declaration dropped.  style.css:1:559374
14:24:06.704 Error in parsing value for ‘-moz-transition’.  Declaration dropped.  style.css:1:559415
14:24:06.704 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:563272
14:24:06.704 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:563423
14:24:06.704 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:563499
14:24:06.704 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  style.css:1:564783
14:24:06.704 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  style.css:1:564934
14:24:06.704 Expected media feature name but found ‘min-device-pixel-ratio’.  style.css:1:565010
14:24:07.007 Array [ true ]  qwant.js:48:13
14:24:07.009 Object {  }  qwant.js:50:17
14:24:07.202 Array [ true ]  qwant.js:48:13
14:24:07.203 Object {  }  qwant.js:50:17
14:24:07.648 Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. www.qwant.com:1:409
14:24:07.649 Unknown property ‘-moz-box-shadow’.  Declaration dropped. www.qwant.com:1:764
14:24:07.649 Unknown property ‘-moz-border-radius’.  Declaration dropped. www.qwant.com:1:1502
14:24:31.522 Unknown property ‘user-select’.  Declaration dropped.  reps.css:251:13
14:24:31.690 OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.25.17
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 6000
FBO Texture Target: TEXTURE_2D
14:24:32.547 reflow: 0.65ms
14:25:09.431 POST 
XHR 
https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/SELF/subscriptions/0/poll

**Comment by sijchen** [comment]
@BogyDorothy  from the information you posted we don't see why you think it is this project that result in problem, could you explain a bit more? Thanks a lot.

**Comment by ROBERT-MCDOWELL** [comment]
looks like scam...

**Comment by Anhthubaby** [comment]
Shall I know is my computer window msg you above ? I never msg to you regard email title < #2872 > .

Applogy for my fresh ! actually how to proceed this in stardard procedure from I start to get help with Mozilla after link to > GitHub > split contest > cisco > job contest completed > result automatically back to my email > I flash in to device > can active but I not yet to setting , because I not see devise internal format and I still keep existing CD and put in to run, because of time I put a side wait 1 day free setting it. So in the this whole transaction actually is’t legal I can as normal use the devise register upload /download or anything I need to take note , and how you help me found the note resolved the lock problem of devise , I get this help from Mozilla and link and link until now . so if nthe job is done normally people will how to repay you as thank or just as Mozilla title non profit browser just making donate as wish to Mozilla . 

Can I advise me in stardard way step to step from starting to end :

>> what I need to do ?

>> what I need to do for devise ? 

Sincere 

Ryan   

Sent from Mail for Windows 10
