### ISSUE TITLE
Setting TagEncParamExt.iMaxBitrate causes initialization error on some systems

### ISSUE THREAD

**Issue by davitadze** [cisco/openh264#2876]
This error concerns 1.7.0 (64-bit linux) binary version released in this repository. When setting TagEncParamExt.iMaxBitrate somehow TagEncParamExt.iLoopFilterDisableIdc parameter gets its value and ends up in initialization error on some systems, but not others.  Error message:

`[OpenH264] this = 0x0x7f09a80152e0, Error:ParamValidation, Invalid iLoopFilterDisableIdc(3200000) or iLoopFilterAlphaC0Offset(6) or iLoopFilterBetaOffset(6)!
[OpenH264] this = 0x0x7f09a80152e0, Error:WelsInitEncoderExt(), ParamValidationExt failed return 2.
[OpenH264] this = 0x0x7f09a80152e0, Error:CWelsH264SVCEncoder::Initialize(), WelsInitEncoderExt failed.`

This happens on a machine with:

`Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz`
`$ uname -a`
`Linux intelhd 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
`lspci`
`00:02.0 VGA compatible controller: Intel Corporation Sky Lake Integrated Graphics (rev 06) (prog-if 00 [VGA controller])`

and with:

`Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz`
`$ uname -a`
`Linux ubuntu 3.19.0-80-generic #88~14.04.1-Ubuntu SMP Fri Jan 13 14:54:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
`lspci`
`00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)`

How to reproduce:
Just set parameter TagEncParamExt.iMaxBitrate to any integer value.

NOTE:
It is not an issue in 1.6.0 binary version.

**Comment by sijchen** [comment]
@davitadze we haven't been able to reproduce the problem, could you kindly share what command line are you using. Thank you.

**Comment by davitadze** [comment]
Sorry, I guess it's the version 1.6.0 that has problems. Could you test on any platform with these settings:
  param.iRCMode = RC_BITRATE_MODE;
  param.iPicWidth = width;
  param.iPicHeight = height;
  param.iTargetBitrate = bitrate
  param.iMaxBitrate = bitrate
  param.iSpatialLayerNum = 1;

**Comment by davitadze** [comment]
Anyway, the problem isn't persistent in newer versions (1.7.0 and above). It's there in 1.6.0. Closing!
