### ISSUE TITLE
Openh264 crash when dynamic change the temporal layer number among 1, 2, 3.

### ISSUE THREAD

**Issue by tonybaigang** [cisco/openh264#2885]
Hi, Experts
In the latest version, openh264 will crash if we try to dynamic change the temporal layer among 1, 2, 3 layers. 
It is always occurred. 
Reproduce methods:
1. Set the config file to encode 720p 15fps 1024kbps 2 temporal layers. 
2. Change the test code to dynamic change the temporal layers.:
    if (iFrameIdx == 50)
    {
        sSvcParam.iTemporalLayerNum  = 3;
        sSvcParam.iTargetBitrate = 1536000;
        sSvcParam.sSpatialLayers[0].iSpatialBitrate 
            = sSvcParam.iTargetBitrate;
        sSvcParam.fMaxFrameRate = 30;

        pPtrEnc->SetOption(ENCODER_OPTION_SVC_ENCODE_PARAM_EXT,
            &sSvcParam);
        
        printf("Set layer to 3\n");
    }
    if (iFrameIdx == 70)
    {
        sSvcParam.iTemporalLayerNum  = 1;
        sSvcParam.iTargetBitrate = 512000;
        sSvcParam.sSpatialLayers[0].iSpatialBitrate 
            = sSvcParam.iTargetBitrate;
        sSvcParam.fMaxFrameRate = 7.5;

        pPtrEnc->SetOption(ENCODER_OPTION_SVC_ENCODE_PARAM_EXT,
            &sSvcParam);

        printf("Set layer to 1\n");
    }
    
    if (iFrameIdx == 140)
    {
        sSvcParam.iTemporalLayerNum  = 2;
        sSvcParam.iTargetBitrate = 1024000;
        sSvcParam.sSpatialLayers[0].iSpatialBitrate 
            = sSvcParam.iTargetBitrate;
        sSvcParam.fMaxFrameRate = 15;

        pPtrEnc->SetOption(ENCODER_OPTION_SVC_ENCODE_PARAM_EXT,
            &sSvcParam);
        
        printf("Set layer to 2\n");
    }
3. Encode the 141th frame, it will crash. 

If we just change the temporal layer between 1 and 2, it works well. 

Bai

**Comment by tonybaigang** [comment]
BTW, there is another little issue, when change the layer config. The warning log is not right, it seems some variable is not correctly setting when the setting is changed. 

 Warning:Actual input fLatestFrameRate = -107.000000 is quite different from framerate in setting 7.500000, please check setting or timestamp unit (ms), cur_Ts = 0 start_Ts = 660

**Comment by huili2** [comment]
@tonybaigang it is an encoder bug from your description. One workaround, or a more natural usage is to prevent changing the variable "sSvcParam.fMaxFrameRate". I'm not sure why this parameter is so frequently changed (it is not designed to change as in your case). 
You may try it first.

**Comment by tonybaigang** [comment]
@huili2 If we integrate the video codec to an Internet application, we have to meet the bad network environment. Under this environment, we have to dynamic to change the bitrate of video encoder, and change the frame rate of encoder. 
I have another workaround to reset encoder when change the frame rate, but I think it is not perfect. Find the root cause, and fix it may be better.

**Comment by ruil2** [comment]
@tonybaigang  Could you help to  check whether master branch fix this issue? thanks!

**Comment by tonybaigang** [comment]
@ruil2 Unfortunately, this issue is not fixed with the latest build.
It still crashed, at the 142 frame in my test. The difference is it was crashed at the 141 frame in old version. 
I see you committed some test code, it seems the fix had passed your test. I don't know why it not works for my test. 
Another clue is I add a log as:
   if ((pNewParam->iMaxNumRefFrame > pOldParam->iMaxNumRefFrame) ||
       ((pOldParam->iMaxNumRefFrame == 1) && (pOldParam->iTemporalLayerNum == 1) && (pNewParam->iTemporalLayerNum == 2))) {
     bNeedReset = true;
+    printf("reset encoder\n");
   }
I just saw the log   when I first change the layer. And did not see the log in the second and the third change the layer. 
The test code is posted in the above.
