### ISSUE TITLE
The correct way to abstract a layer data from svc encode output

### ISSUE THREAD

**Issue by steven8274** [cisco/openh264#2900]
As #2068  said, the correct way to abstract a layer stream data from svc bitstream is to abstract the layers whose spatial ID is equal to the target layer.Howerver, when I set 'bSimulcastAVC' of 'SEncParamExt' to 0, if I abstract layers in this way whether the output frame is 'key frame' or not, the abstracted bitstream can not be decoded.But if I abstract non-key frames as #2068 said and abstract all 'key frames' completely from the svc bitstream, the abstracted bitstream can be decoded.  
**I use openh264 1.7.0 and I'm abstracting data for spatial layer 1(the encoder has two temporal layer and two spatial layer).**
Are the comments in #2068 only for non-key frames?We should **treat key frames in another way**?

**Comment by huili2** [comment]
For layer 1, whatever for simulcast or not,  subset sps and pps are required, whose spatial id is also 0. So I think after these data are extracted, it can be decoded.

**Comment by steven8274** [comment]
What the nal type of subset sps and pps is?Is it 14 for subse sps and 15 for subset pps? But evenif I extact all nals in layer 0 (those whose spatial id is 0) except idr nal(nal type 5) in the key frames , it still can not be decoded.It looks like that the idr nal is common for layer 0 and layer 1.Also If extract all nals in layer 0 except for sps and pps nals(nal type 7 or 8) in the key frames, it also can not be decoded.It looks like that the subset sps and pps for layer 1 is dependent on sps and pps in layer 0.

**Comment by steven8274** [comment]
What the nal type of subset sps and pps is?Is it 14 for subse sps and 15 for subset pps? But evenif I extact all nals in layer 0 (those whose spatial id is 0) except idr nal(nal type 5) in the key frames , it still can not be decoded.It looks like that the idr nal is common for layer 0 and layer 1. Besides, if extract all nals in layer 0 except for sps and pps nals(nal type 7 or 8) in the key frames, it also can not be decoded.It looks like that the subset sps and pps for layer 1 is dependent on sps and pps in layer 0.

**Comment by huili2** [comment]
15 for subset sps, and there's no so-called "subset pps". Neither of them depends on base layer sps/pps.
 Key frame from layer 0 is not required for all layer 1 decoding. Key frame in non-base layer has its own nal unit type, so you needn't remain type 5 (IDR) VCL data for layer 1.

**Comment by steven8274** [comment]
Thanks,huili2!
I do a test right now,but the extracted stream is still can't be decoded.
In the first output encoded data, I got 5 nal unit with spatial id 0, their types are:7,15,8,8,14,5.I extracted the 2nd,3rd,4th nal units to combined with layer 1 uints.Is there any wrong operations?

**Comment by steven8274** [comment]
Thanks,huili2!
I do a test right now,but the extracted stream is still can't be decoded.
In the first output encoded data, I got 6 nal unit with spatial id 0, their types are:7,15,8,8,14,5.I extracted the 2nd,3rd,4th nal units to combined with layer 1 uints.Is there any wrong operation?

**Comment by huili2** [comment]
It should be right. I'll test the case first.

**Comment by steven8274** [comment]
Thanks!Looking forward to your result!

**Comment by steven8274** [comment]
BTW, my encoder configured like this:

SEncParamExt param;
ISVCEncoder* pPtrEnc;
WelsCreateSVCEncoder(&pPtrEnc);
pPtrEnc->GetDefaultParams (&param);

param.iUsageType = CAMERA_VIDEO_REAL_TIME;
param.fMaxFrameRate = _fps;
param.iPicWidth = _width;
param.iPicHeight = _height;
param.iTargetBitrate = _bitrate * 1000;
param.iMaxBitrate = _bitrate * 1000;
param.iRCMode = RC_QUALITY_MODE;
param.iTemporalLayerNum = 2;
param.iSpatialLayerNum = 2;
param.bEnableDenoise = 0; 
param.bEnableBackgroundDetection = 0;
param.bEnableFrameSkip           = 0;
param.bEnableLongTermReference   = 0;
param.iEntropyCodingModeFlag	 = 0; 
param.uiIntraPeriod              = (unsigned int)(_fps >= 1 ? _fps : 1);
param.eSpsPpsIdStrategy          = CONSTANT_ID;
param.iMultipleThreadIdc		= 0;
param.bSimulcastAVC = 0;

int iIndexLayer = 0;
param.sSpatialLayers[iIndexLayer].uiProfileIdc       = PRO_BASELINE;
param.sSpatialLayers[iIndexLayer].iVideoWidth        = _width / 2;
param.sSpatialLayers[iIndexLayer].iVideoHeight       = _height / 2;
param.sSpatialLayers[iIndexLayer].fFrameRate         = param.fMaxFrameRate / 2;
param.sSpatialLayers[iIndexLayer].iSpatialBitrate    = param.iTargetBitrate / 16;
param.sSpatialLayers[iIndexLayer].iMaxSpatialBitrate    = param.iTargetBitrate / 16;
param.sSpatialLayers[iIndexLayer].sSliceArgument.uiSliceMode = SM_SINGLE_SLICE;
        
++ iIndexLayer;
param.sSpatialLayers[iIndexLayer].uiProfileIdc       = PRO_SCALABLE_BASELINE;
param.sSpatialLayers[iIndexLayer].iVideoWidth        = _width;
param.sSpatialLayers[iIndexLayer].iVideoHeight       = _height;
param.sSpatialLayers[iIndexLayer].fFrameRate         = param.fMaxFrameRate;
param.sSpatialLayers[iIndexLayer].iSpatialBitrate    = param.iMaxBitrate * 15 / 16;
param.sSpatialLayers[iIndexLayer].iMaxSpatialBitrate    = param.iMaxBitrate * 15 / 16;
param.sSpatialLayers[iIndexLayer].sSliceArgument.uiSliceMode = SM_SINGLE_SLICE;

pPtrEnc->InitializeExt(&_sSvcParam);

**Comment by huili2** [comment]
After check and test, sps should be remained too for layer 1 decoding. In your example, remain the 1~4 packets should work. Could you please check if it is OK? Thanks.

**Comment by steven8274** [comment]
I checked, your final description is right!The nal uinits should extract from layer 0 is 'sps sub-sps pps'!

**Comment by huili2** [comment]
Good! Thanks again for your opinions and ideas!

**Comment by steven8274** [comment]
Thank you again for your sincerely reply and test!It's very helpful!

**Comment by codecman** [comment]
> After check and test, sps should be remained too for layer 1 decoding. In your example, remain the 1~4 packets should work. Could you please check if it is OK? Thanks.

If you are right, what is the order of the layer #0 sps, sub sps, pps and layer #1 sps, pps, and other NALs ?
