### ISSUE TITLE
Question: encoder options for interleaving image sequence

### ISSUE THREAD

**Issue by vinzf** [cisco/openh264#2907]
I'm not sure if it is openh264 encoder's fault or if I have to blame myself for a complete lack of understanding of H.264 and the concept of reference frames.

For a certain type of experiment I have two list of images.
- A0 -> A1 -> A2 -> A3 -> A4 -> An
- B0 -> B1 -> B2 -> B3 -> B4 ->Bn

The visual difference to the next image in each list is extremely small.

If encoding only the A frames everything is fine.
The size of the encoded data between A[x] -> A[x+1] is minimal as expected.
Same for B of course.

However, I have to encode the frames in the following required way:
A[0] -> B[0] -> A[1] -> B[1] -> A[2] -> B[2] -> .... -> A[n] -> B[n]

Now the visual difference between the encoded frame is big of course.
But also the encoded size of the "A interleaved with B movie" is ten times the size of the sum of "A movie" plus "B movie".

I was expecting that openh264 would recognize that e.g. B[2] is very similar to B[1] and use B[1] as a reference frame when encoding [B2].

Even if H.264 is was not designed for that kind of input, are there any encoding options that can be set to optimize the encoded size for this special input sequence?

**Comment by GuangweiWang** [comment]
thanks for your detailed information. 
we will check this and update later.

**Comment by sijchen** [comment]
the reason:
to minimize the encoded bit stream in the mentioned input param, the encoder need to be able to support selecting reference frames from more than one available reference frames.
H.264 standard has that syntax support, however, the current openh264 encoder does not support multiple reference frame select yet, especially when there is temporal layer in setting.

we will take this as a feature request on multi-reference in encoder.

**Comment by vinzf** [comment]
@sijchen any news regarding this feature ?
