### ISSUE TITLE
Is “Spatial simulcast” and “Dynamic changes of resolution" the same thing

### ISSUE THREAD

**Issue by LiuxjYolanda** [cisco/openh264#2913]
I wonder wether openh264 support Dynamic changes of resolution by  using Spatial scalability. And if so, the MAX_SPATIAL_LAYER_NUM is 4, then the max number of resolution is 4 ,am I right? Thank you so much.

**Comment by ruil2** [comment]
Could you explain "Dynamic changes of resolution" you mentioned more clearly? 

And if so, the MAX_SPATIAL_LAYER_NUM is 4, then the max number of resolution is 4. => Yes

**Comment by LiuxjYolanda** [comment]
Thank you for your answer. 
I mean there are two  features of openh264. One is "Spatial simulcast up to 4 resolutions from a single input". The other one is "Dynamic changes to resolution". Are they the same?

**Comment by sijchen** [comment]
@LiuxjYolanda the answer is no. 

- Spatial simulcast up to 4 resolutions from a single input" : means that you can give the encoder a simulcasting parameters, and the encoder will try to output simulcasting bit streams, that means bitstreams that encoding the same video content but different in resolution. Say you can give a 720 video raw source to the encoder, and set the encoder to be simulcasting up to 4 spatial layers, then the encoder will output encoded packets that can be decoded into 90p, 180p, 360p, 720p **respectively**. 

- "Dynamic changes to resolution": means that when you use the openh264 lib in your application, you can change the resolution to be encoded, in the middle of encoding, by correctly calling the encoder's parameter setting interface (API).

**Comment by LiuxjYolanda** [comment]
Can you show me a coding efficiency comparison of spatial scalable coding and h264?

**Comment by echoxk** [comment]
@ruil2 does openh264 have an example of cfg file supporting spatial scalable coding

**Comment by huili2** [comment]
@echoxk it sure have several cfg files in testbin/ folder.
