### ISSUE TITLE
P frame dependency question

### ISSUE THREAD

**Issue by newmytestgit** [cisco/openh264#2916]
Is there any way or any setting of openh264 to make P frames depended only on previous I frame not previous P frames. that means a missing P frame will not have any affect on rest of the P frames if previous I frame is available.

**Comment by ruil2** [comment]
no setting in openh264 to meet this requirement. You can change code by yourself that makes P frame as non-ref frame, but it will decrease the compression efficiency.

**Comment by newmytestgit** [comment]
Many thanks for your reply. Will setting TemporalLayerNumber>1 do my job ? If not, Is there any way to do this ? If even modification of source code is necessary I will try to do this. Is there any easy way ? If not, which classes and files should I study to do this job ? Thanks in advance :)

**Comment by newmytestgit** [comment]
Hi @ruil2 , how are you ? Can you please help me ? How can I make P frame as non-ref frame, Is there any way to do this ? If even modification of source code is necessary I will try to do this. Is there any easy way ? If not, which classes and files should I study to do this job ? Thanks in advance :)
