### ISSUE TITLE
How to make P frames non-ref frames

### ISSUE THREAD

**Issue by newmytestgit** [cisco/openh264#2917]
I want to make the P frames non-ref frames by modifying the source code of openh264. How can I do this, is there any easy way ? If not, which classes and files should I study to do this job. Can I have some guidelines.

**Comment by sijchen** [comment]
openh264 supports hierachical P when setting TemporalLayerNumber>1. The highest Temporal Layer is encoded to be non-ref P frames in such a case.

**Comment by sijchen** [comment]
there is no setting for individual frame to be set to non-ref though.

**Comment by newmytestgit** [comment]
Many thanks for your reply. I want to make all of the P frames depended only on previous I frame not previous P frames. Will setting TemporalLayerNumber>1 do my job ? If not, Is there any way to do this ? If even modification of source code is necessary I will try to do this. Is there any easy way ? If not, which classes and files should I study to do this job ? Thanks in advance :)

**Comment by bo01ean** [comment]
I think what you are looking for is`IntraPeriod 2` Which will put an Iframe then P:
IPIPIPIPIPIP

**Comment by newmytestgit** [comment]
no I am not looking for IPIPIPIP......
I am looking for IPPPPPPPPPPIPPPPPPPPP........
but the p frames will be dependent only on previous I frame to be decoded correctly. now if any P frame is missing the the later P frames creates distorted video frames.

**Comment by bo01ean** [comment]
Hmmm. I don't think h.264 solves for missing P-frames. If you are missing a P frame it will be garbled until the recovery in the next I frame in the stream. `IntraPeriod` defines the interval of I frames, and thusly, the period for which the stream will correct.
So `IntraPeriod` 2 is IPIPIP, 3 is IPPIPPIPP and so on.
IPPPPPPPPPP is `IntraPeriod` of 11 ...

**Comment by newmytestgit** [comment]
thank you very much for your reply :) . If I just make IntraPeriod larger will it do the job. I mean there is a macro in the source having this name. If I modify the value of the macro to 15 will it work or some other changes are necessary in the source code in some other files. Thanks in advance.

**Comment by bo01ean** [comment]
look at the examples in testbin: https://github.com/cisco/openh264/blob/master/testbin/welsenc.cfg

You can pass config files to the encode:
https://github.com/cisco/openh264/blob/master/testbin/CmdLineExample.sh

**Comment by newmytestgit** [comment]
Hi @bo01ean thanks for your reply but this is not I want. 

My requirement is 

"Is there any way or any setting of openh264 to make P frames depended only on previous I frame not previous P frames. that means a missing P frame will not have any affect on rest of the P frames if previous I frame is available."

@ruil2 replied on this requirement 

"no setting in openh264 to meet this requirement. You can change code by yourself that makes P frame as non-ref frame, but it will decrease the compression efficiency."

can you ( @bo01ean ) or @ruil2 help me on this ? Thanks in advance :)

**Comment by ruil2** [comment]
@newmytestgit  no plan to support his requirement, this is not a normal requirement, right?

**Comment by newmytestgit** [comment]
Please I need this support. How to make openh264 supported for this feature. Please I need a guideline. Which source file I will need to study to modify the source to provide this support. Will you please give me a guideline ?

**Comment by newmytestgit** [comment]
Many Many thanks in advance :)

**Comment by huili2** [comment]
This is not a normal requirement, and is closed then.
