### ISSUE TITLE
How to use open H264 decoder functions

### ISSUE THREAD

**Issue by anoop4** [cisco/openh264#2918]
Hi, 

I am new to Cisco's open H264 library. Can someone point me to a doc that is a good resource to get started working with the H264 library? My objective is to decode the H264 frames I obtain from an IP camera.

Thanks in advance!

**Comment by sijchen** [comment]
after building the openh264 executable files, the decoder can be launched to take your bitstream as input and output the yuv like this:
```
./h264dec {your_bitstream} {your_target_decoded_yuv}
```
