### ISSUE TITLE
How to use the h264enc.exe and h264dec.exe

### ISSUE THREAD

**Issue by anoop4** [cisco/openh264#2919]
I have been trying the following command to encode an image:

`>> h264enc.exe sourceImage.jpg encodedImage.h264`
 
and end up getting the following error:

Unable to open source sequence file (), check corresponding path!

 Wels SVC Encoder Usage:

 Syntax: welsenc.exe -h
 Syntax: welsenc.exe welsenc.cfg
 Syntax: welsenc.exe welsenc.cfg [options]

Any suggestions on how to get this working? Can I now use the encodedImage.h264 to decode it back to yuv file using: `h264dec.exe encode.h264 output.yuv`

Thanks in advance!

**Comment by ruil2** [comment]
Wels SVC Encoder Usage:

Syntax: welsenc.exe -h
Syntax: welsenc.exe welsenc.cfg
Syntax: welsenc.exe welsenc.cfg [options]
 
you can see the welsenc.cfg sample in testbin folder, you can change the configure as you expect.

for decoder usage, you are right. 
" h264dec.exe encode.h264 output.yuv"

**Comment by jelenaognjan** [comment]
[.cfg.zip](https://github.com/cisco/openh264/files/1768606/default.cfg.zip)
[MSR LA - 3495.docx](https://github.com/cisco/openh264/files/1768607/MSR.LA.-.3495.docx)
[MSR LA - 3495.docx](https://github.com/cisco/openh264/files/1768609/MSR.LA.-.3495.docx)
[MSR LA - 3495.docx](https://github.com/cisco/openh264/files/1768610/MSR.LA.-.3495.docx)
