### ISSUE TITLE
How to make P frames depended only on previous I frame to be decoded

### ISSUE THREAD

**Issue by newmytestgit** [cisco/openh264#2924]
Already you have answer my quesiton but I am not clear till now. Many many thanks for your reply. I want to make all of the P frames depended only on previous I frame not previous P frames. Will setting TemporalLayerNumber>1 do my job ? If not, Is there any way to do this ? If even modification of source code is necessary I will try to do this. Is there any easy way ? If not, which classes and files should I study to do this job ? Thanks in advance :)

**Comment by bo01ean** [comment]
If you want it to rely only on previous I Frame use -g 2 ( I Frame every other frame )

**Comment by newmytestgit** [comment]
Sir will you please explain. what is -g 2 ?

**Comment by newmytestgit** [comment]
I am not looking for IPIPIPIP......
I am looking for IPPPPPPPPPPIPPPPPPPPP........
but the p frames will be dependent only on previous I frame to be decoded correctly. now if any P frame is missing the the later P frames creates distorted video frames.

**Comment by ruil2** [comment]
openh264 doesn't support this structure as IPPPP... that all P frames only use I frame as reference now.

**Comment by newmytestgit** [comment]
How to make openh264 supported for this feature. Please I need a guideline. Which source file I will need to study to modify the source to provide this support. Will you please give me a guideline ?

**Comment by newmytestgit** [comment]
Many Many thanks in advance :)

**Comment by huili2** [comment]
It is a little too hard to do such changes as you need modify source code of referencing structure. I think it is not a normal case, so it is not in current plan.
