### ISSUE TITLE
Creating a H264 bytestream for the decoder

### ISSUE THREAD

**Issue by anoop4** [cisco/openh264#2934]
Hi,

I am using Wireshark to monitor the packetized H264 byte stream being sent from the source.
I can see both IDR and non-IDR slice but I create the H264 byte stream using the IDR slices only in the below format:
0x000001[SPS] 0x000001[PPS] 0x000001[assembled IDR Video fragment]

The decoder gives me a "half-decoded" output where the image is blurred halfway through. 

![2018-03-20_8-45-37](https://user-images.githubusercontent.com/14857369/37634096-2037b378-2c1b-11e8-9f0b-dfe33b0d4ba5.jpg)

Am I missing something here? Are the non-IDR slices important for the decoder as well?

**Comment by huili2** [comment]
Per Rec defined, if there is difference between two successive IDR frames (something like idr_pic_id or others), it can be decoded. Otherwise, it may cause error.

**Comment by achirasa** [comment]
![img_0002 1](https://user-images.githubusercontent.com/36072889/38225889-2b212e48-3721-11e8-9ce9-82c2ed3801ef.PNG)

[1[1].txt](https://github.com/cisco/openh264/files/1869979/1.1.txt)
