### ISSUE TITLE
Warning: .. in frame:1 uiDid:0 uiQid:0

### ISSUE THREAD

**Issue by srijith-vijay** [cisco/openh264#2945]
Hi,

I am able to decode the H264 byte stream successfully, except for these warnings:

![2018-03-27_10-26-01](https://user-images.githubusercontent.com/14857369/37949074-b18ec286-31b0-11e8-8f41-826893f27680.png)

Can these warnings be ignored? Is there a way to suppress these warnings(like some kind of tokens) when using the binary file?

**Comment by huili2** [comment]
If you can modify the source code, you can add SetOption() before actual frame decoding to set trace level to be quiet.

**Comment by srijith-vijay** [comment]
I am afraid modifying the source code is not an option I have because I am working with the binaries. Is there a way I can specify the warnings to be off while using the decoder?
something like: decoder.exe -w source.264 output.yuv

**Comment by huili2** [comment]
Currently there is no option for such requirement.

**Comment by srijith-vijay** [comment]
Can you let me know what is causing this error? 

I also get the warning:  Warning:referencing pictures lost due frame gaps exist, prev_frame_num: -1, curr_frame_num: 1

for the very first frame I am trying to decode

Thanks in Advance!

**Comment by huili2** [comment]
All the errors show similar reason: the bitstream is not complete (or may be the parameter set information is wrong) so that it can not be correctly decoded.
For your second warning about "referencing pictures lost", as it indicates, decoder finds frame missing within the bitstream.

**Comment by srijith-vijay** [comment]
Thanks for the support! 
I just found out that the warnings were caused due to the insertion of the 0x000001 header before the P-frames. The decoding works fine with the 3-byte separator removed

**Comment by huili2** [comment]
Glad it is OK now~
