### ISSUE TITLE
H264 binaries: .dll or .exe?

### ISSUE THREAD

**Issue by anoop4** [cisco/openh264#2950]
Hi,

Where can I find the H264 binaries that Cisco[ recommends](https://www.openh264.org/faq.html) to avoid any licensing issues in my project?

Can I use the binaries that I get by building the source files in Visual studio? like here:
[https://github.com/shishuo365/OpenH264Release](https://github.com/shishuo365/OpenH264Release)

Or do you recommend to use the .dll file here? [https://github.com/cisco/openh264/releases](https://github.com/cisco/openh264/releases)

I am currently using the .exe file to decode H264 frames like : >> decoder.exe source.264 op.yuv

**Comment by huili2** [comment]
you can get recommended library files (not executable files) from the links in https://github.com/cisco/openh264/blob/master/RELEASES, at the bottom part.

**Comment by srijith-vijay** [comment]
Can you let me know how to use this .dll to decode a bitstream?

Is there an API/function that can accept the bitstream as input and return a YUV format output?

**Comment by huili2** [comment]
For Windows usage, about APIs you can refer to the examples in h264dec.cpp, by using "LoadLibrary()" function to load this dll.
A rough step can be referenced in the very start of the comments in codec/api/svc/codec_api.h for decoding a bitstream.

**Comment by heartquake** [comment]
@anoop4 Were you able to use the openh264 binary in a VS project?

**Comment by anoop4** [comment]
Yes, I was able to dynamically load the library and call the decoder function using the loadLibray() and getProcAddress() functions, respectively.

You can check out the example code on how to use the decoder function after loading the library.

HTH if you need more info

**Comment by anoop4** [comment]
Here is an example of how the decoder.exe console is implemented.
https://github.com/cisco/openh264/blob/master/codec/console/dec/src/h264dec.cpp

'H264DecodeInstance' implements decoding behavior. You just need to load the openh264.dll and map  the WelsCreateDecoderFunction from the library

>> hDLL = loadLibrary("openh264.dll");
>>foo = (WelsCreateDecoderFunc)GetProcAddress(hDLL, "WelsCreateDecoder");

Now, use 'foo' wherever you want to use 'WelsCreateDecoder' function in your code

**Comment by heartquake** [comment]
Hi,
I'm appreciated.

I'm using the automated build script to compile CEF then import the output to my c# project. Therefore I don't know the c language. Would you mind to share your h264dec.cpp with me?

**Comment by heartquake** [comment]
Or, file(s) that needs to be changed.

**Comment by anoop4** [comment]
I am afraid I don't have the source files with me. This was a project that I tried a year back.
I used the same workflow as given in the h264dec.cpp file here: https://github.com/cisco/openh264/blob/master/codec/console/dec/src/h264dec.cpp.

**Comment by heartquake** [comment]
That'll be a challenge.

Thanks @anoop4

**Comment by heartquake** [comment]
@anoop4 

Was your project a c# or c++ project? I'm asking because I'm a little lost.

My project is c#. I'm using CefSharp as wrapper with my own built CEF binaries. 

Now, you have edited this file [https://github.com/cisco/openh264/blob/master/codec/api/svc/codec_api.h](url), then how did you compile the CEF? After the build did you just place the openh264.dll to the same folder where CEF .dll's files are?

Sorry for the endless questions. I'm really lost.

**Comment by anoop4** [comment]
Mine was a c++ project. I built the code and placed the openh264.dll in the same folder as the executable created from the cpp source.

**Comment by AVMACHINE2** [comment]
Hi Anoop,
I wanna use openh264, can you tell me how to use .dll file. Do i need  other file or dll file will work.

**Comment by anoop4** [comment]
You just need to load the dll file dynamically, no other files needed. Refer to my comment above on how to do that.

**Comment by schandra09net** [comment]
> @anoop4
> 
> Was your project a c# or c++ project? I'm asking because I'm a little lost.
> 
> My project is c#. I'm using CefSharp as wrapper with my own built CEF binaries.
> 
> Now, you have edited this file [https://github.com/cisco/openh264/blob/master/codec/api/svc/codec_api.h](url), then how did you compile the CEF? After the build did you just place the openh264.dll to the same folder where CEF .dll's files are?
> 
> Sorry for the endless questions. I'm really lost.

Hi @anoop4 

Are you able to get the results when you put OpenH264 in C# cef project ? (My understanding is that CEF will not read this .dll file directly as it will look for libcef.dll).

**Comment by wdtkr** [comment]
Hi @anoop4 
I want to use openh264 as dylib (or dll).
I load it from a C++ file like this: void *handle = dlopen(". /libopenh264-2.3.1-mac-arm64.dylib", RTLD_LAZY);
However, some types, such as SEncParamBase, are not declared.
If I want to use only dylib like this, do I still need to include the header file?
If so, is the license free for using the header file?
