### ISSUE TITLE
OPEN H264 SVC 

### ISSUE THREAD

**Issue by VPBalaRama** [cisco/openh264#2954]
Hi Team,
I ám new to open h264 org and i have downloaded source code  in to Linux machine and tried test/sample examples apps, when i decode the h264 svc encoded contents, decoder was throwing following error.

command to encode:
../h264enc welsenc_vd_1d.cfg

#layers defination(All are  spatial sampling)
PrefixNALAddingCtrl              1              
NumLayers                        3              # Number of layers
LayerCfg                layer2.cfg        # Layer 0 configuration file
LayerCfg                layer2_vd_rc.cfg        # Layer 1 configuration file
LayerCfg                layer2_vd.cfg        # Layer 2 configuration file
                                             
[OpenH264] this = 0x0x1a5f040, Warning:UpdateAccessUnit():::::Key frame lost.....CAN NOT find IDR from current AU.
[OpenH264] this = 0x0x1a5f040, Warning:UpdateAccessUnit():::::Key frame lost.....CAN NOT find IDR from current AU.
[OpenH264] this = 0x0x1a5f040, Warning:UpdateAccessUnit():::::Key frame lost.....CAN NOT find IDR from current AU.

I am actually looking in to H264 SVC funtionality and as a server, stream less bandwidth layer to client who is on bad network.
Please provide me
1. document or link which describes how to link openh264 binary in to my project.
2. param's required to set at encoder side for SVC support.
3. How to extract SVC layers.

**Comment by VPBalaRama** [comment]
Hi huili2,
I tried as you pointed,but still i'm getting same error.

i have one doubt from your earlier comment.
**_current decoder only supports single layer data input_** this means OPENH264 decoder doesnt support decoding of SVC stream, then how to decode stream.  please let me know to how extract layers.

sharing config file for multilayer(SVC) encoding will helps me a lot.

**Comment by huili2** [comment]
You are right that "decoder doesn't support decoding of SVC stream".  As I pointed out, you may add necessary info in cfg file to get needed bitstream. Another method is to use command line to encode layers, like the following cmd in mac: 
./h264enc -utype 0 -org PATH/input.yuv -numl 3 -numtl 1 -frin 30 -frout 0 30 -frout 1 30 -frout 2 30 -sw 1280 -sh 720 -dw 0 320 -dh 0 180 -dw 1 640 -dh 1 360 -dw 2 1280 -dh 2 720 -rc -1 -lqp 0 24 -lqp 1 24 -lqp 2 24 -iper 0 -bf OUTPUT.264 -mfile 1
then you'll get OUTPUT_layerX.264 with X=0,1,2 for 3 layers.

**Comment by yanceyxin0326** [comment]
I used command line to  encode layers in windows like the method of the huili2,but only got one OUTPUT.264,so i did not get OUTPUT_layerX.264 with X=0,1,2 for 3 layers; why?

**Comment by huili2** [comment]
did you add "-mfile 1" in command line?

**Comment by yanceyxin0326** [comment]
I did,this is my command line in windows:
encConsole.exe -utype 0 -org meetingmen_1280x720.yuv -numl 3 -numtl 1 -frin 30 -frout 0 30 -frout 1 30 -frout 2 30 -sw 1280 -sh 720 -dw 0 320 -dh 0 180 -dw 1 640 -dh 1 360 -dw 2 1280 -dh 2 720 -rc -1 -lqp 0 24 -lqp 1 24 -lqp 2 24 -iper 0 -bf OUTPUT.264 -mfile 1
i think no problem, please tell me how to get  bitstream of every layers?

**Comment by huili2** [comment]
@yanceyxin0326 I tried your same cmdline in Windows, but get 3 bs files. Did you use latest MASTER branch? This function just takes effect since days ago.

**Comment by yanceyxin0326** [comment]
thanks ,you are right ,my MASTER is not the latest. wow,it is amazing!  if  i have questions ,i will consult to you, thank you  for your help again.

**Comment by huili2** [comment]
Glad and welcome~

**Comment by yanceyxin0326** [comment]
I have a question,if  i want to encode a bs of multilayer,then decode it ,how to realize the function?Do you see what I mean?

**Comment by huili2** [comment]
Not quite get your point. Do you mean key functions of encoder/decoder? As you know, we discussed about how to encode, so you are wondering the decoding part?

**Comment by yanceyxin0326** [comment]
I am sorry ,I don not  express myself clearly. I want say that the problem of  @VPBalaRama .Now, whether  the decoder of openh264  can decode the bs of multilayer?

**Comment by huili2** [comment]
No, it is not supported and not planned till now.

**Comment by AllenChong** [comment]
issue
