### ISSUE TITLE
Can I get fast coding start with openh264 ?

### ISSUE THREAD

**Issue by dmxvlx** [cisco/openh264#2957]
Hi guys!

I am begginer for this library, and I have the question:
Could anyone explain me, how can I get encoded (and after decoded) rgb array with the openh264 ?

[CODE=CPP]
// for example we have an rgb image:
const int width = 640, height = 480, depth = 3;

uint8_t image[width * height * depth]; // fill some image ...
// and what should I do for get encoded that RGB array ?
[/CODE]

PS: Sorry for many words :)) , and thanks for yours answers :)

**Comment by dmxvlx** [comment]
OK, I have found this method in interface of encoder:

int ISVCEncoder::**EncodeFrame** (const SSourcePicture* kpSrcPic, SFrameBSInfo* pBsInfo);

to set source image in the RGB format I can
as explained in codec_api.h:184 - Step4: encode and  store ouput bistream.

But after called the **EncodeFrame**, how can I get size and encoded datas
from `**pBsInfo**' ?

Please, any help!

**Comment by ruil2** [comment]
here is an example to use openh264. https://github.com/cisco/openh264/wiki/UsageExampleForEncoder

the below shows an example that how to process output bitstream.
(info is same with pBsInfo)

int nLayer = 0;
while (nLayer < info.iLayerNum)
{
    SLayerBSInfo* pLayerBsInfo = &info.sLayerInfo[nLayer++];
    if (NULL != pLayerBsInfo)
    {
        int nLayerSize = 0;
        int nNalIndex = pLayerBsInfo->iNalCount - 1;
        
        do
        {
            nLayerSize += pLayerBsInfo->pNalLengthInByte[nNalIndex];
            --nNalIndex;
        } while (nNalIndex >= 0);

        fwrite(pLayerBsInfo->pBsBuf, 1, nLayerSize, fH264);
    }
}

**Comment by ricejasonf** [comment]
This would be useful in the documentation.

The NULL check is probably unnecessary since `pLayerBsInfo` is just referencing an element of a member of `info`. It's address could never be NULL.

**Comment by dmxvlx** [comment]
thanks a lot !
