### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by bobj1212** [cisco/openh264#2961]
1) what with v1.71 binary? I see only 1.7
2) Is the h264 encoding is Hardware accelerated.
I mean for example with Quicksync all video compression is done in a chip on-the-fly and with close to zero CPU load.
Does this the case with this Cisco implementation? If yes how to enable this option?

**Comment by GuangweiWang** [comment]
about Q1: 
There is no plan for release in a short time.
about Q2:
There is no hardware encode/decode on openh264. openh264 is a pure software codec with assembly accelerated. 


If it is convenient, can you tell me why you ask this question?

**Comment by bobj1212** [comment]
I asked because i want to decrease CPU my app takes for encoding so using Hardware sounds like good idea.
Do you have any tips for how to use openH264  (encoding) with less CPU as possible for lets say 
(1080P input and output) around 25FPS

Thanks for your answer

**Comment by huili2** [comment]
Related to CPU performance. No decent way since no hardware acceleration is used.
I think in current years with popular PC, 1080p @ 25fps could be achieved.
