### ISSUE TITLE
openH264 Encoding speed

### ISSUE THREAD

**Issue by VPBalaRama** [cisco/openh264#2962]
Hi Team, 
I'm comparing encoding speed of openH264 and x264. i have found that openh264 is taking more time than x264. Below i shared encoding time of both and i would like to know how to increase encoding speed.

Encoding time taken by openh264 for single frame is _**374432 micro seconds**_ and encoding time for _**600 frames is  124.4 sec**_
Encoding time taken by x264 for single frame is **_160400 micro seconds_**

**param's**
SourceWidth                      1280            # Input  frame width
SourceHeight                     720
EntropyCodingModeFlag            0 //cavlc
RCMode                           -1         
TargetBitrate                    10000        
MaxOverallBitrate                12000         
MaxQp                            51  

**Machine details:**
CPU MHz:               2394.230
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8

**Comment by VPBalaRama** [comment]
Hi 
please find output param's
Width:          1280
Height:         720
Frames:         600
encode time:    124.473569 sec
FPS:            4.820300 fps

**Comment by GuangweiWang** [comment]
can you provide encode parameters of x264?

**Comment by VPBalaRama** [comment]
Hi GuangweiWang,

i used same 720p yuv file for both test scenerio's.

x264 encoder params:
 c_enc->bit_rate = 10000000;// 400000;
c_enc->width = 1280;//iwidth;// 320;//  c_dec->width;// 352;
 c_enc->height = 720;//iheight;// 240;// c_dec->height;// 288;
c_enc->profile =FF_PROFILE_H264_BASELINE;

at x264 i tried _**with or without setting "tune"  param**_, in both cases it was taking less time compared to openh264 encoder.
av_opt_set(c_enc->priv_data, "tune", "zerolatency", 0);

**Comment by VPBalaRama** [comment]
Hi
please find single thread(only one thread doing encoding) results for both openh264 and ffmpeg x264. From results openh264 was taking 3min29seconds to encode 600 frames and ffmpeg x264 was taking 0min54.711s for 600 frames
_**openh264:**_
Width:          1920
Height:         1080
Frames:         600
encode time:    209.705941 sec
FPS:            2.861149 fps

**real    3m30.047s
user    3m29.696s
sys     0m0.340s**


**_FFmpeg x264_**
Width:          1920
Height:         1080
Frames:         600

**real    0m54.711s
user    0m53.607s
sys     0m1.062s**

**Comment by GuangweiWang** [comment]
@VPBalaRama 
I check out the latest commit of openh264 to encode 1280x720 YUVs. the result is different from yours. my result is:
Width:		1280
Height:		720
Frames:		178
encode time:	0.835841 sec
FPS:		212.959163 fps

**Comment by VPBalaRama** [comment]
Hi GuangweiWang,

Thanks for your support.
To debug code path, i have enabled **_Debugging symbols and CFLAGS_OPT=-O0_** in Make file, this could be an issue?

**Comment by GuangweiWang** [comment]
CFLAGS_OPT=-O0 will affect the performance, you can use -O2 or -O3 instead -O0.

**Comment by ruil2** [comment]
@VPBalaRama  Could you try the release library firstly instead of using your private build? thanks!
