### ISSUE TITLE
Speed Optimization

### ISSUE THREAD

**Issue by bobj1212** [cisco/openh264#2966]
I want to decrease CPU my app takes for encoding
Do you have any tips for how to use openH264 (encoding) with less CPU as possible for lets say
(1080P input and output) around 25FPS

Images are taken by capturing Windows desktop and are sent to the h264 encoder (around 25FPS) ...

I am already using LOW_COMPLEXITY

Thanks for your answer

**Comment by bobj1212** [comment]
Someone?

**Comment by huili2** [comment]
By default, openh264 encoder is at high speed. Currently it can just work on 1080p (about 40~50fps under normal Intel I7) within one core.
