### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by bolds07** [cisco/openh264#2968]
I'm running ubuntu 16 lts and trying to compile openh264 to android-27 arm

I run:
export PATH=/home/r/aff/sdk/tools:$PATH
make OS=android NDKROOT=/home/r/aff/ndk TARGET=android-27 NDKLEVEL=27

result:
`root@r:/home/r/aff/openh264# make OS=android NDKROOT=/home/r/aff/ndk TARGET=android-27 NDKLEVEL=27
/home/r/aff/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -O3 -DNDEBUG -DHAVE_NEON -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -DANDROID_NDK -fpic --sysroot=/home/r/aff/ndk/platforms/android-27/arch-arm -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -I/usr/include/x86_64-linux-gnu/sys -Dandroid_getCpuIdArm=wels_getCpuIdArm -Dandroid_setCpuArm=wels_setCpuArm -Dandroid_getCpuCount=wels_getCpuCount -Dandroid_getCpuFamily=wels_getCpuFamily -Dandroid_getCpuFeatures=wels_getCpuFeatures -Dandroid_setCpu=wels_setCpu  -I/home/r/aff/ndk/sources/android/cpufeatures -c -o codec/common/src/cpu-features.o /home/r/aff/ndk/sources/android/cpufeatures/cpu-features.c
In file included from /home/r/aff/ndk/sources/android/cpufeatures/cpu-features.c:64:0:
/home/r/aff/ndk/sources/android/cpufeatures/cpu-features.h:31:23: fatal error: sys/cdefs.h: No such file or directory
 #include <sys/cdefs.h>
                       ^
compilation terminated.
build/platform-android.mk:96: recipe for target 'codec/common/src/cpu-features.o' failed
make: *** [codec/common/src/cpu-features.o] Error 1
`
as I checked the lib sys/cdefs.h is under 
/usr/include/x86_64-linux-gnu/sys/

I tried include it on path... but same error
I tried to create a symbolic link to that folder under the folder /home/r/aff/ndk/sources/android/cpufeatures/ then the error changes for another lib missing

**Comment by GuangweiWang** [comment]
what's the NDK version? you can try this:
make OS=android NDKROOT=/home/r/aff/ndk TARGET=android-27 NDKLEVEL=27 sysroot=/home/r/aff/ndk/sysroot

**Comment by bolds07** [comment]
my ndk is the latest on google repository 17

running
make OS=android NDKROOT=/home/r/aff/ndk TARGET=android-27 NDKLEVEL=27 sysroot=/home/r/aff/ndk/sysroot

same error: 
`/home/r/aff/ndk/sources/android/cpufeatures/cpu-features.h:31:23: fatal error: sys/cdefs.h: No such file or directory
 #include <sys/cdefs.h>
`

is it necessary to keep openh264 in an specific directory? i mean since i set the variables above does it matter the folder structure?

**Comment by bolds07** [comment]
Just another information.... I can sucessfully build by just running make

but with android parameters i get that error

**Comment by GuangweiWang** [comment]
firstly, answer your question:
1. "just running make" will build libraries and binaries for your host platform, it is not for android.
2.  "is it necessary to keep openh264 in a specific directory": no, it does not matter to export PATH value.


about your issue:
this build error is caused by your environment setting. so can you provide the detailed information of your platform?
1. is your host platform Ubuntu 16?
2. how do you download/install your NDK? can your descript this processing in more detail?
if you provide this information, I can try to reproduce this issue on my local PC.

**Comment by liuqijun** [comment]
1 - Compile `sysroot` is `$NDK/sysroot`
2 - Pass `-isystem $NDK/sysroot/usr/include/$TRIPLE` and `-D__ANDROID_API__=$API `when compiling
3 - Link `sysroot` is  `$NDK/platforms/android-$API/arch-$ARCH/`

Modify the `build/platform-android.mk` file.

```
header_triple_arm := arm-linux-androideabi
header_triple_arm64 := aarch64-linux-android
header_triple_mips := mipsel-linux-android
header_triple_mips64 := mips64el-linux-android
header_triple_x86 := i686-linux-android
header_triple_x86_64 := x86_64-linux-android
SYSROOT_ARCH_INC_ARG := -isystem $(NDKROOT)/sysroot/usr/include/$(header_triple_$(ARCH))

SYSROOT = $(NDKROOT)/sysroot \
          $(SYSROOT_ARCH_INC_ARG)
CXX = $(TOOLCHAINPREFIX)g++
CC = $(TOOLCHAINPREFIX)gcc
AR = $(TOOLCHAINPREFIX)ar
CFLAGS += -DANDROID_NDK -fpic --sysroot=$(SYSROOT) -MMD -MP -D__ANDROID_API__=NDKLEVEL
CXXFLAGS += -fno-rtti -fno-exceptions
LDFLAGS += --sysroot=$(NDKROOT)/platforms/android-$(NDKLEVEL)/arch-$(ARCH)
SHLDFLAGS = -Wl,--no-undefined -Wl,-z,relro -Wl,-z,now -Wl,-soname,lib$(PROJECT_NAME).so

ifneq ($(CXX),$(wildcard $(CXX)))
ifneq ($(CXX).exe,$(wildcard $(CXX).exe))
$(error Compiler not found, bad NDKROOT or ARCH?)
endif
endif

STL_INCLUDES = \
    -I$(NDKROOT)/sources/cxx-stl/llvm-libc++/include
STL_LIB = \
    $(NDKROOT)/sources/cxx-stl/llvm-libc++/libs/$(APP_ABI)/libc++_static.a
```

**Comment by folk113** [comment]
you can get the answer from my blog http://www.phubber.com/2018/08/13/openh264-android-compile-ndkr17b/
