### ISSUE TITLE
optimization for mips64

### ISSUE THREAD

**Issue by GuXiWei** [cisco/openh264#2992]
I've done some optimizations base on mips64(cpu: loongson3a),can the code be submitted to the community?How to submit?Thanks a lot.

**Comment by GuangweiWang** [comment]
@GuXiWei 

you can create a pull request to submit your code.

**Comment by GuXiWei** [comment]
ok thanks.

**Comment by GuXiWei** [comment]
@GuangweiWang 
Hi，I have submitted the code for two weeks（#3005）。I don't know if the code is capable of merging and when。thanks。

**Comment by GuangweiWang** [comment]
@GuXiWei 
Ok, Will

**Comment by gxw-loongson** [comment]
@GuangweiWang 
Hi, sorry to bother you, any suggestions about the commit (#3005)? thanks a lot :).

**Comment by gxw-loongson** [comment]
@GuangweiWang 
hi, could you tell me the progress of the code review?I still have a few patches to submit.thanks a lot.

**Comment by GuangweiWang** [comment]
please patch it first.

**Comment by gxw-loongson** [comment]
@GuangweiWang 
hi，I have submitted all the patches。

**Comment by GuangweiWang** [comment]
you can close this issue and use that PR to track the code review.
