### ISSUE TITLE
NV12 / NV21 support for decoder, possible discussion?

### ISSUE THREAD

**Issue by vans163** [cisco/openh264#3022]
A lot of encoders are outputting NV12 or NV21 these days. It kinda sucks being unable to use openH264 with them. I tried a few of my own approaches to fix it, but I kept getting incorrect chroma values.  

I knows its been said only IYUV420 is supported, but that was almost 4 years ago, and times have changed since then.

**Comment by ruil2** [comment]
no plan to support NV12 or NV21 input for openh264 encoder until now. thanks!

**Comment by vans163** [comment]
Just decoder support I mean. Encoder is fine as is, problem is decoder cannot interop with many new encoders because they output NV12/21

**Comment by ruil2** [comment]
no plan to support NV12/NV21 for decoder.
