### ISSUE TITLE
how to close the  assembly optimization?

### ISSUE THREAD

**Issue by gxw-loongson** [cisco/openh264#3023]
If make the source code directly, it will automatically detecting architecture and open the corresponding assembly optimization. what should i do to use the pure c/c++ code instead of the assembly optimization?

**Comment by ruil2** [comment]
make BUILDTYPE=DEBUG

**Comment by GuangweiWang** [comment]
or make USE_ASM=No

**Comment by gxw-loongson** [comment]
thanks, it works.
