### ISSUE TITLE
How to change encoding param during encoding process?

### ISSUE THREAD

**Issue by elesos** [cisco/openh264#3050]
From the sample code, I have found that:

SBitrateInfo target_bitrate;
memset(&target_bitrate, 0, sizeof(SBitrateInfo));
target_bitrate.iLayer = SPATIAL_LAYER_ALL,
target_bitrate.iBitrate = bit_rate*1000;   //  kbps->bps        
(*s->encoder)->SetOption(ENCODER_OPTION_BITRATE, &target_bitrate);

but i am use FFmpeg api.  How to change encoding param during encoding process in ffmpeg?

note:
avctx->priv_data->encoder is  ISVCEncoder

av_opt_set(avctx->priv_data, "preset", "superfast",   0);

**Comment by elesos** [comment]
MaxSpatialBitrate (150 000) should be larger than SpatialBitrate ，considering it as error setting

**Comment by elesos** [comment]
Encoder Features:Dynamic changes to bit rate, frame rate, and resolution

**Comment by puy2773** [comment]
SBitrateInfo target_bitrate;
memset(&target_bitrate, 0, sizeof(SBitrateInfo));
target_bitrate.iLayer = SPATIAL_LAYER_ALL,
target_bitrate.iBitrate = bit_rate*1000; // kbps->bps
(*s->encoder)->SetOption(ENCODER_OPTION_BITRATE, &target_bitrate);

but i am use FFmpeg api. How to change encoding param during encoding process in ffmpeg?

note:
avctx->priv_data->encoder is ISVCEncoder

av_opt_set(avctx->priv_data, "preset", "superfast", 0);
