### ISSUE TITLE
UT failed (maybe FalseAlarm): Engine_SVC_Switch_P

### ISSUE THREAD

**Issue by sijchen** [cisco/openh264#3088]
this is a placeholder.
maybe FalseAlarm, need to double-check.

On Windows10

how to reproduce:

bash -c "make OS=msvc ARCH=i386 USE_ASM=Yes BUILDTYPE=Debug clean"

Random seed: 1547606364

[ FAILED ] EncodeDecodeTestAPI.Engine_SVC_Switch_P

>18:41:34 [ RUN      ] EncodeDecodeTestAPI.Engine_SVC_Switch_P
18:41:35 test/api/decoder_ec_test.cpp(809): error: Expected equality of these values:
18:41:35   iTid
18:41:35     Which is: 0
18:41:35   info.sLayerInfo[0].uiTemporalId
18:41:35     Which is: '\x3' (3)

**Comment by xiaotiansf** [comment]
@sijchen I no longer see the error after I did complete rebuild of Codec_UT for Win32 Debug target.

**Comment by huili2** [comment]
close this one as it is un-reproducible.
