### ISSUE TITLE
dec crash for spec bitstream

### ISSUE THREAD

**Issue by huili2** [cisco/openh264#3110]
using master branch.
please rename it with suffix .264 instead and try "./h264dec gop2.264 out.yuv".

[gop2.txt](https://github.com/cisco/openh264/files/2965602/gop2.txt)

**Comment by xiaotiansf** [comment]
@huili2  Certainly, I will look into the issue.

**Comment by huili2** [comment]
@xiaotiansf  The crash still exists on master branch. Could you please check again?

**Comment by xiaotiansf** [comment]
Let me check.

**Comment by xiaotiansf** [comment]
@huili2 Is the same asset gop2.txt?

**Comment by xiaotiansf** [comment]
@huili2 I just synced to master. Retest many times with this asset gop2.txt and never reproduce the crash.

**Comment by huili2** [comment]
Strange. I repeated to crash .... Let me check on another PC.

**Comment by xiaotiansf** [comment]
I am on Widows 10 64-bit machine.

**Comment by huili2** [comment]
Mac seems OK but one linux reports error. Close this one for now.
