### ISSUE TITLE
whether the encoder of openh264 could support to generate bitstream with spatial inter-layer dependency?

### ISSUE THREAD

**Issue by liangwei1999** [cisco/openh264#3124]
Hi,
I have download and compile the source code, and run the encoder on windows platform. And I have got the output bit stream. Through proper setting in CFG file, I have encoded a bit stream with 2 spatial layer and 2 temporal layers. But I haven’t found any configuration about inter-layer dependency in those CFG file. 
And I have referenced the issue #2900 and #2068 to extract the 2 spatial layers into two files, and both of the two files could be decoded separately through h264dec.exe which is the decoder of openh264, and got two YUV output correctly. So, I think there is no inter-layer dependency between the two spatial layers. 
Also, I have written a little code to extract the bit stream, by extracting “no_inter_layer_pred_flag” of “nal_unit_header_svc_extension” syntax in which frame’s nal_unit_type==20, and found no_inter_layer_pred_flag=1. That is to say, the bit stream does not support inter-layer reference. So, I want to ask is there any method to encode a bit stream with spatial inter-layer dependency.
Thanks in advance.

**Comment by huili2** [comment]
Hi @liangwei1999 thanks for your interest. You are very careful and right, openh254 encoder does not support inter-layer prediction due to various reasons.

**Comment by liangwei1999** [comment]
@huili2 , Thank you! Both spatial and temporal inter-layer prediction are all not being supported now?

**Comment by huili2** [comment]
Temporal layer is fully supported whereas spatial is not.

**Comment by liangwei1999** [comment]
@huili2 I see, Thanks for you kindly reply.

**Comment by liangwei1999** [comment]
My question has been resolved perfectly.
