### ISSUE TITLE
Is there a bit rate setting for temporal layers?

### ISSUE THREAD

**Issue by liangwei1999** [cisco/openh264#3126]
Hi,
I have encoded a bit stream through the encoder of openh264. I encoded the bit stream with 1 spatial layer and 2 temporal layers, by setting NumLayers=1 of the LAYER DEFINITION section and TemporalLayerNum=2 of the GENERAL section in the CFG file. And now I want to set bit rate for each temporal layer, but I find that there is only bitrate settings for spatial layer in the layer definition CFG file. So, I want to ask, is there a bit rate setting for temporal layers?

**Comment by huili2** [comment]
There's no such bitrate settings for different temporal layers.

**Comment by liangwei1999** [comment]
Thanks for your reply, I'm reading these codes related to spatial layers and temporal layers.
