### ISSUE TITLE
Apparently h264dec does not activate GPU (Intel Iris 1536 MB) to decode streams 

### ISSUE THREAD

**Issue by shevachr** [cisco/openh264#3127]
Hi all 

i compiled Openh264 in MacOS and applied h264dec on 1920x1080 video stream. However, decoding time is too low 35fps. Apparently hw decoder of GPU (Intel Iris 1536 MB) is not activated and all decoding is performed in sw. 
How to compile Openh264 in order to activate hw decoding?

**Comment by huili2** [comment]
openh264 does not support hardware decoding till now. However, in our private tests on Windows I7, we get mostly >100 fps for most cases.

**Comment by shevachr** [comment]
Thanks for a prompt reply.

i compiled Openh264 in MAC OS with the following command:

*make ARCH=x86_64*

Perhaps, i should have activated optimization keys to get a performance
above 60 fps.

**Comment by shevachr** [comment]
i build 32-bits version of Openh264 decoder on Windows 10, Intel(R)
Core(TM) i7-8550U CPU @ 1.80GHz (8 CPUs), ~2.0GHz and indeed i observe
decoding rate ~75fps for 1080p video
