### ISSUE TITLE
Guidance for compiling decode to WASM via Emscripten

### ISSUE THREAD

**Issue by rhues** [cisco/openh264#3136]
A web search isn't pulling up any examples of how to build openh264 for WASM via Emscripten. Any suggestions? I'm an experienced developer, but new to C++. Thanks.

**Comment by huili2** [comment]
We have no idea about WebAssembly on Openh264, either. 
Currently we provide libraries on different platforms. For more information, you may refer to README in folder for platform-dependent building, or get specific libraries directly from releases.

**Comment by Frozen-Tofu** [comment]
I've managed to compile openh264 into asm.js and draw the decoded frame into a 2d canvas.
The performance is not as good as native decoder, it's not recommended except for some special situations.

**Comment by DanielHuisman** [comment]
@Frozen-Tofu do you have a public repository for your experiment? I would be interested to toy around with it myself.

**Comment by Frozen-Tofu** [comment]
@DanielHuisman I'll upload it on weekend.

**Comment by DanielHuisman** [comment]
@Frozen-Tofu did you have time to upload it yet?

**Comment by Frozen-Tofu** [comment]
@DanielHuisman I'm busy with work now, sorry.

**Comment by Terricide** [comment]
I'd be interested as well.

**Comment by tommyZZM** [comment]
Reply @Frozen-Tofu @DanielHuisman @Terricide 

Take a look this project, which was compiled an old version openh264 to wasm. may useful.

https://github.com/kazuki/video-codec.js

**Comment by DanielHuisman** [comment]
I have looked into that project and other similar ones, but I haven't been able to find one that has a proper working example and/or docs. So far most projects I found were too old and had, for example, compilation issues.

If anyone has an up-to-date project or demo, I would be interested in checking that out.

**Comment by guest271314** [comment]
@DanielHuisman https://kazuki.github.io/video-codec.js/index.html throws error at 

> test.js:106 Uncaught (in promise) TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at callback (test.js:106)

which appears to be caused by passing a `MediaStream` to `URL.createObjectURL()` instead of a `Blob`. Adjusting the code to set `MediaStream` at `srcObject` of `HTMLMediaElement` should fix that issue.

Arrived here because default Chromium is not shipped with support for `x-matroska;codecs=h264` at `MediaRecorder` `mimeType` https://bugs.chromium.org/p/chromium/issues/detail?id=601636#c29.

**Comment by guest271314** [comment]
@DanielHuisman https://github.com/kazuki/video-codec.js/pull/12
