### ISSUE TITLE
Decoder report error when decoding bitstream with 2 spatial layers

### ISSUE THREAD

**Issue by liangwei1999** [cisco/openh264#3149]
Hi,
I'm using openh264 decoder h264dec.exe to decode a bitstream with 2 spatial layers which is generated by h264enc.exe, but the h264dec.exe reports "Key frame lost.....CAN NOT find IDR from current AU." in the console when decoding every P frame(it seems like that, I'm not sure now.) And I have debug into the decoder code, but no valuable reason were found.

who can help me to get over this problem. 
the bitstream I use is in the attached files.
Thanks in advance.
[test_1.zip](https://github.com/cisco/openh264/files/3371985/test_1.zip)

**Comment by huili2** [comment]
Hi @liangwei1999 current decoder cannot directly decode two-layer input. You need manually separate them first by layer, then pass the one-layer data into decoder.

**Comment by liangwei1999** [comment]
@huili2, thanks for your reply. moreover, the different spatial layer should be separated manually, but different temporal layer should be feeded into the decoder directly, is this right?

**Comment by huili2** [comment]
exactly.

**Comment by liangwei1999** [comment]
@huili2 , OK, Thanks.
