### ISSUE TITLE
How can I use openh264 dll on my visual studio project?

### ISSUE THREAD

**Issue by JangTaekSoo** [cisco/openh264#3151]
Hello!
I have a question for openh264 release(dll).
I am using visual studio 2010 and want to decode frames encoded using H.264.
So I made a project with openh264 dll (I downloaded it at http://ciscobinary.openh264.org/openh264-2.0.0-win32.dll.bz2).
and I added code for decoding according to UsageExampleForDecoder.
But I can't build my project because I can't get import library file(.lib).
How can I use it as binary?
Does anyone know this?
Thank you in advance!

**Comment by huili2** [comment]
On Windows, you may use ::LoadLibraryA() function to import dynamic library.

**Comment by JangTaekSoo** [comment]
Thank you, huili2
When I dump openh264-2.0.0-win32.dll, it seems to export only 6 function.
Is it right?
How can I use ISVCDecoder ?
Please let me know it if you know that.

**Comment by JangTaekSoo** [comment]
Thank you!!
