### ISSUE TITLE
Sound in Firefox 69

### ISSUE THREAD

**Issue by linuxgeekscott** [cisco/openh264#3168]
I recently installed Firefox 69 on my computer,  which runs Linux Mint.  The sound no longer works in Firefox 69.  It did in Firefox 64. I'm not sure how to correct it.

**Comment by nils-ohlmeier** [comment]
That issue has nothing to do with openh264, which is only used for decoding video in webrtc calls. Please fill a bug report for Firefox on https://bugzilla.mozilla.org instead.
