### ISSUE TITLE
Flathub flakpak org.freedesktop.Platform.openh264

### ISSUE THREAD

**Issue by ovari** [cisco/openh264#3171]
Can openh264 please be added to flathub?

https://github.com/flathub/org.freedesktop.Sdk.Extension.node10/issues/4

Thank you

**Comment by alatiera** [comment]
Freedesktop-sdk already ships a openh264 extension. What you are seeing in the link is [this bug](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/886) which has nothing to do with this repo. This issue can be closed :)
