### ISSUE TITLE
Can't use libopenh264-2.0.0-android.so for my android app because of 32-bit support

### ISSUE THREAD

**Issue by KiemDuong** [cisco/openh264#3181]
Hi everyone,
In my video editing android app, I had to download libopenh264-2.0.0-android.so.bz2 dynamically from this site https://github.com/cisco/openh264/releases to use with ffmpeg. 

However, if I disable 64-bit for the app, I can't publish the app on Google Play. The store requires 64-bit support.
If I enable 64-bit,  I can't use thi openh264-android.so library

Here is the way I disabled 64-bit in build.gradle
ndk {
            abiFilters "armeabi","armeabi-v7a","x86"
        }

Anyone can help on this issue please? thanks

**Comment by vaiden** [comment]
Yap - same here. All compiled binaries are 32-bit it seems.

**Comment by KiemDuong** [comment]
Noone can help even this repos is from cisco?

**Comment by vaiden** [comment]
Just compiled for Android 64-bit ourselves.
You may grab the compiled 64-bit versions of libopenh264.so here: https://github.com/HippotecLTD/openh264-lib-android-64-bit/releases/tag/2.0

**Comment by sijchen** [comment]
thanks a lot. We may provide that in next release. (do not have ETA due to low in resource)

**Comment by sijchen** [comment]
some new binaries are available now at https://github.com/cisco/openh264/releases/tag/v2.0.0 , would you kindly help us to verify if it works? Thx

Find ‘android-arm64’ in names.

**Comment by KiemDuong** [comment]
It worked now @sijchen , thank for your help!
