### ISSUE TITLE
consider a new release due to fixed crasher bugs

### ISSUE THREAD

**Issue by ramcq** [cisco/openh264#3218]
We're seeing crashes in the OpenH264 decoder when relying on the main profile support to play back H.264 videos from the internet. Although we're not sure which commit has fixed this, these crashes are no longer reproducible in master. Would it be possible to consider doing a new source and binary release soon so that users can start benefiting from these fixes?

Reference:
 - https://bugs.webkit.org/show_bug.cgi?id=203465
 - https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/922

Thanks,
Rob

**Comment by mcatanzaro** [comment]
Hello, happy 2020! Hope everyone had nice holidays.

These crashes are an emergency for us and there's not much we can do since only Cisco can distribute OpenH264. Please acknowledge this issue. Thanks!

**Comment by mcatanzaro** [comment]
OK, one last try: anybody home?

**Comment by Firm4n** [comment]
Hallo

Pada tanggal Kam, 23 Jan 2020 6.46 AM, Michael Catanzaro <
notifications@github.com> menulis:

**Comment by mcatanzaro** [comment]
Hi there. :) So:

> Would it be possible to consider doing a new source and binary release soon so that users can start benefiting from these fixes?

**Comment by mcatanzaro** [comment]
BTW, I also created a gst-plugins-bad issue where we diagnosed the crash: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1192

**Comment by sijchen** [comment]
next release in planning

**Comment by mcatanzaro** [comment]
Status update, we have a release branch: https://github.com/cisco/openh264/tree/openh264v2.1.0

And we have built new Fedora packages: https://pagure.io/releng/issue/9312

We're still waiting for the actual release to appear at https://github.com/cisco/openh264/releases so that we can update freedesktop-sdk.

**Comment by mcatanzaro** [comment]
With https://github.com/cisco/openh264/releases/tag/v2.1.0, this can now be closed!

**Comment by mcatanzaro** [comment]
The new release is out. This can really be closed.

**Comment by nanonyme** [comment]
@sijchen hey, could you please help us progress https://github.com/cisco/openh264/issues/3264? The new release breaks ABI so we cannot use it without soname bump.

**Comment by mcatanzaro** [comment]
This issue is obsolete and can be closed.
