### ISSUE TITLE
Frames get dropped with  low bitrate

### ISSUE THREAD

**Issue by SkyImplementer** [cisco/openh264#3237]
I am trying to encode a video of 2281 frames (1080p, 30fps) into two spatial layers. The bitrate of the base layer is 1mbps, and 4.5mbps for the enhancement layer. Yet, I noticed huge drop in number of frames (2281  --> 701). Then, when I increased the bitrate for base, and enhancement to 5mbps, 9.5 mbps ; respectively. The number of encoded frames increased ( 701 ->  1726). But still there are a lot of frames got dropped in compare to the original video (2281).

```
./h264enc  -org 1080p_video.yuv -utype 0 -numl 2 -numtl 1 -frin 30 -frout 0 30 -frout 1 30 -sw 1920 -sh 1080 -dw 0 1280 -dh 0 720 -dw 1 1920 -dh 1 1080 -minqp 0 -maxqp 51 -ltarb 0 1000k -lmaxb 0 1000k -ltarb 1 4500k -lmaxb 1 4500k -tarb 5500k -maxbrTotal 5500k -lqp 0 24 -lqp 1 24 -iper 30 -rc 1 -bf layer.h264 -mfile 1
Width:		1920
Height:		1080
Frames:		701
encode time:	25.238339 sec
FPS:		27.775203 fps
```
------------------------------------------------------------------------------------------------
```
./h264enc  -org 1080p_video.yuv -utype 0 -numl 2 -numtl 1 -frin 30 -frout 0 30 -frout 1 30 -sw 1920 -sh 1080 -dw 0 1280 -dh 0 720 -dw 1 1920 -dh 1 1080 -minqp 0 -maxqp 51 -ltarb 0 5000k -lmaxb 0 5000k -ltarb 1 9500k -lmaxb 1 9500k -tarb 14500k -maxbrTotal 14500k -lqp 0 24 -lqp 1 24 -iper 30 -rc 1 -bf L.h264 -mfile 1
Width:		1920
Height:		1080
Frames:		1726
encode time:	50.162285 sec
FPS:		34.408321 fps
```
------------------------------------------------------------------------------------------------

After digging into the source code for a bit, I found that plenty of frames are of type "videoFrameTypeSkip". Any reason why this is happening ?

**Comment by huili2** [comment]
Could you please try "5000000" instead of "5000k", and all similar changes?
