### ISSUE TITLE
Enhancement layer size discrepancy

### ISSUE THREAD

**Issue by SkyImplementer** [cisco/openh264#3238]
I am trying to encode a 5 second video using two layers (720p, 1080p), and a single layer (1080p). To do so I using the commands below. 

Two layers ( Base layer, and En. Layer)
`./h264enc  -org video.yuv -utype 0 -numl 2 -numtl 1 -frin 30 -frout 0 30 -frout 1 30 -sw 1920 -sh 1080 -dw 0 1280 -dh 0 720 -dw 1 1920 -dh 1 1080 -minqp 0 -maxqp 51 -lqp 0 24 -lqp 1 24 -iper 30 -rc -1 -bf frame47.h264 -mfile 1`

Single Layer
`./h264enc  -org video.yuv -utype 0 -numl 1 -numtl 1 -frin 30 -frout 0 30 -sw 1920 -sh 1080  -dw 0 1920 -dh 0 1080 -minqp 0 -maxqp 51  -ltarb 1 -lqp 0 24 -lqp 1 24 -iper 30 -rc -1 -bf frame47_x.h264 -mfile 1`

Issue is, the size of (1080p) enhancement layer is 26.2 MB, while the size of the single (1080p) layer is 20 MB. Is this rationale (i.e. the size of enhancement layer is > single layer)?

**Comment by huili2** [comment]
In your two layer coding, there should be two files generated, let's say 1080p_case1.h264 & 720p_case1.264.
In your single layer coding, one file was generated called 1080p_case2.h264.

A reasonable output is: 1080p_case1.h264 almost the same as 1080p_case2.h264, and both of them bigger than 720p_case1.h264.

Is this correct? If not, let's check further.

**Comment by SkyImplementer** [comment]
The sizes of 1080p_case1.h264 and 1080p_case2.h264 are pretty similar. Then, what is the benefit of using layered coding if the enhancement layer(1080p_case1) and single layer(1080p_case2.h264.) will have the same/similar sizes (bandwidth requirement is the same).

**Comment by mdasari823** [comment]
Looks like right now they are independent spatial layers. So, there is no spatial inter layer dependency, I guess that's why the sizes of enhancement layer(1080p_case1) and single layer(1080p_case2.h264) are similar. Spatial layering is not supported yet.
