### ISSUE TITLE
Enhancement layer decode error

### ISSUE THREAD

**Issue by toilandmoil** [cisco/openh264#3257]
To ensure that the input 264 stream is correct, using ./h264enc get the h264 stream.
./h264enc -org video.yuv -utype 0 -numl 2 -numtl 2 -frin 30 -frout 0 30 -frout 1 30 -sw 1920 -sh 1080 -dw 0 1280 -dh 0 720 -dw 1 1920 -dh 1 1080 -minqp 0 -maxqp 51 -lqp 0 24 -lqp 1 24 -iper 30 -rc -1 -bf frame47.h264 -mfile 1
I have a problem on the decoder side as follows:
Data frames carrying sps can be decoded, but no data can be taken.
		int iRet = pSvcDecoder->DecodeFrameNoDelay(pBuf + iBufPos, iSliceSize, pData, &sDstBufInfo);     iRet result is 0  , sDstBufInfo.iBufferStatus result is 0;

iSliceSize:1
iSliceSize:18
width:0	 height:0
ok (iRet  = 0)
iSliceSize:1
iSliceSize:17
width:0	 height:0
ok (iRet  = 0)
iSliceSize:1
iSliceSize:7
width:0	 height:0
ok (iRet  = 0)
iSliceSize:1
iSliceSize:7
width:0	 height:0
ok  (iRet  = 0)
iSliceSize:1
iSliceSize:251189
width:0	 height:0
ok  (iRet  = 0)
iSliceSize:1
iSliceSize:53494
width:0	 height:0
Decode status: layer lost at reference frame with temporal id 0
iSliceSize:1

**Comment by huili2** [comment]
The encoder parameters look good, and two output files will be generated. 
So Did you use the h264dec console binary, and which file did you feed into the decoder?

**Comment by toilandmoil** [comment]
> The encoder parameters look good, and two output files will be generated.
> So Did you use the h264dec console binary, and which file did you feed into the decoder?

Think you very much, I have solved this problem by reference the h264dec.
Now. I facing a new problem. The enhancement layer can decode separately.it does not need to rely on the data of base layer.In other worlds, each layer is independent on spatial scalability?

**Comment by huili2** [comment]
> > The encoder parameters look good, and two output files will be generated.
> > So Did you use the h264dec console binary, and which file did you feed into the decoder?
> 
> Think you very much, I have solved this problem by reference the h264dec.
> Now. I facing a new problem. The enhancement layer can decode separately.it does not need to rely on the data of base layer.In other worlds, each layer is independent on spatial scalability?

Yes. Currently spatial layers are independently encoded.

**Comment by toilandmoil** [comment]
> > > The encoder parameters look good, and two output files will be generated.
> > > So Did you use the h264dec console binary, and which file did you feed into the decoder?
> > 
> > 
> > Think you very much, I have solved this problem by reference the h264dec.
> > Now. I facing a new problem. The enhancement layer can decode separately.it does not need to rely on the data of base layer.In other worlds, each layer is independent on spatial scalability?
> 
> Yes. Currently spatial layers are independently svc

**Comment by toilandmoil** [comment]
> > > The encoder parameters look good, and two output files will be generated.
> > > So Did you use the h264dec console binary, and which file did you feed into the decoder?
> > 
> > 
> > Think you very much, I have solved this problem by reference the h264dec.
> > Now. I facing a new problem. The enhancement layer can decode separately.it does not need to rely on the data of base layer.In other worlds, each layer is independent on spatial scalability?
> 
> Yes. Currently spatial layers are independently encoded.

h264dec result shows that the enhancement layer (the enhancement in two  layer of spatial)data is larger than the single layer(spatial one layer).is this normal?if normal, what are the advantages of svc?
