### ISSUE TITLE
Converting Buffered Data to SSourcePicture

### ISSUE THREAD

**Issue by codelpech** [cisco/openh264#3258]
Hello,

I'm trying to decode and re-encode a 264 file. 
The decoding seems going well but there is a problem with my encoding. 
I'm not sure i'm doing right when i'm converting the decoding's output to the encoding input. 

Here is the code :

            Frame *frame; // frame not used 
            SBufferInfo *bufInfo;
            if(!DecodeFrame(
                    frame,
                    bufInfo,
                    pSvcDecoder,
                    pData,
                    buf[iBufIndex].data(),
                    buf[iBufIndex].Length())
                ){
                break;
            }

            SSourcePicture pic;
            memset (&pic, 0, sizeof (SSourcePicture));
            pic.iPicWidth = width;
            pic.iPicHeight = height;
            pic.iColorFormat = videoFormatI420;
            pic.iStride[0] = bufInfo->UsrData.sSystemBuffer.iStride[0];
            pic.iStride[1] = bufInfo->UsrData.sSystemBuffer.iStride[1];
            pic.iStride[2] = bufInfo->UsrData.sSystemBuffer.iStride[2];
            pic.pData[0] = bufInfo->pDst[0] ;//frame->y.data;
            pic.pData[1] = bufInfo->pDst[1];//pic.pData[0] + (width * height);
            pic.pData[2] = bufInfo->pDst[2];//pic.pData[1] + (width * height >> 2);
            pic.uiTimeStamp = bufInfo->uiInBsTimeStamp;

            __android_log_write(ANDROID_LOG_ERROR, "JNITEST", "Encoding a frame");
            rv = encoder_->EncodeFrame (&pic, &info);

            std::stringstream sstmDecodeStatus;
            sstmDecodeStatus << "Encode Status ";
            sstmDecodeStatus << rv ;
            __android_log_write(ANDROID_LOG_ERROR, "JNITEST", sstmDecodeStatus.str().c_str());

            if (info.eFrameType != videoFrameTypeSkip) {

                std::stringstream sstmiLayerNum;
                sstmiLayerNum << "info.iLayerNum ";
                sstmiLayerNum << info.iLayerNum;
                __android_log_write(ANDROID_LOG_ERROR, "JNITEST", sstmiLayerNum.str().c_str());

                for( int x = 0 ; x < info.iLayerNum; x++){
                    SLayerBSInfo layerInfo = info.sLayerInfo[x];
                    unsigned char* buffer = layerInfo.pBsBuf;
                    iLayerLen = 0;
                    for (int iNal = 0; iNal < layerInfo.iNalCount; ++iNal) {
                        iLayerLen += layerInfo.pNalLengthInByte[iNal];
                    }

                    std::stringstream sstmiLayerLen;
                    sstmiLayerLen << "iLayerLen ";
                    sstmiLayerLen << iLayerLen;
                    __android_log_write(ANDROID_LOG_ERROR, "JNITEST", sstmiLayerLen.str().c_str());

                    fwrite (buffer, iLayerLen, 1, destFile);
                }
                //output bitstream
            }

            __android_log_write(ANDROID_LOG_ERROR, "JNITEST", "Done decode");
            if (++iBufIndex >= 16) {
              iBufIndex = 0;
            }

**Comment by huili2** [comment]
there maybe something wrong with iLinesize[2]. Could you please try 
        pic.iStride[2] = bufInfo->UsrData.sSystemBuffer.iStride[1];
instead of
        pic.iStride[2] = bufInfo->UsrData.sSystemBuffer.iStride[2]; ?
and see if it works.

**Comment by codelpech** [comment]
It does not work, the encoding status is still 1. thanks anyway

**Comment by codelpech** [comment]
Ok now it works. I put the bad iUsageType. With CAMERA_VIDEO_REAL_TIME now it works.

        memset (&param, 0, sizeof (SEncParamBase));
        param.iUsageType = CAMERA_VIDEO_REAL_TIME;//INPUT_CONTENT_TYPE_ALL;//usageType;
        param.iRCMode    = RC_QUALITY_MODE;
