### ISSUE TITLE
[encoder_ext]set iMinQp to 0 would lead to unexpected QP changing

### ISSUE THREAD

**Issue by fulinjie** [cisco/openh264#3259]
While doing some integrations in FFmpeg, found that if either qmax or qmin is set to 0, unexpected QP changing would be observed.

Log:
Warning:Change QP Range from(0,51) to (12,42)

 if ((pCfg->iMaxQp <= 0) || (pCfg->iMinQp <= 0)) 

https://github.com/cisco/openh264/blob/master/codec/encoder/core/src/encoder_ext.cpp#L375

**Comment by huili2** [comment]
Yes. Although QP=0 is allowed in Rec, it is not well supported here. You may first try to not use QP=0.

**Comment by fulinjie** [comment]
hi @huili2 , thanks for the information.

I'd like to reduce the qp range to (1, 51):
https://github.com/intel-media-ci/ffmpeg/pull/188

**Comment by fulinjie** [comment]
Filed a PR to change the the verbosity level in case we ran into this warning all the time for qp = 0:
https://github.com/cisco/openh264/pull/3278
