### ISSUE TITLE
ABI breakage in OpenH264 2.1.0

### ISSUE THREAD

**Issue by mcatanzaro** [cisco/openh264#3264]
OpenH264 2.1.0 has the same ABI version (soname) as 2.0.0, so there should not have been any ABI changes in this release. However, bbcc2cb202d01767d42aa2b545735342e82f281f changed the size of SBufferInfo. This is a problem because SBufferInfo is public ABI and [it's allocated on the stack in gst_openh264dec_handle_frame](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/blob/12ff0a47979699be25b9657add90350479cc8fb9/ext/openh264/gstopenh264dec.cpp#L247). (Credit to Seppo Yli-Olli and Nicolas Dufresne for debugging this.)

Anyway, using OpenH264 2.1.0 with applications built against 2.0.0 results in crashes. Either the ABI changes should be reverted, or the ABI version should be bumped. A corrected release would be appreciated regardless.

I will prepare a PR to bump the ABI version.

**Comment by nanonyme** [comment]
Note that while the adding at the end of struct seems innocent, that struct is used as a member in this other struct https://github.com/cisco/openh264/blob/82687cca2b22879163632d2ac91d48f91230cf66/codec/decoder/core/inc/decoder_context.h#L283-L289 so that ABI break is *very* severe. Please handle asap.

**Comment by mcatanzaro** [comment]
> Note that while the adding at the end of struct seems innocent, that struct is used as a member in this other struct

It's stack-allocated public API. Nothing innocent about it. :(

**Comment by nanonyme** [comment]
Well, yes, that. The struct is also used in a way in pretty much all OpenH264 consumers that changing it is likely to break things. (allocation from stack)
