### ISSUE TITLE
decode temporal layers together

### ISSUE THREAD

**Issue by mdasari823** [cisco/openh264#3268]
Looks like the spatial layers are currently independent. But the temporal layers have inter layer dependency right? So, I encoded my video just by using temporal layers using the below command. 

`./h264enc -utype 0 -org akiyo_cif.yuv -numl 3 -numtl 1 -frin 30 -frout 0 30 -frout 1 30 -frout 2 30 -sw 352 -sh 288 -rc -1 -lqp 0 24 -lqp 1 24 -lqp 2 24 -iper 0 -bf OUTPUT.264 -mfile 1`

I was wondering if the h264dec supports decoding these temporal layers in dependent manner. I mean can I take advantage of SVC with these layers? Or still not supported?

**Comment by huili2** [comment]
Sorry for late reply.
temporal layers are fully supported in openh264 encoder/decoder, by temporal number (in your example, it is 1). Higher temporal layers could be dropped without affecting lower temporal layers' decoding. But you need drop the data by yourself.
BTW, temporal inter-layer dependency are always used in the encoder (if IDR period is not 1).
