### ISSUE TITLE
Does encoding uses GPU or it is software based only?

### ISSUE THREAD

**Issue by bobj1212** [cisco/openh264#3270]
Does encoding uses GPU or it is software based only?
If GPU then how to enable it?
If software then are there any planing for GPU acceleration?when?

Thanks

**Comment by huili2** [comment]
It is software based only. Till now, there's no plan to enable HW acceleration.

**Comment by bobj1212** [comment]
Thanks for answer.
Can you if possible explain what is the reason not to add HW acceleration

**Comment by huili2** [comment]
There's not enough resource on this. And it is not easy to maintain the HW acceleration for different platforms as well as device providers.
