### ISSUE TITLE
screen content LTR losslesslink

### ISSUE THREAD

**Issue by Allen1207** [cisco/openh264#3274]
Hi experts,

I understand the LTR function in camera video usage, e.g, the encoder can mark the LTR in a period, and confirm it is received by decoder through the network feedback, and encode a P frame using the confirmed LTR as reference when receive a LTR recovery request.
but I find for screen content input, the LTR is disabled if the losslesslink==0. Could you please tell me what is the "losslesslink" mean?  what is the difference between screen content and camera video for LTR usage ?

**Comment by huili2** [comment]
As the name indicates, "losslesslink" means the application channel is error free, and no data loss occurs.
LTR is not well supported in screen type, so it is closed.

**Comment by Allen1207** [comment]
Thanks, I also studied the screen LTR strategy, it is interesting:
1. in all 5 refs, all refs are LTR
2. if scene change is detected for one picture, then it is marked as scene LTR
3. in scene change detection preprocess, select one best LTR as ref. Scene change pic can only use scene LTR as ref.
4. after encode one picture, set it as LTR (if it is not non-ref), and remove one LTR (if numLTR is full)
