### ISSUE TITLE
Encode sequence of jpg files into h264 sequence

### ISSUE THREAD

**Issue by CatsNipYummy** [cisco/openh264#3279]
I use the ./h264enc code to read a series of jpg, frame by frame, and then I encode it to h264 and I am trying to stream it using WebRTC. The issue I think what is happening is that each h264 does not know any details of the NAL components of the previous nor the next frame. Due to which my stream is failing. Is there a way to pass this information around while encoding?

**Comment by huili2** [comment]
From the Rec, there should be less dependency among NALs, except these common syntax elements in SPS/PPS/Slice_header, etc. And what kind of information is needed in your case? Seems it is not in the scope of a video encoder.
