### ISSUE TITLE
Decode and Encode H264 High Profile (AVC)

### ISSUE THREAD

**Issue by hgulamabbass** [cisco/openh264#3280]
Hi There,

Apologies if this is already answered but I cannot see any recent update of my question that's why I ask.

I am working on a project that needs to decode and encode H264 High Profile AVC, can you please confirm if the library will support this? I compiled the code in windows and tried using the decoder and tried to decode a h264 file that plays on VLC and MPC-HC Player but this is the error that I get

decConsoled.exe Video.h264 foo.avi

H264 source file name: .\Video.h264..
Sequence output file name: foo.avi..
------------------------------------------------------
[OpenH264] this = 0x006DCD58, Warning:referencing pictures lost due frame gaps exist, prev_frame_num: 0, curr_frame_num: 2
[OpenH264] this = 0x006DCD58, Warning:WelsDecodeMbCavlcISlice()::::pBs incomplete, iUsedBits:83102 > pBs->iBits:83068, MUST stop decoding.
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (468772) in frame: 10 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459805) in frame: 0 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:referencing pictures lost due frame gaps exist, prev_frame_num: 10, curr_frame_num: 1
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459793) in frame: 1 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459793) in frame: 2 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459789) in frame: 3 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459807) in frame: 4 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459793) in frame: 5 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459806) in frame: 6 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459807) in frame: 7 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459793) in frame: 8 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459807) in frame: 9 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459793) in frame: 10 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:WelsDecodeMbCavlcISlice()::::pBs incomplete, iUsedBits:83127 > pBs->iBits:83070, MUST stop decoding.
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (468772) in frame: 10 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459805) in frame: 0 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:referencing pictures lost due frame gaps exist, prev_frame_num: 10, curr_frame_num: 1
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459793) in frame: 1 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459793) in frame: 2 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459781) in frame: 3 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459805) in frame: 4 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459806) in frame: 5 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459805) in frame: 6 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:referencing pictures lost due frame gaps exist, prev_frame_num: 5, curr_frame_num: 7
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459805) in frame: 7 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:referencing pictures lost due frame gaps exist, prev_frame_num: 5, curr_frame_num: 8
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459805) in frame: 8 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:referencing pictures lost due frame gaps exist, prev_frame_num: 5, curr_frame_num: 9
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459789) in frame: 9 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459781) in frame: 10 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (12) in frame: 10 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459805) in frame: 0 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:referencing pictures lost due frame gaps exist, prev_frame_num: 10, curr_frame_num: 1
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459789) in frame: 1 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459805) in frame: 2 uiDId: 0 uiQId: 0
[OpenH264] this = 0x006DCD58, Warning:DecodeCurrentAccessUnit() failed (459789) in frame: 3 uiDId: 0 uiQId: 0
-------------------------------------------------------
iWidth:         720
height:         1280
Frames:         63
decode time:    1.036677 sec
FPS:            60.771098 fps
-------------------------------------------------------

1.) What file output would the decConsoled.exe generate?
2.) Does it throw warnings because the High Profile AVC is not supported?

I would appreciate any help.

**Comment by huili2** [comment]
1) YUV 4:2:0 format is generated in decoder.
2) part of High Profile tools are supported. So decoder will not directly throw error unless it meets with what it does not actually support.
3) From the log, it shows your input file has picture loss. Is it in your expectation?

**Comment by sijchen** [comment]
is multithreading decoding turned ON in this case? 

if yes, do you still have the same problem when multi-threading decoding is OFF?

Note that in 2.1.0 release notes, we already stated that the support for multi-thread decoding is experimental. There can be unsolved problems when it is turned ON.
