### ISSUE TITLE
RC_BITRATE_MODE vs RC_QUALITY_MODE

### ISSUE THREAD

**Issue by bobj1212** [cisco/openh264#3284]
Hi
What is the difference between RC_BITRATE_MODE vs RC_QUALITY_MODE
I do not see much of a change when using one over the other i see almost same bandwidth is used in both.
My target using the openh264 is to capture the screen and send it to another location just like remote desktop software and I am not so sure which one is better to use.

**Comment by huili2** [comment]
There's minor difference between them, and for your case, either can do.

**Comment by bobj1212** [comment]
Thank you Huili
And same question for CAMERA_VIDEO_REAL_TIME vs SCREEN_CONTENT_REAL_TIME
Can you please explain the difference between the two.
I did noticed that CAMERA_VIDEO_REAL_TIME gives better image quality than SCREEN_CONTENT_REAL_TIME (under same settings)
And also as result the stream bandwidth is almost twice as big using CAMERA_VIDEO_REAL_TIME.
So if I want better image quality then i should use CAMERA_VIDEO_REAL_TIME  and if i want less bandwidth i should use SCREEN_CONTENT_REAL_TIME?
Or there are more expects to that.
