### ISSUE TITLE
Executables

### ISSUE THREAD

**Issue by msalai** [cisco/openh264#3287]
Can anyone upload compiled executable files of encoder, decoder or perhaps some player so I can test this codec without compiling by myself?

Another question is can decoder decode h264 video generated by Microsoft Media Foundation API?

**Comment by huili2** [comment]
For executable files, we would not provide them formally. Looking forward other guys' help on this.
For second question, current openh264 decoder supports Constrained High Profile. If the data from MF conform to that, everything should be OK.
