### ISSUE TITLE
Are there plans to provide pre-built OpenH264 binaries for Arm64 / aarch64 Linux?

### ISSUE THREAD

**Issue by JeffUnderhill** [cisco/openh264#3309]
There's already support for Arm64 + Neon and aarch64 binary releases for [Android & iOS](https://github.com/cisco/openh264/blob/master/RELEASES), the Mozilla folks have built aarch64 for [Windows 10 on Arm](https://bugzilla.mozilla.org/show_bug.cgi?id=1515210). Are there plans to offer Linux aarch64 binaries?

If not are there specific blockers that need to be addressed to enable the generation of aarch64 Linux binaries?

**Comment by sijchen** [comment]
could you suggest the desired building instructions to get this binary? thx

**Comment by JeffUnderhill** [comment]
I believe the build flags all exist and if you build on an Arm64 platform it will generate the appropriate binary. This should be possible by adding an Arm64 build to the TravisCI job using their Alpha feature that provides multi-architecture builds for open source projects - see: [Building on Multiple CPU Architectures](https://docs.travis-ci.com/user/multi-cpu-architectures/)

**Comment by AGSaidi** [comment]
@sijchen I had no problem building the project on an [Graviton2](https://aws.amazon.com/ec2/graviton/) instance simply by running make after installing the required dependencies on Ubuntu 16.04 Xenial and a shared-object like you [release for x86](http://ciscobinary.openh264.org/libopenh264-2.1.1-linux64.6.so.bz2) was created.  I assume it would also build on newer versions of Ubuntu, but haven't tried. 

All the unit tests also passed along with binary comparisons on Adobe_PDF_sample_a_1024x768_50Frms and BA_MW_D.264. The binary comparison on Zhling_1280x720.264 seems to be failing.

**Comment by ccooksey** [comment]
I have a keen interest in the outcome of this effort. I can help with testing the binaries.

**Comment by JeffUnderhill** [comment]
@sijchen Any updates from your debug of the unit test failure mentioned above?

**Comment by JeffUnderhill** [comment]
This issue has been resolved and Arm64 Linux binaries are now available as of the v2.1.1 release - see: https://github.com/cisco/openh264/releases/tag/v2.1.1
