### ISSUE TITLE
Not able to Build

### ISSUE THREAD

**Issue by AVMACHINE2** [cisco/openh264#3310]
Build type: native build
Project name: openh264
Project version: 2.1.1
C compiler for the host machine: gcc (gcc 9.2.0 "gcc (MinGW.org GCC Build-20200227-1) 9.2.0")
C linker for the host machine: gcc ld.bfd 2.32
C++ compiler for the host machine: c++ (gcc 9.2.0 "c++ (MinGW.org GCC Build-20200227-1) 9.2.0")
C++ linker for the host machine: c++ ld.bfd 2.32
Host machine cpu family: x86
Host machine cpu: x86
Program nasm found: YES (C:\Users\amitv\AppData\Local\bin\NASM\nasm.EXE)
Compiler for C++ supports arguments -Wno-non-virtual-dtor -Wnon-virtual-dtor: YES
Compiler for C++ supports arguments -Wno-class-memaccess -Wclass-memaccess: YES
Compiler for C++ supports arguments -Wno-strict-aliasing -Wstrict-aliasing: YES
Run-time dependency threads found: YES
Did not find pkg-config by name 'pkg-config'
Found Pkg-config: NO
Run-time dependency GTest found: NO (tried pkgconfig and system)
Looking for a fallback subproject for the dependency gtest

test\meson.build:2:2: ERROR: Git program not found.

**Comment by huili2** [comment]
could you please give more detailed information about the build issue, e.g., platform, environment?

**Comment by LQliuqin** [comment]
How is this problem solved?

**Comment by eli-schwartz** [comment]
I don't understand this issue, since git isn't used anywhere in test/meson.build and that line points to a subproject wrap: subprojects/gtest.wrap uses https urls to download, not git.
