### ISSUE TITLE
Compilation on Cygwin

### ISSUE THREAD

**Issue by JohnnyErnest** [cisco/openh264#3311]
<img width="960" alt="OpenH264Error" src="https://user-images.githubusercontent.com/25945156/87503036-d0112f00-c628-11ea-91ae-fed87a9daddb.png">

Here's a screenshot of the error, just simply used the make command in cygwin. It is using x86_64-pc-cygwin-g++ as expected, have nasm and yasm installed on machine, Windows 10. Any ideas?

**Comment by huili2** [comment]
cygwin is not formally supported, from the document. 
could you please try mingw?

**Comment by GuangweiWang** [comment]
@JohnnyErnest 
if has no update, this issue will be closed.
