### ISSUE TITLE
SEncoderStatistics.uiAverageFrameQP always return 0 when get the encoder stats

### ISSUE THREAD

**Issue by mypopydev** [cisco/openh264#3317]
SEncoderStatistics.uiAverageFrameQP  always return 0 when get the encoder stats with option ENCODER_OPTION_GET_STATISTICS

**Comment by huili2** [comment]
any detailed case for this issue? Actually If the encoder is called properly, and encoding is just in the process, the return value should be true.

**Comment by mypopydev** [comment]
I think uiAverageFrameQP means  Average Frame QP base on Frame, but openh264enc just return 0 now

**Comment by huili2** [comment]
your guess is right. But it is strange that it returns 0. Any more details on how it occurs?

**Comment by Allen1207** [comment]
that because the uiAverageFrameQP is not assigned when GetOption ENCODER_OPTION_GET_STATISTICS. You can add the following bold line to solve it:
`case ENCODER_OPTION_GET_STATISTICS: {
    SEncoderStatistics* pStatistics = (static_cast<SEncoderStatistics*> (pOption));
    SEncoderStatistics* pEncStatistics = &m_pEncContext->sEncoderStatistics[m_pEncContext->pSvcParam->iSpatialLayerNum - 1];
    pStatistics->uiWidth = pEncStatistics->uiWidth;
    pStatistics->uiHeight = pEncStatistics->uiHeight;
    pStatistics->fAverageFrameSpeedInMs = pEncStatistics->fAverageFrameSpeedInMs;
    pStatistics->sEncMv = pEncStatistics->sEncMv;

    // rate control related
    pStatistics->fAverageFrameRate = pEncStatistics->fAverageFrameRate;
    pStatistics->fLatestFrameRate = pEncStatistics->fLatestFrameRate;
    pStatistics->uiBitRate = pEncStatistics->uiBitRate;
    **pStatistics->uiAverageFrameQP = pEncStatistics->uiAverageFrameQP;**

    pStatistics->uiInputFrameCount = pEncStatistics->uiInputFrameCount;
    pStatistics->uiSkippedFrameCount = pEncStatistics->uiSkippedFrameCount;

    pStatistics->uiResolutionChangeTimes = pEncStatistics->uiResolutionChangeTimes;
    pStatistics->uiIDRReqNum = pEncStatistics->uiIDRReqNum;
    pStatistics->uiIDRSentNum = pEncStatistics->uiIDRSentNum;
    pStatistics->uiLTRSentNum = pEncStatistics->uiLTRSentNum;
  }`

**Comment by mypopydev** [comment]
Will try this patch, thx

**Comment by mypopydev** [comment]
@huili2 can you try Allen1207's patch for this issue

**Comment by huili2** [comment]
I do not have code at hand, but from above code lines, I think it should be OK.
