### ISSUE TITLE
Linking Binaries on Windows - how to import the functions?

### ISSUE THREAD

**Issue by AlpinChisholm** [cisco/openh264#3329]
Is there an easy way to link to the functions such as WelsCreateDecoder() on windows? I know I can use LoadLibrary but surely there is an easier way. Is there a reason you did not just include an IMPLIB with the DLLs in the binaries distribution?

**Comment by huili2** [comment]
You'd better get help from other societies for better solution, as it is not concerned with openh264 only.
We recommended to use LoadLibrary(), as it is a conventional method from Microsoft.

**Comment by pabloko** [comment]
see #3307 on how to edit your header, im usually static linking it anyway.
