### ISSUE TITLE
IDR Frames freeze WebRTC stream 

### ISSUE THREAD

**Issue by NoOverflow** [cisco/openh264#3344]
Hi, I'm using a .net C++ / CLI around OpenH264 DLL and I've noticed a strange issue.

The stream starts fine, but when the encoder generates IDR frames, the stream freezes. It then resumes when I send another set of IDR frames, and the process repeats indefinitely.

Do you have any idea on what could cause that / troubleshoots ? Thanks

(Edit 1: I've tried with another wrapper and the same issue occurred, so I made my own one and same issue again.
The problem is not coming from I webrtc library because I used x264 and it worked fine)

**Comment by rogerzhou-github** [comment]
Is there any packet loss? It could be a bug of jitter buffer of webrtc.

**Comment by NoOverflow** [comment]
> Is there any packet loss? It could be a bug of jitter buffer of webrtc.  

I'm gonna double check, I doubt so, I'm sending the frames to a browser on localhost. Right now I'm stuck forcing key frames, it works but it's ugly.

**Comment by huili2** [comment]
Any update on this? If no, this will be closed.

**Comment by NoOverflow** [comment]
> Any update on this? If no, this will be closed.

Hi, yes this issue was fixed a long time ago and it was indeed coming from the library I was using. Forgot I had opened a ticket here, you can close it.

**Comment by huili2** [comment]
good to know.
