### ISSUE TITLE
Seeking in stream works with IDR frames only

### ISSUE THREAD

**Issue by stransky** [cisco/openh264#3350]
When OpenH264 is used for youtube playback in Firefox and the stream position is moved, decoding fails if it starts on non IDR I-frame. When decoding starts on IDR frame the stream is decoded correctly.

Mozilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1670333

**Comment by huili2** [comment]
Sorry for too late response. Openh264 does not support I-frame decoding as IDR.

**Comment by Conan-Kudo** [comment]
Could support for this be added to OpenH264?
