### ISSUE TITLE
Apple CPU M1 Arch arm64 compilation issue

### ISSUE THREAD

**Issue by grijon** [cisco/openh264#3353]
There are new Apple M1 CPU with ARCH arm64 for system darwin.

I can't compile it with 
make OS=darwinn ARCH=arm64

It finished with errors in neon files
If i remove -DHAVE_NEON_AARCH64  in mk files it will be compiled in x86_64 arch

**Comment by vova1914** [comment]
adding platform-macos.mk :
ARCH = armv7
include $(SRC_PATH)build/platform-darwin.mk
CXX = clang++
CC = clang
SDKTYPE = MacOSX
SDK_MIN = 10.11

SDKROOT := $(shell xcrun --sdk $(shell echo $(SDKTYPE) | tr A-Z a-z) --show-sdk-path)
CFLAGS += -arch $(ARCH) -isysroot $(SDKROOT) -mmacosx-version-min=$(SDK_MIN) -DAPPLE_MAC -fembed-bitcode
LDFLAGS += -arch $(ARCH) -isysroot $(SDKROOT) -mmacosx-version-min=$(SDK_MIN)

and run it with "make OS=macos ARCH=arm64" or "make OS=macos ARCH=x86_64"
I'm not sure... correct me

**Comment by grijon** [comment]
not enough

**Comment by grijon** [comment]
I have compiled it after next changes:

1. Create platform-macos.mk :
ARCH = arm64
include $(SRC_PATH)build/platform-darwin.mk
CXX = clang++
CC = clang
SDKTYPE = MacOSX
SDK_MIN = 10.11

SDKROOT := $(shell xcrun --sdk $(shell echo $(SDKTYPE) | tr A-Z a-z) --show-sdk-path)
CFLAGS += -arch $(ARCH) -isysroot $(SDKROOT) -mmacosx-version-min=$(SDK_MIN) -DAPPLE_OSX -fembed-bitcode
LDFLAGS += -arch $(ARCH) -isysroot $(SDKROOT) -mmacosx-version-min=$(SDK_MIN)

2. change next line in Makefile
OS=$(shell uname | tr A-Z a-z | tr -d \\-0-9. | sed -E 's/^(net|open|free)bsd/bsd/')
to 
OS=macos

compile with 
make OSX=macos ARCH=arm64
make OSX=macos ARCH=x86_64

**Comment by GuangweiWang** [comment]
@grijon 
your command line is : make OS=darwinn ARCH=arm64
"darwinn" may be a typo. please use darwin instead. 

In fact, you can make directly. build script can detect OS and ARCH automatically

**Comment by enginespot** [comment]
> @grijon
> your command line is : make OS=darwinn ARCH=arm64
> "darwinn" may be a typo. please use darwin instead.
> 
> In fact, you can make directly. build script can detect OS and ARCH automatically

with apple m1 arch ,  you can compile by two commands

```
arch -arm64  brew install nasm
make
```

**Comment by GuangweiWang** [comment]
@grijon 
has this issue been resolved now?

**Comment by grijon** [comment]
@GuangweiWang 
Yes, now it's compiling correctly without any additional changes. I have download sources and compile it for arm64 with next command
make OS=darwin ARCH=arm64

You could check architecture of library with next command 
lipo -info libname.a

**Comment by GuangweiWang** [comment]
@grijon please checkout the latest master code.
