### ISSUE TITLE
what does wels mean?

### ISSUE THREAD

**Issue by sshsu** [cisco/openh264#3383]
really curious about it

**Comment by sshsu** [comment]
and I find little document about openh264, where can I get some document or reference? and I don't know how to generate doxygen correctly, it tells  lack of files
```
 ⚡ root@ubuntu  ~/git/openh264/docs   master  python doxygen2rst.py 
Traceback (most recent call last):
  File "doxygen2rst.py", line 618, in <module>
    github_ext = ext)
  File "doxygen2rst.py", line 65, in __init__
    self.index_root = etree.parse(os.path.join(self.doxy_output_dir, "index.xml")).getroot()
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
IOError: Error reading file 'doxygen/_doxygen/xml/index.xml': failed to load external entity "doxygen/_doxygen/xml/index.xml"
```

**Comment by sshsu** [comment]
> and I find little document about openh264, where can I get some document or reference? and I don't know how to generate doxygen correctly, it tells lack of files
> 
> ```
>  ⚡ root@ubuntu  ~/git/openh264/docs   master  python doxygen2rst.py 
> Traceback (most recent call last):
>   File "doxygen2rst.py", line 618, in <module>
>     github_ext = ext)
>   File "doxygen2rst.py", line 65, in __init__
>     self.index_root = etree.parse(os.path.join(self.doxy_output_dir, "index.xml")).getroot()
>   File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
>   File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
>   File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
>   File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
>   File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
>   File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
>   File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
>   File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
> IOError: Error reading file 'doxygen/_doxygen/xml/index.xml': failed to load external entity "doxygen/_doxygen/xml/index.xml"
> ```

ok, I have find lots of document in repo wiki

**Comment by vacing** [comment]
> > and I find little document about openh264, where can I get some document or reference? and I don't know how to generate doxygen correctly, it tells lack of files
> > ```
> >  ⚡ root@ubuntu  ~/git/openh264/docs   master  python doxygen2rst.py 
> > Traceback (most recent call last):
> >   File "doxygen2rst.py", line 618, in <module>
> >     github_ext = ext)
> >   File "doxygen2rst.py", line 65, in __init__
> >     self.index_root = etree.parse(os.path.join(self.doxy_output_dir, "index.xml")).getroot()
> >   File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
> >   File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
> >   File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
> >   File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
> >   File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
> >   File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
> >   File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
> >   File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
> > IOError: Error reading file 'doxygen/_doxygen/xml/index.xml': failed to load external entity "doxygen/_doxygen/xml/index.xml"
> > ```
> 
> ok, I have find lots of document in repo wiki

where did you find them, can you give a link here, thanks : )

**Comment by kanzhu-cisco** [comment]
"wels" is our project name, which has no practical meaning :)
