### ISSUE TITLE
How to use multiple output buffers when encoding

### ISSUE THREAD

**Issue by kuzux** [cisco/openh264#3386]
When we call `EncodeFrame` and then retrieve the encoded video info (by calling `info.sLayerInfo[last].pBsBuf`), I believe the buffer we receive is a pre-allocated internal buffer (of a pre-determined size). And when we call the same function again, that buffer is reused and the encoded data within it overwritten.

That causes some issues with multithreading (when using an encoder thread to write the data to a buffer and another output thread to read that data and output it) and sometimes the output thread lags behind and misses a frame. I want to use a few output buffers for that reason (Say, have openh24 output to bufs[0] in one frame and bufs[1] the next frame and then go back) - so that the lagging thread can catch up.

Does this make sense? Is it possible? If yes, how?

**Comment by kanzhu-cisco** [comment]
We don't support multiple output buffers for now.

**Comment by huili2** [comment]
Close this one since no response from asker.
