### ISSUE TITLE
How to carry temporal layer information in the nalu stream?

### ISSUE THREAD

**Issue by WeilWei** [cisco/openh264#3396]
I want to get single spatial layer with multi-temporal layers from one encode stream.
sParam->bSimulcastAVC = false;
sParam->iTemporalLayerNum = 2;
sParam->iSpatialLayerNum = 1;

In the following function of the src file openh264\src\codec\encoder\core\src\encoder_ext.cpp
int32_t WelsEncoderEncodeExt (sWelsEncCtx* pCtx, SFrameBSInfo* pFbi, const SSourcePicture* pSrcPic)
{   ......
    //3603
    bAvcBased = ((pSvcParam->bSimulcastAVC) || (iCurDid == BASE_DEPENDENCY_ID));
    pCtx->bNeedPrefixNalFlag    = ((!pSvcParam->bSimulcastAVC) && (bAvcBased &&
                                   (pSvcParam->bPrefixNalAddingCtrl ||
                                    (pSvcParam->iSpatialLayerNum > 1))));
    if (eFrameType == videoFrameTypeP) {
      eNalType = bAvcBased ? NAL_UNIT_CODED_SLICE : NAL_UNIT_CODED_SLICE_EXT; //nal 1 : nal 20
    } else if (eFrameType == videoFrameTypeIDR) {
      eNalType = bAvcBased ? NAL_UNIT_CODED_SLICE_IDR : NAL_UNIT_CODED_SLICE_EXT;
    }
    ... ...
}
it means only high spacial layer can use nat unit type 20 (NAL_UNIT_CODED_SLICE_EXT), 
while hight temporal layer can't use it.
In T-REC-H.264-201906-I!!PDF-E.pdf
if( nal_unit_type = = 14 | | nal_unit_type = = 20  | | nal_unit_type = =  21 ) {
  if( svc_extension_flag ) {
    nal_unit_header_svc_extension( )
  }
}
Only in nal_unit_header_svc_extension( ), there is syntax temporal_id filed.
So temporal high layer's nalu stream can't carry temporal layer information.
Is it right? 
Then how to carry temporal layer information in the nalu stream?

**Comment by kanzhu-cisco** [comment]
if( nal_unit_type = = 14 | | nal_unit_type = = 20 | | nal_unit_type = = 21 ) {
if( nal_unit_type ! = 21 )
    svc_extension_flag
else
    avc_3d_extension_flag
}
When iCurDid > 0, the nal_unit_type will be 20, and svc_extension_flag will be true.

**Comment by huili2** [comment]
Close this one since no response from asker.
