### ISSUE TITLE
setting sps->direct_8x8_inference_flag doesn't take level into account

### ISSUE THREAD

**Issue by vacing** [cisco/openh264#3401]
According to Rec. ITU-T H.264 (10/2016) A3.3.2 A-4, `direct_8x8_inference_flag` should be 1 when level beyond or equal 3, but all set to 0 now.

**Comment by sijchen** [comment]
thank you for the input! Rec. ITU-T H.264 (10/2016) A3.3.2 A-4, is only for Main .... Profile, should we add a profile check in PR#3404 ? thank you

**Comment by vacing** [comment]
more discussion at #3404
