### ISSUE TITLE
openh264-2.1.1-win64.dll has not been signed

### ISSUE THREAD

**Issue by ncatlin** [cisco/openh264#3409]
There is no digital signature on the binary and no .sig to check it with either

**Comment by GuangweiWang** [comment]
.dll file has no extra .sig, the signature is include in the .dll file. please right click the .dll and open Properties to check the copyright. thanks.

**Comment by ncatlin** [comment]
It's not in the DLL:
![win64.dll](https://user-images.githubusercontent.com/5470374/131473486-d1035068-9d47-4a78-ba1f-01c81512929d.png)

vs the 32 bit dll that is signed:

![image](https://user-images.githubusercontent.com/5470374/131473601-7f9111de-62af-4802-b28c-31b013d22437.png)

**Comment by GuangweiWang** [comment]
thanks. will fix this later

**Comment by leejeonghun** [comment]
@GuangweiWang I would like to ask when the digital signature will be fixed?

**Comment by GuangweiWang** [comment]
@leejeonghun will update soon.

**Comment by GuangweiWang** [comment]
this library has been updated. please check.

**Comment by leejeonghun** [comment]
In the properties tab, I confirmed that [openh264-2.2.0-win64.dll](http://ciscobinary.openh264.org/openh264-2.2.0-win64.dll.bz2) has a valid signature. Thank you!

**Comment by ncatlin** [comment]
Fixed, thankyou
