### ISSUE TITLE
builds successfully on ppc64el, add to supported architectures?

### ISSUE THREAD

**Issue by dpocock** [cisco/openh264#3413]
I made a build on a [Talos II POWER9](https://danielpocock.com/talos-II-quickstart/) workstation:

```
$ make OS=linux ARCH=ppc64el
...
$ ldd libopenh264.so
	linux-vdso64.so.1 (0x00003fffb3950000)
	libpthread.so.0 => /lib/powerpc64le-linux-gnu/libpthread.so.0 (0x00003fffb3725000)
	libstdc++.so.6 => /lib/powerpc64le-linux-gnu/libstdc++.so.6 (0x00003fffb34af000)
	libm.so.6 => /lib/powerpc64le-linux-gnu/libm.so.6 (0x00003fffb338e000)
	libgcc_s.so.1 => /lib/powerpc64le-linux-gnu/libgcc_s.so.1 (0x00003fffb335d000)
	libc.so.6 => /lib/powerpc64le-linux-gnu/libc.so.6 (0x00003fffb3147000)
	/lib64/ld64.so.2 (0x00003fffb3955000)
```

Would you be happy to include ```ppc64el``` in the README.md?

Would you consider publishing a ```ppc64el``` binary in the [official releases page](https://github.com/cisco/openh264/releases)?

**Comment by GuangweiWang** [comment]
as I know, ppc64el is a architecture for PowerPC, and is different from i386/x86_64/arm/arm64/mips ...
it it right?

if yes, the openh264 does not support SIMD optimization for ppc64el, just support C/C++ functions. so it is not recommend to publish a ppc64el binary. 
if you need this support for other special reasons, please let me know. thanks.

**Comment by dpocock** [comment]
It looks like [each architecture with optimization is listed here](https://github.com/cisco/openh264/blob/master/codec/processing/src/arm64/vaa_calc_aarch64_neon.S)

OpenPOWER (PPC64, etc) is not listed there

Maybe it is a good idea to keep two lists:

- architectures where it is optimized (x86, ARM, ARM64, etc)
- architectures where it is verified to be working but not yet optimized

**Comment by GuangweiWang** [comment]
will update this part in README later. thanks.
