### ISSUE TITLE
Dangling commits on v2.1.0 branch

### ISSUE THREAD

**Issue by ade** [cisco/openh264#3416]
There are dangling commits on branch: **openh264v2.1.0** that are not included in neither of 2.1.0 or 2.1.1 releases.

For example, the code in https://github.com/cisco/openh264/pull/3261

Please merge this code properly to releases

**Comment by kanzhu-cisco** [comment]
From history log, the #3261 already merged to cisco:openh264v2.1.0

**Comment by GuangweiWang** [comment]
it should be on master now. 
The master contains all the commits

**Comment by act262** [comment]
@GuangweiWang this commit not merge into master, is any idea?

**Comment by GuangweiWang** [comment]
PR #3599 will merge PR #3261 to master.

**Comment by GuangweiWang** [comment]
has been meerged now.
