### ISSUE TITLE
potential overflow 

### ISSUE THREAD

**Issue by autofuzzoss** [cisco/openh264#3426]
A bug was found within the openh264. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using openh264. It would be best if the affected logic is checked beforehand. 
The bug was found with a fuzzer based on the function "WelsDeblockingMb" This is probably like a global-buffer-overflow bugs

Steps to reproduce:
1. git clone https://github.com/cisco/openh264.git
2. cd openh264
3. make CC=/bin/clang CXX=/bin/clang++ CFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link" CXXFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link -fPIC" LDFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link" LD=/bin/clang++ AR=/usr/lib/llvm-10/bin/llvm-ar USE_ASM=No BUILDTYPE=Debug OS=linux ARCH=x86_64 libraries
4. Download the attached file(1.cpp)
5. Build TEST CODE (1.cpp)
   clang++ -g -fsanitize=address,fuzzer-no-link -o 1 1.cpp  -I openh264/ -I openh264/codec/common/inc/  -I openh264/codec/api/svc/ -I openh264/codec/encoder/core/inc/  -I openh264/codec/processing/interface/ -I openh264/test -I openh264/test/encoder -Lopenh264 -lopenh264
6. Run
   LD_LIBRARY_PATH=openh264/ ./1
   
Browser/OS: ubuntu 18.04
[openh264_poc1.tar.gz](https://github.com/cisco/openh264/files/7256533/openh264_poc1.tar.gz)

**Comment by GuangweiWang** [comment]
the same as issue #3427 and  #3428
