### ISSUE TITLE
potential overflow by null-dereference pointer

### ISSUE THREAD

**Issue by autofuzzoss** [cisco/openh264#3428]
A bug was found within the openh264. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using openh264. It would be best if the affected logic is checked beforehand. 
The bug was found with a fuzzer based on the test-code "ExtendLayerBufferTest" 

Steps to reproduce:
1. git clone https://github.com/cisco/openh264.git
2. Download the attached file(EncUT_SliceBufferReallocate.cpp)
3. cp EncUT_SliceBufferReallocate.cpp openh264/test/encoder/.
4. cd openh264
5. make CC=/bin/clang CXX=/bin/clang++ CFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link" CXXFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link -fPIC" LDFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link" LD=/bin/clang++ AR=/usr/lib/llvm-10/bin/llvm-ar USE_ASM=No BUILDTYPE=Debug OS=linux ARCH=x86_64 libraries
6. make CC=/bin/clang CXX=/bin/clang++ CFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link" CXXFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link -fPIC" LDFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link" LD=/bin/clang++ AR=/usr/lib/llvm-10/bin/llvm-ar USE_ASM=No BUILDTYPE=Debug OS=linux ARCH=x86_64 test
7. Run
   ./codec_unittest --gtest_filter=CSliceBufferReallocatTest.ExtendLayerBufferTest

 Browser/OS: ubuntu 18.04
[openh264_poc3.tar.gz](https://github.com/cisco/openh264/files/7256575/openh264_poc3.tar.gz)

**Comment by GuangweiWang** [comment]
-2147483644 is illegal value for pCtx->pSvcParam->iSpatialLayerNum. I don't think it is meaningful to set the iSpatialLayerNum as this number directly.
