### ISSUE TITLE
Static image encoding

### ISSUE THREAD

**Issue by OmnomnomCat** [cisco/openh264#3429]
I'm trying to encode static image (yuv420 single frame) with openh264 (and stream it with live555 library), but getting only black screen into vlc. With dynamic scenes my code works correctly. I've tried to reset `bEnableFrameSkip` flag, but it works only after stream restart. Does anybody has the same problem or any ideas?

**Comment by mfeia** [comment]
i guess the static image(yuv420 single frame) should be encoded as IDR frame,  so your code works only after stream restart.

**Comment by huili2** [comment]
@OmnomnomCat is there any more requirement on this issue?

**Comment by huili2** [comment]
close this sincee no response.
