### ISSUE TITLE
potential overflow by negative-size-param

### ISSUE THREAD

**Issue by autofuzzoss** [cisco/openh264#3430]
A bug was found within the openh264. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using openh264. It would be best if the affected logic is checked beforehand. 
The bug was found with a fuzzer based on the test-code "FrameBsReallocateTest" 
This is probably like a negative-size-param bugs

As a result of analyzing, openh264/codec /encoder/core/src/svc_encode_slice.cpp: Call Memcpy at 1557
memcpy (pNalList, pCtx->pOut->sNalList, sizeof (SWelsNalRaw) * pCtx->pOut->iCountNals);
At this time, the pCtx->pOut->iCountNals value contains a number less than 0

_*crash-log*
==84199==ERROR: AddressSanitizer: negative-size-param: (size=-85899343000)
    #0 0x4f5927 in __asan_memcpy 
    #1 0xe648ec in WelsEnc::FrameBsRealloc(WelsEnc::TagWelsEncCtx*, SFrameBSInfo*, SLayerBSInfo*, int) 
    #2 0x76676c in CSliceBufferReallocatTest_FrameBsReallocateTest_Test::TestBody() 
    #3 0xa4b1b9 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) 
    #4 0x9b40ea in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) 
    #5 0x9b3bca in testing::Test::Run()_ 

Steps to reproduce:
1. git clone https://github.com/cisco/openh264.git
2. Download the attached file(EncUT_SliceBufferReallocate.cpp)
3. cp EncUT_SliceBufferReallocate.cpp openh264/test/encoder/.
4. cd openh264
5. make CC=/bin/clang CXX=/bin/clang++ CFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link" CXXFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link -fPIC" LDFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link" LD=/bin/clang++ AR=/usr/lib/llvm-10/bin/llvm-ar USE_ASM=No BUILDTYPE=Debug OS=linux ARCH=x86_64 libraries
6. make CC=/bin/clang CXX=/bin/clang++ CFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link" CXXFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link -fPIC" LDFLAGS="-g -fno-omit-frame-pointer -fsanitize=address,fuzzer-no-link" LD=/bin/clang++ AR=/usr/lib/llvm-10/bin/llvm-ar USE_ASM=No BUILDTYPE=Debug OS=linux ARCH=x86_64 test
7. Run
   ./codec_unittest --gtest_filter=CSliceBufferReallocatTest.FrameBsReallocateTest

   
Browser/OS: ubuntu 18.04
[openh264_poc4.tar.gz](https://github.com/cisco/openh264/files/7262961/openh264_poc4.tar.gz)

**Comment by mfeia** [comment]
In EncUT_SliceBufferReallocate.cpp, you have modified  `pCtx->pSvcParam->iSpatialLayerNum = 600`, but we support max SpatialLayerNum is 4,  so you can’t modify it directly in UT like this. btw,  we will check whether iSpatialLayerNum is legal in the normal coding process.

**Comment by GuangweiWang** [comment]
@junsik-kim0  Is your problem solved？
