### ISSUE TITLE
Purpose of SCREEN_CONTENT_NON_REAL_TIME and CAMERA_VIDEO_NON_REAL_TIME?

### ISSUE THREAD

**Issue by midn1** [cisco/openh264#3433]
Using both causes an error within `ParamValidationExt`, which is called by `WelsEncoderInitExt` so I don't understand what their purpose is.

Furthermore, they are handled in `ParamValidation`, but control flow seems to never get there..

	ISVCEncoder *enc;
	assert(WelsCreateSVCEncoder(&enc) == 0);
	
	SEncParamBase param;
	memset(&param, 0, sizeof(param));
	param.iUsageType = CAMERA_VIDEO_NON_REAL_TIME;
	param.fMaxFrameRate = FPS;
	param.iPicWidth = WIDTH;
	param.iPicHeight = HEIGHT;
	param.iTargetBitrate = BITRATE;
	enc->Initialize(&param);

**Comment by mfeia** [comment]
From the code, we can see that `ParamValidation` is called by `ParamValidationExt`, so if you set `param.iUsageType = CAMERA_VIDEO_NON_REAL_TIME`, `ParamValidationExt` function will return early before calling `ParamValidation`.  BTW, Both SCREEN_CONTENT_NON_REAL_TIME and CAMERA_VIDEO_NON_REAL_TIME are unavailable to users.
