### ISSUE TITLE
Why did you set PRO_SCALABLE_BASELINE = 83,   PRO_SCALABLE_HIGH     = 86 ?

### ISSUE THREAD

**Issue by hzk7287** [cisco/openh264#3443]
Hello everyone,  I have found if I set  "SimulcastAVC                     0              # 0: use SVC syntax for higher layers; 1: use Simulcast AVC"

    take a look at"  uiProfileIdc = (!bSimulcastAVC) ? PRO_SCALABLE_BASELINE : uiProfileIdc;" The IDR frame is set to PRO_SCALABLE_BASELINE 83. After I extract one layer of streams in SVC streams, uiProfileIdc  cannot be parsed by FFMPEG.

My question is why do you set PRO_SCALABLE_BASELINE to 83.

**Comment by listener51** [comment]
![image](https://user-images.githubusercontent.com/7181630/141927818-571491e3-715c-4340-a950-81a85266966b.png)
As can be seen from the standard protocol, the baseline profile of SVC is 83(in this case, you set SimulcastAVC to false, means you will enable svc coding)

**Comment by hzk7287** [comment]
Thank you very much.  I have to rewrite NAL to meet the requirement of FFMPEG.

**Comment by mfeia** [comment]
Maybe you can set SimulcastAVC to true, it will achieve the same purpose.

**Comment by GuangweiWang** [comment]
@hzk7287 is your problem resolved?

**Comment by hzk7287** [comment]
Yes.

**Comment by GuangweiWang** [comment]
great. 
so I will close this issue. thank you for you attention.
