### ISSUE TITLE
unable to make

### ISSUE THREAD

**Issue by Ghayas-cyber** [cisco/openh264#3447]
I am building on windows platform. I am unable to **make** it successfully. 
I tried several times but failed. 

Thanks

**Comment by GuangweiWang** [comment]
@Ghayas-cyber
please install cygwin(make must be include) or MinGW on you Windows platform.

**Comment by GuangweiWang** [comment]
or could you provide more  detailed log/error message?

**Comment by Ghayas-cyber** [comment]
@GuangweiWang Thanks for reply. I follow all instructions but unable to configure Open.H264. 
The issue is I cannot make it using MinGW. Can you please guide me. Thanks

**Comment by Ghayas-cyber** [comment]
@GuangweiWang When I try to 'make' it shows following messages. 

MSYS /c/openh264-master
$ make ARCH=x86_64
Makefile:83: build/platform-msys_nt.mk: No such file or directory
make: *** No rule to make target 'build/platform-msys_nt.mk'.  Stop.

**Comment by RamseyFowler** [comment]
what up yall try to fuck me up


Sent from Yahoo Mail for iPhone


On Sunday, December 26, 2021, 3:08 PM, Syed ***@***.***> wrote:




@GuangweiWang When I try to 'make' it shows following messages.

MSYS /c/openh264-master
$ make ARCH=x86_64
Makefile:83: build/platform-msys_nt.mk: No such file or directory
make: *** No rule to make target 'build/platform-msys_nt.mk'. Stop.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RamseyFowler** [comment]
fuck yall doing


Sent from Yahoo Mail for iPhone


On Sunday, December 26, 2021, 3:08 PM, Syed ***@***.***> wrote:




@GuangweiWang When I try to 'make' it shows following messages.

MSYS /c/openh264-master
$ make ARCH=x86_64
Makefile:83: build/platform-msys_nt.mk: No such file or directory
make: *** No rule to make target 'build/platform-msys_nt.mk'. Stop.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GuangweiWang** [comment]
according to you error message, I suppose you used the minGW bash.
you can try to specify your OS as this:
make OS=msvc ARCH=x86_64    #will pick up the msvc compiler
make OS=mingw_nt ARCH=x86_64  #will pick up the compiler in mingw
make OS=cygwin_nt ARCH=x86_64  #will pick up the compiler in cygwin

in addition, it is recommended that you‘d better use windows cmd and add the minGW path to PATH

**Comment by Ghayas-cyber** [comment]
@GuangweiWang Thanks alot. Can you please share email I want to send you details. Thanks

**Comment by GuangweiWang** [comment]
> @GuangweiWang Thanks alot. Can you please share email I want to send you details. Thanks

guangwwa@cisco.com

**Comment by Ghayas-cyber** [comment]
@GuangweiWang I send you email. thanks

**Comment by Ghayas-cyber** [comment]
@GuangweiWang  
I run the following command from within Project Directory (C:\openh264-master) 
C:\openh264-master>make OS=mingw_ntARCH=x86_64
Makefile:83: build/platform-mingw_ntARCH=x86_64.mk: No such file or directory
make: *** No rule to make target 'build/platform-mingw_ntARCH=x86_64.mk'.  Stop.

**Comment by GuangweiWang** [comment]
> @GuangweiWang I run the following command from within Project Directory (C:\openh264-master) C:\openh264-master>make OS=mingw_ntARCH=x86_64 Makefile:83: build/platform-mingw_ntARCH=x86_64.mk: No such file or directory make: *** No rule to make target 'build/platform-mingw_ntARCH=x86_64.mk'. Stop.

you should keep at least one space between these 2 paramters OS=mingw_nt      ARCH=x86_64

**Comment by Ghayas-cyber** [comment]
@GuangweiWang Thanks. do you mean OS=mingw_nt ARCH=x86_64?  Do i need to run it from MinGW or windows command line.

**Comment by GuangweiWang** [comment]
> @GuangweiWang Thanks. do you mean OS=mingw_nt ARCH=x86_64? Do i need to run it from MinGW or windows command line.

yes. windows command line is recommended. 

and you can choose provided .bat to compile like this:
cd openh264\build; 
AutoBuildForWPAndWindows.bat

**Comment by GuangweiWang** [comment]
Is this problem solved?

**Comment by huangqingbiao8831** [comment]
I got this message?
$ make ARCH=x86_64 OS=msvc
cl -O2 -Ob1 -Oy- -Zi -FS -GF -GS -Gy -DNDEBUG -MT -DNDEBUG  -DX86_ASM -DHAVE_AVX2 -nologo -W3 -EHsc -fp:precise -Zc:wchar_t -Zc:forScope -D_VARIADIC_MAX=10 -DGENERATED_VERSION_HEADER -DHAVE_AVX2 -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -Focodec/common/src/common_tables.obj codec/common/src/common_tables.cpp
make: cl: No such file or directory
make: *** [codec/common/targets.mk:116: codec/common/src/common_tables.obj] Error 127

**Comment by huili2** [comment]
Does this issue still exsit? And did you install the correct environment as in ReadMe? 
If no update, it will be closed.
