### ISSUE TITLE
Artifacts 

### ISSUE THREAD

**Issue by Benc1900** [cisco/openh264#3448]
![encoder](https://user-images.githubusercontent.com/12776069/145875383-5dadcd6d-c7b2-496c-8d06-55ced5423d8a.JPG)

After some time, encoder starts to produce images like the one i attached - with gray Artifacts.
When that happens i can only restart the encoder to make them go away.

Why that happens and how can I prevent it from happening?

Thanks.

**Comment by Bagwell80** [comment]
#3435

**Comment by joakim-tjernlund** [comment]
If it was working before, the a git bisect can find the commit causing this.

**Comment by Benc1900** [comment]
From day 1 it does this. After few hours on random it starts to do that ...
I guess that randomly after some time something is broken in the encoder data...
Deleting the encoder and recreate it solves it. But what that happens?

**Comment by joakim-tjernlund** [comment]
Oh, I figured it was a recent regression. What release are you running ?

**Comment by Benc1900** [comment]
2.1.1.2005

**Comment by joakim-tjernlund** [comment]
Latest release is known to be a little broken.

**Comment by Benc1900** [comment]
That latest 2.1.1 binary release is from May 22, 2020 ...
here:
http://ciscobinary.openh264.org/openh264-2.1.1-win32.dll.bz2
So it is broken for 1.5 years?
Or it just shows 2.1.1 but it does got updated?

**Comment by joakim-tjernlund** [comment]
It is that old

**Comment by Benc1900** [comment]
I asked this same question 7 years ago when i first noticed the issue and this is the answer i got:
Packets in IDR lost, error concealment for now used the grey pixels for lost area in I frame. In the next release, we will do copy from previous frame for IDR error concealment.

So if you think this is really the issue, does the new code fix it? if yes when it will be compiled to binaries (I need it as binary for licensing issue)

**Comment by joakim-tjernlund** [comment]
I don't know, not an openh264 developer.

**Comment by GuangweiWang** [comment]
@Benc1900 
the next release is in progress now.
about this issue, as issue #1658 mentioned, error concealment do copy from previous frame instead of  grey pixels for lost area after version 1.3.

**Comment by bobj1212** [comment]
@huili2 You just closed this issue but was it resolved in one of the released version?
Or this issue still exists?..

**Comment by huili2** [comment]
@bobj1212 it was caused by data loss, which is not considered to be an issue.
To prevent this from happening, data loss should not occur by any transmission protection.
Once error happens, error concealment method could be modified to get different effect by SetOption(...). Details could be seen in API document.

**Comment by bobj1212** [comment]
But my app uses the H264 encoder. I do not have any access to the decoder which probably does not use h264 anyway.
And the  error concealment method is applied to the decoder as far as I saw.
So what should I do?

**Comment by bobj1212** [comment]
@huili2 
But my app uses the H264 encoder. I do not have any access to the decoder which probably does not use h264 anyway.
And the  error concealment method is applied to the decoder as far as I saw.
So what should I do?
