### ISSUE TITLE
Shoud we free SBufferInfo.pDst?

### ISSUE THREAD

**Issue by takuya-takeuchi** [cisco/openh264#3450]
I'm very sorry to ask bored quetion.
sample code does not have free/delete memory about SBufferInfo.pDst.
We should not take care of it?

Thank you for your cooperations.

**Comment by GuangweiWang** [comment]
do not need to release this buffer manually. you can use WelsDestroyDecoder to destroy decoder when you no longer use the decoder.

**Comment by takuya-takeuchi** [comment]
@GuangweiWang 

thanks.
OK, I understand.
SBufferInfo.pDst is shared on process so WelsCreateDecoder allocate memory and WelsDestroyDecoder destory it, right?

**Comment by GuangweiWang** [comment]
> @GuangweiWang
> 
> thanks. OK, I understand. SBufferInfo.pDst is shared on process so WelsCreateDecoder allocate memory and WelsDestroyDecoder destory it, right?

yes, you are right.
