### ISSUE TITLE
Bug report on openh264( AddressSanitizer: requested allocation)

### ISSUE THREAD

**Issue by afosscontact** [cisco/openh264#3451]
Describe the bug
A bug was found within the openh264. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using openh264. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the function "MotionEstimateTest.TestDiamondSearch". 
This may cause problems in the use of libraries

How To Reproduce
1. Download the attached file
2. Execute  make_openh264_bug1.sh
3. ./codec_unittest --gtest_filter=MotionEstimateTest.TestDiamondSearch

==47030==ERROR: AddressSanitizer: requested allocation size 0xffffffffef37991b (0xffffffffef37a920 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T0)
    #0 0x4f653d in malloc (openh264/codec_unittest+0x4f653d)
    #1 0xf1b0ab in WelsCommon::WelsMalloc(unsigned int, char const*, unsigned int) openh264/codec/common/src/memory_align.cpp:72:30
    #2 0xf1b489 in WelsCommon::CMemoryAlign::WelsMalloc(unsigned int, char const*) openh264/codec/common/src/memory_align.cpp:129:20
    #3 0x70b0a7 in MotionEstimateTest::SetUp() openh264/test/encoder/EncUT_MotionEstimate.cpp:48:2

Platform (please complete the following information):
OS: Ubuntu 18.04
[openh264_bug1.tar.gz](https://github.com/cisco/openh264/files/7765971/openh264_bug1.tar.gz)

**Comment by huili2** [comment]
Actually motion estimation is not an exposed API but just internal function call, so there would be enough limitation on the environmental variables. I don't think it is meaningful to set the width/height as the number in this attachment.
Anyway, thanks for your information.

**Comment by GuangweiWang** [comment]
if have no update, this issue will be closed later.
