### ISSUE TITLE
Bug report on openh264( AddressSanitizer: heap-buffer-overflow)

### ISSUE THREAD

**Issue by afosscontact** [cisco/openh264#3452]
Describe the bug
A bug was found within the openh264. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using openh264. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the function "CSliceBufferReallocatTest.Reallocate_in_one_partition". 
This may cause problems in the use of libraries

How To Reproduce
1. Download the attached file
2. Execute  make_openh264_bug1.sh
3. ./codec_unittest --gtest_filter=CSliceBufferReallocatTest.Reallocate_in_one_partition

==47445==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000052f8 at pc 0x000000f1b15d bp 0x7ffe979a7990 sp 0x7ffe979a7988
WRITE of size 8 at 0x6020000052f8 thread T0
    #0 0xf1b15c in WelsCommon::WelsMalloc(unsigned int, char const*, unsigned int) openh264/codec/common/src/memory_align.cpp:95:55
    #1 0xf1b489 in WelsCommon::CMemoryAlign::WelsMalloc(unsigned int, char const*) openh264/codec/common/src/memory_align.cpp:129:20
    #2 0xf1b340 in WelsCommon::CMemoryAlign::WelsMallocz(unsigned int, char const*) openh264/codec/common/src/memory_align.cpp:118:20

Platform (please complete the following information):
OS: Ubuntu 18.04
[openh264_bug2.tar.gz](https://github.com/cisco/openh264/files/7765986/openh264_bug2.tar.gz)

**Comment by GuangweiWang** [comment]
pCtx->pSvcParam->iSpatialLayerNum = -2 is not supported. -2 is a invalid parameter.

**Comment by bird-rookie** [comment]
> v
Hello, it seems that you know this code very well, would like to ask, do you know the Module this file directory is used for? What is the difference between gmp-openh264.cpp and common openh264?

**Comment by GuangweiWang** [comment]
> > v
> > Hello, it seems that you know this code very well, would like to ask, do you know the Module this file directory is used for? What is the difference between gmp-openh264.cpp and common openh264?

gmp is for Firefox. please use openh264 if you just want to use openh264 codec.

**Comment by GuangweiWang** [comment]
if have no update, this issue will be closed later.
