### ISSUE TITLE
WelsMallocz  bug

### ISSUE THREAD

**Issue by junsik-kim0** [cisco/openh264#3453]
Hi,
I found a logic bug in the memory allocation.
In the Welsmallocz function below, Kuisize is an unsigned int and used as a parameter of the Welsmalloc function
Kuisize is calculated in the Welsmalloc function, which is the result value of this is a signed int type
I think this is obviously a problem and may cause errors.

void* CMemoryAlign::WelsMallocz (const uint32_t **kuiSize**, const char* kpTag) {
  void* pPointer = **WelsMalloc** (**kuiSize**, kpTag);
  if (NULL == pPointer) {
    return NULL;
  }
  // zero memory
  memset (pPointer, 0, kuiSize);

  return pPointer;
}

void* WelsMalloc (const uint32_t **kuiSize**, const char* kpTag, const uint32_t kiAlign) {
  const int32_t kiSizeOfVoidPointer     = sizeof (void**);
  const int32_t kiSizeOfInt             = sizeof (int32_t);
  const int32_t kiAlignedBytes          = kiAlign - 1;
  const int32_t **kiTrialRequestedSize**    = **kuiSize** + kiAlignedBytes + kiSizeOfVoidPointer + kiSizeOfInt;
  const int32_t kiActualRequestedSize   = kiTrialRequestedSize;
  const uint32_t kiPayloadSize          = kuiSize;

  uint8_t* pBuf = (uint8_t*) malloc (kiActualRequestedSize);

**Comment by bird-rookie** [comment]
Hello, it seems that you know this code very well, would like to ask, do you know the Module this file directory is used for? What is the difference between gmp-openh264.cpp and common openh264?

**Comment by huili2** [comment]
Hi @bird-rookie it really does not seems good, but it won't be a bug as function malloc will use type size_t as input parameter, and this is also unsigned type.
Of course, it will be better to use all uint32_t in this calculation to make fewer misunderstandings.

**Comment by GuangweiWang** [comment]
has been fixed in PR #3464
