### ISSUE TITLE
oss-fuzz 39294

### ISSUE THREAD

**Issue by xiaotiansf** [cisco/openh264#3456]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39294#c2
So far this issue is not reproducible on Windows. Looking it on Linux.

**Comment by xiaotiansf** [comment]
Not reproducible on Linux. I attached the testcases. Let me know if anyone can reproduce the issue.
[39294_.zip](https://github.com/cisco/openh264/files/7798392/39294_.zip)

**Comment by GuangweiWang** [comment]
has been fixed in PR #3460
