### ISSUE TITLE
Decoder not continue to decoding after a lost frame

### ISSUE THREAD

**Issue by thirtyninekilovolts** [cisco/openh264#3486]
The decoder works perfectly if there is not any lost frame. If a frame is lost(no matter whether keyframe); the decoder goes to fallback and returns error code 0x12 (dsRefLost | dsNoParamSets). So the decoder does not continue by the time a new keyframe comes.

I wonder that is there a flag that sets the decoder to continue to decode the remaining frame.

**Comment by huili2** [comment]
From video codec itself, if you disable the video error concealment (means you only want to see correctly decoded data), it is impossible to do this due to the loss of necessary information. Even you set a flag, that helps nothing.

**Comment by huili2** [comment]
Will close this if no update.

**Comment by thirtyninekilovolts** [comment]
Okay, thanks for your reply
