### ISSUE TITLE
What pixel formats does this support?

### ISSUE THREAD

**Issue by Videogamer555** [cisco/openh264#3511]
Does this support only YUV420? Does it support any other YUV subsamplings? For example FFMPEG supports YUV422 and YUV444, both 8-bit-per-sample (standard bitdepth) and 10-bit-per-sample (high bitdepth) versions, both encoding and decoding. It also supports RGB h264 (where RGB is directly compressed or decompressed via the h264 codec, rather than first converting RGB to or from YUV). Does Open h264 support any of these additional pixel formats? Or does it only support 8-bit-per-sample YUV420?

**Comment by huili2** [comment]
Openh264 only supports 8-bit YUV420 as your final answer.
