### ISSUE TITLE
Decode hang for every few seconds (Error:PPS id (xx) is invalid, previous id (xx) error ignored (xx))

### ISSUE THREAD

**Issue by LinusABC** [cisco/openh264#3515]
Dear all,

I am new to OpenH264 and try to use it (v2.2.0) to encode and decode my video stream.
If I try it locally (no error loss), it decodes normally.

However, if I send the encoded video packets and decode it at another PC (i.e., with some packet loss), it can decode for a few seconds (e.g. 10s) but then it hangs for a few sec (e.g. 3s, with no bitmap returned when decode) with the error similar as follows (each line represents one error):
```
[OpenH264] this = 0x000001E35DB81440, Error:PPS id (7) is invalid, previous id (-1) error ignored (0)!
[OpenH264] this = 0x000001E35DB81440, Error:PPS id (8) is invalid, previous id (7) error ignored (58)!
[OpenH264] this = 0x000001E35DB81440, Error:PPS id (9) is invalid, previous id (8) error ignored (59)!
[OpenH264] this = 0x000001E35DB81440, Error:PPS id (11) is invalid, previous id (-1) error ignored (59)!
[OpenH264] this = 0x000001E35DB81440, Error:PPS id (12) is invalid, previous id (11) error ignored (57)!
```

This error occurs repeatingly. Is it due to my incorrect setup and encode/decode of OpenH264?

I setup and encode/decode as follows:
**Encoder Setup**
```
SEncParamBase base;
memset(&base, 0, sizeof(SEncParamBase));
base.iPicWidth = width;				// =640
base.iPicHeight = height;			// =480
base.fMaxFrameRate = fps;			// =30
base.iUsageType = CAMERA_VIDEO_REAL_TIME;	// =0
base.iTargetBitrate = bps;			// =1M
base.iRCMode = RC_QUALITY_MODE;			// =0
int rc = encoder->Initialize(&base);
```

**Encode**
`int ret = encoder->EncodeFrame(pic, bsi);`

**Decoder Setup**
```
SDecodingParam decParam;
memset(&decParam, 0, sizeof(SDecodingParam));
decParam.uiTargetDqLayer = UCHAR_MAX;
decParam.eEcActiveIdc = ERROR_CON_SLICE_COPY;	// =2
decParam.sVideoProperty.eVideoBsType = VIDEO_BITSTREAM_DEFAULT;		// =1
int rc = decoder->Initialize(&decParam);
```

**Decode**
`int rc = decoder->DecodeFrame2(frame, length, buffer, &bufInfo);`

Please help.
Thanks a lot.

**Comment by huili2** [comment]
@LinusABC does it still exist in latest version?

**Comment by huili2** [comment]
close this one since no response.
