### ISSUE TITLE
SBufferInfo byte alignment

### ISSUE THREAD

**Issue by dx12346789** [cisco/openh264#3518]
I use Openh264 to decode a 1080P video,but in the SBufferInfo Structure, iWidth is 1920, iHeight is 1080, stride[0] is 1984, stride[1] is 992.  The decode image is 1984x1080.
Is there any way to cancle the byte aligment? Because 1920 was aligned.

**Comment by dx12346789** [comment]
I debugged the source code and found that the memory alignment of the image is WELS_ALIGN(picwidth + (PADDING_LENGTH << 1), PICTURE_RESOLUTION_ALIGNMENT).

#define WELS_ALIGN(x, n) (((x) + (n) - 1) & ~((n) - 1)
#define PADDING_LENGTH 32
#define PICTURE_RESOLUTION_ALIGNMENT 32

Can i turn it off? Or choose not to add (PADDING_LENGTH << 1). Because the width of image is originally memory aligned.

**Comment by kanzhu-cisco** [comment]
The buffer alignment is required by intrinsic framework.

**Comment by dx12346789** [comment]
So i need to decode first and then crop out the extra pixels?

**Comment by huili2** [comment]
stride is necessary and always there. The padding is not only for alignment, but also for other purpose inside decoder. So it is always required that pointer and stride to be used together to access the output YUV data.
