### ISSUE TITLE
how to decode SpatialLayer [1]?

### ISSUE THREAD

**Issue by LoserDream** [cisco/openh264#3519]
encode param
   iSpatialLayerNum=2
   iTemporalLayerNum = 1
it's work.

if iBufferStatus == 0
   DecodeFrame2(encodeData)
it's work

if iBufferStatus == 1
DecodeFrame2(encodeData)
it's not  work.

how can i decode that?

iBufferStatus == 0
naltype 7 15 8 8 14 5 14 1 14 1

iBufferStatus == 1
naltype all 20

**Comment by huili2** [comment]
Please refer to https://github.com/cisco/openh264/issues/3532
