### ISSUE TITLE
Possible error in ratectl.cpp

### ISSUE THREAD

**Issue by cnsndr** [cisco/openh264#3530]
I was compiling openh264-2.2.0 and a compiler warning led me to a potential error in source file codec/encoder/core/src/ratectl.cpp (line 494) inside the following routine:

void RcCalculatePictureQp (sWelsEncCtx* pEncCtx) {
  ...
  int32_t iDeltaQpTemporal = 0;
  ...
  if (0 == pTOverRc->iPFrameNum) {
    ...
  } else if (pWelsSvcRc->iCurrentBitsLevel == BITS_EXCEEDED) {
    ...
  } else {
    ,,,
    int32_t iDeltaQpTemporal = iTl - iTlLast;
    ...
  }
  ... the value of iDeltaQpTemporal is used ...
  ...
}

As you may notice, the variable iDeltaQpTemporal is both defined at the routine's level and inside the second "else" branch of the "if" statement. So on that branch the value assigned to the branch-local iDeltaQpTemporal does nothing to affect the main instance of the variable. In fact the compiler warned that "iDeltaQpTemporal is assigned a value that is never used" and it took me a few minutes to understand why.

This is probably an error and the variable shouldn't have been redefined but only assigned, I leave however that determination to the author of the code.

**Comment by huili2** [comment]
@cnsndr  you are right, it is really a potential rate control issue, and will make it not very accurate to what we actually want.
After all, it is not very critical not severe, we'll not fix it in coming release (as it is in progress already). We hope to fix it in next next version. Thanks!

**Comment by huili2** [comment]
Fixed in https://github.com/cisco/openh264/pull/3594
