### ISSUE TITLE
SVC decode failed.

### ISSUE THREAD

**Issue by dx12346789** [cisco/openh264#3532]
I decode an SVC encoded video that has T0(480x270)+T1(960x540)+T2(1920x1080).  
First, send sps and pps into decoder, then send IDR frame into decoder, at this time if a P frame data with only T0+T1 is sent to the decoder, an error will be reported.  
I don't understand why this happens,isn't the SVC encoded enhancement layer optional? Or the IDR frame is T0+T1+T2 then the P frame must also be T0+T1+T2.

**Comment by huili2** [comment]
Current openh264 decoder cannot support multi-layer decoding. Only one resolution data should be sent into it. Otherwise, decoder will consider it as resolution switch, also named new sequence.
