### ISSUE TITLE
New Release for v2.3.0

### ISSUE THREAD

**Issue by LinusABC** [cisco/openh264#3541]
Dear all,

I am not skillful at building DLL from source code. Currently I am using v2.2.0 (Windows x64 version) downloaded from Release and found that v2.3.0 source code is available now.
When will be the DLL for v2.3.0 (Windows x64) available for download?

Thanks.

**Comment by huili2** [comment]
It is already available in http://ciscobinary.openh264.org/openh264-2.3.0-win64.dll.bz2

**Comment by LinusABC** [comment]
> It is already available in http://ciscobinary.openh264.org/openh264-2.3.0-win64.dll.bz2

Thanks. I have tried to rename the old link and downloaded it, too.
