### ISSUE TITLE
[MSVC] openh264 failed to build with "fatal error C1083: Cannot open include file: 'codec_def.h': No such file or directory"

### ISSUE THREAD

**Issue by Zhaojun-Liu** [cisco/openh264#3542]
Hi,
Recently, we update the commit of openh264 (commit is : 2e63786), it failed to build with "fatal error C1083: Cannot open include file: 'codec_def.h': No such file or directory (D:\a01\_work\2\s\src\vctools\Compiler\CxxFE\sl\p1\c\p0prepro.c:1934) [F:\gitP\cisco\openh264\test\build\win32\codec_ut\codec_unittest.vcxproj]"
Could you please help look this issue? Thanks.

**Repro steps:**
1. git clone https://github.com/cisco/openh264 F:\gitP\cisco\openh264
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
3. cd F:\gitP\cisco\openh264
4. if exist F:\gitP\cisco\openh264\test\build\win32\codec_ut rd /s /q F:\gitP\cisco\openh264\test\build\win32\codec_ut
5. xcopy F:\tools\openh264\patch\gtest F:\gitP\cisco\openh264\gtest /k/r/e/i/s/c/h/f/y 2>&1
6. xcopy F:\tools\openh264\patch\codec_ut F:\gitP\cisco\openh264\test\build\win32\codec_ut /k/r/e/i/s/c/h/f/y 2>&1
7. devenv /upgrade .\codec\build\win32\dec\WelsDecoder.sln 2>&1
8. devenv /upgrade .\codec\build\win32\enc\WelsEncoder.sln 2>&1
9. devenv /upgrade .\test\build\win32\codec_ut\Codec_UT.sln 2>&1
10. msbuild /p:Platform=x64 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.18362.0 .\test\build\win32\codec_ut\Codec_UT.sln /t:Rebuild 2>&1

**Expected result:**
build successfully.

**Actural result:**
......
F:\gitP\cisco\openh264\codec\encoder\core\inc\param_svc.h(46,10): fatal error C1083: Cannot open include file: 'codec_def.h': No such file or directory (D:\a01\_work\2\s\src\vctools\Compiler\CxxFE\sl\p1\c\p0prepro.c:1934) [F:\gitP\cisco\openh264\test\build\win32\codec_ut\codec_unittest.vcxproj]
......

**Detailed log:**
[build.log](https://github.com/cisco/openh264/files/8908182/build.log)

**Comment by Marssssss** [comment]
‘codec_def.h’ is under '\codec\api\svc\'
maybe the include directory has not include?

**Comment by Zhaojun-Liu** [comment]
@Marssssss Thanks for your reply. This issue has already been solved.
