### ISSUE TITLE
Issue: 45607

### ISSUE THREAD

**Issue by xiaotiansf** [cisco/openh264#3544]
Issue 45607: openh264:decoder_fuzzer: Index-out-of-bounds in WelsDec::WelsInitRefList. I am looking at  this one now.

**Comment by xiaotiansf** [comment]
@huili2  It looks like mingw does not build correctly, which is unrelated to my fix. Can you take a look? Thanks.
https://github.com/xiaotiansf/openh264-1/actions/runs/2517045566

**Comment by jrmuizel** [comment]
That's #3533 which can be worked around using #3537

**Comment by xiaotiansf** [comment]
@jrmuizel I see. Thanks.

**Comment by jrmuizel** [comment]
@xiaotiansf the mingw CI should be fixed now. Is your change ready to be landed?

**Comment by xiaotiansf** [comment]
@jrmuizel Okay. PR #3559 is created.
