### ISSUE TITLE
Does openh264 support B frame when decoding now?

### ISSUE THREAD

**Issue by WeiChungChang** [cisco/openh264#3546]
I have a file with B frame, download from 
https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_1MB.mp4

However, I cannot decode B frame; it can decode some I or P frames but has problem in B frame.

Does openh264 supports B frame when decoding now? If so, what's the potential issue I met?

I got a lot of 0x4(dsBitstreamError).

Thanks

**Comment by jrmuizel** [comment]
What version of openh264 are you using? That clip plays ok for me (though there are some brightness changes that shouldn't be there)

**Comment by WeiChungChang** [comment]
@jrmuizel  thanks to the reply. I updated to the latest repo and it is O.K now.

May I have one more question please?

How could I get all decoded frames if there are B frame?
Since the API is;
```
  virtual DECODING_STATE EXTAPI DecodeFrameNoDelay (const unsigned char* pSrc,
      const int iSrcLen,
      unsigned char** ppDst,
      SBufferInfo* pDstInfo) = 0;
```
After decode, by the criterion:
```
    if (bufInfo.iBufferStatus == 0) {
      continue;
    }
```
We know if there is a decoded frame I can receive.

**If a movie has B frame, sometimes, bufInfo.iBufferStatus will be zero. Assume there are 2 frames.
Hence at the end of decoding, there are still 2 frames to be received.
How can I get them?**

Thanks.

**Comment by jrmuizel** [comment]
Can you just call `DecodeFrameNoDelay` again?

**Comment by WeiChungChang** [comment]
Thanks to the suggestion, it is OK now.
