### ISSUE TITLE
Create 2.3.0 release?

### ISSUE THREAD

**Issue by mcatanzaro** [cisco/openh264#3549]
Hi, I see https://github.com/cisco/openh264/commit/2e637867315ffeda3cd8970825ec86acc3fc4a30 and https://github.com/cisco/openh264/commit/8fe55e3f4accac7fd1af4262bcd6eff5d008396d and even http://ciscobinary.openh264.org/libopenh264-2.3.0-linux64.6.so.bz2, but there is no 2.3.0 release available at https://github.com/cisco/openh264/releases or https://github.com/cisco/openh264/tags. Recommend creating a 2.3.0 release.

**Comment by joakim-tjernlund** [comment]
yes please.

**Comment by joakim-tjernlund** [comment]
Ping? Can't be difficult to an v2.3.0 tag.

**Comment by Conan-Kudo** [comment]
ping @justaugustus

**Comment by dv1** [comment]
Another ping here @GuangweiWang . Is there a specific reason for the missing tag, or was it just forgotten?

**Comment by GuangweiWang** [comment]
the lasted release for openh264v2.3.0 has been created.
