### ISSUE TITLE
Encoder resolution cannot exceed 3840x2160

### ISSUE THREAD

**Issue by RyanHir** [cisco/openh264#3553]
Hello,

In the `README.md` file the following line is present "Encoder errors when resolution exceeds 3840x2160" in the [Known Issues](https://github.com/cisco/openh264#known-issues) section. I am unable to find any issue referencing this which makes it difficult to track any development, if any, has been made to fix this.

I am currently needing openh264 to process an h264/h265 encoded video with a shape of 5472x3078. Right now I am resizing the content to 3840x2160 but this is not ideal as I am loosing detail on small objects. This can be seen in a different project at https://github.com/cvat-ai/cvat/issues/20

**Comment by huili2** [comment]
No. Currently the encoder/decoder could only support up to level 5.2, corresponding to the frame size around 4k. For now there's no plan to support higher resolution, as the encoder/decoder speed will be a limitation.
