### ISSUE TITLE
openh264: multi-slice has lower image quality at higher bitrates

### ISSUE THREAD

**Issue by sivapatibandla** [cisco/openh264#3558]
I experimented with multiple slices and threads in openh264 and found that at higher bitrates (>1.5 mbps) the image quality (PSNR) of multi-slice/thread mode is ~10% lower than single slice. Some compression efficiency / image quality loss is expected due to cabac context resets, MBs not spanning across slice boundaries, etc. but is this high PSNR difference expected?

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/8024151/187093058-76c132b5-f8cb-42dd-9ec5-026a9a76028a.png">

**Comment by jrmuizel** [comment]
Can you share the code for creating this data?

**Comment by huili2** [comment]
Actually for screen content, the BD-PSNR model is not very useful, or even the PSNR measurement is not meaningful. You can just take it as a reference.
