### ISSUE TITLE
In Firefox | version of GMP openh264 reported as "system-installed"

### ISSUE THREAD

**Issue by Ricky-Tigg** [cisco/openh264#3580]
**OS:** Fedora
```
$ rpm -q --qf "%{name} %{version} %{license}\n" mozilla-openh264
mozilla-openh264 2.3.0 BSD
```
In Firefox session | In pages `about:plugins` and `about:addons` the version of GMP openh264 is reported as _system-installed_ instead of a **numbered version**, currently 2.3.0.

**Comment by Darkspirit** [comment]
That's only the case on Fedora, please file an enhancement request here:
https://bugzilla.redhat.com/enter_bug.cgi?component=firefox&product=Fedora

It would be good if Fedora could try again to upstream its patch to be able to drop its custom Firefox GMP plugin package:
https://bugzilla.mozilla.org/show_bug.cgi?id=1663844
https://bugzilla.mozilla.org/show_bug.cgi?id=1619988

**Comment by Ricky-Tigg** [comment]
[Reported](https://bugzilla.redhat.com/show_bug.cgi?id=2131218).
