### ISSUE TITLE
Prebuilt binaries download link for v2.3.0 for OSX not working

### ISSUE THREAD

**Issue by ozvoz** [cisco/openh264#3582]
Download links for binaries from RELEASES for v2.3.0 for OSX  are not working:

http://ciscobinary.openh264.org/libopenh264-2.3.0-osx-arm64.6.dylib.bz2
http://ciscobinary.openh264.org/libopenh264-2.3.0-osx-x64.6.dylib.bz2

**Comment by jrmuizel** [comment]
In which way are they not working?

**Comment by Darkspirit** [comment]
Both links are 404 Not Found.

**Comment by Darkspirit** [comment]
2.3.0 file names are wrong:
http://ciscobinary.openh264.org/libopenh264-2.3.0-osx-arm64.6.dylib.bz2
http://ciscobinary.openh264.org/libopenh264-2.3.0-osx-x64.6.dylib.bz2
should be
http://ciscobinary.openh264.org/libopenh264-2.3.0-mac-arm64.dylib.bz2
http://ciscobinary.openh264.org/libopenh264-2.3.0-mac-x64.dylib.bz2

2.3.1 is available with correct file names:
http://ciscobinary.openh264.org/libopenh264-2.3.1-mac-arm64.dylib.bz2
http://ciscobinary.openh264.org/libopenh264-2.3.1-mac-arm64.dylib.signed.md5.txt
http://ciscobinary.openh264.org/libopenh264-2.3.1-mac-x64.dylib.bz2
http://ciscobinary.openh264.org/libopenh264-2.3.1-mac-x64.dylib.signed.md5.txt

**Comment by huili2** [comment]
thanks above for the update.
