### ISSUE TITLE
Visual artifacts when encoding

### ISSUE THREAD

**Issue by jozefchutka** [cisco/openh264#3588]
using libopenh264 with ffmpeg ([master-latest](https://github.com/BtbN/FFmpeg-Builds/releases)), there appears to be visual artifacts in some cases. I managed to create minimal reproducible example as following:

```
ffmpeg -filter_complex "color=black:100x50:60:4[b];movie=img.jpg[i];[b][i]overlay=x=n" -vcodec libopenh264 -y out.mp4
```
The img.jpg is being animated to the right over the black background. The resulting video contains visual artifacts (1x1 px dots) as demonstrated in artifact.jpg

This has something to do with p/i frames. As I decrease gop size to `-g 10` the artifacts are not visible anymore.

I have tried other encoders (like x264) and no artifacts appears visible so I guess the issue exists with libopenh264. 

![img.jpg](https://user-images.githubusercontent.com/750041/199942957-99ecb8c0-1ac5-4422-b2ec-5da8c8d88dfd.jpg)
![artifact.jpg](https://user-images.githubusercontent.com/750041/199943183-19074732-f2c5-49dc-b3c4-766303bc2b7a.jpg)

https://user-images.githubusercontent.com/750041/199944508-faa8b423-39a1-40ec-b3af-7d1c8001f470.mp4

**Comment by huili2** [comment]
Thanks all the same. Openh264 is tuned suitably for real-time meeting case, so it may not be suitable for some other specific scenarios, including above cases.
