### ISSUE TITLE
QA: Does openh264 support VBR now ?

### ISSUE THREAD

**Issue by walker-WSH** [cisco/openh264#3596]
Excuse me, I searched previous issues for **VBR**:
https://github.com/cisco/openh264/issues/2102

I want to know whether it is supported now.
```
typedef enum {
  RC_QUALITY_MODE = 0,     ///< quality mode
  RC_BITRATE_MODE = 1,     ///< bitrate mode
  RC_BUFFERBASED_MODE = 2, ///< no bitrate control,only using buffer status,adjust the video quality
  RC_TIMESTAMP_MODE = 3, //rate control based timestamp
  RC_BITRATE_MODE_POST_SKIP = 4, ///< this is in-building RC MODE, WILL BE DELETED after algorithm tuning!
  RC_OFF_MODE = -1,         ///< rate control off mode
} RC_MODES;
```

Many thanks ~

**Comment by huili2** [comment]
No changes yet. As prompted there, you may use fixed QP for one case of VBR coding.

**Comment by walker-WSH** [comment]
> No changes yet. As prompted there, you may use fixed QP for one case of VBR coding.

非常感谢您的及时回复!
我去试试~

**Comment by walker-WSH** [comment]
@huili2 @HaiboZhu 


我看过openh264的encode sample （https://github.com/cisco/openh264/blob/master/codec/console/enc/src/welsenc.cpp）

如果要通过`RC_OFF_MODE + fixed QP`的方式，openh264似乎和其他编码器的CQP RC method一样，不能同时设置`max_bitrate`.  这和真实的VBR有一些区别。
请问是这样的吗？

谢谢~

**Comment by huili2** [comment]
Yes you are right. (let me still keep English:) )
Fixed bitrate would never consider max bitrate in openh264.

**Comment by walker-WSH** [comment]
> Yes you are right. (let me still keep English:) ) Fixed QP would never consider max bitrate in openh264.

got it !
thanks a lot.
