### ISSUE TITLE
Warning: Potential Security Risk Ahead when downloading binarry from github

### ISSUE THREAD

**Issue by bobj1212** [cisco/openh264#3602]
When downloading this file:
https://ciscobinary.openh264.org/openh264-2.3.1-win32.dll.bz2
using firefox or chrome you get this warning about the https certificate - see attached: 
Warning: Potential Security Risk Ahead

Firefox detected a potential security threat and did not continue to ciscobinary.openh264.org. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

What can you do about it?

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

![h_err](https://user-images.githubusercontent.com/29187668/207212098-ea1e1cf8-d2b4-4c29-98fa-e9869f526fb5.png)

**Comment by huili2** [comment]
you can click the "advanced" button to go on following operations.

**Comment by flossposse** [comment]
In 2023, obtaining an SSL certificate is [easy and free](https://letsencrypt.org/getting-started/).  What is preventing the use of https to serve these files?

**Comment by bwildenhain** [comment]
See #909

**Comment by fluffy** [comment]
HTTPS is not supported for this and we would turn if off if we easily could. A more secure approach is to check the checksum of the downloaded file.

**Comment by flossposse** [comment]
> HTTPS is not supported for this and we would turn if off if we easily could. A more secure approach is to check the checksum of the downloaded file.

@fluffy How can one securely obtain checksums?  
The links at https://github.com/cisco/openh264/releases are not https, so we can't know whether a checksum file downloaded there is genuine and hasn't been altered by a man-in-the-middle.  Is there another source for checksums?
