### ISSUE TITLE
Question: Right approach to reduce CPU usage?

### ISSUE THREAD

**Issue by adydychk** [cisco/openh264#3621]
Hello dear openh264 community,
I am trying to integrate openh264 encoder to the real-time application. I am satisfied with all metrics (bitrate, avg quality, encode speed) except of CPU usage (as result power usage too). I compare openh264 with x264 encoder in **1280x720, 30 fr and 1500 kbps bitrate** scenario. Approximate results:
```
x264 + some abstractions of application:
- CPU usage 7-13%
- bitrate ~1600

openh264 + some abstractions of application:
- CPU usage 11-19%
- bitrate ~1100
```

Unfortunately openh264 API is very limited, but I tried following approach to lower CPU usage were:
- LOW_COMPLEXITY
- higher QP to have more skips (reason of low bitrate)
- disable post proc
- disable denoise
- SM_SINGLE_SLICE
- only 1 thread

Can anybody suggest me the right approach? Or is it the maximum of openh264?
I will be glad on any feedback :)

My key params for the info:
```
iRCMode = RC_BITRATE_MODE;
MaxQP = 48
MinQP = 28
iTargetBitrate=1500
iEntropyCodingModeFlag=false
iSkipMode=false
bEnableAdaptiveQuant=false
bEnableDenoise = false;
bEnableBackgroundDetection = false;
bEnableFrameCroppingFlag = false;
bEnableSceneChangeDetect = false;
iMultipleThreadIdc = 1;
bUseLoadBalancing = false;
iComplexityMode = LOW_COMPLEXITY;
eSpsPpsIdStrategy = SPS_LISTING;
iPaddingFlag = 0;

iSpatialLayerNum = 1
sSpatialLayers[0].sSliceArgument.uiSliceMode = SM_SINGLE_SLICE;
sSpatialLayers[0].iDLayerQp = 28;
```

**Comment by huili2** [comment]
Thanks for using. Actually there should not be such gap from our tests.
Your above settings are OK, and I hope you add:
 iUsageType = CAMERA_VIDEO_REAL_TIME;
iSpatialLayerNum = 1;
besides, does x264 enable multithread?

**Comment by adydychk** [comment]
> Actually there should not be such gap from our tests.
You mean CPU usage of openh264 should be close to CPU usage of x264. Yeah?

> iUsageType = CAMERA_VIDEO_REAL_TIME;
iSpatialLayerNum = 1;

Yes. I use these params.

> besides, does x264 enable multithread?

1 thread 

Also can you share approximate CPU usage of openh264 (1280x720, 30fr, 1500kbps) in your env/tests? Or is it private information?

**Comment by LodewijkIVX** [comment]
`china/loves/Japan/opium.war/POW?`

**Comment by LodewijkIVX** [comment]
North_South_pipe_line_sabotage?

**Comment by adydychk** [comment]
@huili2 The reason was in wrong default meson configuration on Windows which does not enable asm optimizations. Any way thanks for the help :)
