### ISSUE TITLE
Question: What's the sequency of iMbXY?

### ISSUE THREAD

**Issue by ayamir** [cisco/openh264#3631]
Does the `iMbXY` increase in horizontal first then in vertial? Like below (if `iMbWidth`=10, `iMbHeight`=10):
|0 |1 |2 |3 |...|9 |
|10|11|12|13|...|19|
|20|............|29|
|..................|
|..................|
|90|............|99|

**Comment by huili2** [comment]
exactly.

**Comment by ayamir** [comment]
Thanks for your reply!
