### ISSUE TITLE
What does WELS stand for?

### ISSUE THREAD

**Issue by EvanCarroll** [cisco/openh264#3645]
I see this prefix all over. What does this actually stand for?

**Comment by faysalnadim** [comment]
Hi Evan, It stands for Windows Subsystem for Linux. It was integrated by MS in Windows to cater developers community. 

https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by EvanCarroll** [comment]
@faysalnadim I doubt that: I said WELS not WSL. And, why would all of the encoder be in a namespace devoted to WSL?

https://github.com/cisco/openh264/blob/2caedb7c5a618534d727189549bd8900d41b8517/codec/encoder/core/src/encode_mb_aux.cpp#L37

**Comment by faysalnadim** [comment]
I must have been hungry and thirsty while reading your question. Apologies, I've no clue about WELS.

**Comment by ethanhugg** [comment]
The W stands for Webex, and the ELS stands for er, liu, si which are the
Pinyin spellings for 264 in Chinese.

-EH

**Comment by EvanCarroll** [comment]
That's some real trivia there.. Very interesting.
