### ISSUE TITLE
Error when compiling in x64 bits on Windows Visual Studio

### ISSUE THREAD

**Issue by athissel** [cisco/openh264#3651]
Hello Sir, Madam,

I am writting to you because i am working on H264 codec for video. I build successfully for 32b windows target but have some errors when trying to build in 64b windows. I don't hknow how to resolve this. Can you help me ?
Here you can see error, it is link error, like not found definition of functions.
I get WARN when building in 64b, which I don't have on 32b :
cl : command line warning D9002: ignoring unknown option '/arch:SSE2'

I use for build :
Visual studio 2019
nasm 2.16.01 (setted nasm on variable environnement and path)
openh264 version 1.8.0
Thank you for your reply.
![capt](https://user-images.githubusercontent.com/131259057/233055947-c2721e15-d492-4ee2-8a3e-f32ddd2e0fd4.png)

**Comment by huili2** [comment]
How about lower version of nasm and try latest open264? haven't tried nasm 2.16.01, and not sure if it successfully compiles the asm files.

**Comment by athissel** [comment]
Found the problem, sorry for the ticket. Thanks for your help.
