### ISSUE TITLE
Error receiving data: Connection reset by peer on binary

### ISSUE THREAD

**Issue by premkumar5012002** [cisco/openh264#3660]
When updating openh264 on flatpack receiving this following error,

 1. [✗] org.freedesktop.Platform.openh264            2.2.0            i            flathub           1.0 kB / 944.3 kB

Warning: While downloading http://ciscobinary.openh264.org/libopenh264-2.2.0-linux64.6.so.bz2: Error receiving data: Connection reset by peer
Installation complete.

**Comment by huili2** [comment]
could you please try more times?

**Comment by premkumar5012002** [comment]
Problem is fixed
