### ISSUE TITLE
Fix TLS certificate for https://ciscobinary.openh264.org

### ISSUE THREAD

**Issue by nanonyme** [cisco/openh264#3662]
Please use a correct certificate for the site so HTTPS works out of the box. It's currently having Akamai name in subject alternative name. Eg Let's Encrypt can be combined quite well with Akamai CDN to get correct subject alternative name so the site is accepted by TLS libraries.

**Comment by bwildenhain** [comment]
See #909 :-(

**Comment by nanonyme** [comment]
This is a serious issue. No one should be using OpenH264 in current state where

1. GitHub doesn't have SHA2 for files
2. Cisco download site is subject to MITM attacks due to lack of proper HTTPS support
3. No GPG signatures for validating file origin

One of three must be fixed, preferably all.

**Comment by mcatanzaro** [comment]
If anybody is home, this should be closed as a duplicate of #909

**Comment by Bluewater1020** [comment]
infringement of copyright 48 cfr 102 uk 48 cfr 101 japan farmer president international canabis project intellectual property meaning bussines requirements unlawful intrest in a public contract is a violation 2921.15 ohio merchabilty and fitness is a stand alone policy

**Comment by cebele** [comment]
#3669 Could you please help with this issue?

**Comment by mcatanzaro** [comment]
@BenzhengZhang you can mark this as a duplicate of #909

**Comment by nanonyme** [comment]
The only conclusion I've reached here is binaries built by Cisco should not be used. Cisco also hosts binaries build by Mozilla whose hashes are securely distributed.
