### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by joakim-tjernlund** [cisco/openh264#3681]
Some firefox/chrome fixes w.r.t screen sharing looks interesting.

**Comment by BenzhengZhang** [comment]
Expected to be mid-November.

**Comment by joakim-tjernlund** [comment]
Nice :)

**Comment by kalev** [comment]
Thanks for starting the release process! Could you please tag the release in git, so that downstreams can start building it as well?

See https://github.com/cisco/openh264/tags how tagging was done for previous releases.

**Comment by joakim-tjernlund** [comment]
release 2.4.0 is out, closing.

**Comment by kalev** [comment]
Thanks, @BenzhengZhang!
