### ISSUE TITLE
Release 2.4.1

### ISSUE THREAD

**Issue by mcatanzaro** [cisco/openh264#3711]
Hi, it would be nice to have an OpenH264 2.4.1 release with [this fix](https://github.com/cisco/openh264/commit/fd66e67ac6136aff80b1567488568ba1ed7e8fb8) that's required to play the Big Buck Bunny test video.

**Comment by tyan0** [comment]
I hope 2.4.1 includes also https://github.com/cisco/openh264/pull/3707.

**Comment by torokati44** [comment]
+1 from me on both of the above.

**Comment by mcatanzaro** [comment]
Hi @fluffy, we believe the current OpenH264 release is seriously broken. Suggest creating a 2.4.1 release with the fix that has already landed.

Unfortunately I don't know any way to contact the OpenH264 developers other than to ping you directly, which is unfortunate. It would be nice if this issue tracker were monitored more actively.

**Comment by BenzhengZhang** [comment]
Hi @mcatanzaro, I will release version 2.4.1 in the next few days.

**Comment by torokati44** [comment]
> I will release version 2.4.1 in the next few days.

That's great news, @BenzhengZhang?
Is https://github.com/cisco/openh264/pull/3723 going to be part of that?

**Comment by BenzhengZhang** [comment]
> > I will release version 2.4.1 in the next few days.
> 
> That's great news, @BenzhengZhang! Is #3723 going to be part of that?

@torokati44 Unfortunately, I cannot include this PR because it has not been reviewed yet and I am not sure whether there is a risk of regression. We will evaluate it in the next release. You are also welcome to review it.

**Comment by BenzhengZhang** [comment]
@joakim-tjernlund These fixes are expected to be included in the next release and will be picked up after review : )

**Comment by BenzhengZhang** [comment]
v2.4.1 release completed https://github.com/cisco/openh264/releases/tag/v2.4.1

**Comment by mcatanzaro** [comment]
Thank you!

(And now I know whom to ping in the future... sorry Benzheng. :)

**Comment by joakim-tjernlund** [comment]
> @joakim-tjernlund These fixes are expected to be included in the next release and will be picked up after review : )

openh264 has not moved at all since release, surely you must have an hour/week to spend on open264?
