### ISSUE TITLE
Latest update broke video and made it glitchy

### ISSUE THREAD

**Issue by romulasry** [cisco/openh264#3738]
Latest on Fedora Rawhide as of Sun Mar 31 it is still broken.

**Comment by romulasry** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2265458

**Comment by BenzhengZhang** [comment]
@tyan0  any thought?

**Comment by tyan0** [comment]
@romulasry , how did you install libopenh264.so.2.4.1? I tried but fedora 39 installed 2.4.0-2.fc39. So, I replaced it manually with http://ciscobinary.openh264.org/libopenh264-2.4.1-linux64.7.so.bz2, however the issue could not be reproduced. I will try fedora 40 beta next.

**Comment by romulasry** [comment]
@tyan0
Installed Packages
Name         : openh264
Version      : 2.3.1
Release      : 2.fc39
Architecture : x86_64
Size         : 1.1 M
Source       : openh264-2.3.1-2.fc39.src.rpm
Repository   : @System
From repo    : fedora-cisco-openh264
Summary      : H.264 codec library
URL          : https://www.openh264.org/
License      : BSD
Description  : OpenH264 is a codec library which supports H.264 encoding and
             : decoding. It is suitable for use in real time applications such
             : as WebRTC.

**Comment by tyan0** [comment]
2.3.1? Rather than 2.4.1?

**Comment by romulasry** [comment]
@tyan0 yes.

**Comment by tyan0** [comment]
I cannot find 2.3.1-2.fc39. How can I install it? It seems that only 2.4.0-2.fc39 is available on the server. How did you install it?

I also replace 2.4.0-2.fc39 manually with http://ciscobinary.openh264.org/libopenh264-2.3.1-linux64.7.so.bz2, however the issue cannot be reproduced as well.

**Comment by romulasry** [comment]
I am running Feodra rawhide.

**Comment by kalev** [comment]
@romulasry Ah, sorry, I mistakenly thought you were on latest 2.4.1 version when I asked you to report it here. I think the best course of action for now is to just wait until we get 2.4.1 released in Fedora and then you can retest and see if it helps with this.

2.4.1 is currently waiting on https://pagure.io/releng/issue/11955

**Comment by romulasry** [comment]
> @romulasry Ah, sorry, I mistakenly thought you were on latest 2.4.1 version when I asked you to report it here. I think the best course of action for now is to just wait until we get 2.4.1 released in Fedora and then you can retest and see if it helps with this.
> 
> 2.4.1 is currently waiting on https://pagure.io/releng/issue/11955

Okay, thank you.

**Comment by BenzhengZhang** [comment]
2.4.1 is ready, please re-try. @romulasry

**Comment by romulasry** [comment]
@BenzhengZhang Not quite ready yet:

Last metadata expiration check: 0:02:04 ago on Sun 07 Apr 2024 09:37:19 AM PDT.
Installed Packages
Name         : openh264
Version      : 2.3.1
Release      : 2.fc39
Architecture : x86_64
Size         : 1.1 M
Source       : openh264-2.3.1-2.fc39.src.rpm
Repository   : @System
From repo    : fedora-cisco-openh264
Summary      : H.264 codec library
URL          : https://www.openh264.org/
License      : BSD
Description  : OpenH264 is a codec library which supports H.264 encoding and
             : decoding. It is suitable for use in real time applications such
             : as WebRTC.

**Comment by kalev** [comment]
@romulasry openh264 2.4.1 should be available for rawhide now - did that fix the glitches you were seeing?

**Comment by romulasry** [comment]
@kalev 2.4.0 fixed it for me, thanks.

**Comment by kalev** [comment]
Excellent! Glad to hear that.

Can you close this ticket please? I don't have the permissions to do that here.
