### ISSUE TITLE
Request for pre-compiled binaries for Windows [11] ARM

### ISSUE THREAD

**Issue by lassana** [cisco/openh264#3764]
Given that ARM has received first-level support from Microsoft, can we also expect Arm64 binaries to be available for Windows? Arm64 libraries have been available for Linux for some time now: https://github.com/cisco/openh264/issues/3157

**Comment by BenzhengZhang** [comment]
Hi @lassana, We are considering adding Win-Arm64 binaries to future releases.

**Comment by BenzhengZhang** [comment]
Windows ARM binaries had released by https://github.com/cisco/openh264/releases/tag/v2.5.0 @lassana
