### ISSUE TITLE
Not able to generate SEI NAL

### ISSUE THREAD

**Issue by paragpatel** [cisco/openh264#836]
Hello,

I want to generate SEI (supplemental enhancement information) while encoding three spatial layer SVC stream.

I have seen flag in configuration structure but seems it does not do any thing at core level.

From code seems openH264 do support SEI parsing while decoding stream, but do not support SEI NAL generation.

Thanks,
Parag Patel

**Comment by cecilpeng** [comment]
Is there a way to generate SEI now?

**Comment by chenbd** [comment]
Feature want
