### ISSUE TITLE
Bad SSL certificate on https://ciscobinary.openh264.org

### ISSUE THREAD

**Issue by vi** [cisco/openh264#909]
ciscobinary.openh264.org uses an invalid security certificate.

The certificate is only valid for the following names:
  *.akamaihd.net , *.akamaihd-staging.net , a248.e.akamai.net  

(Error code: ssl_error_bad_cert_domain)

**Comment by PhilLab** [comment]
Please re-evaluate this decision. People might not do this out of laziness / ignorance (count me in!). Making sure they at least have something from the owner of openh264.org might prevent a lot of harm.

Checking the checksum is definitely needed for true safety, but why not make the worst case a little less worse?

**Comment by PhilLab** [comment]
By the way, where can I find the fingerprint Mozilla uses?

**Comment by nils-ohlmeier** [comment]
@dminor do you know if we store the current fingerprints in tree somewhere?

**Comment by fluffy** [comment]
I'll reopen for discution

**Comment by dminor** [comment]
These should be the current fingerprints: https://searchfox.org/mozilla-central/source/toolkit/content/gmp-sources/openh264.json. However, that file is only used as a fallback when we can't reach the normal update server. The update server sends Firefox a url and a fingerprint to use. The intention is to make it easy to roll out updates to a portion of the population, but obviously does not make it easy to trace what is being downloaded. @Callek would know more about that side of things.

**Comment by Callek** [comment]
Ok, so the issue in https://github.com/cisco/openh264/issues/909#issue-34658985 looks like its a cert issue on the domain itself... 

![image](https://user-images.githubusercontent.com/1415602/59433720-1f4ab780-8db8-11e9-869f-7b9468d99a6f.png)

I'm not sure what https://github.com/cisco/openh264/issues/909#issuecomment-500594569 is asking specifically, though Mozilla is downloading the binaries from `http://ciscobinary.openh264.org/` and not `https://...` so we don't encounter the certificate issue. We do however have code that validates that our update service is the correct service (via cert) and that the urls it sends over are validated once downloaded with a `sha512` algorithm, so we never invoke untrusted code (even if a MITM struck and gave the user unexpected content)

Finally we codesign the binaries on windows, and gpg sign on linux (note the gpg sig is harder to verify since we don't expose this anywhere officially, nor is it fully guaranteed to exist in the future) e.g. `http://ciscobinary.openh264.org/openh264-linux64-2e1774ab6dc6c43debb0b5b628bdf122a391d521.zip.asc`

So I think this issue comes down to @fluffy and Cisco in general for if they want the ciscobinary.openh264.org to have a valid https cert.

**Comment by sijchen** [comment]
for cross-reference https://bugzilla.mozilla.org/show_bug.cgi?id=1102531

**Comment by flossposse** [comment]
Can this issue be revisited?  The [FreeDektop sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/) used in flatpak app packages downloads from this URL, so this is a potential security issue for anyone using flatpak.

**Comment by nanonyme** [comment]
This is not just potential but real security vulnerability. The GPG that was there seems to be gone. Cisco binaries are at this point not safe to use without locally reproducing same binary so you can collect sha256.

**Comment by mcatanzaro** [comment]
Hi @fluffy, could somebody from Cisco help fix this please?

There are two related issues above that can be closed as duplicates.

**Comment by fluffy** [comment]
HTTPS is not supported for this. We think a better approach is to check the fingerprint of the downloaded files.

**Comment by nanonyme** [comment]
@fluffy then can you please start providing strong hashes for the files from GitHub releases? Download server only has weak hashes which are useless by modern standards and they are untrusted since you are not supporting TLS or providing GPG scheme.

**Comment by flossposse** [comment]
@fluffy Is there a secure way to get the fingerprints?

**Comment by fluffy** [comment]
Mozilla is the group that is securely publishing the hashes. They actually compile the code to.  I'me feeling guilty I can not point you at the exactly location.   

Even if we did move to https from github, the whole process by which the executables get to github is not very secure thus the realiance on the hashes.

**Comment by Callek** [comment]
Few places Mozilla takes on stuff for this plugin [context I used to be a release engineer there, and one of the primary people responsible for delivering this]

https://searchfox.org/mozilla-central/source/taskcluster/ci/openh264-plugin/kind.yml
https://searchfox.org/mozilla-central/source/taskcluster/ci/openh264-signing/kind.yml

https://searchfox.org/mozilla-central/source/testing/mozharness/configs/openh264
https://searchfox.org/mozilla-central/source/testing/mozharness/scripts/openh264_build.py

Some more results:
https://searchfox.org/mozilla-central/search?q=openh264&path=openh264&case=false&regexp=false

But yes, Mozilla builds them for Cisco [at least used to, but I think still does] and then Cisco published the binaries on their own server.  Mozilla publishes update information to point Firefox at the binaries and at the related file hashes, this update *information* is protected much the same way actual Firefox updates are protected.

**Comment by mcatanzaro** [comment]
Let's also post instructions for how to verify the hashes somewhere prominent (like the toplevel README.md).

**Comment by mcatanzaro** [comment]
And probably also instructions explaining that ciscobinary.openh264.org is not intended to be accessed via HTTPS.

And close #3662

**Comment by bhearsum** [comment]
Hi, I'm a current engineer on Mozilla's Release Engineering team (hi @Callek!), and I just want to clarify one point.
 
> I'm not super familiar with the Mozilla codebase or infrastructure, so I could be wrong about this, but it _appears_ like [this](https://searchfox.org/mozilla-central/source/dom/media/tools/generateGmpJson.py) is the script that is being used to generate the [hashes](https://searchfox.org/mozilla-central/source/toolkit/content/gmp-sources/openh264.json) for the openh264 plugn: https://searchfox.org/mozilla-central/source/dom/media/tools/generateGmpJson.py

That script may be used to generate the in tree hashes (I'm not sure - I'm checking with the folks that update them), but it is definitely not used to generate the hashes [served by our update server](https://aus5.mozilla.org/update/3/GMP/120.0/20200518093924/WINNT_x86_64-msvc-x64/en-US/release/Windows_NT%2010.0.0.0.18363.1016%20(x64)/default/default/update.xml). Those are generated by hand by Release Engineers, who pull the builds securely from our CI system.

> Unfortunately, I can't find any CI tasks in Mozilla-Central that invoke `generateGmpJson` or that upload the artifacts to Cisco, so I can't tell whether the script is being used securely or not (or at all). The fact that the insecure behavior is the default one reduces my confidence.

As @Callek alluded to in an earlier comment - we do not use that script as part of builds, signing, or update publishing. Most of the build task is described [in stanzas like this](https://searchfox.org/mozilla-central/rev/49566d906ad040cf233b0a5acd597e1a63b92f72/taskcluster/ci/openh264-plugin/kind.yml#28-52), which uses [mozharness/scripts/openh264_build.py](https://searchfox.org/mozilla-central/source/testing/mozharness/scripts/openh264_build.py) to make the builds, and pulls the source [via https from a pinned revision in a github repository](https://searchfox.org/mozilla-central/rev/49566d906ad040cf233b0a5acd597e1a63b92f72/taskcluster/ci/openh264-plugin/kind.yml#22-23).

My belief is that the checked in hashes _may_ be used in the update server cannot be contacted - but I'm still working to confirm that. If they are, we obviously need to do better here.

**Comment by nanonyme** [comment]
@bhearsum okay, so what is the right way to discover the hashes? It doesn't seem like it can be https://searchfox.org/mozilla-central/source/toolkit/content/gmp-sources/openh264.json as it is about OpenH264 1.8.1.1 which is at this point ancient. https://aus5.mozilla.org/update/3/GMP/120.0/20200518093924/WINNT_x86_64-msvc-x64/en-US/release/Windows_NT%2010.0.0.0.18363.1016%20(x64)/default/default/update.xml does indeed point to more modern release (2.3.2) but not latest either (2.4.0).

**Comment by bhearsum** [comment]
> @bhearsum okay, so what is the right way to discover the hashes? It doesn't seem like it can be https://searchfox.org/mozilla-central/source/toolkit/content/gmp-sources/openh264.json as it is about OpenH264 1.8.1.1 which is at this point ancient. https://aus5.mozilla.org/update/3/GMP/120.0/20200518093924/WINNT_x86_64-msvc-x64/en-US/release/Windows_NT%2010.0.0.0.18363.1016%20(x64)/default/default/update.xml does indeed point to more modern release (2.3.2) but not latest either (2.4.0).

As far as I know, we're still only pointing Firefox users at 2.3.2. You can find the complete list of hashes for all platforms in https://aus-api.mozilla.org/api/v1/releases/OpenH264-2.3.2. (And you can find out the latest OpenH264 that we're shipping via the `mapping` field on https://aus-api.mozilla.org/api/v1/rules/17820.)

**Comment by Callek** [comment]
> > @bhearsum okay, so what is the right way to discover the hashes? It doesn't seem like it can be https://searchfox.org/mozilla-central/source/toolkit/content/gmp-sources/openh264.json as it is about OpenH264 1.8.1.1 which is at this point ancient. https://aus5.mozilla.org/update/3/GMP/120.0/20200518093924/WINNT_x86_64-msvc-x64/en-US/release/Windows_NT%2010.0.0.0.18363.1016%20(x64)/default/default/update.xml does indeed point to more modern release (2.3.2) but not latest either (2.4.0).
> 
> As far as I know, we're still only pointing Firefox users at 2.3.2. You can find the complete list of hashes for all platforms in https://aus-api.mozilla.org/api/v1/releases/OpenH264-2.3.2. (And you can find out the latest OpenH264 that we're shipping via the `mapping` field on https://aus-api.mozilla.org/api/v1/rules/17820.)

Also https://bugzilla.mozilla.org/show_bug.cgi?id=1619988 tracks the 2.4 rollout for Firefox

**Comment by nanonyme** [comment]
@mcatanzaro okay. So I would say flatpak updates should be using ^ to get the hashes. If it's not present there (like 2.4.0), then we should wait. @bhearsum is there an API call to get *latest* version?

**Comment by mcatanzaro** [comment]
> @mcatanzaro okay. So I would say flatpak updates should be using ^ to get the hashes. If it's not present there (like 2.4.0), then we should wait.

I would rather ship the latest release and rely on trust-on-first-use, even though it's not very secure. We shouldn't have to wait for Firefox to adopt the new version before we can update.

**Comment by mcatanzaro** [comment]
I'd really like to see the GitHub releases fixed. E.g. https://github.com/cisco/openh264/releases/tag/v2.4.0 says "All the binaries have been digitally signed" but in fact they are just MD5 hashes, not digital signatures, and any man-in-the-middle attacker who can change the binaries can also just as easily change the hashes. And even if the hashes were delivered securely, MD5 hasn't been safe for nearly 20 years now.

> The thing is though that as we have learned, Mozilla runs the show with OpenH264 (after tags). They are the only party you can trust for ensuring your browser users are not MITM'able. If their metadata system doesn't contain the build, then we should consider it not formally released.

Well you're not wrong, but this is really unfortunate. The Mozilla APIs are designed to be used by computers, not by humans.

**Comment by nanonyme** [comment]
> I'd really like to see the GitHub releases fixed. E.g. https://github.com/cisco/openh264/releases/tag/v2.4.0 says "All the binaries have been digitally signed" but in fact they are just MD5 hashes, not digital signatures, and any man-in-the-middle attacker who can change the binaries can also just as easily change the hashes. And even if the hashes were delivered securely, MD5 hasn't been safe for nearly 20 years now.
 


Well, yes, that is true. It would be totally awesome if Mozilla could ship GPG signatures next to every file delivered to Cisco so we could simply trust those to prove the files originate from Mozilla. But this is something to request from Mozilla, not Cisco.

**Comment by bhearsum** [comment]
> @mcatanzaro okay. So I would say flatpak updates should be using ^ to get the hashes. If it's not present there (like 2.4.0), then we should wait. @bhearsum is there an API call to get _latest_ version?

Our update server does not contain the data yet, and won't until we've been asked to get it ready for testing. (I have no idea when this will happen...I'm not even sure if we've produced 2.4.0 builds yet in fact...

> Well, yes, that is true. It would be totally awesome if Mozilla could ship GPG signatures next to every file delivered to Cisco so we could simply trust those to prove the files originate from Mozilla. (this would potentially also increase security with the handover) But this is something to request from Mozilla, not Cisco.

Please feel free to file a bug for this over in https://bugzilla.mozilla.org/enter_bug.cgi?product=Release+Engineering&component=General. I can't make any promises, but at the very least it's good to have such things on file.

**Comment by nanonyme** [comment]
@bhearsum I think you have and they have been handed over to Cisco. They are just missing from metadata service. See https://gitlab.com/freedesktop-sdk/openh264-extension/-/merge_requests/46/diffs

**Comment by nanonyme** [comment]
I think it's probably fine @mcatanzaro integrates them before they land in Firefox QA as they are handling them being tested in the context of another browser. As long as we can prove to users these are authentic Mozilla binaries.

**Comment by flossposse** [comment]
@bhearsum can you confirm whether the binaries linked to on [Cisco's github releases page](https://github.com/cisco/openh264/releases) were built by Mozilla?  The URLs on that page are not the same as the ones on aus-api.mozilla.org/api/v1/releases/OpenH264-x.x.x


For example, let's compare the 2.3.1 binaries, since 2.3.2 doesn't appear on the github releases page and 2.4.0 isn't on aus, but 2.3.1 exists in both places...

on https://aus-api.mozilla.org/api/v1/releases/OpenH264-2.3.1 we see the following:
```
"Linux_x86_64-gcc3": {
                    "fileUrl": "http://ciscobinary.openh264.org/openh264-linux64-0a48f4d2e9be2abb4fb01b4c3be83cf44ce91a6e.zip",
                    ...
                }
```
And on https://github.com/cisco/openh264/releases/tag/v2.3.1 we have:
`http://ciscobinary.openh264.org/libopenh264-2.3.1-linux64.7.so.bz2`

To check this isn't simply a case of renaming and recompressing, I decompressed both archives and hashed the .so files.  The two produce different results:
```
flossposse@flossposse:~/Downloads/openh264$ sha512sum libopenh264-2.3.1-linux64.7.so 
cbeb89f41db289deccbfa5a3d448ea978490bc22e40cc0e23069594578f4dd886fe6b95c6bf905c7745ba95e31fae6c13fd354e50dee87e033512bc49d3dc3e4  libopenh264-2.3.1-linux64.7.so
flossposse@flossposse:~/Downloads/openh264$ sha512sum libgmpopenh264.so 
9d1defc632ceb6dca5997a623f682673d75c6541ab4309f4464ab2213c6cce50fddd95088d510a151e123705057c351774ed344517e92e43dab7de777fdfc56c  libgmpopenh264.so

@bhearsum If the `.bz2` files that show up on the github release page _are_ in fact built by Mozilla, could you point us toward a source for hashes?

**Comment by bhearsum** [comment]
> @bhearsum can you confirm whether the binaries linked to on Cisco's github releases page were built by Mozilla? The URLs on that page are not the same as the ones on aus-api.mozilla.org/api/v1/releases/OpenH264-x.x.x

I have no knowledge on what happens with our builds after we hand them off to Cisco, but based on a comparison of the files from https://aus-api.mozilla.org/api/v1/releases/OpenH264-2.3.1, and the 2.3.1 release on https://github.com/cisco/openh264/releases, it certainly does not seem like they upload what Mozilla builds.

The only place I can point you for hashes for the builds we produce are the aforementioned links like https://aus-api.mozilla.org/api/v1/releases/OpenH264-2.3.1.

**Comment by nanonyme** [comment]
Okay, then what fluffy said is clearly bogus and this issue should be open.

**Comment by nils-ohlmeier** [comment]
I think the issue is a little two fold: for Mozilla this isn't really a big issue as they simply know the hashes of the binaries they build and bake them either into Firefox or put them on secured/trustworthy server for Firefox to download from.

But for everybody else who hasn't build the binary them self it's a little bit more tricky.

**Comment by nanonyme** [comment]
@nils-ohlmeier no, the problem is Cisco says Mozilla builds the binaries but binaries differ from what Mozilla builds.

**Comment by mcatanzaro** [comment]
So for avoidance of doubt, fluffy seems to be mistaken with regards to the release process. The binary releases appear to most likely be built by Cisco, not by Mozilla. Certainly there doesn't appear to be any known way to download hashes for them from Mozilla.

**Comment by nils-ohlmeier** [comment]
@mcatanzaro @bhearsum provided the URL for downloading the hashes which Mozilla uses. It is https://aus-api.mozilla.org/api/v1/releases/OpenH264-2.3.2 (and that is a HTTPS URL and the hashes are using modern, stronger hash algorithms).

Now Mozilla isn't always using the latest version of OpenH264. That is a completely different problem.

I don't know who build the 2.4.0 binaries. Maybe the more secure solution would be then for Cisco to not publish any binaries, until Mozilla builds them and provides them to Cisco?

@bhearsum I'm pretty sure from when I used to work on this that Bryce told me that the build in hashes in Firefox are only used if the update services are not reachable. So who ever did OpenH264 updates recently forgot to update these internal hashes (which if I remember it correctly is a pretty common issue).

**Comment by Erick555** [comment]
Even for older releases like 2.3.1 Cisco doesn't present those mozilla builds anywhere but only shows their own. The binary difference as checked with diffoscope is massive.

Is the recommendation to use those mozilla builds instead of ones listed at https://github.com/cisco/openh264/releases ? The filename doesn't match so everyone would need to rename them. Does this comply with Cisco binary license?

**Comment by Erick555** [comment]
Even for older releases like [2.3.1](https://github.com/cisco/openh264/releases/tag/v2.3.1) Cisco doesn't present those mozilla builds anywhere but only shows their own. The binary difference as checked with diffoscope is massive.

Is the recommendation to use those mozilla builds instead of ones listed in openh264 github release page? Does this comply with Cisco binary license?

**Comment by mcatanzaro** [comment]
(We are now pretty confident that the binaries produced by Mozilla for Firefox simply do not correspond to the binaries released by Cisco.)

**Comment by nils-ohlmeier** [comment]
I guess who's binaries you trust more depends on your individual perspective. The Mozilla binaries do have better hashes which can be fetched from an HTTPS URL.

My personal guess is that Cisco in general pays the MPEG royalties for all it's encoders. So as long as the encoders are distributed by Cisco they should be covered. But I'm neither a lawyer nor do I speak for Cisco.

**Comment by mcatanzaro** [comment]
I don't mean I don't trust the Mozilla binaries. I just mean they are not the binaries that Cisco is releasing. I think we've established this by now. :)

**Comment by mcatanzaro** [comment]
> I'd really like to see the GitHub releases fixed. E.g. https://github.com/cisco/openh264/releases/tag/v2.4.0 says "All the binaries have been digitally signed" but in fact they are just MD5 hashes, not digital signatures, and any man-in-the-middle attacker who can change the binaries can also just as easily change the hashes. And even if the hashes were delivered securely, MD5 hasn't been safe for nearly 20 years now.

We have detected that the OpenH264 2.4.1 binaries have unexpectedly changed after release for at least x86_64 and aarch64. The binaries that I downloaded on February 2 do not match the binaries distributed today, February 8. I don't know when they changed. [Here are sha256sums and sizes for the files distributed on February 2.](https://gitlab.com/freedesktop-sdk/openh264-extension/-/commit/0a9b921ec53e707d313b4b62b57336bd60fb3381#bc688134294e254daf949a259f872272289cab6c) The x86_64 libopenh264-2.4.1-linux64.7.so.bz2 that I downloaded on February 2 was 633714 bytes and had a SHA-256 hash of 47107cfc244f2d4c87d1f360f682024d7d50322d8c66fb4a1ae69bd976675285. The same file downloaded today, February 8, is 633796 bytes and has a SHA-256 hash of ca413853d99d960ebcd5ae5b4c65a85bb2b5598e9042e64700a9f4b737ca3a3f.

Needless to say, this should never happen without some sort of official announcement telling people to expect it. I'm assuming Cisco has intentionally changed the binaries and that there is no attacker, but absent some sort of announcement, there's no way for us to know.

This incident further reinforces the importance of supply chain security. I was worried about theoretical issues; I certainly didn't expect it to be a real problem in practice. Properly supporting TLS would be the bare minimum to restore confidence; adding GPG signatures would be better. Please stop using MD5 hashes and certainly stop referring to them as "digital signatures."

**Comment by torokati44** [comment]
> I'm assuming Cisco has intentionally changed the binaries

I'm assuming it has to do with this, maybe: https://github.com/cisco/openh264/issues/3728

> Properly supporting TLS would be the bare minimum to restore confidence; adding GPG signatures would be better. Please stop using MD5 hashes and certainly stop referring to them as "digital signatures."

100% agree.

**Comment by torokati44** [comment]
About MD5:
https://twitter.com/DiscussingFilm/status/1770198014319026436

> Here is a 72-byte alphanum MD5 collision with 1-byte difference for fun:
>
> md5("TEXTCOLLBYfGiJUETHQ4hAcKSMd5zYpgqf1YRDhkmxHkhPWptrkoyz28wnI9V0aHeAuaKnak")
=
md5("TEXTCOLLBYfGiJUETHQ4hEcKSMd5zYpgqf1YRDhkmxHkhPWptrkoyz28wnI9V0aHeAuaKnak")

🤡🚨

**Comment by mcatanzaro** [comment]
> About MD5:

I was about to report you as a spammer, but you don't look like a spammer. Did you just paste the wrong link there?

**Comment by torokati44** [comment]
What, yes, sorry, how did that end up in my clipboard? 😂

**Comment by torokati44** [comment]
Okay, now I know. Fixed the link. 😅

**Comment by fluffy** [comment]
The more I read on this more concerned I get.  If cisco had compiled these or changed them, the binaries hash would not be in FF and FF fox would fail to load the binaries.  Perhaps that is happening. 

I wonder if we could get a call together with the people at Mozilla and Cisco and verify all of this was going as expected. I am also sure that if mozilla wants to change to better hashes, GPG, post quntum, whatever, Cisco is in favour of better security and glad to post them.

**Comment by fluffy** [comment]
nils-ohlmeier has this right.  The goal was to set this up so that you only had to trust Mozilla, not Cisco, yet Cisco could cover the MPEG-LA royalty fees for people that wanted to use this. Here is a video that explains how this was set up https://vimeo.com/79578794 

It is certainly possible things have migrated from this along the way but I think the goals remain the same.

**Comment by Erick555** [comment]
Trusting Mozilla may be ok although there is a catch - there is a time lag (counted in months) between Cisco making release and Mozilla added it in their setup. For example Mozilla is still at [OpenH264 2.3.1](https://bugzilla.mozilla.org/show_bug.cgi?id=1619988).

That means when someone wanted a bugfix then they need to fix it in source code, wait for Cisco release then wait for Mozilla adding it which is many months of delay even for high priority bugfixes (from user perspective). If Cisco used stronger verification for released binaries then nobody would face dilemma between trust and time.

**Comment by Erick555** [comment]
> Mozilla builds, presumably built by Mozilla and kindly hosted by Cisco? (not relevant to this thread)

Yes, mozila builds are hosted on Cisco [servers](https://aus-api.mozilla.org/api/v1/releases/OpenH264-2.3.1). With few adjustments it should be technically possible to use them in flatpak runtime but there is release delay catch I mentioned.

> Official Cisco releases hosted here on GitHub (these are what we're discussing in this thread)

On GitHub there are just links posted, everything is hosted on ciscobinary.openh264.org

**Comment by fluffy** [comment]
Than you @Erick555  and @mcatanzaro - I was not understanding the problem. Sorry. 

Can someone summarize the problem and we are on this and what it is Cisco ( or Mozilla ) should do. I do not think I can get significantly more Cisco people working on this but I can get Cisco to help make the right thing happen.  I would also add that I think we could add more/other external maintainers for this as long as that person was acceptable to both Mozilla and Cisco.

**Comment by fluffy** [comment]
That does not seem to deal with the problem reported above of "We have detected that the OpenH264 2.4.1 binaries have unexpectedly changed after release for at least x86_64 and aarch64."   At this point it is not clear to me who is making the builds or who uploaded the ones that changed.  That should deeply concern everyone and gets to why we do not view they way this is working as a secure build chain.

**Comment by Erick555** [comment]
The changed binaries problem was discussed [here](https://github.com/cisco/openh264/issues/3728#issuecomment-1953376166). Yes, such accidents combined with lack of secure verification make the trust case even worse.

**Comment by mcatanzaro** [comment]
> At this point it is not clear to me who is making the builds or who uploaded the ones that changed.

The 2.4.0 and 2.4.1 releases were created by Benzheng Zhang, who I presume works for Cisco. He would know who is making the builds.

The unexpected change to the binaries turned out to be an innocent mistake to fix the version number. The original 2.4.1 binaries improperly reported their version as 2.4.0, and the replacement binaries correctly report 2.4.1. Benzheng has already agreed to avoid replacing previously-released binaries in the future; a better solution would have been to just release 2.4.2.

**Comment by ErikCumps** [comment]
I don't mind on which issue this gets fixed, as long as it gets fixed. :blush: 

Browsers are more and more reluctant to connect with plain http sites _(like it or not)_ and there is really, really no point at all in using a TLS certificate for a webserver that is not matching the identity of that server.

So please fix the invalid TLS certificate on https://ciscobinary.openh264.org/, so that web browsers can load that link without security warnings.

**Comment by ErikCumps** [comment]
Seeing as this issue is closed, I understand the TLS certificate for the webserver will not get fixed here.

So please fix it in #3748.

Browsers are more and more reluctant to connect with plain http sites (like it or not) and **there is really, really no point at all in using a TLS certificate for a webserver that is not matching the identity of that server**.

**Comment by mcatanzaro** [comment]
This should be reopened because the problem is clearly not fixed.

**Comment by PhilLab** [comment]
@fluffy can you re-evaluate this? In many configurations nowadays, non-ssl connections are simply blocked. And hosting the binaries on your own, SSL-equipped CDN is also not an option, as this does not comply with Cisco's license.

This situation is an open door for supply-chain attacks and given the prominence of OpenH264, this is a catastrophe bound to happen.
