### ISSUE TITLE
Duplicate File Names

### ISSUE THREAD

**Issue by ethanhugg** [cisco/openh264#921]
It seems we still have many files with duplicate names.  Some of these have duplicate content and some have nearly duplicate content which seems dangerous.  Here is a quick list of some examples.  We should probably resolve these by renaming the ones that are really different and moving the ones that should be the same into common.

as264_common.h
bit_stream.h
deblocking.h
decode_mb_aux.h
expand_pic.h
get_intra_predictor.h
mb_cache.h
mc.h
mv_pred.h
nal_prefix.h
parameter_sets.h
picture.h
read_config.h
resource.h
slice.h
utils.h
welsCodecTrace.h
wels_common_basis.h
wels_const.h

**Comment by huili2** [comment]
All files now have been reviewed, with possible merges done by recent pull requests #1880 , #1871 , #1868 , #1847, #1843 ,  as well as early pull requests.
